import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { resolve } from "node:path";

// Credential response bodies and secret dialogs must never enter retained traces.
test.use({ trace: "off", screenshot: "off", video: "off" });
const enabled = process.env.SEMLIA_DISTRIBUTION_QA === "1";
const evidence = process.env.SEMLIA_BROWSER_EVIDENCE_DIR ?? resolve(process.cwd(), "../docs/evidence/FMB-T006/screenshots");
const credentialsToRevoke: { workspaceId: string; credentialId: string }[] = [];
const webhooksToDisable: { workspaceId: string; subscriptionId: string }[] = [];
test.afterEach(async ({ page, request }, testInfo) => {
  // Playwright's failure DOM snapshot is independent of its trace option.
  // Dismiss the secret and close a failed page before that snapshot is collected.
  if (!page.isClosed()) {
    await page.keyboard.press("Escape").catch(() => {});
    await page.locator(".integration-secret-view code").evaluateAll(nodes => nodes.forEach(node => { node.textContent = "[redacted]"; })).catch(() => {});
    if (testInfo.status !== testInfo.expectedStatus) await page.close();
  }
  for (const item of credentialsToRevoke.splice(0)) await request.post(`/api/v1/workspaces/${item.workspaceId}/client-credentials/${item.credentialId}/revoke`, { headers: { "X-Semlia-Principal": "local-author" } }).catch(() => {});
  for (const item of webhooksToDisable.splice(0)) {
    const headers = { "X-Semlia-Principal": "local-author" };
    const response = await request.get(`/api/v1/workspaces/${item.workspaceId}/webhooks`, { headers }).catch(() => undefined);
    if (!response?.ok()) continue;
    const page = await response.json() as { items: { id: string; version: number; name: string; endpoint: string; enabled: boolean; eventTypes: string[] }[] };
    const subscription = page.items.find(value => value.id === item.subscriptionId);
    if (subscription?.enabled) await request.patch(`/api/v1/workspaces/${item.workspaceId}/webhooks/${item.subscriptionId}`, { headers, data: { name: subscription.name, endpoint: subscription.endpoint, enabled: false, eventTypes: subscription.eventTypes, expectedVersion: subscription.version } }).catch(() => {});
  }
});

test("real machine identity, grant, consumer and credential lifecycle persists", async ({ page, request, playwright, baseURL }, testInfo) => {
  test.skip(!enabled, "Explicit distribution QA flag required; creates an isolated synthetic workspace.");
  const suffix = `${testInfo.project.name}-${Date.now()}`;
  const workspaceResponse = await request.post("/api/v1/workspaces", { data: { slug: `fmb006-${suffix}`, displayName: `FMB006 QA ${suffix}` } });
  expect(workspaceResponse.status()).toBe(201);
  const workspace = await workspaceResponse.json() as { id: string };
  mkdirSync(evidence, { recursive: true });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  await page.getByRole("combobox", { name: "工作区" }).selectOption(workspace.id);
  const navigate = async () => {
    await page.getByRole("button", { name: "系统设置", exact: true }).click();
    await page.getByRole("complementary", { name: "治理上下文" }).getByRole("button", { name: /接口与集成/ }).click();
  };
  await navigate();
  const panel = page.getByRole("region", { name: "接口与集成", exact: true });
  await expect(panel.getByText("尚无客户端凭据")).toBeVisible();
  await panel.getByRole("button", { name: "创建机器身份", exact: true }).click();
  let dialog = page.getByRole("dialog", { name: "创建机器身份", exact: true });
  await dialog.getByLabel("名称", { exact: true }).fill(`Machine ${suffix}`);
  const created = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith("/machine-principals"));
  await dialog.getByRole("button", { name: "创建", exact: true }).click();
  const principalResponse = await created;
  expect(principalResponse.status()).toBe(201);
  const principal = await principalResponse.json() as { id: string };
  dialog = page.getByRole("dialog", { name: "机器身份已创建" });
  await expect(dialog).toContainText("当前身份尚无角色授权");
  const granted = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith("/authorization/role-bindings"));
  await dialog.getByRole("button", { name: "授予消费开发者角色" }).click();
  expect((await granted).status()).toBe(201);
  await expect(dialog).toContainText("消费开发者角色已授予");
  await dialog.getByRole("button", { name: "完成", exact: true }).click();
  await panel.getByRole("button", { name: "登记消费方", exact: true }).click();
  dialog = page.getByRole("dialog", { name: "登记消费方", exact: true });
  await dialog.getByLabel("名称", { exact: true }).fill(`Consumer ${suffix}`);
  await dialog.getByLabel("稳定键").fill(`consumer-${suffix}`);
  const bound = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith("/consumer-bindings"));
  await dialog.getByRole("button", { name: "创建", exact: true }).click();
  expect((await bound).status()).toBe(201);
  await expect(dialog).toHaveCount(0);
  const trigger = panel.getByRole("button", { name: "创建客户端", exact: true });
  await trigger.click();
  dialog = page.getByRole("dialog", { name: "创建客户端", exact: true });
  await dialog.getByLabel("名称", { exact: true }).fill(`Credential ${suffix}`);
  await dialog.getByLabel("机器身份 ID").fill(principal.id);
  await dialog.getByRole("combobox", { name: "消费方", exact: true }).selectOption({ label: `Consumer ${suffix}` });
  await dialog.getByRole("combobox", { name: "消费绑定", exact: true }).selectOption({ index: 1 });
  await expect(dialog.getByRole("checkbox", { name: "semantic.resolve" })).toBeChecked();
  const actionCheckbox = dialog.getByRole("checkbox", { name: "semantic.resolve" });
  await expect(actionCheckbox).toHaveCSS("width", "16px");
  await expect(actionCheckbox).toHaveCSS("height", "16px");
  await expect.poll(async () => (await actionCheckbox.boundingBox())?.width).toBeCloseTo(16, 1);
  await expect.poll(async () => (await actionCheckbox.boundingBox())?.height).toBeCloseTo(16, 1);
  const issued = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith("/client-credentials"));
  await dialog.getByRole("button", { name: "创建", exact: true }).click();
  const issuedResponse = await issued;
  expect(issuedResponse.status()).toBe(201);
  const issuance = await issuedResponse.json() as { token: string; credential: { id: string } };
  credentialsToRevoke.push({ workspaceId: workspace.id, credentialId: issuance.credential.id });
  expect(issuance.token.startsWith("ccd_")).toBe(true);
  dialog = page.getByRole("dialog", { name: "保存一次性凭据" });
  expect((await dialog.locator("code").textContent()) === issuance.token).toBe(true);
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();
  expect((await page.locator("body").textContent())?.includes(issuance.token)).toBe(false);
  const machine = await playwright.request.newContext({ baseURL });
  let requestSequence = 0;
  const resolveWith = (token: string) => machine.post(`/api/v1/workspaces/${workspace.id}/semantic-queries:resolve`, {
    headers: { Authorization: `Bearer ${token}` }, data: { query: { schemaVersion: "1.0.0", intent: "describe", measures: [{ address: "qa.missing" }], context: { mode: "current" } }, channel: "api", idempotencyKey: `live-${suffix}-${requestSequence++}` },
  });
  expect((await resolveWith(issuance.token)).status()).toBe(200);
  await page.reload();
  await page.getByRole("combobox", { name: "工作区" }).selectOption(workspace.id);
  await navigate();
  const object = panel.locator("article").filter({ has: page.getByText(`Credential ${suffix}`, { exact: true }) });
  await expect(object).toContainText("有效");
  const list = await request.get(`/api/v1/workspaces/${workspace.id}/client-credentials`, { headers: { "X-Semlia-Principal": "local-author" } });
  expect(list.status()).toBe(200);
  expect((await list.text()).includes(issuance.token)).toBe(false);
  const rotation = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith(`/client-credentials/${issuance.credential.id}/rotate`));
  await object.getByRole("button", { name: `轮换 Credential ${suffix} 的凭据` }).click();
  const rotationResponse = await rotation;
  expect(rotationResponse.status()).toBe(201);
  const rotated = await rotationResponse.json() as { token: string; credential: { id: string } };
  credentialsToRevoke.push({ workspaceId: workspace.id, credentialId: rotated.credential.id });
  expect(rotated.token !== issuance.token).toBe(true);
  await page.getByRole("dialog", { name: "保存一次性凭据" }).getByRole("button", { name: "完成" }).click();
  expect((await resolveWith(issuance.token)).status()).toBe(401);
  expect((await resolveWith(rotated.token)).status()).toBe(200);
  const revocation = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith(`/client-credentials/${rotated.credential.id}/revoke`));
  await panel.getByRole("button", { name: `撤销客户端 Credential ${suffix}` }).filter({ hasNot: page.locator(":disabled") }).all().then(async buttons => { for (const button of buttons) if (await button.isEnabled()) { await button.click(); break; } });
  expect((await revocation).status()).toBe(204);
  expect((await resolveWith(rotated.token)).status()).toBe(401);
  await machine.dispose();
  await panel.getByRole("button", { name: "刷新集成设置" }).click();
  await expect(panel.getByText("已撤销", { exact: true })).toHaveCount(2);
  expect((await page.locator("body").textContent())?.includes(rotated.token)).toBe(false);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false);
  const accessibility = await new AxeBuilder({ page }).include(".integration-settings-view").analyze();
  expect(accessibility.violations.filter(item => item.impact === "serious" || item.impact === "critical")).toEqual([]);
  await page.screenshot({ path: resolve(evidence, `${testInfo.project.name}-persisted-revoked-clients.png`), fullPage: true });

  // This isolated workspace has no asset/release mutations or outbox deliveries.
  // Only subscription persistence and one-time signing material are exercised.
  await panel.getByRole("tab", { name: /Webhook/ }).click();
  await panel.getByRole("button", { name: "新增 Webhook" }).click();
  dialog = page.getByRole("dialog", { name: "新增 Webhook" });
  await dialog.getByLabel("名称", { exact: true }).fill(`Hook ${suffix}`);
  await dialog.getByLabel("HTTPS 接收地址").fill("https://example.com/semlia-qa/a");
  const eventCheckbox = dialog.getByRole("checkbox", { name: "release.published" });
  await expect(eventCheckbox).toHaveCSS("width", "16px");
  await expect(eventCheckbox).toHaveCSS("height", "16px");
  await expect.poll(async () => (await eventCheckbox.boundingBox())?.width).toBeCloseTo(16, 1);
  await expect.poll(async () => (await eventCheckbox.boundingBox())?.height).toBeCloseTo(16, 1);
  const hookCreated = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith("/webhooks"));
  await dialog.getByRole("button", { name: "创建", exact: true }).click();
  const hookResponse = await hookCreated;
  expect(hookResponse.status()).toBe(201);
  const hook = await hookResponse.json() as { subscription: { id: string }; signingSecret: string };
  webhooksToDisable.push({ workspaceId: workspace.id, subscriptionId: hook.subscription.id });
  expect(hook.signingSecret.length === 43).toBe(true);
  await page.getByRole("dialog", { name: "保存一次性凭据" }).getByRole("button", { name: "完成" }).click();
  const hookObject = panel.locator("article").filter({ has: page.getByText(`Hook ${suffix}`, { exact: true }) });
  await hookObject.getByRole("button", { name: `编辑 Hook ${suffix} 的订阅` }).click();
  dialog = page.getByRole("dialog", { name: "编辑 Webhook" });
  await dialog.getByLabel("HTTPS 接收地址").fill("https://example.com/semlia-qa/b");
  await dialog.getByRole("checkbox", { name: "catalog.asset.changed" }).check();
  await dialog.getByRole("checkbox", { name: "release.published" }).uncheck();
  const hookEdited = page.waitForResponse(r => r.request().method() === "PATCH" && r.url().endsWith(`/webhooks/${hook.subscription.id}`));
  await dialog.getByRole("button", { name: "保存", exact: true }).click();
  expect((await hookEdited).status()).toBe(200);
  await expect(dialog).toHaveCount(0);
  await expect(hookObject).toContainText("https://example.com/semlia-qa/b");
  await expect(hookObject.getByRole("checkbox", { name: "启用" })).toBeChecked();
  const hookDisabled = page.waitForResponse(r => r.request().method() === "PATCH" && r.url().endsWith(`/webhooks/${hook.subscription.id}`));
  await hookObject.getByRole("checkbox", { name: "启用" }).click();
  expect((await hookDisabled).status()).toBe(200);
  await expect(hookObject.getByRole("checkbox", { name: "启用" })).not.toBeChecked();
  const hookRotated = page.waitForResponse(r => r.request().method() === "POST" && r.url().endsWith(`/webhooks/${hook.subscription.id}/rotate`));
  await hookObject.getByRole("button", { name: `轮换 Hook ${suffix} 的签名` }).click();
  const hookRotationResponse = await hookRotated;
  expect(hookRotationResponse.status()).toBe(200);
  const hookRotation = await hookRotationResponse.json() as { signingSecret: string };
  expect(hookRotation.signingSecret !== hook.signingSecret).toBe(true);
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.reload();
  await page.getByRole("combobox", { name: "工作区" }).selectOption(workspace.id);
  await navigate();
  await panel.getByRole("tab", { name: /Webhook/ }).click();
  await expect(hookObject).toContainText("https://example.com/semlia-qa/b");
  await expect(hookObject).toContainText("catalog.asset.changed");
  await expect(hookObject.getByRole("checkbox", { name: "启用" })).not.toBeChecked();
  await expect(panel.getByText("尚无投递记录")).toBeVisible();
  const hookList = await request.get(`/api/v1/workspaces/${workspace.id}/webhooks`, { headers: { "X-Semlia-Principal": "local-author" } });
  const hookListBody = await hookList.text();
  expect(hookListBody.includes(hook.signingSecret) || hookListBody.includes(hookRotation.signingSecret)).toBe(false);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false);
  await page.screenshot({ path: resolve(evidence, `${testInfo.project.name}-persisted-disabled-webhook.png`), fullPage: true });
});
