// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ask.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAskRequest = `-- name: ClaimAskRequest :one
INSERT INTO ask_requests(workspace_id,requested_by,idempotency_key,input_digest,knowledge_digest,agent_run_id,claim_token,call_deadline,status,created_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,'running',$9)
ON CONFLICT DO NOTHING RETURNING workspace_id, requested_by, idempotency_key, input_digest, knowledge_digest, agent_run_id, claim_token, call_deadline, status, semantic_query_id, error_code, created_at, completed_at
`

type ClaimAskRequestParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	RequestedBy     pgtype.UUID        `json:"requested_by"`
	IdempotencyKey  string             `json:"idempotency_key"`
	InputDigest     string             `json:"input_digest"`
	KnowledgeDigest string             `json:"knowledge_digest"`
	AgentRunID      pgtype.UUID        `json:"agent_run_id"`
	ClaimToken      pgtype.UUID        `json:"claim_token"`
	CallDeadline    pgtype.Timestamptz `json:"call_deadline"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ClaimAskRequest(ctx context.Context, arg ClaimAskRequestParams) (AskRequest, error) {
	row := q.db.QueryRow(ctx, claimAskRequest,
		arg.WorkspaceID,
		arg.RequestedBy,
		arg.IdempotencyKey,
		arg.InputDigest,
		arg.KnowledgeDigest,
		arg.AgentRunID,
		arg.ClaimToken,
		arg.CallDeadline,
		arg.CreatedAt,
	)
	var i AskRequest
	err := row.Scan(
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.IdempotencyKey,
		&i.InputDigest,
		&i.KnowledgeDigest,
		&i.AgentRunID,
		&i.ClaimToken,
		&i.CallDeadline,
		&i.Status,
		&i.SemanticQueryID,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeAskRequest = `-- name: CompleteAskRequest :one
UPDATE ask_requests SET status=$5,semantic_query_id=$6,error_code=$7,completed_at=$8
WHERE workspace_id=$1 AND requested_by=$2 AND idempotency_key=$3 AND claim_token=$4 AND status='running'
RETURNING workspace_id, requested_by, idempotency_key, input_digest, knowledge_digest, agent_run_id, claim_token, call_deadline, status, semantic_query_id, error_code, created_at, completed_at
`

type CompleteAskRequestParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	RequestedBy     pgtype.UUID        `json:"requested_by"`
	IdempotencyKey  string             `json:"idempotency_key"`
	ClaimToken      pgtype.UUID        `json:"claim_token"`
	Status          string             `json:"status"`
	SemanticQueryID pgtype.UUID        `json:"semantic_query_id"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CompleteAskRequest(ctx context.Context, arg CompleteAskRequestParams) (AskRequest, error) {
	row := q.db.QueryRow(ctx, completeAskRequest,
		arg.WorkspaceID,
		arg.RequestedBy,
		arg.IdempotencyKey,
		arg.ClaimToken,
		arg.Status,
		arg.SemanticQueryID,
		arg.ErrorCode,
		arg.CompletedAt,
	)
	var i AskRequest
	err := row.Scan(
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.IdempotencyKey,
		&i.InputDigest,
		&i.KnowledgeDigest,
		&i.AgentRunID,
		&i.ClaimToken,
		&i.CallDeadline,
		&i.Status,
		&i.SemanticQueryID,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const expiredAskRequests = `-- name: ExpiredAskRequests :many
SELECT workspace_id, requested_by, idempotency_key, input_digest, knowledge_digest, agent_run_id, claim_token, call_deadline, status, semantic_query_id, error_code, created_at, completed_at FROM ask_requests WHERE status='running' AND call_deadline<=clock_timestamp()
ORDER BY call_deadline LIMIT $1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) ExpiredAskRequests(ctx context.Context, limit int32) ([]AskRequest, error) {
	rows, err := q.db.Query(ctx, expiredAskRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AskRequest{}
	for rows.Next() {
		var i AskRequest
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.RequestedBy,
			&i.IdempotencyKey,
			&i.InputDigest,
			&i.KnowledgeDigest,
			&i.AgentRunID,
			&i.ClaimToken,
			&i.CallDeadline,
			&i.Status,
			&i.SemanticQueryID,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAskRequest = `-- name: GetAskRequest :one
SELECT workspace_id, requested_by, idempotency_key, input_digest, knowledge_digest, agent_run_id, claim_token, call_deadline, status, semantic_query_id, error_code, created_at, completed_at FROM ask_requests WHERE workspace_id=$1 AND requested_by=$2 AND idempotency_key=$3
`

type GetAskRequestParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	RequestedBy    pgtype.UUID `json:"requested_by"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetAskRequest(ctx context.Context, arg GetAskRequestParams) (AskRequest, error) {
	row := q.db.QueryRow(ctx, getAskRequest, arg.WorkspaceID, arg.RequestedBy, arg.IdempotencyKey)
	var i AskRequest
	err := row.Scan(
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.IdempotencyKey,
		&i.InputDigest,
		&i.KnowledgeDigest,
		&i.AgentRunID,
		&i.ClaimToken,
		&i.CallDeadline,
		&i.Status,
		&i.SemanticQueryID,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const lockAskRequest = `-- name: LockAskRequest :one
SELECT workspace_id, requested_by, idempotency_key, input_digest, knowledge_digest, agent_run_id, claim_token, call_deadline, status, semantic_query_id, error_code, created_at, completed_at FROM ask_requests WHERE workspace_id=$1 AND requested_by=$2 AND idempotency_key=$3 FOR UPDATE
`

type LockAskRequestParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	RequestedBy    pgtype.UUID `json:"requested_by"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) LockAskRequest(ctx context.Context, arg LockAskRequestParams) (AskRequest, error) {
	row := q.db.QueryRow(ctx, lockAskRequest, arg.WorkspaceID, arg.RequestedBy, arg.IdempotencyKey)
	var i AskRequest
	err := row.Scan(
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.IdempotencyKey,
		&i.InputDigest,
		&i.KnowledgeDigest,
		&i.AgentRunID,
		&i.ClaimToken,
		&i.CallDeadline,
		&i.Status,
		&i.SemanticQueryID,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
