// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpWorkspaceAuthorizationVersion = `-- name: BumpWorkspaceAuthorizationVersion :one
UPDATE workspaces
SET authorization_version = authorization_version + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING authorization_version
`

func (q *Queries) BumpWorkspaceAuthorizationVersion(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, bumpWorkspaceAuthorizationVersion, workspaceID)
	var authorization_version int64
	err := row.Scan(&authorization_version)
	return authorization_version, err
}

const createAuthorizationEvent = `-- name: CreateAuthorizationEvent :exec
INSERT INTO authorization_events (
    id, workspace_id, principal_id, actor, action, resource_type, resource_id,
    decision, reason_code, authorization_version, trace_id, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12
)
`

type CreateAuthorizationEventParams struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	PrincipalID          pgtype.UUID        `json:"principal_id"`
	Actor                string             `json:"actor"`
	Action               string             `json:"action"`
	ResourceType         string             `json:"resource_type"`
	ResourceID           string             `json:"resource_id"`
	Decision             string             `json:"decision"`
	ReasonCode           string             `json:"reason_code"`
	AuthorizationVersion int64              `json:"authorization_version"`
	TraceID              string             `json:"trace_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthorizationEvent(ctx context.Context, arg CreateAuthorizationEventParams) error {
	_, err := q.db.Exec(ctx, createAuthorizationEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.Actor,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Decision,
		arg.ReasonCode,
		arg.AuthorizationVersion,
		arg.TraceID,
		arg.CreatedAt,
	)
	return err
}

const createPrincipal = `-- name: CreatePrincipal :one
INSERT INTO principals (id, workspace_id, kind, display_name, owner_principal_id, status)
VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, workspace_id, kind, display_name, owner_principal_id, status, created_at
`

type CreatePrincipalParams struct {
	ID               pgtype.UUID `json:"id"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	Kind             string      `json:"kind"`
	DisplayName      string      `json:"display_name"`
	OwnerPrincipalID pgtype.UUID `json:"owner_principal_id"`
	Status           string      `json:"status"`
}

func (q *Queries) CreatePrincipal(ctx context.Context, arg CreatePrincipalParams) (Principal, error) {
	row := q.db.QueryRow(ctx, createPrincipal,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.DisplayName,
		arg.OwnerPrincipalID,
		arg.Status,
	)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.DisplayName,
		&i.OwnerPrincipalID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createRoleBinding = `-- name: CreateRoleBinding :one
INSERT INTO role_bindings (id, principal_id, role_id, scope_type, scope_id, granted_by)
VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, principal_id, role_id, scope_type, scope_id, granted_by, granted_at
`

type CreateRoleBindingParams struct {
	ID          pgtype.UUID `json:"id"`
	PrincipalID pgtype.UUID `json:"principal_id"`
	RoleID      string      `json:"role_id"`
	ScopeType   string      `json:"scope_type"`
	ScopeID     string      `json:"scope_id"`
	GrantedBy   pgtype.UUID `json:"granted_by"`
}

func (q *Queries) CreateRoleBinding(ctx context.Context, arg CreateRoleBindingParams) (RoleBinding, error) {
	row := q.db.QueryRow(ctx, createRoleBinding,
		arg.ID,
		arg.PrincipalID,
		arg.RoleID,
		arg.ScopeType,
		arg.ScopeID,
		arg.GrantedBy,
	)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.GrantedBy,
		&i.GrantedAt,
	)
	return i, err
}

const getDefaultWorkspacePrincipal = `-- name: GetDefaultWorkspacePrincipal :one
SELECT principal.id, principal.workspace_id, principal.kind, principal.display_name, principal.owner_principal_id, principal.status, principal.created_at FROM principals AS principal
JOIN role_bindings AS binding ON binding.principal_id = principal.id
WHERE principal.workspace_id = $1
  AND binding.role_id = 'workspace_admin'
  AND binding.scope_type = 'workspace'
  AND binding.scope_id = $1::text
  AND binding.granted_by IS NULL
ORDER BY principal.created_at, principal.id
LIMIT 1
`

func (q *Queries) GetDefaultWorkspacePrincipal(ctx context.Context, workspaceID pgtype.UUID) (Principal, error) {
	row := q.db.QueryRow(ctx, getDefaultWorkspacePrincipal, workspaceID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.DisplayName,
		&i.OwnerPrincipalID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceAuthorizationVersion = `-- name: GetWorkspaceAuthorizationVersion :one
SELECT authorization_version FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceAuthorizationVersion(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getWorkspaceAuthorizationVersion, workspaceID)
	var authorization_version int64
	err := row.Scan(&authorization_version)
	return authorization_version, err
}

const getWorkspacePrincipal = `-- name: GetWorkspacePrincipal :one
SELECT id, workspace_id, kind, display_name, owner_principal_id, status, created_at FROM principals
WHERE workspace_id = $1 AND id = $2
`

type GetWorkspacePrincipalParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	PrincipalID pgtype.UUID `json:"principal_id"`
}

func (q *Queries) GetWorkspacePrincipal(ctx context.Context, arg GetWorkspacePrincipalParams) (Principal, error) {
	row := q.db.QueryRow(ctx, getWorkspacePrincipal, arg.WorkspaceID, arg.PrincipalID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.DisplayName,
		&i.OwnerPrincipalID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPrincipalRoleBindings = `-- name: ListPrincipalRoleBindings :many
SELECT id, principal_id, role_id, scope_type, scope_id, granted_by, granted_at FROM role_bindings
WHERE principal_id = $1
ORDER BY granted_at, id
`

func (q *Queries) ListPrincipalRoleBindings(ctx context.Context, principalID pgtype.UUID) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, listPrincipalRoleBindings, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleBinding{}
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.RoleID,
			&i.ScopeType,
			&i.ScopeID,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleActionsForRoles = `-- name: ListRoleActionsForRoles :many
SELECT role_id, action FROM role_actions
WHERE role_id = ANY ($1::text[])
`

func (q *Queries) ListRoleActionsForRoles(ctx context.Context, roleIds []string) ([]RoleAction, error) {
	rows, err := q.db.Query(ctx, listRoleActionsForRoles, roleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleAction{}
	for rows.Next() {
		var i RoleAction
		if err := rows.Scan(&i.RoleID, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
