// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatalogAssetRevisions = `-- name: CountCatalogAssetRevisions :one
SELECT count(*)::bigint
FROM asset_revisions
WHERE workspace_id = $1
  AND asset_id = $2
`

type CountCatalogAssetRevisionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
}

func (q *Queries) CountCatalogAssetRevisions(ctx context.Context, arg CountCatalogAssetRevisionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogAssetRevisions, arg.WorkspaceID, arg.AssetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCatalogAssets = `-- name: CountCatalogAssets :one
SELECT count(*)::bigint
FROM semantic_assets AS asset
LEFT JOIN asset_revisions AS revision ON revision.id = asset.current_revision_id
WHERE asset.workspace_id = $1
  AND ($2::text = '' OR asset.asset_type = $2::text)
  AND ($3::text = '' OR asset.lifecycle_state = $3::text)
  AND (
      $4::text = ''
      OR asset.namespace || '.' || asset.key ILIKE '%' || $4::text || '%'
      OR to_tsvector('simple', COALESCE(revision.content::text, '')) @@
         plainto_tsquery('simple', $4::text)
  )
`

type CountCatalogAssetsParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	AssetType      string      `json:"asset_type"`
	LifecycleState string      `json:"lifecycle_state"`
	Search         string      `json:"search"`
}

func (q *Queries) CountCatalogAssets(ctx context.Context, arg CountCatalogAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogAssets,
		arg.WorkspaceID,
		arg.AssetType,
		arg.LifecycleState,
		arg.Search,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCatalogAsset = `-- name: GetCatalogAsset :one
SELECT asset.id,
       asset.workspace_id,
       asset.namespace,
       asset.key,
       asset.asset_type,
       asset.lifecycle_state,
       asset.current_revision_id,
       asset.created_at,
       asset.updated_at,
       revision.id AS revision_id,
       revision.sequence AS revision_sequence,
       revision.schema_version,
       revision.content_digest,
       revision.content,
       revision.created_by,
       revision.created_at AS revision_created_at,
       COALESCE(NULLIF(revision.content->>'displayName', ''), revision.content->>'name', revision.content->>'title', asset.key) AS title,
       COALESCE(revision.content->>'summary', revision.content->>'definition', '')::text AS summary,
       (SELECT count(*)::integer
        FROM semantic_relations relation
        WHERE relation.workspace_id = asset.workspace_id
          AND (relation.subject_asset_id = asset.id OR relation.object_asset_id = asset.id)) AS relation_count
FROM semantic_assets AS asset
LEFT JOIN asset_revisions AS revision ON revision.id = asset.current_revision_id
WHERE asset.workspace_id = $1
  AND asset.id = $2
`

type GetCatalogAssetParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
}

type GetCatalogAssetRow struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Namespace         string             `json:"namespace"`
	Key               string             `json:"key"`
	AssetType         string             `json:"asset_type"`
	LifecycleState    string             `json:"lifecycle_state"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	RevisionID        pgtype.UUID        `json:"revision_id"`
	RevisionSequence  pgtype.Int8        `json:"revision_sequence"`
	SchemaVersion     pgtype.Text        `json:"schema_version"`
	ContentDigest     pgtype.Text        `json:"content_digest"`
	Content           []byte             `json:"content"`
	CreatedBy         pgtype.Text        `json:"created_by"`
	RevisionCreatedAt pgtype.Timestamptz `json:"revision_created_at"`
	Title             string             `json:"title"`
	Summary           string             `json:"summary"`
	RelationCount     int32              `json:"relation_count"`
}

func (q *Queries) GetCatalogAsset(ctx context.Context, arg GetCatalogAssetParams) (GetCatalogAssetRow, error) {
	row := q.db.QueryRow(ctx, getCatalogAsset, arg.WorkspaceID, arg.AssetID)
	var i GetCatalogAssetRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Namespace,
		&i.Key,
		&i.AssetType,
		&i.LifecycleState,
		&i.CurrentRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionID,
		&i.RevisionSequence,
		&i.SchemaVersion,
		&i.ContentDigest,
		&i.Content,
		&i.CreatedBy,
		&i.RevisionCreatedAt,
		&i.Title,
		&i.Summary,
		&i.RelationCount,
	)
	return i, err
}

const getCatalogAssetAuthorityFacts = `-- name: GetCatalogAssetAuthorityFacts :one
WITH latest_pin AS (
    SELECT release_asset.release_id,
           release_asset.revision_id,
           release.sequence AS release_sequence,
           release.origin_proposal_id
    FROM release_assets AS release_asset
    JOIN releases AS release
      ON release.workspace_id = release_asset.workspace_id
     AND release.id = release_asset.release_id
    WHERE release_asset.workspace_id = $1
      AND release_asset.asset_id = $2
    ORDER BY release.sequence DESC, release.id DESC
    LIMIT 1
), effective_objects AS (
    SELECT DISTINCT ON (snapshot.object_type, snapshot.object_id)
           snapshot.object_type, snapshot.object_id, snapshot.payload,
           snapshot.release_id, release.sequence AS release_sequence
    FROM release_object_snapshots AS snapshot
    JOIN releases AS release
      ON release.workspace_id = snapshot.workspace_id
     AND release.id = snapshot.release_id
    WHERE snapshot.workspace_id = $1
    ORDER BY snapshot.object_type, snapshot.object_id, release.sequence DESC, release.id DESC
), asset_objects AS (
    SELECT object_type, object_id, payload, release_id, release_sequence
    FROM effective_objects
    WHERE object_type IN ('physical_binding', 'model_grain', 'entity_key')
      AND payload->>'asset_id' = $2::uuid::text
), released_datasets AS (
    SELECT DISTINCT (payload->>'dataset_id')::uuid AS dataset_id
    FROM asset_objects
    WHERE object_type = 'physical_binding'
      AND payload ? 'dataset_id'
), join_objects AS (
    SELECT object_type, object_id, payload, release_id, release_sequence
    FROM effective_objects
    WHERE object_type = 'join_contract'
      AND (
          (payload->>'left_dataset_id')::uuid IN (SELECT dataset_id FROM released_datasets)
          OR (payload->>'right_dataset_id')::uuid IN (SELECT dataset_id FROM released_datasets)
      )
), object_facts AS (
    SELECT count(*) FILTER (
               WHERE object_type = 'physical_binding'
           )::bigint AS physical_binding_count,
           count(*) FILTER (
               WHERE object_type = 'model_grain'
           )::bigint AS model_grain_count,
           count(*) FILTER (
               WHERE object_type = 'entity_key'
           )::bigint AS entity_key_count
    FROM asset_objects
), object_basis AS (
    SELECT release_id, release_sequence
    FROM asset_objects
    ORDER BY release_sequence DESC, release_id DESC
    LIMIT 1
), join_facts AS (
    SELECT count(*)::bigint AS join_contract_count
    FROM join_objects
), join_basis AS (
    SELECT release_id, release_sequence
    FROM join_objects
    ORDER BY release_sequence DESC, release_id DESC
    LIMIT 1
), validation_counts AS (
    SELECT count(DISTINCT run.id)::bigint AS run_count,
           count(result.id) FILTER (WHERE result.severity = 'blocker')::bigint AS blocker_count,
           count(result.id) FILTER (WHERE result.severity = 'warning')::bigint AS warning_count
    FROM latest_pin
    JOIN validation_runs AS run
      ON run.workspace_id = $1
     AND run.proposal_id = latest_pin.origin_proposal_id
    LEFT JOIN validation_results AS result
      ON result.workspace_id = run.workspace_id
     AND result.validation_run_id = run.id
), current_release AS (
    SELECT release.id
    FROM releases AS release
    WHERE release.workspace_id = $1
    ORDER BY release.sequence DESC, release.id DESC
    LIMIT 1
), effective_bindings AS (
    SELECT binding.mode,
           CASE WHEN binding.mode = 'current' THEN current_release.id ELSE binding.release_id END AS effective_release_id
    FROM consumer_bindings AS binding
    LEFT JOIN current_release ON true
    WHERE binding.workspace_id = $1
      AND binding.status = 'active'
      AND (binding.expires_at IS NULL OR binding.expires_at > CURRENT_TIMESTAMP)
), consumer_counts AS (
    SELECT count(*) FILTER (WHERE binding.mode = 'current')::bigint AS current_count,
           count(*) FILTER (WHERE binding.mode = 'pinned')::bigint AS pinned_count
    FROM effective_bindings AS binding
    JOIN latest_pin ON true
    JOIN release_assets AS manifest
      ON manifest.workspace_id = $1
     AND manifest.release_id = binding.effective_release_id
     AND manifest.asset_id = $2
     AND manifest.revision_id = latest_pin.revision_id
), basis AS (
    SELECT asset.current_revision_id,
           latest_pin.release_id,
           latest_pin.revision_id AS released_revision_id,
           latest_pin.release_sequence,
		   asset.current_revision_id AS evidence_revision_id
    FROM semantic_assets AS asset
    LEFT JOIN latest_pin ON true
    WHERE asset.workspace_id = $1
      AND asset.id = $2
)
SELECT basis.current_revision_id,
       basis.release_id,
       basis.released_revision_id,
       basis.release_sequence,
       basis.evidence_revision_id,
       (SELECT release_id FROM object_basis) AS physical_release_id,
       COALESCE((SELECT release_sequence FROM object_basis), 0)::bigint AS physical_release_sequence,
       (SELECT release_id FROM join_basis) AS join_release_id,
       COALESCE((SELECT release_sequence FROM join_basis), 0)::bigint AS join_release_sequence,
       (SELECT count(*)::bigint FROM semantic_relations AS relation
        WHERE relation.workspace_id = $1
          AND (relation.subject_asset_id = $2 OR relation.object_asset_id = $2)) AS relation_count,
       (SELECT count(*)::bigint
        FROM lineage_edges AS edge
        WHERE edge.workspace_id = $1
          AND (edge.upstream_dataset_id IN (SELECT dataset_id FROM released_datasets)
            OR edge.downstream_dataset_id IN (SELECT dataset_id FROM released_datasets))) AS lineage_count,
       COALESCE((SELECT physical_binding_count FROM object_facts), 0)::bigint AS physical_binding_count,
       COALESCE((SELECT model_grain_count FROM object_facts), 0)::bigint AS model_grain_count,
       COALESCE((SELECT entity_key_count FROM object_facts), 0)::bigint AS entity_key_count,
       COALESCE((SELECT join_contract_count FROM join_facts), 0)::bigint AS join_contract_count,
       COALESCE((SELECT run_count FROM validation_counts), 0)::bigint AS validation_run_count,
       COALESCE((SELECT blocker_count FROM validation_counts), 0)::bigint AS validation_blocker_count,
       COALESCE((SELECT warning_count FROM validation_counts), 0)::bigint AS validation_warning_count,
       (SELECT count(*)::bigint FROM revision_evidence_links AS link
        WHERE link.workspace_id = $1
          AND link.asset_revision_id = basis.evidence_revision_id) AS evidence_count,
       COALESCE((SELECT current_count FROM consumer_counts), 0)::bigint AS current_consumer_count,
       COALESCE((SELECT pinned_count FROM consumer_counts), 0)::bigint AS pinned_consumer_count
FROM basis
`

type GetCatalogAssetAuthorityFactsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
}

type GetCatalogAssetAuthorityFactsRow struct {
	CurrentRevisionID       pgtype.UUID `json:"current_revision_id"`
	ReleaseID               pgtype.UUID `json:"release_id"`
	ReleasedRevisionID      pgtype.UUID `json:"released_revision_id"`
	ReleaseSequence         pgtype.Int8 `json:"release_sequence"`
	EvidenceRevisionID      pgtype.UUID `json:"evidence_revision_id"`
	PhysicalReleaseID       pgtype.UUID `json:"physical_release_id"`
	PhysicalReleaseSequence int64       `json:"physical_release_sequence"`
	JoinReleaseID           pgtype.UUID `json:"join_release_id"`
	JoinReleaseSequence     int64       `json:"join_release_sequence"`
	RelationCount           int64       `json:"relation_count"`
	LineageCount            int64       `json:"lineage_count"`
	PhysicalBindingCount    int64       `json:"physical_binding_count"`
	ModelGrainCount         int64       `json:"model_grain_count"`
	EntityKeyCount          int64       `json:"entity_key_count"`
	JoinContractCount       int64       `json:"join_contract_count"`
	ValidationRunCount      int64       `json:"validation_run_count"`
	ValidationBlockerCount  int64       `json:"validation_blocker_count"`
	ValidationWarningCount  int64       `json:"validation_warning_count"`
	EvidenceCount           int64       `json:"evidence_count"`
	CurrentConsumerCount    int64       `json:"current_consumer_count"`
	PinnedConsumerCount     int64       `json:"pinned_consumer_count"`
}

func (q *Queries) GetCatalogAssetAuthorityFacts(ctx context.Context, arg GetCatalogAssetAuthorityFactsParams) (GetCatalogAssetAuthorityFactsRow, error) {
	row := q.db.QueryRow(ctx, getCatalogAssetAuthorityFacts, arg.WorkspaceID, arg.AssetID)
	var i GetCatalogAssetAuthorityFactsRow
	err := row.Scan(
		&i.CurrentRevisionID,
		&i.ReleaseID,
		&i.ReleasedRevisionID,
		&i.ReleaseSequence,
		&i.EvidenceRevisionID,
		&i.PhysicalReleaseID,
		&i.PhysicalReleaseSequence,
		&i.JoinReleaseID,
		&i.JoinReleaseSequence,
		&i.RelationCount,
		&i.LineageCount,
		&i.PhysicalBindingCount,
		&i.ModelGrainCount,
		&i.EntityKeyCount,
		&i.JoinContractCount,
		&i.ValidationRunCount,
		&i.ValidationBlockerCount,
		&i.ValidationWarningCount,
		&i.EvidenceCount,
		&i.CurrentConsumerCount,
		&i.PinnedConsumerCount,
	)
	return i, err
}

const getCatalogAssetForUpdate = `-- name: GetCatalogAssetForUpdate :one
SELECT id, workspace_id, namespace, key, asset_type, lifecycle_state, current_revision_id, created_at, updated_at
FROM semantic_assets
WHERE workspace_id = $1
  AND id = $2
FOR UPDATE
`

type GetCatalogAssetForUpdateParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
}

func (q *Queries) GetCatalogAssetForUpdate(ctx context.Context, arg GetCatalogAssetForUpdateParams) (SemanticAsset, error) {
	row := q.db.QueryRow(ctx, getCatalogAssetForUpdate, arg.WorkspaceID, arg.AssetID)
	var i SemanticAsset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Namespace,
		&i.Key,
		&i.AssetType,
		&i.LifecycleState,
		&i.CurrentRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCatalogAssetRevision = `-- name: GetCatalogAssetRevision :one
SELECT id, workspace_id, asset_id, sequence, schema_version, content_digest, content, created_by, created_at
FROM asset_revisions
WHERE workspace_id = $1
  AND asset_id = $2
  AND id = $3
`

type GetCatalogAssetRevisionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
	RevisionID  pgtype.UUID `json:"revision_id"`
}

func (q *Queries) GetCatalogAssetRevision(ctx context.Context, arg GetCatalogAssetRevisionParams) (AssetRevision, error) {
	row := q.db.QueryRow(ctx, getCatalogAssetRevision, arg.WorkspaceID, arg.AssetID, arg.RevisionID)
	var i AssetRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AssetID,
		&i.Sequence,
		&i.SchemaVersion,
		&i.ContentDigest,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCatalogDiscoveryFindings = `-- name: GetCatalogDiscoveryFindings :many
SELECT id, discovery_run_id, sequence, code, severity, locator, details, created_at
FROM discovery_findings
WHERE discovery_run_id = $1
ORDER BY sequence
`

func (q *Queries) GetCatalogDiscoveryFindings(ctx context.Context, runID pgtype.UUID) ([]DiscoveryFinding, error) {
	rows, err := q.db.Query(ctx, getCatalogDiscoveryFindings, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoveryFinding{}
	for rows.Next() {
		var i DiscoveryFinding
		if err := rows.Scan(
			&i.ID,
			&i.DiscoveryRunID,
			&i.Sequence,
			&i.Code,
			&i.Severity,
			&i.Locator,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCatalogDiscoveryRun = `-- name: GetCatalogDiscoveryRun :one
SELECT id, workspace_id, source_connection_id, source_revision_id, adapter_version, status, error_code, stats, started_at, completed_at, created_at, updated_at, credential_version, job_id, requested_by, trace_id, projection_reused, artifact_set_id, request_fingerprint, source_input_fingerprint, source_config
FROM discovery_runs
WHERE workspace_id = $1
  AND id = $2
`

type GetCatalogDiscoveryRunParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RunID       pgtype.UUID `json:"run_id"`
}

func (q *Queries) GetCatalogDiscoveryRun(ctx context.Context, arg GetCatalogDiscoveryRunParams) (DiscoveryRun, error) {
	row := q.db.QueryRow(ctx, getCatalogDiscoveryRun, arg.WorkspaceID, arg.RunID)
	var i DiscoveryRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceConnectionID,
		&i.SourceRevisionID,
		&i.AdapterVersion,
		&i.Status,
		&i.ErrorCode,
		&i.Stats,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CredentialVersion,
		&i.JobID,
		&i.RequestedBy,
		&i.TraceID,
		&i.ProjectionReused,
		&i.ArtifactSetID,
		&i.RequestFingerprint,
		&i.SourceInputFingerprint,
		&i.SourceConfig,
	)
	return i, err
}

const getRevisionEvidence = `-- name: GetRevisionEvidence :many
SELECT evidence.id, evidence.workspace_id, evidence.evidence_type, evidence.source_revision_id, evidence.locator, evidence.content_digest, evidence.metadata, evidence.created_at, link.role, link.field_path, link.note
FROM revision_evidence_links AS link
JOIN evidence_artifacts AS evidence ON evidence.id = link.evidence_artifact_id
WHERE link.workspace_id = $1
  AND link.asset_revision_id = $2
ORDER BY link.role, evidence.id
`

type GetRevisionEvidenceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RevisionID  pgtype.UUID `json:"revision_id"`
}

type GetRevisionEvidenceRow struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	EvidenceType     string             `json:"evidence_type"`
	SourceRevisionID pgtype.UUID        `json:"source_revision_id"`
	Locator          string             `json:"locator"`
	ContentDigest    string             `json:"content_digest"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Role             string             `json:"role"`
	FieldPath        pgtype.Text        `json:"field_path"`
	Note             pgtype.Text        `json:"note"`
}

func (q *Queries) GetRevisionEvidence(ctx context.Context, arg GetRevisionEvidenceParams) ([]GetRevisionEvidenceRow, error) {
	rows, err := q.db.Query(ctx, getRevisionEvidence, arg.WorkspaceID, arg.RevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevisionEvidenceRow{}
	for rows.Next() {
		var i GetRevisionEvidenceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EvidenceType,
			&i.SourceRevisionID,
			&i.Locator,
			&i.ContentDigest,
			&i.Metadata,
			&i.CreatedAt,
			&i.Role,
			&i.FieldPath,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkRevisionEvidence = `-- name: LinkRevisionEvidence :execrows
INSERT INTO revision_evidence_links (
    workspace_id, asset_revision_id, evidence_artifact_id, role
)
SELECT $1, $2, evidence.id, 'supports'
FROM evidence_artifacts AS evidence
WHERE evidence.workspace_id = $1
  AND evidence.id = $3
`

type LinkRevisionEvidenceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RevisionID  pgtype.UUID `json:"revision_id"`
	EvidenceID  pgtype.UUID `json:"evidence_id"`
}

func (q *Queries) LinkRevisionEvidence(ctx context.Context, arg LinkRevisionEvidenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkRevisionEvidence, arg.WorkspaceID, arg.RevisionID, arg.EvidenceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCatalogAssetAuthorityRecords = `-- name: ListCatalogAssetAuthorityRecords :many
WITH latest_pin AS (
    SELECT release_asset.release_id, release_asset.revision_id,
           release.sequence AS release_sequence, release.origin_proposal_id
    FROM release_assets AS release_asset
    JOIN releases AS release
      ON release.workspace_id = release_asset.workspace_id AND release.id = release_asset.release_id
    WHERE release_asset.workspace_id = $5
      AND release_asset.asset_id = $6
    ORDER BY release.sequence DESC, release.id DESC
    LIMIT 1
), effective_objects AS (
    SELECT DISTINCT ON (snapshot.object_type, snapshot.object_id)
           snapshot.object_type, snapshot.object_id, snapshot.version, snapshot.payload,
           snapshot.release_id, release.sequence AS release_sequence
    FROM release_object_snapshots AS snapshot
    JOIN releases AS release
      ON release.workspace_id = snapshot.workspace_id AND release.id = snapshot.release_id
    WHERE snapshot.workspace_id = $5
    ORDER BY snapshot.object_type, snapshot.object_id, release.sequence DESC, release.id DESC
), asset_objects AS (
    SELECT object_type, object_id, version, payload, release_id, release_sequence FROM effective_objects
    WHERE object_type IN ('physical_binding', 'model_grain', 'entity_key')
      AND payload->>'asset_id' = $6::uuid::text
), asset_datasets AS (
    SELECT DISTINCT (payload->>'dataset_id')::uuid AS dataset_id
    FROM asset_objects
    WHERE object_type = 'physical_binding' AND payload ? 'dataset_id'
), join_objects AS (
    SELECT object_type, object_id, version, payload, release_id, release_sequence FROM effective_objects
    WHERE object_type = 'join_contract'
      AND ((payload->>'left_dataset_id')::uuid IN (SELECT dataset_id FROM asset_datasets)
        OR (payload->>'right_dataset_id')::uuid IN (SELECT dataset_id FROM asset_datasets))
), current_release AS (
    SELECT release.id
    FROM releases AS release
    WHERE release.workspace_id = $5
    ORDER BY release.sequence DESC, release.id DESC
    LIMIT 1
), effective_bindings AS (
    SELECT binding.id, binding.workspace_id, binding.consumer_id, binding.environment, binding.purpose, binding.mode, binding.release_id, binding.compatibility_constraint, binding.expires_at, binding.status, binding.version, binding.created_at, binding.updated_at,
           CASE WHEN binding.mode = 'current' THEN current_release.id ELSE binding.release_id END AS effective_release_id
    FROM consumer_bindings AS binding
    LEFT JOIN current_release ON true
    WHERE binding.workspace_id = $5
      AND binding.status = 'active'
      AND (binding.expires_at IS NULL OR binding.expires_at > CURRENT_TIMESTAMP)
), records AS (
    SELECT 'relations'::text AS section_kind, 'relation'::text AS record_kind,
           relation.id AS record_id, 'semantic_relations'::text AS authority,
           NULL::uuid AS release_id, 0::bigint AS release_sequence, 0::integer AS version,
           relation.assertion_state AS status, relation.predicate AS label,
           CASE WHEN relation.subject_asset_id = $6
                THEN relation.object_asset_id ELSE relation.subject_asset_id END::text AS related_id,
           jsonb_build_object(
               'direction', CASE WHEN relation.subject_asset_id = $6 THEN 'outgoing' ELSE 'incoming' END,
               'predicate', relation.predicate, 'plane', relation.plane,
               'assertionState', relation.assertion_state,
               'subjectAssetId', relation.subject_asset_id,
               'objectAssetId', relation.object_asset_id
           ) AS details
    FROM semantic_relations AS relation
    WHERE relation.workspace_id = $5
      AND (relation.subject_asset_id = $6 OR relation.object_asset_id = $6)
    UNION ALL
    SELECT 'physical_bindings', object_type, object_id, 'release_object_snapshots',
           release_id, release_sequence, version,
           CASE WHEN object_type = 'physical_binding' AND payload->>'retired_at' IS NOT NULL THEN 'retired' ELSE 'available' END,
           CASE object_type
               WHEN 'physical_binding' THEN COALESCE(payload->>'transform', payload->>'dataset_id', object_type)
               WHEN 'model_grain' THEN COALESCE(payload->>'grain_expression', object_type)
               WHEN 'entity_key' THEN COALESCE(payload->>'uniqueness_semantics', object_type)
           END,
           CASE WHEN object_type = 'physical_binding' THEN COALESCE(payload->>'dataset_id', '') ELSE '' END,
           CASE object_type
               WHEN 'physical_binding' THEN jsonb_build_object(
                   'assetId', payload->>'asset_id', 'datasetId', payload->>'dataset_id',
                   'fieldId', payload->>'field_id', 'transform', payload->>'transform'
               )
               WHEN 'model_grain' THEN jsonb_build_object(
                   'assetId', payload->>'asset_id', 'grainExpression', payload->>'grain_expression',
                   'grainFieldRefs', COALESCE(payload->'grain_field_refs', '[]'::jsonb),
                   'documentedBy', payload->>'documented_by'
               )
               WHEN 'entity_key' THEN jsonb_build_object(
                   'assetId', payload->>'asset_id',
                   'keyFieldRefs', COALESCE(payload->'key_field_refs', '[]'::jsonb),
                   'uniquenessSemantics', payload->>'uniqueness_semantics'
               )
           END
    FROM asset_objects
    UNION ALL
    SELECT 'join_contracts', object_type, object_id, 'release_object_snapshots',
           release_id, release_sequence, version, COALESCE(payload->>'status', 'available'),
           COALESCE(payload->>'join_expression', payload->>'cardinality', object_type),
           CASE
               WHEN (payload->>'left_dataset_id')::uuid IN (SELECT dataset_id FROM asset_datasets)
                AND (payload->>'right_dataset_id')::uuid NOT IN (SELECT dataset_id FROM asset_datasets)
                 THEN COALESCE(payload->>'right_dataset_id', '')
               WHEN (payload->>'right_dataset_id')::uuid IN (SELECT dataset_id FROM asset_datasets)
                 THEN COALESCE(payload->>'left_dataset_id', '')
               ELSE ''
           END,
           jsonb_build_object(
               'direction', CASE
                   WHEN (payload->>'left_dataset_id')::uuid IN (SELECT dataset_id FROM asset_datasets)
                    AND (payload->>'right_dataset_id')::uuid IN (SELECT dataset_id FROM asset_datasets) THEN 'both'
                   WHEN (payload->>'left_dataset_id')::uuid IN (SELECT dataset_id FROM asset_datasets) THEN 'outgoing'
                   ELSE 'incoming'
               END,
               'leftDatasetId', payload->>'left_dataset_id',
               'rightDatasetId', payload->>'right_dataset_id',
               'leftFieldRefs', COALESCE(payload->'left_field_refs', '[]'::jsonb),
               'rightFieldRefs', COALESCE(payload->'right_field_refs', '[]'::jsonb),
               'joinType', payload->>'join_type', 'cardinality', payload->>'cardinality',
               'joinExpression', payload->>'join_expression'
           )
    FROM join_objects
    UNION ALL
    SELECT 'validation', 'validation_run', run.id, 'validation_runs',
           latest_pin.release_id, latest_pin.release_sequence, 0, run.status, run.validator_id,
           run.proposal_id::text, '{}'::jsonb
    FROM latest_pin
    JOIN validation_runs AS run
      ON run.workspace_id = $5 AND run.proposal_id = latest_pin.origin_proposal_id
    UNION ALL
    SELECT 'lineage', 'lineage', edge.id, 'lineage_edges', NULL, 0, 0, edge.edge_kind,
           edge.edge_kind, CASE WHEN edge.upstream_dataset_id IN (SELECT dataset_id FROM asset_datasets)
                                THEN edge.downstream_dataset_id ELSE edge.upstream_dataset_id END::text,
           jsonb_build_object(
               'direction', CASE WHEN edge.upstream_dataset_id IN (SELECT dataset_id FROM asset_datasets)
                                 THEN 'outgoing' ELSE 'incoming' END,
               'upstreamDatasetId', edge.upstream_dataset_id,
               'downstreamDatasetId', edge.downstream_dataset_id,
               'edgeKind', edge.edge_kind, 'sourceRevisionId', edge.source_revision_id,
               'codeArtifactId', edge.code_artifact_id, 'confidence', edge.confidence
           )
    FROM lineage_edges AS edge
    WHERE edge.workspace_id = $5
      AND (edge.upstream_dataset_id IN (SELECT dataset_id FROM asset_datasets)
        OR edge.downstream_dataset_id IN (SELECT dataset_id FROM asset_datasets))
    UNION ALL
    SELECT 'consumer_impact', 'consumer_binding', binding.id, 'consumer_bindings',
           binding.effective_release_id, release.sequence, binding.version, binding.status,
           binding.environment, binding.consumer_id::text,
           jsonb_build_object('consumerId', binding.consumer_id, 'environment', binding.environment,
                              'purpose', binding.purpose, 'mode', binding.mode, 'status', binding.status,
                              'effectiveReleaseId', binding.effective_release_id,
                              'compatibilityConstraint', binding.compatibility_constraint,
                              'expiresAt', binding.expires_at)
    FROM effective_bindings AS binding
    JOIN latest_pin ON true
    JOIN release_assets AS manifest
      ON manifest.workspace_id = $5
     AND manifest.release_id = binding.effective_release_id
     AND manifest.asset_id = $6
     AND manifest.revision_id = latest_pin.revision_id
    JOIN releases AS release
      ON release.workspace_id = binding.workspace_id AND release.id = binding.effective_release_id
), section_records AS (
    SELECT records.section_kind, records.record_kind, records.record_id, records.authority, records.release_id, records.release_sequence, records.version, records.status, records.label, records.related_id, records.details, count(*) OVER()::bigint AS total_count
    FROM records
    WHERE section_kind = $7::text
)
SELECT section_kind, record_kind, record_id, authority, release_id,
       release_sequence, version, status, label, related_id, details, total_count
FROM section_records
WHERE (
      NOT $1::boolean
      OR record_kind > $2::text
      OR (record_kind = $2::text AND record_id > $3::uuid)
  )
ORDER BY section_kind, record_kind, record_id
LIMIT $4
`

type ListCatalogAssetAuthorityRecordsParams struct {
	HasCursor        bool        `json:"has_cursor"`
	CursorRecordKind string      `json:"cursor_record_kind"`
	CursorRecordID   pgtype.UUID `json:"cursor_record_id"`
	PageLimit        int32       `json:"page_limit"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	AssetID          pgtype.UUID `json:"asset_id"`
	SectionKind      string      `json:"section_kind"`
}

type ListCatalogAssetAuthorityRecordsRow struct {
	SectionKind     string      `json:"section_kind"`
	RecordKind      string      `json:"record_kind"`
	RecordID        pgtype.UUID `json:"record_id"`
	Authority       string      `json:"authority"`
	ReleaseID       pgtype.UUID `json:"release_id"`
	ReleaseSequence int64       `json:"release_sequence"`
	Version         int32       `json:"version"`
	Status          string      `json:"status"`
	Label           string      `json:"label"`
	RelatedID       string      `json:"related_id"`
	Details         []byte      `json:"details"`
	TotalCount      int64       `json:"total_count"`
}

func (q *Queries) ListCatalogAssetAuthorityRecords(ctx context.Context, arg ListCatalogAssetAuthorityRecordsParams) ([]ListCatalogAssetAuthorityRecordsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogAssetAuthorityRecords,
		arg.HasCursor,
		arg.CursorRecordKind,
		arg.CursorRecordID,
		arg.PageLimit,
		arg.WorkspaceID,
		arg.AssetID,
		arg.SectionKind,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogAssetAuthorityRecordsRow{}
	for rows.Next() {
		var i ListCatalogAssetAuthorityRecordsRow
		if err := rows.Scan(
			&i.SectionKind,
			&i.RecordKind,
			&i.RecordID,
			&i.Authority,
			&i.ReleaseID,
			&i.ReleaseSequence,
			&i.Version,
			&i.Status,
			&i.Label,
			&i.RelatedID,
			&i.Details,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogAssetRevisions = `-- name: ListCatalogAssetRevisions :many
SELECT revision.id, revision.workspace_id, revision.asset_id, revision.sequence, revision.schema_version, revision.content_digest, revision.content, revision.created_by, revision.created_at
FROM asset_revisions AS revision
WHERE revision.workspace_id = $1
  AND revision.asset_id = $2
  AND (
      NOT $3::boolean
      OR revision.sequence < $4
      OR (revision.sequence = $4 AND revision.id < $5)
  )
ORDER BY revision.sequence DESC, revision.id DESC
LIMIT $6
`

type ListCatalogAssetRevisionsParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	AssetID        pgtype.UUID `json:"asset_id"`
	HasCursor      bool        `json:"has_cursor"`
	CursorSequence int64       `json:"cursor_sequence"`
	CursorID       pgtype.UUID `json:"cursor_id"`
	PageLimit      int32       `json:"page_limit"`
}

func (q *Queries) ListCatalogAssetRevisions(ctx context.Context, arg ListCatalogAssetRevisionsParams) ([]AssetRevision, error) {
	rows, err := q.db.Query(ctx, listCatalogAssetRevisions,
		arg.WorkspaceID,
		arg.AssetID,
		arg.HasCursor,
		arg.CursorSequence,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetRevision{}
	for rows.Next() {
		var i AssetRevision
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AssetID,
			&i.Sequence,
			&i.SchemaVersion,
			&i.ContentDigest,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogAssets = `-- name: ListCatalogAssets :many
SELECT asset.id,
       asset.workspace_id,
       asset.namespace,
       asset.key,
       asset.asset_type,
       asset.lifecycle_state,
       asset.current_revision_id,
       COALESCE(NULLIF(revision.content->>'displayName', ''), revision.content->>'name', revision.content->>'title', asset.key) AS title,
       COALESCE(revision.content->>'summary', revision.content->>'definition', '')::text AS summary,
       asset.updated_at,
       CASE
           WHEN $1::text = '' THEN 0::double precision
           WHEN asset.namespace || '.' || asset.key = lower($1::text) THEN 3::double precision
           WHEN asset.namespace || '.' || asset.key LIKE lower($1::text) || '%' THEN 2::double precision
           ELSE ts_rank(
               to_tsvector('simple', COALESCE(revision.content::text, '')),
               plainto_tsquery('simple', $1::text)
           )::double precision
       END AS search_rank
FROM semantic_assets AS asset
LEFT JOIN asset_revisions AS revision ON revision.id = asset.current_revision_id
WHERE asset.workspace_id = $2
  AND ($3::text = '' OR asset.asset_type = $3::text)
  AND ($4::text = '' OR asset.lifecycle_state = $4::text)
  AND (
      $1::text = ''
      OR asset.namespace || '.' || asset.key ILIKE '%' || $1::text || '%'
      OR to_tsvector('simple', COALESCE(revision.content::text, '')) @@
         plainto_tsquery('simple', $1::text)
  )
  AND (
      NOT $5::boolean
      OR (CASE
              WHEN $1::text = '' THEN 0::double precision
              WHEN asset.namespace || '.' || asset.key = lower($1::text) THEN 3::double precision
              WHEN asset.namespace || '.' || asset.key LIKE lower($1::text) || '%' THEN 2::double precision
              ELSE ts_rank(
                  to_tsvector('simple', COALESCE(revision.content::text, '')),
                  plainto_tsquery('simple', $1::text)
              )::double precision
          END) < $6::double precision
      OR ((CASE
               WHEN $1::text = '' THEN 0::double precision
               WHEN asset.namespace || '.' || asset.key = lower($1::text) THEN 3::double precision
               WHEN asset.namespace || '.' || asset.key LIKE lower($1::text) || '%' THEN 2::double precision
               ELSE ts_rank(
                   to_tsvector('simple', COALESCE(revision.content::text, '')),
                   plainto_tsquery('simple', $1::text)
               )::double precision
           END) = $6::double precision
          AND (asset.updated_at < $7
               OR (asset.updated_at = $7 AND asset.id < $8::uuid)))
  )
ORDER BY search_rank DESC, asset.updated_at DESC, asset.id DESC
LIMIT $9
`

type ListCatalogAssetsParams struct {
	Search          string             `json:"search"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	AssetType       string             `json:"asset_type"`
	LifecycleState  string             `json:"lifecycle_state"`
	HasCursor       bool               `json:"has_cursor"`
	CursorRank      float64            `json:"cursor_rank"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListCatalogAssetsRow struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Namespace         string             `json:"namespace"`
	Key               string             `json:"key"`
	AssetType         string             `json:"asset_type"`
	LifecycleState    string             `json:"lifecycle_state"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	Title             string             `json:"title"`
	Summary           string             `json:"summary"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SearchRank        float64            `json:"search_rank"`
}

func (q *Queries) ListCatalogAssets(ctx context.Context, arg ListCatalogAssetsParams) ([]ListCatalogAssetsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogAssets,
		arg.Search,
		arg.WorkspaceID,
		arg.AssetType,
		arg.LifecycleState,
		arg.HasCursor,
		arg.CursorRank,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogAssetsRow{}
	for rows.Next() {
		var i ListCatalogAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Namespace,
			&i.Key,
			&i.AssetType,
			&i.LifecycleState,
			&i.CurrentRevisionID,
			&i.Title,
			&i.Summary,
			&i.UpdatedAt,
			&i.SearchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectCatalogAssetRelations = `-- name: ListDirectCatalogAssetRelations :many
SELECT relation.id,
       relation.subject_asset_id,
       relation.predicate,
       relation.object_asset_id,
       relation.plane,
       relation.assertion_state,
       relation.source_revision_id,
       relation.evidence_artifact_id,
       relation.created_at,
       CASE WHEN relation.subject_asset_id = $1 THEN 'outgoing' ELSE 'incoming' END AS direction,
       (CASE WHEN relation.subject_asset_id = $1
             THEN relation.object_asset_id ELSE relation.subject_asset_id END)::uuid AS counterpart_id,
       counterpart.namespace,
       counterpart.key,
       counterpart.asset_type,
       counterpart.lifecycle_state,
       counterpart.current_revision_id,
       counterpart.updated_at,
       COALESCE(NULLIF(revision.content->>'displayName', ''), revision.content->>'name', revision.content->>'title', counterpart.key) AS counterpart_title,
       COALESCE(revision.content->>'summary', revision.content->>'definition', '')::text AS counterpart_summary
FROM semantic_relations AS relation
JOIN semantic_assets AS counterpart
  ON counterpart.workspace_id = $2
 AND counterpart.id = CASE WHEN relation.subject_asset_id = $1
                           THEN relation.object_asset_id ELSE relation.subject_asset_id END
LEFT JOIN asset_revisions AS revision ON revision.id = counterpart.current_revision_id
WHERE relation.workspace_id = $2
  AND (relation.subject_asset_id = $1 OR relation.object_asset_id = $1)
  AND ($3::text = 'both'
       OR ($3::text = 'outgoing' AND relation.subject_asset_id = $1)
       OR ($3::text = 'incoming' AND relation.object_asset_id = $1))
  AND ($4::text = '' OR relation.plane = $4::text)
ORDER BY relation.id
LIMIT $5
`

type ListDirectCatalogAssetRelationsParams struct {
	AssetID     pgtype.UUID `json:"asset_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Direction   string      `json:"direction"`
	Plane       string      `json:"plane"`
	PageLimit   int32       `json:"page_limit"`
}

type ListDirectCatalogAssetRelationsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SubjectAssetID     pgtype.UUID        `json:"subject_asset_id"`
	Predicate          string             `json:"predicate"`
	ObjectAssetID      pgtype.UUID        `json:"object_asset_id"`
	Plane              string             `json:"plane"`
	AssertionState     string             `json:"assertion_state"`
	SourceRevisionID   pgtype.UUID        `json:"source_revision_id"`
	EvidenceArtifactID pgtype.UUID        `json:"evidence_artifact_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Direction          string             `json:"direction"`
	CounterpartID      pgtype.UUID        `json:"counterpart_id"`
	Namespace          string             `json:"namespace"`
	Key                string             `json:"key"`
	AssetType          string             `json:"asset_type"`
	LifecycleState     string             `json:"lifecycle_state"`
	CurrentRevisionID  pgtype.UUID        `json:"current_revision_id"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CounterpartTitle   string             `json:"counterpart_title"`
	CounterpartSummary string             `json:"counterpart_summary"`
}

func (q *Queries) ListDirectCatalogAssetRelations(ctx context.Context, arg ListDirectCatalogAssetRelationsParams) ([]ListDirectCatalogAssetRelationsRow, error) {
	rows, err := q.db.Query(ctx, listDirectCatalogAssetRelations,
		arg.AssetID,
		arg.WorkspaceID,
		arg.Direction,
		arg.Plane,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectCatalogAssetRelationsRow{}
	for rows.Next() {
		var i ListDirectCatalogAssetRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectAssetID,
			&i.Predicate,
			&i.ObjectAssetID,
			&i.Plane,
			&i.AssertionState,
			&i.SourceRevisionID,
			&i.EvidenceArtifactID,
			&i.CreatedAt,
			&i.Direction,
			&i.CounterpartID,
			&i.Namespace,
			&i.Key,
			&i.AssetType,
			&i.LifecycleState,
			&i.CurrentRevisionID,
			&i.UpdatedAt,
			&i.CounterpartTitle,
			&i.CounterpartSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAssetRevisionSequence = `-- name: NextAssetRevisionSequence :one
SELECT CAST(COALESCE(max(sequence), 0) + 1 AS bigint) AS next_sequence
FROM asset_revisions
WHERE workspace_id = $1
  AND asset_id = $2
`

type NextAssetRevisionSequenceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
}

func (q *Queries) NextAssetRevisionSequence(ctx context.Context, arg NextAssetRevisionSequenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextAssetRevisionSequence, arg.WorkspaceID, arg.AssetID)
	var next_sequence int64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}
