// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCatalogAsset = `-- name: GetCatalogAsset :one
SELECT asset.id,
       asset.workspace_id,
       asset.namespace,
       asset.key,
       asset.asset_type,
       asset.lifecycle_state,
       asset.current_revision_id,
       asset.created_at,
       asset.updated_at,
       revision.id AS revision_id,
       revision.sequence AS revision_sequence,
       revision.schema_version,
       revision.content_digest,
       revision.content,
       revision.created_by,
       revision.created_at AS revision_created_at,
       COALESCE(revision.content->>'name', revision.content->>'title', asset.key) AS title,
       COALESCE(revision.content->>'summary', revision.content->>'definition', '')::text AS summary,
       (SELECT count(*)::integer
        FROM semantic_relations relation
        WHERE relation.workspace_id = asset.workspace_id
          AND (relation.subject_asset_id = asset.id OR relation.object_asset_id = asset.id)) AS relation_count
FROM semantic_assets AS asset
LEFT JOIN asset_revisions AS revision ON revision.id = asset.current_revision_id
WHERE asset.workspace_id = $1
  AND asset.id = $2
`

type GetCatalogAssetParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
}

type GetCatalogAssetRow struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Namespace         string             `json:"namespace"`
	Key               string             `json:"key"`
	AssetType         string             `json:"asset_type"`
	LifecycleState    string             `json:"lifecycle_state"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	RevisionID        pgtype.UUID        `json:"revision_id"`
	RevisionSequence  pgtype.Int8        `json:"revision_sequence"`
	SchemaVersion     pgtype.Text        `json:"schema_version"`
	ContentDigest     pgtype.Text        `json:"content_digest"`
	Content           []byte             `json:"content"`
	CreatedBy         pgtype.Text        `json:"created_by"`
	RevisionCreatedAt pgtype.Timestamptz `json:"revision_created_at"`
	Title             string             `json:"title"`
	Summary           string             `json:"summary"`
	RelationCount     int32              `json:"relation_count"`
}

func (q *Queries) GetCatalogAsset(ctx context.Context, arg GetCatalogAssetParams) (GetCatalogAssetRow, error) {
	row := q.db.QueryRow(ctx, getCatalogAsset, arg.WorkspaceID, arg.AssetID)
	var i GetCatalogAssetRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Namespace,
		&i.Key,
		&i.AssetType,
		&i.LifecycleState,
		&i.CurrentRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionID,
		&i.RevisionSequence,
		&i.SchemaVersion,
		&i.ContentDigest,
		&i.Content,
		&i.CreatedBy,
		&i.RevisionCreatedAt,
		&i.Title,
		&i.Summary,
		&i.RelationCount,
	)
	return i, err
}

const getCatalogAssetForUpdate = `-- name: GetCatalogAssetForUpdate :one
SELECT id, workspace_id, namespace, key, asset_type, lifecycle_state, current_revision_id, created_at, updated_at
FROM semantic_assets
WHERE workspace_id = $1
  AND id = $2
FOR UPDATE
`

type GetCatalogAssetForUpdateParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
}

func (q *Queries) GetCatalogAssetForUpdate(ctx context.Context, arg GetCatalogAssetForUpdateParams) (SemanticAsset, error) {
	row := q.db.QueryRow(ctx, getCatalogAssetForUpdate, arg.WorkspaceID, arg.AssetID)
	var i SemanticAsset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Namespace,
		&i.Key,
		&i.AssetType,
		&i.LifecycleState,
		&i.CurrentRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCatalogAssetRevision = `-- name: GetCatalogAssetRevision :one
SELECT id, workspace_id, asset_id, sequence, schema_version, content_digest, content, created_by, created_at
FROM asset_revisions
WHERE workspace_id = $1
  AND asset_id = $2
  AND id = $3
`

type GetCatalogAssetRevisionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
	RevisionID  pgtype.UUID `json:"revision_id"`
}

func (q *Queries) GetCatalogAssetRevision(ctx context.Context, arg GetCatalogAssetRevisionParams) (AssetRevision, error) {
	row := q.db.QueryRow(ctx, getCatalogAssetRevision, arg.WorkspaceID, arg.AssetID, arg.RevisionID)
	var i AssetRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AssetID,
		&i.Sequence,
		&i.SchemaVersion,
		&i.ContentDigest,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCatalogDiscoveryFindings = `-- name: GetCatalogDiscoveryFindings :many
SELECT id, discovery_run_id, sequence, code, severity, locator, details, created_at
FROM discovery_findings
WHERE discovery_run_id = $1
ORDER BY sequence
`

func (q *Queries) GetCatalogDiscoveryFindings(ctx context.Context, runID pgtype.UUID) ([]DiscoveryFinding, error) {
	rows, err := q.db.Query(ctx, getCatalogDiscoveryFindings, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoveryFinding{}
	for rows.Next() {
		var i DiscoveryFinding
		if err := rows.Scan(
			&i.ID,
			&i.DiscoveryRunID,
			&i.Sequence,
			&i.Code,
			&i.Severity,
			&i.Locator,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCatalogDiscoveryRun = `-- name: GetCatalogDiscoveryRun :one
SELECT id, workspace_id, source_connection_id, source_revision_id, adapter_version, status, error_code, stats, started_at, completed_at, created_at, updated_at
FROM discovery_runs
WHERE workspace_id = $1
  AND id = $2
`

type GetCatalogDiscoveryRunParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RunID       pgtype.UUID `json:"run_id"`
}

func (q *Queries) GetCatalogDiscoveryRun(ctx context.Context, arg GetCatalogDiscoveryRunParams) (DiscoveryRun, error) {
	row := q.db.QueryRow(ctx, getCatalogDiscoveryRun, arg.WorkspaceID, arg.RunID)
	var i DiscoveryRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceConnectionID,
		&i.SourceRevisionID,
		&i.AdapterVersion,
		&i.Status,
		&i.ErrorCode,
		&i.Stats,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRevisionEvidence = `-- name: GetRevisionEvidence :many
SELECT evidence.id, evidence.workspace_id, evidence.evidence_type, evidence.source_revision_id, evidence.locator, evidence.content_digest, evidence.metadata, evidence.created_at, link.role, link.field_path, link.note
FROM revision_evidence_links AS link
JOIN evidence_artifacts AS evidence ON evidence.id = link.evidence_artifact_id
WHERE link.workspace_id = $1
  AND link.asset_revision_id = $2
ORDER BY link.role, evidence.id
`

type GetRevisionEvidenceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RevisionID  pgtype.UUID `json:"revision_id"`
}

type GetRevisionEvidenceRow struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	EvidenceType     string             `json:"evidence_type"`
	SourceRevisionID pgtype.UUID        `json:"source_revision_id"`
	Locator          string             `json:"locator"`
	ContentDigest    string             `json:"content_digest"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Role             string             `json:"role"`
	FieldPath        pgtype.Text        `json:"field_path"`
	Note             pgtype.Text        `json:"note"`
}

func (q *Queries) GetRevisionEvidence(ctx context.Context, arg GetRevisionEvidenceParams) ([]GetRevisionEvidenceRow, error) {
	rows, err := q.db.Query(ctx, getRevisionEvidence, arg.WorkspaceID, arg.RevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevisionEvidenceRow{}
	for rows.Next() {
		var i GetRevisionEvidenceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EvidenceType,
			&i.SourceRevisionID,
			&i.Locator,
			&i.ContentDigest,
			&i.Metadata,
			&i.CreatedAt,
			&i.Role,
			&i.FieldPath,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkRevisionEvidence = `-- name: LinkRevisionEvidence :execrows
INSERT INTO revision_evidence_links (
    workspace_id, asset_revision_id, evidence_artifact_id, role
)
SELECT $1, $2, evidence.id, 'supports'
FROM evidence_artifacts AS evidence
WHERE evidence.workspace_id = $1
  AND evidence.id = $3
`

type LinkRevisionEvidenceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RevisionID  pgtype.UUID `json:"revision_id"`
	EvidenceID  pgtype.UUID `json:"evidence_id"`
}

func (q *Queries) LinkRevisionEvidence(ctx context.Context, arg LinkRevisionEvidenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkRevisionEvidence, arg.WorkspaceID, arg.RevisionID, arg.EvidenceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCatalogAssetRevisions = `-- name: ListCatalogAssetRevisions :many
SELECT revision.id, revision.workspace_id, revision.asset_id, revision.sequence, revision.schema_version, revision.content_digest, revision.content, revision.created_by, revision.created_at
FROM asset_revisions AS revision
WHERE revision.workspace_id = $1
  AND revision.asset_id = $2
  AND (
      NOT $3::boolean
      OR revision.sequence < $4
      OR (revision.sequence = $4 AND revision.id < $5)
  )
ORDER BY revision.sequence DESC, revision.id DESC
LIMIT $6
`

type ListCatalogAssetRevisionsParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	AssetID        pgtype.UUID `json:"asset_id"`
	HasCursor      bool        `json:"has_cursor"`
	CursorSequence int64       `json:"cursor_sequence"`
	CursorID       pgtype.UUID `json:"cursor_id"`
	PageLimit      int32       `json:"page_limit"`
}

func (q *Queries) ListCatalogAssetRevisions(ctx context.Context, arg ListCatalogAssetRevisionsParams) ([]AssetRevision, error) {
	rows, err := q.db.Query(ctx, listCatalogAssetRevisions,
		arg.WorkspaceID,
		arg.AssetID,
		arg.HasCursor,
		arg.CursorSequence,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetRevision{}
	for rows.Next() {
		var i AssetRevision
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AssetID,
			&i.Sequence,
			&i.SchemaVersion,
			&i.ContentDigest,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogAssets = `-- name: ListCatalogAssets :many
SELECT asset.id,
       asset.workspace_id,
       asset.namespace,
       asset.key,
       asset.asset_type,
       asset.lifecycle_state,
       asset.current_revision_id,
       COALESCE(revision.content->>'name', revision.content->>'title', asset.key) AS title,
       COALESCE(revision.content->>'summary', revision.content->>'definition', '')::text AS summary,
       asset.updated_at,
       CASE
           WHEN $1::text = '' THEN 0::double precision
           WHEN asset.namespace || '.' || asset.key = lower($1::text) THEN 3::double precision
           WHEN asset.namespace || '.' || asset.key LIKE lower($1::text) || '%' THEN 2::double precision
           ELSE ts_rank(
               to_tsvector('simple', COALESCE(revision.content::text, '')),
               plainto_tsquery('simple', $1::text)
           )::double precision
       END AS search_rank
FROM semantic_assets AS asset
LEFT JOIN asset_revisions AS revision ON revision.id = asset.current_revision_id
WHERE asset.workspace_id = $2
  AND ($3::text = '' OR asset.asset_type = $3::text)
  AND ($4::text = '' OR asset.lifecycle_state = $4::text)
  AND (
      $1::text = ''
      OR asset.namespace || '.' || asset.key ILIKE '%' || $1::text || '%'
      OR to_tsvector('simple', COALESCE(revision.content::text, '')) @@
         plainto_tsquery('simple', $1::text)
  )
  AND (
      NOT $5::boolean
      OR (CASE
              WHEN $1::text = '' THEN 0::double precision
              WHEN asset.namespace || '.' || asset.key = lower($1::text) THEN 3::double precision
              WHEN asset.namespace || '.' || asset.key LIKE lower($1::text) || '%' THEN 2::double precision
              ELSE ts_rank(
                  to_tsvector('simple', COALESCE(revision.content::text, '')),
                  plainto_tsquery('simple', $1::text)
              )::double precision
          END) < $6::double precision
      OR ((CASE
               WHEN $1::text = '' THEN 0::double precision
               WHEN asset.namespace || '.' || asset.key = lower($1::text) THEN 3::double precision
               WHEN asset.namespace || '.' || asset.key LIKE lower($1::text) || '%' THEN 2::double precision
               ELSE ts_rank(
                   to_tsvector('simple', COALESCE(revision.content::text, '')),
                   plainto_tsquery('simple', $1::text)
               )::double precision
           END) = $6::double precision
          AND (asset.updated_at < $7
               OR (asset.updated_at = $7 AND asset.id < $8::uuid)))
  )
ORDER BY search_rank DESC, asset.updated_at DESC, asset.id DESC
LIMIT $9
`

type ListCatalogAssetsParams struct {
	Search          string             `json:"search"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	AssetType       string             `json:"asset_type"`
	LifecycleState  string             `json:"lifecycle_state"`
	HasCursor       bool               `json:"has_cursor"`
	CursorRank      float64            `json:"cursor_rank"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListCatalogAssetsRow struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Namespace         string             `json:"namespace"`
	Key               string             `json:"key"`
	AssetType         string             `json:"asset_type"`
	LifecycleState    string             `json:"lifecycle_state"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	Title             string             `json:"title"`
	Summary           string             `json:"summary"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SearchRank        float64            `json:"search_rank"`
}

func (q *Queries) ListCatalogAssets(ctx context.Context, arg ListCatalogAssetsParams) ([]ListCatalogAssetsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogAssets,
		arg.Search,
		arg.WorkspaceID,
		arg.AssetType,
		arg.LifecycleState,
		arg.HasCursor,
		arg.CursorRank,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogAssetsRow{}
	for rows.Next() {
		var i ListCatalogAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Namespace,
			&i.Key,
			&i.AssetType,
			&i.LifecycleState,
			&i.CurrentRevisionID,
			&i.Title,
			&i.Summary,
			&i.UpdatedAt,
			&i.SearchRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectCatalogAssetRelations = `-- name: ListDirectCatalogAssetRelations :many
SELECT relation.id,
       relation.subject_asset_id,
       relation.predicate,
       relation.object_asset_id,
       relation.plane,
       relation.assertion_state,
       relation.source_revision_id,
       relation.evidence_artifact_id,
       relation.created_at,
       CASE WHEN relation.subject_asset_id = $1 THEN 'outgoing' ELSE 'incoming' END AS direction,
       (CASE WHEN relation.subject_asset_id = $1
             THEN relation.object_asset_id ELSE relation.subject_asset_id END)::uuid AS counterpart_id,
       counterpart.namespace,
       counterpart.key,
       counterpart.asset_type,
       counterpart.lifecycle_state,
       counterpart.current_revision_id,
       counterpart.updated_at,
       COALESCE(revision.content->>'name', revision.content->>'title', counterpart.key) AS counterpart_title,
       COALESCE(revision.content->>'summary', revision.content->>'definition', '')::text AS counterpart_summary
FROM semantic_relations AS relation
JOIN semantic_assets AS counterpart
  ON counterpart.workspace_id = $2
 AND counterpart.id = CASE WHEN relation.subject_asset_id = $1
                           THEN relation.object_asset_id ELSE relation.subject_asset_id END
LEFT JOIN asset_revisions AS revision ON revision.id = counterpart.current_revision_id
WHERE relation.workspace_id = $2
  AND (relation.subject_asset_id = $1 OR relation.object_asset_id = $1)
  AND ($3::text = 'both'
       OR ($3::text = 'outgoing' AND relation.subject_asset_id = $1)
       OR ($3::text = 'incoming' AND relation.object_asset_id = $1))
  AND ($4::text = '' OR relation.plane = $4::text)
ORDER BY relation.id
`

type ListDirectCatalogAssetRelationsParams struct {
	AssetID     pgtype.UUID `json:"asset_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Direction   string      `json:"direction"`
	Plane       string      `json:"plane"`
}

type ListDirectCatalogAssetRelationsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SubjectAssetID     pgtype.UUID        `json:"subject_asset_id"`
	Predicate          string             `json:"predicate"`
	ObjectAssetID      pgtype.UUID        `json:"object_asset_id"`
	Plane              string             `json:"plane"`
	AssertionState     string             `json:"assertion_state"`
	SourceRevisionID   pgtype.UUID        `json:"source_revision_id"`
	EvidenceArtifactID pgtype.UUID        `json:"evidence_artifact_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Direction          string             `json:"direction"`
	CounterpartID      pgtype.UUID        `json:"counterpart_id"`
	Namespace          string             `json:"namespace"`
	Key                string             `json:"key"`
	AssetType          string             `json:"asset_type"`
	LifecycleState     string             `json:"lifecycle_state"`
	CurrentRevisionID  pgtype.UUID        `json:"current_revision_id"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CounterpartTitle   string             `json:"counterpart_title"`
	CounterpartSummary string             `json:"counterpart_summary"`
}

func (q *Queries) ListDirectCatalogAssetRelations(ctx context.Context, arg ListDirectCatalogAssetRelationsParams) ([]ListDirectCatalogAssetRelationsRow, error) {
	rows, err := q.db.Query(ctx, listDirectCatalogAssetRelations,
		arg.AssetID,
		arg.WorkspaceID,
		arg.Direction,
		arg.Plane,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectCatalogAssetRelationsRow{}
	for rows.Next() {
		var i ListDirectCatalogAssetRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectAssetID,
			&i.Predicate,
			&i.ObjectAssetID,
			&i.Plane,
			&i.AssertionState,
			&i.SourceRevisionID,
			&i.EvidenceArtifactID,
			&i.CreatedAt,
			&i.Direction,
			&i.CounterpartID,
			&i.Namespace,
			&i.Key,
			&i.AssetType,
			&i.LifecycleState,
			&i.CurrentRevisionID,
			&i.UpdatedAt,
			&i.CounterpartTitle,
			&i.CounterpartSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAssetRevisionSequence = `-- name: NextAssetRevisionSequence :one
SELECT CAST(COALESCE(max(sequence), 0) + 1 AS bigint) AS next_sequence
FROM asset_revisions
WHERE workspace_id = $1
  AND asset_id = $2
`

type NextAssetRevisionSequenceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
}

func (q *Queries) NextAssetRevisionSequence(ctx context.Context, arg NextAssetRevisionSequenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextAssetRevisionSequence, arg.WorkspaceID, arg.AssetID)
	var next_sequence int64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}
