// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompletedDiscoveryRun = `-- name: CreateCompletedDiscoveryRun :one
INSERT INTO discovery_runs (
    id, workspace_id, source_connection_id, source_revision_id, adapter_version,
    status, error_code, stats, started_at, completed_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $9, $9
)
RETURNING id, workspace_id, source_connection_id, source_revision_id, adapter_version, status, error_code, stats, started_at, completed_at, created_at, updated_at, credential_version, job_id, requested_by, trace_id, projection_reused, artifact_set_id, request_fingerprint, source_input_fingerprint, source_config
`

type CreateCompletedDiscoveryRunParams struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	SourceConnectionID pgtype.UUID        `json:"source_connection_id"`
	SourceRevisionID   pgtype.UUID        `json:"source_revision_id"`
	AdapterVersion     string             `json:"adapter_version"`
	Status             string             `json:"status"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	Stats              []byte             `json:"stats"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateCompletedDiscoveryRun(ctx context.Context, arg CreateCompletedDiscoveryRunParams) (DiscoveryRun, error) {
	row := q.db.QueryRow(ctx, createCompletedDiscoveryRun,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceConnectionID,
		arg.SourceRevisionID,
		arg.AdapterVersion,
		arg.Status,
		arg.ErrorCode,
		arg.Stats,
		arg.CompletedAt,
	)
	var i DiscoveryRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceConnectionID,
		&i.SourceRevisionID,
		&i.AdapterVersion,
		&i.Status,
		&i.ErrorCode,
		&i.Stats,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CredentialVersion,
		&i.JobID,
		&i.RequestedBy,
		&i.TraceID,
		&i.ProjectionReused,
		&i.ArtifactSetID,
		&i.RequestFingerprint,
		&i.SourceInputFingerprint,
		&i.SourceConfig,
	)
	return i, err
}

const createDiscoveryFinding = `-- name: CreateDiscoveryFinding :exec
INSERT INTO discovery_findings (
    discovery_run_id, sequence, code, severity, locator, details
) VALUES (
    $1, $2, $3, $4,
    $5, $6
)
`

type CreateDiscoveryFindingParams struct {
	DiscoveryRunID pgtype.UUID `json:"discovery_run_id"`
	Sequence       int32       `json:"sequence"`
	Code           string      `json:"code"`
	Severity       string      `json:"severity"`
	Locator        pgtype.Text `json:"locator"`
	Details        []byte      `json:"details"`
}

func (q *Queries) CreateDiscoveryFinding(ctx context.Context, arg CreateDiscoveryFindingParams) error {
	_, err := q.db.Exec(ctx, createDiscoveryFinding,
		arg.DiscoveryRunID,
		arg.Sequence,
		arg.Code,
		arg.Severity,
		arg.Locator,
		arg.Details,
	)
	return err
}

const createDiscoverySourceRevision = `-- name: CreateDiscoverySourceRevision :one
WITH inserted AS (
    INSERT INTO source_revisions (
        id, workspace_id, source_connection_id, external_revision, content_digest,
        adapter_version, observed_at, metadata
    ) VALUES (
        $1, $2, $3, $4,
        $5, $6, $7, $8
    )
    ON CONFLICT (source_connection_id, content_digest) DO NOTHING
    RETURNING source_revisions.id, source_revisions.workspace_id, source_revisions.source_connection_id, source_revisions.external_revision, source_revisions.content_digest, source_revisions.adapter_version, source_revisions.observed_at, source_revisions.metadata, source_revisions.created_at, true AS created
)
SELECT id, workspace_id, source_connection_id, external_revision, content_digest, adapter_version, observed_at, metadata, created_at, created FROM inserted
UNION ALL
SELECT source_revisions.id, source_revisions.workspace_id, source_revisions.source_connection_id, source_revisions.external_revision, source_revisions.content_digest, source_revisions.adapter_version, source_revisions.observed_at, source_revisions.metadata, source_revisions.created_at, false AS created
FROM source_revisions
WHERE workspace_id = $2
  AND source_connection_id = $3
  AND content_digest = $5
LIMIT 1
`

type CreateDiscoverySourceRevisionParams struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	SourceConnectionID pgtype.UUID        `json:"source_connection_id"`
	ExternalRevision   pgtype.Text        `json:"external_revision"`
	ContentDigest      string             `json:"content_digest"`
	AdapterVersion     string             `json:"adapter_version"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
	Metadata           []byte             `json:"metadata"`
}

type CreateDiscoverySourceRevisionRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	SourceConnectionID pgtype.UUID        `json:"source_connection_id"`
	ExternalRevision   pgtype.Text        `json:"external_revision"`
	ContentDigest      string             `json:"content_digest"`
	AdapterVersion     string             `json:"adapter_version"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Created            bool               `json:"created"`
}

func (q *Queries) CreateDiscoverySourceRevision(ctx context.Context, arg CreateDiscoverySourceRevisionParams) (CreateDiscoverySourceRevisionRow, error) {
	row := q.db.QueryRow(ctx, createDiscoverySourceRevision,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceConnectionID,
		arg.ExternalRevision,
		arg.ContentDigest,
		arg.AdapterVersion,
		arg.ObservedAt,
		arg.Metadata,
	)
	var i CreateDiscoverySourceRevisionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceConnectionID,
		&i.ExternalRevision,
		&i.ContentDigest,
		&i.AdapterVersion,
		&i.ObservedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.Created,
	)
	return i, err
}

const createLineageEdge = `-- name: CreateLineageEdge :execrows
INSERT INTO lineage_edges (
    id, workspace_id, source_revision_id, upstream_dataset_id, downstream_dataset_id,
    edge_kind, code_artifact_id, confidence
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
ON CONFLICT (source_revision_id, upstream_dataset_id, downstream_dataset_id, edge_kind) DO NOTHING
`

type CreateLineageEdgeParams struct {
	ID                  pgtype.UUID    `json:"id"`
	WorkspaceID         pgtype.UUID    `json:"workspace_id"`
	SourceRevisionID    pgtype.UUID    `json:"source_revision_id"`
	UpstreamDatasetID   pgtype.UUID    `json:"upstream_dataset_id"`
	DownstreamDatasetID pgtype.UUID    `json:"downstream_dataset_id"`
	EdgeKind            string         `json:"edge_kind"`
	CodeArtifactID      pgtype.UUID    `json:"code_artifact_id"`
	Confidence          pgtype.Numeric `json:"confidence"`
}

func (q *Queries) CreateLineageEdge(ctx context.Context, arg CreateLineageEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, createLineageEdge,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceRevisionID,
		arg.UpstreamDatasetID,
		arg.DownstreamDatasetID,
		arg.EdgeKind,
		arg.CodeArtifactID,
		arg.Confidence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPhysicalDatasetRevision = `-- name: CreatePhysicalDatasetRevision :one
INSERT INTO physical_dataset_revisions (
    id, workspace_id, physical_dataset_id, source_revision_id,
    dataset_kind, locator, content_digest, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, workspace_id, physical_dataset_id, source_revision_id, dataset_kind, locator, content_digest, metadata, created_at
`

type CreatePhysicalDatasetRevisionParams struct {
	ID                pgtype.UUID `json:"id"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	PhysicalDatasetID pgtype.UUID `json:"physical_dataset_id"`
	SourceRevisionID  pgtype.UUID `json:"source_revision_id"`
	DatasetKind       string      `json:"dataset_kind"`
	Locator           string      `json:"locator"`
	ContentDigest     string      `json:"content_digest"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreatePhysicalDatasetRevision(ctx context.Context, arg CreatePhysicalDatasetRevisionParams) (PhysicalDatasetRevision, error) {
	row := q.db.QueryRow(ctx, createPhysicalDatasetRevision,
		arg.ID,
		arg.WorkspaceID,
		arg.PhysicalDatasetID,
		arg.SourceRevisionID,
		arg.DatasetKind,
		arg.Locator,
		arg.ContentDigest,
		arg.Metadata,
	)
	var i PhysicalDatasetRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PhysicalDatasetID,
		&i.SourceRevisionID,
		&i.DatasetKind,
		&i.Locator,
		&i.ContentDigest,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createPhysicalFieldRevision = `-- name: CreatePhysicalFieldRevision :one
INSERT INTO physical_field_revisions (
    id, workspace_id, physical_field_id, dataset_revision_id,
    ordinal, data_type, nullable, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, workspace_id, physical_field_id, dataset_revision_id, ordinal, data_type, nullable, metadata, created_at
`

type CreatePhysicalFieldRevisionParams struct {
	ID                pgtype.UUID `json:"id"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	PhysicalFieldID   pgtype.UUID `json:"physical_field_id"`
	DatasetRevisionID pgtype.UUID `json:"dataset_revision_id"`
	Ordinal           int32       `json:"ordinal"`
	DataType          string      `json:"data_type"`
	Nullable          bool        `json:"nullable"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreatePhysicalFieldRevision(ctx context.Context, arg CreatePhysicalFieldRevisionParams) (PhysicalFieldRevision, error) {
	row := q.db.QueryRow(ctx, createPhysicalFieldRevision,
		arg.ID,
		arg.WorkspaceID,
		arg.PhysicalFieldID,
		arg.DatasetRevisionID,
		arg.Ordinal,
		arg.DataType,
		arg.Nullable,
		arg.Metadata,
	)
	var i PhysicalFieldRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PhysicalFieldID,
		&i.DatasetRevisionID,
		&i.Ordinal,
		&i.DataType,
		&i.Nullable,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const findPhysicalDatasetByQualifiedName = `-- name: FindPhysicalDatasetByQualifiedName :one
SELECT id, workspace_id, source_connection_id, external_key, qualified_name, current_revision_id, created_at, updated_at FROM physical_datasets
WHERE workspace_id = $1
  AND source_connection_id = $2
  AND qualified_name = $3
  AND external_key <> $4
LIMIT 1
`

type FindPhysicalDatasetByQualifiedNameParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	SourceConnectionID pgtype.UUID `json:"source_connection_id"`
	QualifiedName      string      `json:"qualified_name"`
	ExternalKey        string      `json:"external_key"`
}

func (q *Queries) FindPhysicalDatasetByQualifiedName(ctx context.Context, arg FindPhysicalDatasetByQualifiedNameParams) (PhysicalDataset, error) {
	row := q.db.QueryRow(ctx, findPhysicalDatasetByQualifiedName,
		arg.WorkspaceID,
		arg.SourceConnectionID,
		arg.QualifiedName,
		arg.ExternalKey,
	)
	var i PhysicalDataset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceConnectionID,
		&i.ExternalKey,
		&i.QualifiedName,
		&i.CurrentRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentPhysicalDatasetRevision = `-- name: GetCurrentPhysicalDatasetRevision :one
SELECT revision.id, revision.workspace_id, revision.physical_dataset_id, revision.source_revision_id, revision.dataset_kind, revision.locator, revision.content_digest, revision.metadata, revision.created_at
FROM physical_datasets dataset
JOIN physical_dataset_revisions revision ON revision.id = dataset.current_revision_id
WHERE dataset.workspace_id = $1
  AND dataset.id = $2
`

type GetCurrentPhysicalDatasetRevisionParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	PhysicalDatasetID pgtype.UUID `json:"physical_dataset_id"`
}

func (q *Queries) GetCurrentPhysicalDatasetRevision(ctx context.Context, arg GetCurrentPhysicalDatasetRevisionParams) (PhysicalDatasetRevision, error) {
	row := q.db.QueryRow(ctx, getCurrentPhysicalDatasetRevision, arg.WorkspaceID, arg.PhysicalDatasetID)
	var i PhysicalDatasetRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PhysicalDatasetID,
		&i.SourceRevisionID,
		&i.DatasetKind,
		&i.Locator,
		&i.ContentDigest,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentPhysicalFieldRevision = `-- name: GetCurrentPhysicalFieldRevision :one
SELECT revision.id, revision.workspace_id, revision.physical_field_id, revision.dataset_revision_id, revision.ordinal, revision.data_type, revision.nullable, revision.metadata, revision.created_at
FROM physical_fields field
JOIN physical_field_revisions revision ON revision.id = field.current_revision_id
WHERE field.workspace_id = $1
  AND field.id = $2
`

type GetCurrentPhysicalFieldRevisionParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	PhysicalFieldID pgtype.UUID `json:"physical_field_id"`
}

func (q *Queries) GetCurrentPhysicalFieldRevision(ctx context.Context, arg GetCurrentPhysicalFieldRevisionParams) (PhysicalFieldRevision, error) {
	row := q.db.QueryRow(ctx, getCurrentPhysicalFieldRevision, arg.WorkspaceID, arg.PhysicalFieldID)
	var i PhysicalFieldRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PhysicalFieldID,
		&i.DatasetRevisionID,
		&i.Ordinal,
		&i.DataType,
		&i.Nullable,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getPhysicalDatasetRevisionByDigest = `-- name: GetPhysicalDatasetRevisionByDigest :one
SELECT id, workspace_id, physical_dataset_id, source_revision_id, dataset_kind, locator, content_digest, metadata, created_at FROM physical_dataset_revisions
WHERE workspace_id=$1 AND physical_dataset_id=$2
  AND content_digest=$3
ORDER BY created_at,id LIMIT 1
`

type GetPhysicalDatasetRevisionByDigestParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	PhysicalDatasetID pgtype.UUID `json:"physical_dataset_id"`
	ContentDigest     string      `json:"content_digest"`
}

func (q *Queries) GetPhysicalDatasetRevisionByDigest(ctx context.Context, arg GetPhysicalDatasetRevisionByDigestParams) (PhysicalDatasetRevision, error) {
	row := q.db.QueryRow(ctx, getPhysicalDatasetRevisionByDigest, arg.WorkspaceID, arg.PhysicalDatasetID, arg.ContentDigest)
	var i PhysicalDatasetRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PhysicalDatasetID,
		&i.SourceRevisionID,
		&i.DatasetKind,
		&i.Locator,
		&i.ContentDigest,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getPhysicalFieldRevisionByDigest = `-- name: GetPhysicalFieldRevisionByDigest :one
SELECT id, workspace_id, physical_field_id, dataset_revision_id, ordinal, data_type, nullable, metadata, created_at FROM physical_field_revisions
WHERE workspace_id=$1 AND physical_field_id=$2
  AND dataset_revision_id=$3 AND metadata->>'fingerprint'=$4::text
ORDER BY created_at,id LIMIT 1
`

type GetPhysicalFieldRevisionByDigestParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	PhysicalFieldID   pgtype.UUID `json:"physical_field_id"`
	DatasetRevisionID pgtype.UUID `json:"dataset_revision_id"`
	ContentDigest     string      `json:"content_digest"`
}

func (q *Queries) GetPhysicalFieldRevisionByDigest(ctx context.Context, arg GetPhysicalFieldRevisionByDigestParams) (PhysicalFieldRevision, error) {
	row := q.db.QueryRow(ctx, getPhysicalFieldRevisionByDigest,
		arg.WorkspaceID,
		arg.PhysicalFieldID,
		arg.DatasetRevisionID,
		arg.ContentDigest,
	)
	var i PhysicalFieldRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PhysicalFieldID,
		&i.DatasetRevisionID,
		&i.Ordinal,
		&i.DataType,
		&i.Nullable,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceSnapshotForRun = `-- name: GetSourceSnapshotForRun :one
SELECT snapshot_id FROM source_snapshot_runs
WHERE workspace_id=$1 AND run_id=$2
`

type GetSourceSnapshotForRunParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RunID       pgtype.UUID `json:"run_id"`
}

func (q *Queries) GetSourceSnapshotForRun(ctx context.Context, arg GetSourceSnapshotForRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSourceSnapshotForRun, arg.WorkspaceID, arg.RunID)
	var snapshot_id pgtype.UUID
	err := row.Scan(&snapshot_id)
	return snapshot_id, err
}

const getSuccessfulDiscoveryRun = `-- name: GetSuccessfulDiscoveryRun :one
SELECT id, workspace_id, source_connection_id, source_revision_id, adapter_version, status, error_code, stats, started_at, completed_at, created_at, updated_at, credential_version, job_id, requested_by, trace_id, projection_reused, artifact_set_id, request_fingerprint, source_input_fingerprint, source_config FROM discovery_runs
WHERE workspace_id = $1
  AND source_revision_id = $2
  AND adapter_version = $3
  AND status IN ('succeeded', 'degraded') AND NOT projection_reused
`

type GetSuccessfulDiscoveryRunParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	SourceRevisionID pgtype.UUID `json:"source_revision_id"`
	AdapterVersion   string      `json:"adapter_version"`
}

func (q *Queries) GetSuccessfulDiscoveryRun(ctx context.Context, arg GetSuccessfulDiscoveryRunParams) (DiscoveryRun, error) {
	row := q.db.QueryRow(ctx, getSuccessfulDiscoveryRun, arg.WorkspaceID, arg.SourceRevisionID, arg.AdapterVersion)
	var i DiscoveryRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceConnectionID,
		&i.SourceRevisionID,
		&i.AdapterVersion,
		&i.Status,
		&i.ErrorCode,
		&i.Stats,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CredentialVersion,
		&i.JobID,
		&i.RequestedBy,
		&i.TraceID,
		&i.ProjectionReused,
		&i.ArtifactSetID,
		&i.RequestFingerprint,
		&i.SourceInputFingerprint,
		&i.SourceConfig,
	)
	return i, err
}

const setCurrentPhysicalDatasetRevision = `-- name: SetCurrentPhysicalDatasetRevision :execrows
UPDATE physical_datasets
SET current_revision_id = $1, updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = $2 AND id = $3
`

type SetCurrentPhysicalDatasetRevisionParams struct {
	RevisionID        pgtype.UUID `json:"revision_id"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	PhysicalDatasetID pgtype.UUID `json:"physical_dataset_id"`
}

func (q *Queries) SetCurrentPhysicalDatasetRevision(ctx context.Context, arg SetCurrentPhysicalDatasetRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCurrentPhysicalDatasetRevision, arg.RevisionID, arg.WorkspaceID, arg.PhysicalDatasetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCurrentPhysicalFieldRevision = `-- name: SetCurrentPhysicalFieldRevision :execrows
UPDATE physical_fields
SET current_revision_id = $1, updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = $2 AND id = $3
`

type SetCurrentPhysicalFieldRevisionParams struct {
	RevisionID      pgtype.UUID `json:"revision_id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	PhysicalFieldID pgtype.UUID `json:"physical_field_id"`
}

func (q *Queries) SetCurrentPhysicalFieldRevision(ctx context.Context, arg SetCurrentPhysicalFieldRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCurrentPhysicalFieldRevision, arg.RevisionID, arg.WorkspaceID, arg.PhysicalFieldID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCodeArtifact = `-- name: UpsertCodeArtifact :one
INSERT INTO code_artifacts (
    id, workspace_id, source_revision_id, path, blob_oid, language, content_digest
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (source_revision_id, path) DO UPDATE
SET blob_oid = EXCLUDED.blob_oid, language = EXCLUDED.language, content_digest = EXCLUDED.content_digest
RETURNING id, workspace_id, source_revision_id, path, blob_oid, language, content_digest, created_at
`

type UpsertCodeArtifactParams struct {
	ID               pgtype.UUID `json:"id"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	SourceRevisionID pgtype.UUID `json:"source_revision_id"`
	Path             string      `json:"path"`
	BlobOid          pgtype.Text `json:"blob_oid"`
	Language         string      `json:"language"`
	ContentDigest    string      `json:"content_digest"`
}

func (q *Queries) UpsertCodeArtifact(ctx context.Context, arg UpsertCodeArtifactParams) (CodeArtifact, error) {
	row := q.db.QueryRow(ctx, upsertCodeArtifact,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceRevisionID,
		arg.Path,
		arg.BlobOid,
		arg.Language,
		arg.ContentDigest,
	)
	var i CodeArtifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceRevisionID,
		&i.Path,
		&i.BlobOid,
		&i.Language,
		&i.ContentDigest,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPhysicalDataset = `-- name: UpsertPhysicalDataset :one
INSERT INTO physical_datasets (
    id, workspace_id, source_connection_id, external_key, qualified_name
) VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (source_connection_id, external_key) DO UPDATE
SET qualified_name = CASE WHEN $6::boolean THEN EXCLUDED.qualified_name ELSE physical_datasets.qualified_name END,
    updated_at = CASE WHEN $6::boolean THEN CURRENT_TIMESTAMP ELSE physical_datasets.updated_at END
RETURNING id, workspace_id, source_connection_id, external_key, qualified_name, current_revision_id, created_at, updated_at
`

type UpsertPhysicalDatasetParams struct {
	ID                 pgtype.UUID `json:"id"`
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	SourceConnectionID pgtype.UUID `json:"source_connection_id"`
	ExternalKey        string      `json:"external_key"`
	QualifiedName      string      `json:"qualified_name"`
	PublishCurrent     bool        `json:"publish_current"`
}

func (q *Queries) UpsertPhysicalDataset(ctx context.Context, arg UpsertPhysicalDatasetParams) (PhysicalDataset, error) {
	row := q.db.QueryRow(ctx, upsertPhysicalDataset,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceConnectionID,
		arg.ExternalKey,
		arg.QualifiedName,
		arg.PublishCurrent,
	)
	var i PhysicalDataset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceConnectionID,
		&i.ExternalKey,
		&i.QualifiedName,
		&i.CurrentRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPhysicalField = `-- name: UpsertPhysicalField :one
INSERT INTO physical_fields (
    id, workspace_id, physical_dataset_id, external_key, name
) VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (physical_dataset_id, external_key) DO UPDATE
SET name = CASE WHEN $6::boolean THEN EXCLUDED.name ELSE physical_fields.name END,
    updated_at = CASE WHEN $6::boolean THEN CURRENT_TIMESTAMP ELSE physical_fields.updated_at END
RETURNING id, workspace_id, physical_dataset_id, external_key, name, current_revision_id, created_at, updated_at
`

type UpsertPhysicalFieldParams struct {
	ID                pgtype.UUID `json:"id"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	PhysicalDatasetID pgtype.UUID `json:"physical_dataset_id"`
	ExternalKey       string      `json:"external_key"`
	Name              string      `json:"name"`
	PublishCurrent    bool        `json:"publish_current"`
}

func (q *Queries) UpsertPhysicalField(ctx context.Context, arg UpsertPhysicalFieldParams) (PhysicalField, error) {
	row := q.db.QueryRow(ctx, upsertPhysicalField,
		arg.ID,
		arg.WorkspaceID,
		arg.PhysicalDatasetID,
		arg.ExternalKey,
		arg.Name,
		arg.PublishCurrent,
	)
	var i PhysicalField
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PhysicalDatasetID,
		&i.ExternalKey,
		&i.Name,
		&i.CurrentRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
