// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embedding.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const failExpiredEmbedding = `-- name: FailExpiredEmbedding :exec
UPDATE embedding_index_versions
SET state='failed',error_code='EMBEDDING_LEASE_EXPIRED',updated_at=clock_timestamp()
WHERE workspace_id=$1 AND job_id=$2 AND state='building'
`

type FailExpiredEmbeddingParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	JobID       pgtype.UUID `json:"job_id"`
}

func (q *Queries) FailExpiredEmbedding(ctx context.Context, arg FailExpiredEmbeddingParams) error {
	_, err := q.db.Exec(ctx, failExpiredEmbedding, arg.WorkspaceID, arg.JobID)
	return err
}
