// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExecutionRun = `-- name: GetExecutionRun :one
SELECT id, workspace_id, runtime_run_id, semantic_query_id, resolved_plan_id, plan_digest, principal_id, consumer_id, credential_id, channel, source_connection_id, source_revision_id, adapter_version, policy_version, timeout_ms, max_rows, max_bytes, cancel_requested, idempotency_key, state, error_code, row_count, byte_count, result_digest, trace_id, started_at, deadline_at, finished_at FROM query_execution_runs WHERE workspace_id=$1 AND id=$2
`

type GetExecutionRunParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetExecutionRun(ctx context.Context, arg GetExecutionRunParams) (QueryExecutionRun, error) {
	row := q.db.QueryRow(ctx, getExecutionRun, arg.WorkspaceID, arg.ID)
	var i QueryExecutionRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeRunID,
		&i.SemanticQueryID,
		&i.ResolvedPlanID,
		&i.PlanDigest,
		&i.PrincipalID,
		&i.ConsumerID,
		&i.CredentialID,
		&i.Channel,
		&i.SourceConnectionID,
		&i.SourceRevisionID,
		&i.AdapterVersion,
		&i.PolicyVersion,
		&i.TimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.CancelRequested,
		&i.IdempotencyKey,
		&i.State,
		&i.ErrorCode,
		&i.RowCount,
		&i.ByteCount,
		&i.ResultDigest,
		&i.TraceID,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
	)
	return i, err
}

const getExecutionRunByKey = `-- name: GetExecutionRunByKey :one
SELECT id, workspace_id, runtime_run_id, semantic_query_id, resolved_plan_id, plan_digest, principal_id, consumer_id, credential_id, channel, source_connection_id, source_revision_id, adapter_version, policy_version, timeout_ms, max_rows, max_bytes, cancel_requested, idempotency_key, state, error_code, row_count, byte_count, result_digest, trace_id, started_at, deadline_at, finished_at FROM query_execution_runs WHERE workspace_id=$1 AND principal_id=$2 AND idempotency_key=$3
`

type GetExecutionRunByKeyParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	PrincipalID    pgtype.UUID `json:"principal_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetExecutionRunByKey(ctx context.Context, arg GetExecutionRunByKeyParams) (QueryExecutionRun, error) {
	row := q.db.QueryRow(ctx, getExecutionRunByKey, arg.WorkspaceID, arg.PrincipalID, arg.IdempotencyKey)
	var i QueryExecutionRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeRunID,
		&i.SemanticQueryID,
		&i.ResolvedPlanID,
		&i.PlanDigest,
		&i.PrincipalID,
		&i.ConsumerID,
		&i.CredentialID,
		&i.Channel,
		&i.SourceConnectionID,
		&i.SourceRevisionID,
		&i.AdapterVersion,
		&i.PolicyVersion,
		&i.TimeoutMs,
		&i.MaxRows,
		&i.MaxBytes,
		&i.CancelRequested,
		&i.IdempotencyKey,
		&i.State,
		&i.ErrorCode,
		&i.RowCount,
		&i.ByteCount,
		&i.ResultDigest,
		&i.TraceID,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
	)
	return i, err
}

const latestPublishedAssetPins = `-- name: LatestPublishedAssetPins :many
SELECT DISTINCT ON (a.asset_id) a.workspace_id, a.release_id, a.asset_id, a.revision_id, a.compatibility, a.position, a.created_at FROM release_assets a
JOIN releases r ON r.workspace_id=a.workspace_id AND r.id=a.release_id
WHERE a.workspace_id=$1 AND r.state='published'
ORDER BY a.asset_id,r.sequence DESC
`

func (q *Queries) LatestPublishedAssetPins(ctx context.Context, workspaceID pgtype.UUID) ([]ReleaseAsset, error) {
	rows, err := q.db.Query(ctx, latestPublishedAssetPins, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseAsset{}
	for rows.Next() {
		var i ReleaseAsset
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ReleaseID,
			&i.AssetID,
			&i.RevisionID,
			&i.Compatibility,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestPublishedObjectPins = `-- name: LatestPublishedObjectPins :many
SELECT DISTINCT ON (a.object_type,a.object_id) a.workspace_id, a.release_id, a.object_type, a.object_id, a.version, a.position, a.created_at FROM release_objects a
JOIN releases r ON r.workspace_id=a.workspace_id AND r.id=a.release_id
WHERE a.workspace_id=$1 AND r.state='published'
ORDER BY a.object_type,a.object_id,r.sequence DESC
`

func (q *Queries) LatestPublishedObjectPins(ctx context.Context, workspaceID pgtype.UUID) ([]ReleaseObject, error) {
	rows, err := q.db.Query(ctx, latestPublishedObjectPins, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseObject{}
	for rows.Next() {
		var i ReleaseObject
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ReleaseID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Version,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseExecutionBindingPins = `-- name: ListReleaseExecutionBindingPins :many
SELECT binding_id,version,dataset_id,COALESCE(payload->>'datasetRevisionId','')::text AS dataset_revision_id
FROM release_execution_binding_pins WHERE workspace_id=$1 AND release_id=$2 ORDER BY binding_id
`

type ListReleaseExecutionBindingPinsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ReleaseID   pgtype.UUID `json:"release_id"`
}

type ListReleaseExecutionBindingPinsRow struct {
	BindingID         pgtype.UUID `json:"binding_id"`
	Version           int32       `json:"version"`
	DatasetID         pgtype.UUID `json:"dataset_id"`
	DatasetRevisionID string      `json:"dataset_revision_id"`
}

func (q *Queries) ListReleaseExecutionBindingPins(ctx context.Context, arg ListReleaseExecutionBindingPinsParams) ([]ListReleaseExecutionBindingPinsRow, error) {
	rows, err := q.db.Query(ctx, listReleaseExecutionBindingPins, arg.WorkspaceID, arg.ReleaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseExecutionBindingPinsRow{}
	for rows.Next() {
		var i ListReleaseExecutionBindingPinsRow
		if err := rows.Scan(
			&i.BindingID,
			&i.Version,
			&i.DatasetID,
			&i.DatasetRevisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseExecutionRelations = `-- name: ListReleaseExecutionRelations :many
SELECT payload FROM release_execution_relations WHERE workspace_id=$1 AND release_id=$2 ORDER BY dataset_id
`

type ListReleaseExecutionRelationsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ReleaseID   pgtype.UUID `json:"release_id"`
}

func (q *Queries) ListReleaseExecutionRelations(ctx context.Context, arg ListReleaseExecutionRelationsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listReleaseExecutionRelations, arg.WorkspaceID, arg.ReleaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var payload []byte
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
