// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: governed_objects.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyEntityKeyChange = `-- name: ApplyEntityKeyChange :execrows
UPDATE entity_keys
SET content = $1, version = version + 1, updated_at = $2
WHERE workspace_id = $3 AND id = $4
  AND version = $5
`

type ApplyEntityKeyChangeParams struct {
	Content         []byte             `json:"content"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	EntityKeyID     pgtype.UUID        `json:"entity_key_id"`
	ExpectedVersion int32              `json:"expected_version"`
}

func (q *Queries) ApplyEntityKeyChange(ctx context.Context, arg ApplyEntityKeyChangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyEntityKeyChange,
		arg.Content,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.EntityKeyID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyJoinContractChange = `-- name: ApplyJoinContractChange :execrows
UPDATE join_contracts
SET content = $1, version = version + 1, updated_at = $2
WHERE workspace_id = $3 AND id = $4
  AND version = $5
`

type ApplyJoinContractChangeParams struct {
	Content         []byte             `json:"content"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	JoinContractID  pgtype.UUID        `json:"join_contract_id"`
	ExpectedVersion int32              `json:"expected_version"`
}

func (q *Queries) ApplyJoinContractChange(ctx context.Context, arg ApplyJoinContractChangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyJoinContractChange,
		arg.Content,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.JoinContractID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyModelGrainChange = `-- name: ApplyModelGrainChange :execrows
UPDATE model_grains
SET content = $1, version = version + 1, updated_at = $2
WHERE workspace_id = $3 AND id = $4
  AND version = $5
`

type ApplyModelGrainChangeParams struct {
	Content         []byte             `json:"content"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ModelGrainID    pgtype.UUID        `json:"model_grain_id"`
	ExpectedVersion int32              `json:"expected_version"`
}

func (q *Queries) ApplyModelGrainChange(ctx context.Context, arg ApplyModelGrainChangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyModelGrainChange,
		arg.Content,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ModelGrainID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyPhysicalBindingChange = `-- name: ApplyPhysicalBindingChange :execrows
UPDATE physical_bindings
SET content = $1, version = version + 1, updated_at = $2
WHERE workspace_id = $3 AND id = $4
  AND version = $5
`

type ApplyPhysicalBindingChangeParams struct {
	Content           []byte             `json:"content"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	PhysicalBindingID pgtype.UUID        `json:"physical_binding_id"`
	ExpectedVersion   int32              `json:"expected_version"`
}

func (q *Queries) ApplyPhysicalBindingChange(ctx context.Context, arg ApplyPhysicalBindingChangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyPhysicalBindingChange,
		arg.Content,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.PhysicalBindingID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEntityKey = `-- name: CreateEntityKey :one
INSERT INTO entity_keys (
    id, workspace_id, asset_id, key_field_refs, uniqueness_semantics,
    version, content, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, workspace_id, asset_id, key_field_refs, uniqueness_semantics, version, content, created_by, created_at, updated_at
`

type CreateEntityKeyParams struct {
	ID                  pgtype.UUID        `json:"id"`
	WorkspaceID         pgtype.UUID        `json:"workspace_id"`
	AssetID             pgtype.UUID        `json:"asset_id"`
	KeyFieldRefs        []byte             `json:"key_field_refs"`
	UniquenessSemantics string             `json:"uniqueness_semantics"`
	Version             int32              `json:"version"`
	Content             []byte             `json:"content"`
	CreatedBy           string             `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEntityKey(ctx context.Context, arg CreateEntityKeyParams) (EntityKey, error) {
	row := q.db.QueryRow(ctx, createEntityKey,
		arg.ID,
		arg.WorkspaceID,
		arg.AssetID,
		arg.KeyFieldRefs,
		arg.UniquenessSemantics,
		arg.Version,
		arg.Content,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EntityKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AssetID,
		&i.KeyFieldRefs,
		&i.UniquenessSemantics,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJoinContract = `-- name: CreateJoinContract :one
INSERT INTO join_contracts (
    id, workspace_id, left_dataset_id, right_dataset_id, left_field_refs, right_field_refs,
    join_type, cardinality, join_expression, contract_notes,
    version, content, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13, $14,
    $15
)
RETURNING id, workspace_id, left_dataset_id, right_dataset_id, left_field_refs, right_field_refs, join_type, cardinality, join_expression, contract_notes, version, content, created_by, created_at, updated_at
`

type CreateJoinContractParams struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	LeftDatasetID  pgtype.UUID        `json:"left_dataset_id"`
	RightDatasetID pgtype.UUID        `json:"right_dataset_id"`
	LeftFieldRefs  []byte             `json:"left_field_refs"`
	RightFieldRefs []byte             `json:"right_field_refs"`
	JoinType       string             `json:"join_type"`
	Cardinality    string             `json:"cardinality"`
	JoinExpression string             `json:"join_expression"`
	ContractNotes  pgtype.Text        `json:"contract_notes"`
	Version        int32              `json:"version"`
	Content        []byte             `json:"content"`
	CreatedBy      string             `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateJoinContract(ctx context.Context, arg CreateJoinContractParams) (JoinContract, error) {
	row := q.db.QueryRow(ctx, createJoinContract,
		arg.ID,
		arg.WorkspaceID,
		arg.LeftDatasetID,
		arg.RightDatasetID,
		arg.LeftFieldRefs,
		arg.RightFieldRefs,
		arg.JoinType,
		arg.Cardinality,
		arg.JoinExpression,
		arg.ContractNotes,
		arg.Version,
		arg.Content,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i JoinContract
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LeftDatasetID,
		&i.RightDatasetID,
		&i.LeftFieldRefs,
		&i.RightFieldRefs,
		&i.JoinType,
		&i.Cardinality,
		&i.JoinExpression,
		&i.ContractNotes,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createModelGrain = `-- name: CreateModelGrain :one
INSERT INTO model_grains (
    id, workspace_id, asset_id, grain_expression, grain_field_refs, documented_by,
    version, content, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11
)
RETURNING id, workspace_id, asset_id, grain_expression, grain_field_refs, documented_by, version, content, created_by, created_at, updated_at
`

type CreateModelGrainParams struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	AssetID         pgtype.UUID        `json:"asset_id"`
	GrainExpression string             `json:"grain_expression"`
	GrainFieldRefs  []byte             `json:"grain_field_refs"`
	DocumentedBy    pgtype.UUID        `json:"documented_by"`
	Version         int32              `json:"version"`
	Content         []byte             `json:"content"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateModelGrain(ctx context.Context, arg CreateModelGrainParams) (ModelGrain, error) {
	row := q.db.QueryRow(ctx, createModelGrain,
		arg.ID,
		arg.WorkspaceID,
		arg.AssetID,
		arg.GrainExpression,
		arg.GrainFieldRefs,
		arg.DocumentedBy,
		arg.Version,
		arg.Content,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ModelGrain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AssetID,
		&i.GrainExpression,
		&i.GrainFieldRefs,
		&i.DocumentedBy,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPhysicalBinding = `-- name: CreatePhysicalBinding :one

INSERT INTO physical_bindings (
    id, workspace_id, asset_id, dataset_id, field_id, transform, retired_at,
    version, content, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, workspace_id, asset_id, dataset_id, field_id, transform, retired_at, version, content, created_by, created_at, updated_at
`

type CreatePhysicalBindingParams struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	AssetID     pgtype.UUID        `json:"asset_id"`
	DatasetID   pgtype.UUID        `json:"dataset_id"`
	FieldID     pgtype.UUID        `json:"field_id"`
	Transform   pgtype.Text        `json:"transform"`
	RetiredAt   pgtype.Timestamptz `json:"retired_at"`
	Version     int32              `json:"version"`
	Content     []byte             `json:"content"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// M2-T008 governance objects. All four tables share one shape: a workspace
// scope, a TypeID identity, a version bumped only by the governed change
// application path, a flexible content object and the shared
// create/get/list/lock/apply pipeline.
func (q *Queries) CreatePhysicalBinding(ctx context.Context, arg CreatePhysicalBindingParams) (PhysicalBinding, error) {
	row := q.db.QueryRow(ctx, createPhysicalBinding,
		arg.ID,
		arg.WorkspaceID,
		arg.AssetID,
		arg.DatasetID,
		arg.FieldID,
		arg.Transform,
		arg.RetiredAt,
		arg.Version,
		arg.Content,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PhysicalBinding
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AssetID,
		&i.DatasetID,
		&i.FieldID,
		&i.Transform,
		&i.RetiredAt,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const entityKeyExists = `-- name: EntityKeyExists :one
SELECT EXISTS (
    SELECT 1 FROM entity_keys
    WHERE workspace_id = $1 AND id = $2
) AS present
`

type EntityKeyExistsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityKeyID pgtype.UUID `json:"entity_key_id"`
}

func (q *Queries) EntityKeyExists(ctx context.Context, arg EntityKeyExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, entityKeyExists, arg.WorkspaceID, arg.EntityKeyID)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const getEntityKey = `-- name: GetEntityKey :one
SELECT id, workspace_id, asset_id, key_field_refs, uniqueness_semantics, version, content, created_by, created_at, updated_at FROM entity_keys
WHERE workspace_id = $1 AND id = $2
`

type GetEntityKeyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityKeyID pgtype.UUID `json:"entity_key_id"`
}

func (q *Queries) GetEntityKey(ctx context.Context, arg GetEntityKeyParams) (EntityKey, error) {
	row := q.db.QueryRow(ctx, getEntityKey, arg.WorkspaceID, arg.EntityKeyID)
	var i EntityKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AssetID,
		&i.KeyFieldRefs,
		&i.UniquenessSemantics,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJoinContract = `-- name: GetJoinContract :one
SELECT id, workspace_id, left_dataset_id, right_dataset_id, left_field_refs, right_field_refs, join_type, cardinality, join_expression, contract_notes, version, content, created_by, created_at, updated_at FROM join_contracts
WHERE workspace_id = $1 AND id = $2
`

type GetJoinContractParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	JoinContractID pgtype.UUID `json:"join_contract_id"`
}

func (q *Queries) GetJoinContract(ctx context.Context, arg GetJoinContractParams) (JoinContract, error) {
	row := q.db.QueryRow(ctx, getJoinContract, arg.WorkspaceID, arg.JoinContractID)
	var i JoinContract
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LeftDatasetID,
		&i.RightDatasetID,
		&i.LeftFieldRefs,
		&i.RightFieldRefs,
		&i.JoinType,
		&i.Cardinality,
		&i.JoinExpression,
		&i.ContractNotes,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelGrain = `-- name: GetModelGrain :one
SELECT id, workspace_id, asset_id, grain_expression, grain_field_refs, documented_by, version, content, created_by, created_at, updated_at FROM model_grains
WHERE workspace_id = $1 AND id = $2
`

type GetModelGrainParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	ModelGrainID pgtype.UUID `json:"model_grain_id"`
}

func (q *Queries) GetModelGrain(ctx context.Context, arg GetModelGrainParams) (ModelGrain, error) {
	row := q.db.QueryRow(ctx, getModelGrain, arg.WorkspaceID, arg.ModelGrainID)
	var i ModelGrain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AssetID,
		&i.GrainExpression,
		&i.GrainFieldRefs,
		&i.DocumentedBy,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhysicalBinding = `-- name: GetPhysicalBinding :one
SELECT id, workspace_id, asset_id, dataset_id, field_id, transform, retired_at, version, content, created_by, created_at, updated_at FROM physical_bindings
WHERE workspace_id = $1 AND id = $2
`

type GetPhysicalBindingParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	PhysicalBindingID pgtype.UUID `json:"physical_binding_id"`
}

func (q *Queries) GetPhysicalBinding(ctx context.Context, arg GetPhysicalBindingParams) (PhysicalBinding, error) {
	row := q.db.QueryRow(ctx, getPhysicalBinding, arg.WorkspaceID, arg.PhysicalBindingID)
	var i PhysicalBinding
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AssetID,
		&i.DatasetID,
		&i.FieldID,
		&i.Transform,
		&i.RetiredAt,
		&i.Version,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const joinContractExists = `-- name: JoinContractExists :one
SELECT EXISTS (
    SELECT 1 FROM join_contracts
    WHERE workspace_id = $1 AND id = $2
) AS present
`

type JoinContractExistsParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	JoinContractID pgtype.UUID `json:"join_contract_id"`
}

func (q *Queries) JoinContractExists(ctx context.Context, arg JoinContractExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, joinContractExists, arg.WorkspaceID, arg.JoinContractID)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const listEntityKeys = `-- name: ListEntityKeys :many
SELECT id, workspace_id, asset_id, key_field_refs, uniqueness_semantics, version, content, created_by, created_at, updated_at FROM entity_keys
WHERE workspace_id = $1
ORDER BY updated_at DESC, id
`

func (q *Queries) ListEntityKeys(ctx context.Context, workspaceID pgtype.UUID) ([]EntityKey, error) {
	rows, err := q.db.Query(ctx, listEntityKeys, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityKey{}
	for rows.Next() {
		var i EntityKey
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AssetID,
			&i.KeyFieldRefs,
			&i.UniquenessSemantics,
			&i.Version,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJoinContracts = `-- name: ListJoinContracts :many
SELECT id, workspace_id, left_dataset_id, right_dataset_id, left_field_refs, right_field_refs, join_type, cardinality, join_expression, contract_notes, version, content, created_by, created_at, updated_at FROM join_contracts
WHERE workspace_id = $1
ORDER BY updated_at DESC, id
`

func (q *Queries) ListJoinContracts(ctx context.Context, workspaceID pgtype.UUID) ([]JoinContract, error) {
	rows, err := q.db.Query(ctx, listJoinContracts, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JoinContract{}
	for rows.Next() {
		var i JoinContract
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.LeftDatasetID,
			&i.RightDatasetID,
			&i.LeftFieldRefs,
			&i.RightFieldRefs,
			&i.JoinType,
			&i.Cardinality,
			&i.JoinExpression,
			&i.ContractNotes,
			&i.Version,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelGrains = `-- name: ListModelGrains :many
SELECT id, workspace_id, asset_id, grain_expression, grain_field_refs, documented_by, version, content, created_by, created_at, updated_at FROM model_grains
WHERE workspace_id = $1
ORDER BY updated_at DESC, id
`

func (q *Queries) ListModelGrains(ctx context.Context, workspaceID pgtype.UUID) ([]ModelGrain, error) {
	rows, err := q.db.Query(ctx, listModelGrains, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelGrain{}
	for rows.Next() {
		var i ModelGrain
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AssetID,
			&i.GrainExpression,
			&i.GrainFieldRefs,
			&i.DocumentedBy,
			&i.Version,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhysicalBindings = `-- name: ListPhysicalBindings :many
SELECT id, workspace_id, asset_id, dataset_id, field_id, transform, retired_at, version, content, created_by, created_at, updated_at FROM physical_bindings
WHERE workspace_id = $1
ORDER BY updated_at DESC, id
`

func (q *Queries) ListPhysicalBindings(ctx context.Context, workspaceID pgtype.UUID) ([]PhysicalBinding, error) {
	rows, err := q.db.Query(ctx, listPhysicalBindings, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhysicalBinding{}
	for rows.Next() {
		var i PhysicalBinding
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AssetID,
			&i.DatasetID,
			&i.FieldID,
			&i.Transform,
			&i.RetiredAt,
			&i.Version,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEntityKeyForUpdate = `-- name: LockEntityKeyForUpdate :one
SELECT version FROM entity_keys
WHERE workspace_id = $1 AND id = $2
FOR UPDATE
`

type LockEntityKeyForUpdateParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityKeyID pgtype.UUID `json:"entity_key_id"`
}

func (q *Queries) LockEntityKeyForUpdate(ctx context.Context, arg LockEntityKeyForUpdateParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockEntityKeyForUpdate, arg.WorkspaceID, arg.EntityKeyID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const lockJoinContractForUpdate = `-- name: LockJoinContractForUpdate :one
SELECT version FROM join_contracts
WHERE workspace_id = $1 AND id = $2
FOR UPDATE
`

type LockJoinContractForUpdateParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	JoinContractID pgtype.UUID `json:"join_contract_id"`
}

func (q *Queries) LockJoinContractForUpdate(ctx context.Context, arg LockJoinContractForUpdateParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockJoinContractForUpdate, arg.WorkspaceID, arg.JoinContractID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const lockModelGrainForUpdate = `-- name: LockModelGrainForUpdate :one
SELECT version FROM model_grains
WHERE workspace_id = $1 AND id = $2
FOR UPDATE
`

type LockModelGrainForUpdateParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	ModelGrainID pgtype.UUID `json:"model_grain_id"`
}

func (q *Queries) LockModelGrainForUpdate(ctx context.Context, arg LockModelGrainForUpdateParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockModelGrainForUpdate, arg.WorkspaceID, arg.ModelGrainID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const lockPhysicalBindingForUpdate = `-- name: LockPhysicalBindingForUpdate :one
SELECT version FROM physical_bindings
WHERE workspace_id = $1 AND id = $2
FOR UPDATE
`

type LockPhysicalBindingForUpdateParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	PhysicalBindingID pgtype.UUID `json:"physical_binding_id"`
}

func (q *Queries) LockPhysicalBindingForUpdate(ctx context.Context, arg LockPhysicalBindingForUpdateParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockPhysicalBindingForUpdate, arg.WorkspaceID, arg.PhysicalBindingID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const modelGrainExists = `-- name: ModelGrainExists :one
SELECT EXISTS (
    SELECT 1 FROM model_grains
    WHERE workspace_id = $1 AND id = $2
) AS present
`

type ModelGrainExistsParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	ModelGrainID pgtype.UUID `json:"model_grain_id"`
}

func (q *Queries) ModelGrainExists(ctx context.Context, arg ModelGrainExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, modelGrainExists, arg.WorkspaceID, arg.ModelGrainID)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const physicalBindingExists = `-- name: PhysicalBindingExists :one
SELECT EXISTS (
    SELECT 1 FROM physical_bindings
    WHERE workspace_id = $1 AND id = $2
) AS present
`

type PhysicalBindingExistsParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	PhysicalBindingID pgtype.UUID `json:"physical_binding_id"`
}

func (q *Queries) PhysicalBindingExists(ctx context.Context, arg PhysicalBindingExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, physicalBindingExists, arg.WorkspaceID, arg.PhysicalBindingID)
	var present bool
	err := row.Scan(&present)
	return present, err
}
