// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptWorkspaceInvitation = `-- name: AcceptWorkspaceInvitation :one
UPDATE workspace_invitations
SET status = 'accepted', accepted_by_account_id = $1,
    accepted_at = $2, updated_at = $2
WHERE id = $3 AND status = 'pending'
RETURNING id, workspace_id, issuer, subject, email, role_id, token_digest, status, created_by_principal_id, accepted_by_account_id, expires_at, accepted_at, revoked_at, created_at, updated_at, role_version
`

type AcceptWorkspaceInvitationParams struct {
	AccountID    pgtype.UUID        `json:"account_id"`
	AcceptedAt   pgtype.Timestamptz `json:"accepted_at"`
	InvitationID pgtype.UUID        `json:"invitation_id"`
}

func (q *Queries) AcceptWorkspaceInvitation(ctx context.Context, arg AcceptWorkspaceInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, acceptWorkspaceInvitation, arg.AccountID, arg.AcceptedAt, arg.InvitationID)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.RoleID,
		&i.TokenDigest,
		&i.Status,
		&i.CreatedByPrincipalID,
		&i.AcceptedByAccountID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleVersion,
	)
	return i, err
}

const consumeOIDCLoginAttempt = `-- name: ConsumeOIDCLoginAttempt :one
UPDATE oidc_login_attempts
SET consumed_at = $1
WHERE state_digest = $2
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING state_digest, nonce_digest, verifier_envelope, return_to, expires_at, consumed_at, created_at
`

type ConsumeOIDCLoginAttemptParams struct {
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	StateDigest []byte             `json:"state_digest"`
}

func (q *Queries) ConsumeOIDCLoginAttempt(ctx context.Context, arg ConsumeOIDCLoginAttemptParams) (OidcLoginAttempt, error) {
	row := q.db.QueryRow(ctx, consumeOIDCLoginAttempt, arg.ConsumedAt, arg.StateDigest)
	var i OidcLoginAttempt
	err := row.Scan(
		&i.StateDigest,
		&i.NonceDigest,
		&i.VerifierEnvelope,
		&i.ReturnTo,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createClientCredential = `-- name: CreateClientCredential :exec
INSERT INTO client_credentials(id,workspace_id,consumer_id,binding_id,principal_id,name,token_prefix,verifier_digest,allowed_actions,scope_type,scope_id,issued_by_principal_id,issued_at,expires_at,rotated_from_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
`

type CreateClientCredentialParams struct {
	ID                  pgtype.UUID        `json:"id"`
	WorkspaceID         pgtype.UUID        `json:"workspace_id"`
	ConsumerID          pgtype.UUID        `json:"consumer_id"`
	BindingID           pgtype.UUID        `json:"binding_id"`
	PrincipalID         pgtype.UUID        `json:"principal_id"`
	Name                string             `json:"name"`
	TokenPrefix         string             `json:"token_prefix"`
	VerifierDigest      []byte             `json:"verifier_digest"`
	AllowedActions      []string           `json:"allowed_actions"`
	ScopeType           string             `json:"scope_type"`
	ScopeID             string             `json:"scope_id"`
	IssuedByPrincipalID pgtype.UUID        `json:"issued_by_principal_id"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RotatedFromID       pgtype.UUID        `json:"rotated_from_id"`
}

func (q *Queries) CreateClientCredential(ctx context.Context, arg CreateClientCredentialParams) error {
	_, err := q.db.Exec(ctx, createClientCredential,
		arg.ID,
		arg.WorkspaceID,
		arg.ConsumerID,
		arg.BindingID,
		arg.PrincipalID,
		arg.Name,
		arg.TokenPrefix,
		arg.VerifierDigest,
		arg.AllowedActions,
		arg.ScopeType,
		arg.ScopeID,
		arg.IssuedByPrincipalID,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RotatedFromID,
	)
	return err
}

const createExternalIdentity = `-- name: CreateExternalIdentity :one
INSERT INTO external_identities (
    id, user_account_id, issuer, subject, verified_email, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, 'active', $6, $6
)
RETURNING id, user_account_id, issuer, subject, verified_email, status, created_at, updated_at
`

type CreateExternalIdentityParams struct {
	ID            pgtype.UUID        `json:"id"`
	UserAccountID pgtype.UUID        `json:"user_account_id"`
	Issuer        string             `json:"issuer"`
	Subject       string             `json:"subject"`
	VerifiedEmail pgtype.Text        `json:"verified_email"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateExternalIdentity(ctx context.Context, arg CreateExternalIdentityParams) (ExternalIdentity, error) {
	row := q.db.QueryRow(ctx, createExternalIdentity,
		arg.ID,
		arg.UserAccountID,
		arg.Issuer,
		arg.Subject,
		arg.VerifiedEmail,
		arg.CreatedAt,
	)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.Issuer,
		&i.Subject,
		&i.VerifiedEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOIDCLoginAttempt = `-- name: CreateOIDCLoginAttempt :exec
INSERT INTO oidc_login_attempts (
    state_digest, nonce_digest, verifier_envelope, return_to, expires_at, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type CreateOIDCLoginAttemptParams struct {
	StateDigest      []byte             `json:"state_digest"`
	NonceDigest      []byte             `json:"nonce_digest"`
	VerifierEnvelope []byte             `json:"verifier_envelope"`
	ReturnTo         string             `json:"return_to"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOIDCLoginAttempt(ctx context.Context, arg CreateOIDCLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, createOIDCLoginAttempt,
		arg.StateDigest,
		arg.NonceDigest,
		arg.VerifierEnvelope,
		arg.ReturnTo,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, token_digest, csrf_digest, user_account_id, idle_expires_at,
    absolute_expires_at, last_seen_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $8
)
RETURNING id, token_digest, csrf_digest, user_account_id, idle_expires_at, absolute_expires_at, last_seen_at, revoked_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID                pgtype.UUID        `json:"id"`
	TokenDigest       []byte             `json:"token_digest"`
	CsrfDigest        []byte             `json:"csrf_digest"`
	UserAccountID     pgtype.UUID        `json:"user_account_id"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.TokenDigest,
		arg.CsrfDigest,
		arg.UserAccountID,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.LastSeenAt,
		arg.CreatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.UserAccountID,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_accounts (id, display_name, status, created_at, updated_at)
VALUES ($1, $2, 'active', $3, $3)
RETURNING id, display_name, status, created_at, updated_at
`

type CreateUserAccountParams struct {
	ID          pgtype.UUID        `json:"id"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUserAccount, arg.ID, arg.DisplayName, arg.CreatedAt)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceInvitation = `-- name: CreateWorkspaceInvitation :one
INSERT INTO workspace_invitations (
    id, workspace_id, issuer, subject, email, role_id, role_version, token_digest, status,
    created_by_principal_id, expires_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, 'pending',
    $9, $10, $11, $11
)
RETURNING id, workspace_id, issuer, subject, email, role_id, token_digest, status, created_by_principal_id, accepted_by_account_id, expires_at, accepted_at, revoked_at, created_at, updated_at, role_version
`

type CreateWorkspaceInvitationParams struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	Issuer               string             `json:"issuer"`
	Subject              pgtype.Text        `json:"subject"`
	Email                pgtype.Text        `json:"email"`
	RoleID               string             `json:"role_id"`
	RoleVersion          int64              `json:"role_version"`
	TokenDigest          []byte             `json:"token_digest"`
	CreatedByPrincipalID pgtype.UUID        `json:"created_by_principal_id"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWorkspaceInvitation(ctx context.Context, arg CreateWorkspaceInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, createWorkspaceInvitation,
		arg.ID,
		arg.WorkspaceID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
		arg.RoleID,
		arg.RoleVersion,
		arg.TokenDigest,
		arg.CreatedByPrincipalID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.RoleID,
		&i.TokenDigest,
		&i.Status,
		&i.CreatedByPrincipalID,
		&i.AcceptedByAccountID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleVersion,
	)
	return i, err
}

const createWorkspaceMembership = `-- name: CreateWorkspaceMembership :one
INSERT INTO workspace_memberships (
    id, workspace_id, user_account_id, principal_id, status,
    admitted_by_principal_id, admitted_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    'active', $5, $6,
    $6, $6
)
ON CONFLICT (workspace_id, user_account_id) DO UPDATE
SET status = 'active', suspended_at = NULL, revoked_at = NULL, updated_at = EXCLUDED.updated_at
RETURNING id, workspace_id, user_account_id, principal_id, status, admitted_by_principal_id, admitted_at, suspended_at, revoked_at, created_at, updated_at
`

type CreateWorkspaceMembershipParams struct {
	ID                    pgtype.UUID        `json:"id"`
	WorkspaceID           pgtype.UUID        `json:"workspace_id"`
	UserAccountID         pgtype.UUID        `json:"user_account_id"`
	PrincipalID           pgtype.UUID        `json:"principal_id"`
	AdmittedByPrincipalID pgtype.UUID        `json:"admitted_by_principal_id"`
	AdmittedAt            pgtype.Timestamptz `json:"admitted_at"`
}

func (q *Queries) CreateWorkspaceMembership(ctx context.Context, arg CreateWorkspaceMembershipParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, createWorkspaceMembership,
		arg.ID,
		arg.WorkspaceID,
		arg.UserAccountID,
		arg.PrincipalID,
		arg.AdmittedByPrincipalID,
		arg.AdmittedAt,
	)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserAccountID,
		&i.PrincipalID,
		&i.Status,
		&i.AdmittedByPrincipalID,
		&i.AdmittedAt,
		&i.SuspendedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredOIDCLoginAttempts = `-- name: DeleteExpiredOIDCLoginAttempts :execrows
DELETE FROM oidc_login_attempts
WHERE expires_at <= $1::timestamptz OR consumed_at IS NOT NULL
`

func (q *Queries) DeleteExpiredOIDCLoginAttempts(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOIDCLoginAttempts, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireWorkspaceInvitations = `-- name: ExpireWorkspaceInvitations :execrows
UPDATE workspace_invitations
SET status = 'expired', updated_at = $1
WHERE workspace_id = $2
  AND status = 'pending'
  AND expires_at <= $1::timestamptz
`

type ExpireWorkspaceInvitationsParams struct {
	Now         pgtype.Timestamptz `json:"now"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

func (q *Queries) ExpireWorkspaceInvitations(ctx context.Context, arg ExpireWorkspaceInvitationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireWorkspaceInvitations, arg.Now, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExternalIdentityBySubject = `-- name: GetExternalIdentityBySubject :one
SELECT external_identity.id, external_identity.user_account_id, external_identity.issuer, external_identity.subject, external_identity.verified_email, external_identity.status, external_identity.created_at, external_identity.updated_at, account.display_name, account.status AS account_status,
       account.created_at AS account_created_at, account.updated_at AS account_updated_at
FROM external_identities AS external_identity
JOIN user_accounts AS account ON account.id = external_identity.user_account_id
WHERE external_identity.issuer = $1
  AND external_identity.subject = $2
`

type GetExternalIdentityBySubjectParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

type GetExternalIdentityBySubjectRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserAccountID    pgtype.UUID        `json:"user_account_id"`
	Issuer           string             `json:"issuer"`
	Subject          string             `json:"subject"`
	VerifiedEmail    pgtype.Text        `json:"verified_email"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DisplayName      string             `json:"display_name"`
	AccountStatus    string             `json:"account_status"`
	AccountCreatedAt pgtype.Timestamptz `json:"account_created_at"`
	AccountUpdatedAt pgtype.Timestamptz `json:"account_updated_at"`
}

func (q *Queries) GetExternalIdentityBySubject(ctx context.Context, arg GetExternalIdentityBySubjectParams) (GetExternalIdentityBySubjectRow, error) {
	row := q.db.QueryRow(ctx, getExternalIdentityBySubject, arg.Issuer, arg.Subject)
	var i GetExternalIdentityBySubjectRow
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.Issuer,
		&i.Subject,
		&i.VerifiedEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.AccountStatus,
		&i.AccountCreatedAt,
		&i.AccountUpdatedAt,
	)
	return i, err
}

const getPendingBootstrapInvitation = `-- name: GetPendingBootstrapInvitation :one
SELECT id, workspace_id, issuer, subject, email, role_id, token_digest, status, created_by_principal_id, accepted_by_account_id, expires_at, accepted_at, revoked_at, created_at, updated_at, role_version FROM workspace_invitations
WHERE workspace_id = $1
  AND issuer = $2
  AND email = $3
  AND role_id = 'workspace_admin'
  AND status = 'pending'
  AND expires_at > $4::timestamptz
ORDER BY created_at, id
LIMIT 1
`

type GetPendingBootstrapInvitationParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Issuer      string             `json:"issuer"`
	Email       pgtype.Text        `json:"email"`
	Now         pgtype.Timestamptz `json:"now"`
}

func (q *Queries) GetPendingBootstrapInvitation(ctx context.Context, arg GetPendingBootstrapInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getPendingBootstrapInvitation,
		arg.WorkspaceID,
		arg.Issuer,
		arg.Email,
		arg.Now,
	)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.RoleID,
		&i.TokenDigest,
		&i.Status,
		&i.CreatedByPrincipalID,
		&i.AcceptedByAccountID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleVersion,
	)
	return i, err
}

const getWorkspaceMembershipByAccount = `-- name: GetWorkspaceMembershipByAccount :one
SELECT id, workspace_id, user_account_id, principal_id, status, admitted_by_principal_id, admitted_at, suspended_at, revoked_at, created_at, updated_at FROM workspace_memberships
WHERE workspace_id = $1
  AND user_account_id = $2
`

type GetWorkspaceMembershipByAccountParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	UserAccountID pgtype.UUID `json:"user_account_id"`
}

func (q *Queries) GetWorkspaceMembershipByAccount(ctx context.Context, arg GetWorkspaceMembershipByAccountParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMembershipByAccount, arg.WorkspaceID, arg.UserAccountID)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserAccountID,
		&i.PrincipalID,
		&i.Status,
		&i.AdmittedByPrincipalID,
		&i.AdmittedAt,
		&i.SuspendedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMembershipDetails = `-- name: GetWorkspaceMembershipDetails :one
SELECT membership.id, membership.workspace_id, membership.user_account_id, membership.principal_id, membership.status, membership.admitted_by_principal_id, membership.admitted_at, membership.suspended_at, membership.revoked_at, membership.created_at, membership.updated_at, account.display_name AS account_display_name,
       principal.display_name AS principal_display_name,
       COALESCE(array_agg(binding.role_id ORDER BY binding.role_id)
           FILTER (WHERE binding.role_id IS NOT NULL), ARRAY[]::text[])::text[] AS role_ids
FROM workspace_memberships AS membership
JOIN user_accounts AS account ON account.id = membership.user_account_id
JOIN principals AS principal
  ON principal.workspace_id = membership.workspace_id AND principal.id = membership.principal_id
LEFT JOIN role_bindings AS binding ON binding.principal_id = principal.id
WHERE membership.workspace_id = $1 AND membership.id = $2
GROUP BY membership.id, account.display_name, principal.display_name
`

type GetWorkspaceMembershipDetailsParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	MembershipID pgtype.UUID `json:"membership_id"`
}

type GetWorkspaceMembershipDetailsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	WorkspaceID           pgtype.UUID        `json:"workspace_id"`
	UserAccountID         pgtype.UUID        `json:"user_account_id"`
	PrincipalID           pgtype.UUID        `json:"principal_id"`
	Status                string             `json:"status"`
	AdmittedByPrincipalID pgtype.UUID        `json:"admitted_by_principal_id"`
	AdmittedAt            pgtype.Timestamptz `json:"admitted_at"`
	SuspendedAt           pgtype.Timestamptz `json:"suspended_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	AccountDisplayName    string             `json:"account_display_name"`
	PrincipalDisplayName  string             `json:"principal_display_name"`
	RoleIds               []string           `json:"role_ids"`
}

func (q *Queries) GetWorkspaceMembershipDetails(ctx context.Context, arg GetWorkspaceMembershipDetailsParams) (GetWorkspaceMembershipDetailsRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMembershipDetails, arg.WorkspaceID, arg.MembershipID)
	var i GetWorkspaceMembershipDetailsRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserAccountID,
		&i.PrincipalID,
		&i.Status,
		&i.AdmittedByPrincipalID,
		&i.AdmittedAt,
		&i.SuspendedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountDisplayName,
		&i.PrincipalDisplayName,
		&i.RoleIds,
	)
	return i, err
}

const getWorkspaceMembershipForUpdate = `-- name: GetWorkspaceMembershipForUpdate :one
SELECT id, workspace_id, user_account_id, principal_id, status, admitted_by_principal_id, admitted_at, suspended_at, revoked_at, created_at, updated_at FROM workspace_memberships
WHERE workspace_id = $1 AND id = $2
FOR UPDATE
`

type GetWorkspaceMembershipForUpdateParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	MembershipID pgtype.UUID `json:"membership_id"`
}

func (q *Queries) GetWorkspaceMembershipForUpdate(ctx context.Context, arg GetWorkspaceMembershipForUpdateParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMembershipForUpdate, arg.WorkspaceID, arg.MembershipID)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserAccountID,
		&i.PrincipalID,
		&i.Status,
		&i.AdmittedByPrincipalID,
		&i.AdmittedAt,
		&i.SuspendedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantWorkspaceRole = `-- name: GrantWorkspaceRole :execrows
INSERT INTO role_bindings (
    id, workspace_id, principal_id, role_id, role_version, scope_type, scope_id,
    granted_by, granted_at
)
VALUES (
    $1, $2, $3, $4,
    $5, 'workspace', $2::uuid::text,
    $6, $7
)
ON CONFLICT DO NOTHING
`

type GrantWorkspaceRoleParams struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	PrincipalID pgtype.UUID        `json:"principal_id"`
	RoleID      string             `json:"role_id"`
	RoleVersion int64              `json:"role_version"`
	GrantedBy   pgtype.UUID        `json:"granted_by"`
	GrantedAt   pgtype.Timestamptz `json:"granted_at"`
}

func (q *Queries) GrantWorkspaceRole(ctx context.Context, arg GrantWorkspaceRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantWorkspaceRole,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.RoleID,
		arg.RoleVersion,
		arg.GrantedBy,
		arg.GrantedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAccountMemberships = `-- name: ListAccountMemberships :many
SELECT membership.id, membership.workspace_id, membership.user_account_id, membership.principal_id, membership.status, membership.admitted_by_principal_id, membership.admitted_at, membership.suspended_at, membership.revoked_at, membership.created_at, membership.updated_at, principal.display_name AS principal_display_name,
       workspace.slug AS workspace_slug, workspace.display_name AS workspace_display_name,
       workspace.authorization_version,
       COALESCE(array_agg(binding.role_id ORDER BY binding.role_id)
           FILTER (WHERE binding.role_id IS NOT NULL), ARRAY[]::text[])::text[] AS role_ids
FROM workspace_memberships AS membership
JOIN principals AS principal
  ON principal.workspace_id = membership.workspace_id AND principal.id = membership.principal_id
JOIN workspaces AS workspace ON workspace.id = membership.workspace_id
LEFT JOIN role_bindings AS binding ON binding.principal_id = principal.id
WHERE membership.user_account_id = $1
  AND membership.status = 'active'
  AND principal.status = 'active'
GROUP BY membership.id, principal.display_name, workspace.slug, workspace.display_name,
         workspace.authorization_version
ORDER BY workspace.display_name, membership.workspace_id
`

type ListAccountMembershipsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	WorkspaceID           pgtype.UUID        `json:"workspace_id"`
	UserAccountID         pgtype.UUID        `json:"user_account_id"`
	PrincipalID           pgtype.UUID        `json:"principal_id"`
	Status                string             `json:"status"`
	AdmittedByPrincipalID pgtype.UUID        `json:"admitted_by_principal_id"`
	AdmittedAt            pgtype.Timestamptz `json:"admitted_at"`
	SuspendedAt           pgtype.Timestamptz `json:"suspended_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	PrincipalDisplayName  string             `json:"principal_display_name"`
	WorkspaceSlug         string             `json:"workspace_slug"`
	WorkspaceDisplayName  string             `json:"workspace_display_name"`
	AuthorizationVersion  int64              `json:"authorization_version"`
	RoleIds               []string           `json:"role_ids"`
}

func (q *Queries) ListAccountMemberships(ctx context.Context, userAccountID pgtype.UUID) ([]ListAccountMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listAccountMemberships, userAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountMembershipsRow{}
	for rows.Next() {
		var i ListAccountMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserAccountID,
			&i.PrincipalID,
			&i.Status,
			&i.AdmittedByPrincipalID,
			&i.AdmittedAt,
			&i.SuspendedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrincipalDisplayName,
			&i.WorkspaceSlug,
			&i.WorkspaceDisplayName,
			&i.AuthorizationVersion,
			&i.RoleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientCredentials = `-- name: ListClientCredentials :many
SELECT id, workspace_id, consumer_id, binding_id, principal_id, name, token_prefix, verifier_digest, verifier_version, allowed_actions, scope_type, scope_id, issued_by_principal_id, issued_at, expires_at, revoked_at, revoked_by_principal_id, rotated_from_id, last_used_at FROM client_credentials WHERE workspace_id=$1 ORDER BY issued_at DESC,id DESC LIMIT 200
`

func (q *Queries) ListClientCredentials(ctx context.Context, workspaceID pgtype.UUID) ([]ClientCredential, error) {
	rows, err := q.db.Query(ctx, listClientCredentials, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientCredential{}
	for rows.Next() {
		var i ClientCredential
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ConsumerID,
			&i.BindingID,
			&i.PrincipalID,
			&i.Name,
			&i.TokenPrefix,
			&i.VerifierDigest,
			&i.VerifierVersion,
			&i.AllowedActions,
			&i.ScopeType,
			&i.ScopeID,
			&i.IssuedByPrincipalID,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedByPrincipalID,
			&i.RotatedFromID,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchingPendingInvitations = `-- name: ListMatchingPendingInvitations :many
SELECT id, workspace_id, issuer, subject, email, role_id, token_digest, status, created_by_principal_id, accepted_by_account_id, expires_at, accepted_at, revoked_at, created_at, updated_at, role_version FROM workspace_invitations
WHERE issuer = $1
  AND status = 'pending'
  AND expires_at > $2::timestamptz
  AND (
      (subject IS NOT NULL AND subject = $3)
      OR (email IS NOT NULL AND $4::boolean AND email = $5)
  )
ORDER BY created_at, id
`

type ListMatchingPendingInvitationsParams struct {
	Issuer        string             `json:"issuer"`
	Now           pgtype.Timestamptz `json:"now"`
	Subject       pgtype.Text        `json:"subject"`
	EmailVerified bool               `json:"email_verified"`
	Email         pgtype.Text        `json:"email"`
}

func (q *Queries) ListMatchingPendingInvitations(ctx context.Context, arg ListMatchingPendingInvitationsParams) ([]WorkspaceInvitation, error) {
	rows, err := q.db.Query(ctx, listMatchingPendingInvitations,
		arg.Issuer,
		arg.Now,
		arg.Subject,
		arg.EmailVerified,
		arg.Email,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceInvitation{}
	for rows.Next() {
		var i WorkspaceInvitation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Issuer,
			&i.Subject,
			&i.Email,
			&i.RoleID,
			&i.TokenDigest,
			&i.Status,
			&i.CreatedByPrincipalID,
			&i.AcceptedByAccountID,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceInvitations = `-- name: ListWorkspaceInvitations :many
SELECT id, workspace_id, issuer, subject, email, role_id, token_digest, status, created_by_principal_id, accepted_by_account_id, expires_at, accepted_at, revoked_at, created_at, updated_at, role_version FROM workspace_invitations
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListWorkspaceInvitations(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceInvitation, error) {
	rows, err := q.db.Query(ctx, listWorkspaceInvitations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceInvitation{}
	for rows.Next() {
		var i WorkspaceInvitation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Issuer,
			&i.Subject,
			&i.Email,
			&i.RoleID,
			&i.TokenDigest,
			&i.Status,
			&i.CreatedByPrincipalID,
			&i.AcceptedByAccountID,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMemberships = `-- name: ListWorkspaceMemberships :many
SELECT membership.id, membership.workspace_id, membership.user_account_id, membership.principal_id, membership.status, membership.admitted_by_principal_id, membership.admitted_at, membership.suspended_at, membership.revoked_at, membership.created_at, membership.updated_at, account.display_name AS account_display_name,
       principal.display_name AS principal_display_name,
       COALESCE(array_agg(binding.role_id ORDER BY binding.role_id)
           FILTER (WHERE binding.role_id IS NOT NULL), ARRAY[]::text[])::text[] AS role_ids
FROM workspace_memberships AS membership
JOIN user_accounts AS account ON account.id = membership.user_account_id
JOIN principals AS principal
  ON principal.workspace_id = membership.workspace_id AND principal.id = membership.principal_id
LEFT JOIN role_bindings AS binding ON binding.principal_id = principal.id
WHERE membership.workspace_id = $1
GROUP BY membership.id, account.display_name, principal.display_name
ORDER BY account.display_name, membership.id
`

type ListWorkspaceMembershipsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	WorkspaceID           pgtype.UUID        `json:"workspace_id"`
	UserAccountID         pgtype.UUID        `json:"user_account_id"`
	PrincipalID           pgtype.UUID        `json:"principal_id"`
	Status                string             `json:"status"`
	AdmittedByPrincipalID pgtype.UUID        `json:"admitted_by_principal_id"`
	AdmittedAt            pgtype.Timestamptz `json:"admitted_at"`
	SuspendedAt           pgtype.Timestamptz `json:"suspended_at"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	AccountDisplayName    string             `json:"account_display_name"`
	PrincipalDisplayName  string             `json:"principal_display_name"`
	RoleIds               []string           `json:"role_ids"`
}

func (q *Queries) ListWorkspaceMemberships(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMemberships, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembershipsRow{}
	for rows.Next() {
		var i ListWorkspaceMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserAccountID,
			&i.PrincipalID,
			&i.Status,
			&i.AdmittedByPrincipalID,
			&i.AdmittedAt,
			&i.SuspendedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountDisplayName,
			&i.PrincipalDisplayName,
			&i.RoleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadActiveSession = `-- name: LoadActiveSession :one
SELECT session.id, session.token_digest, session.csrf_digest, session.user_account_id, session.idle_expires_at, session.absolute_expires_at, session.last_seen_at, session.revoked_at, session.created_at, session.updated_at, account.display_name, account.status AS account_status,
       account.created_at AS account_created_at, account.updated_at AS account_updated_at
FROM sessions AS session
JOIN user_accounts AS account ON account.id = session.user_account_id
WHERE session.token_digest = $1
  AND session.revoked_at IS NULL
  AND session.idle_expires_at > $2::timestamptz
  AND session.absolute_expires_at > $2::timestamptz
  AND account.status = 'active'
`

type LoadActiveSessionParams struct {
	TokenDigest []byte             `json:"token_digest"`
	Now         pgtype.Timestamptz `json:"now"`
}

type LoadActiveSessionRow struct {
	ID                pgtype.UUID        `json:"id"`
	TokenDigest       []byte             `json:"token_digest"`
	CsrfDigest        []byte             `json:"csrf_digest"`
	UserAccountID     pgtype.UUID        `json:"user_account_id"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DisplayName       string             `json:"display_name"`
	AccountStatus     string             `json:"account_status"`
	AccountCreatedAt  pgtype.Timestamptz `json:"account_created_at"`
	AccountUpdatedAt  pgtype.Timestamptz `json:"account_updated_at"`
}

func (q *Queries) LoadActiveSession(ctx context.Context, arg LoadActiveSessionParams) (LoadActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, loadActiveSession, arg.TokenDigest, arg.Now)
	var i LoadActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.UserAccountID,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.AccountStatus,
		&i.AccountCreatedAt,
		&i.AccountUpdatedAt,
	)
	return i, err
}

const loadClientCredential = `-- name: LoadClientCredential :one
SELECT id, workspace_id, consumer_id, binding_id, principal_id, name, token_prefix, verifier_digest, verifier_version, allowed_actions, scope_type, scope_id, issued_by_principal_id, issued_at, expires_at, revoked_at, revoked_by_principal_id, rotated_from_id, last_used_at FROM client_credentials WHERE id=$1
`

func (q *Queries) LoadClientCredential(ctx context.Context, id pgtype.UUID) (ClientCredential, error) {
	row := q.db.QueryRow(ctx, loadClientCredential, id)
	var i ClientCredential
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ConsumerID,
		&i.BindingID,
		&i.PrincipalID,
		&i.Name,
		&i.TokenPrefix,
		&i.VerifierDigest,
		&i.VerifierVersion,
		&i.AllowedActions,
		&i.ScopeType,
		&i.ScopeID,
		&i.IssuedByPrincipalID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByPrincipalID,
		&i.RotatedFromID,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeClientCredential = `-- name: RevokeClientCredential :execrows
UPDATE client_credentials SET revoked_at=COALESCE(revoked_at,$3),revoked_by_principal_id=COALESCE(revoked_by_principal_id,$4)
WHERE workspace_id=$1 AND id=$2
`

type RevokeClientCredentialParams struct {
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	ID                   pgtype.UUID        `json:"id"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
	RevokedByPrincipalID pgtype.UUID        `json:"revoked_by_principal_id"`
}

func (q *Queries) RevokeClientCredential(ctx context.Context, arg RevokeClientCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeClientCredential,
		arg.WorkspaceID,
		arg.ID,
		arg.RevokedAt,
		arg.RevokedByPrincipalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByDigest = `-- name: RevokeSessionByDigest :execrows
UPDATE sessions
SET revoked_at = $1, updated_at = $1
WHERE token_digest = $2 AND revoked_at IS NULL
`

type RevokeSessionByDigestParams struct {
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	TokenDigest []byte             `json:"token_digest"`
}

func (q *Queries) RevokeSessionByDigest(ctx context.Context, arg RevokeSessionByDigestParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByDigest, arg.RevokedAt, arg.TokenDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMembershipPrincipalStatus = `-- name: SetMembershipPrincipalStatus :execrows
UPDATE principals
SET status = $1
WHERE workspace_id = $2 AND id = $3
`

type SetMembershipPrincipalStatusParams struct {
	Status      string      `json:"status"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	PrincipalID pgtype.UUID `json:"principal_id"`
}

func (q *Queries) SetMembershipPrincipalStatus(ctx context.Context, arg SetMembershipPrincipalStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMembershipPrincipalStatus, arg.Status, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkspaceMembershipStatus = `-- name: SetWorkspaceMembershipStatus :one
UPDATE workspace_memberships
SET status = $1,
    suspended_at = CASE WHEN $1::text = 'suspended' THEN $2::timestamptz ELSE NULL END,
    revoked_at = CASE WHEN $1::text = 'revoked' THEN $2::timestamptz ELSE NULL END,
    updated_at = $2
WHERE workspace_id = $3 AND id = $4
RETURNING id, workspace_id, user_account_id, principal_id, status, admitted_by_principal_id, admitted_at, suspended_at, revoked_at, created_at, updated_at
`

type SetWorkspaceMembershipStatusParams struct {
	Status       string             `json:"status"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	MembershipID pgtype.UUID        `json:"membership_id"`
}

func (q *Queries) SetWorkspaceMembershipStatus(ctx context.Context, arg SetWorkspaceMembershipStatusParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, setWorkspaceMembershipStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.MembershipID,
	)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserAccountID,
		&i.PrincipalID,
		&i.Status,
		&i.AdmittedByPrincipalID,
		&i.AdmittedAt,
		&i.SuspendedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchClientCredential = `-- name: TouchClientCredential :exec
UPDATE client_credentials SET last_used_at=$2 WHERE id=$1 AND (last_used_at IS NULL OR last_used_at<$2::timestamptz-interval '1 minute')
`

type TouchClientCredentialParams struct {
	ID         pgtype.UUID        `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchClientCredential(ctx context.Context, arg TouchClientCredentialParams) error {
	_, err := q.db.Exec(ctx, touchClientCredential, arg.ID, arg.LastUsedAt)
	return err
}

const touchSession = `-- name: TouchSession :one
UPDATE sessions
SET last_seen_at = $1,
    idle_expires_at = LEAST($2, absolute_expires_at),
    updated_at = $1
WHERE id = $3 AND revoked_at IS NULL
  AND idle_expires_at > $1::timestamptz
  AND absolute_expires_at > $1::timestamptz
RETURNING id, token_digest, csrf_digest, user_account_id, idle_expires_at, absolute_expires_at, last_seen_at, revoked_at, created_at, updated_at
`

type TouchSessionParams struct {
	Now           pgtype.Timestamptz `json:"now"`
	IdleExpiresAt pgtype.Timestamptz `json:"idle_expires_at"`
	SessionID     pgtype.UUID        `json:"session_id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.Now, arg.IdleExpiresAt, arg.SessionID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.UserAccountID,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const workspaceExistsBySlug = `-- name: WorkspaceExistsBySlug :one
SELECT id FROM workspaces WHERE slug = $1
`

func (q *Queries) WorkspaceExistsBySlug(ctx context.Context, slug string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, workspaceExistsBySlug, slug)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
