// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
WITH candidate AS (
    SELECT id
    FROM jobs
    WHERE status IN ('queued', 'retryable')
      AND available_at <= $3
    ORDER BY available_at, created_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE jobs
SET status = 'running',
    attempt = attempt + 1,
    leased_until = $1,
    lease_owner = $2,
    last_error_code = NULL,
    updated_at = $3
FROM candidate
WHERE jobs.id = candidate.id
RETURNING jobs.legacy_id, jobs.legacy_workspace_id, jobs.job_type, jobs.payload, jobs.status, jobs.attempt, jobs.max_attempts, jobs.available_at, jobs.leased_until, jobs.lease_owner, jobs.idempotency_key, jobs.last_error_code, jobs.trace_id, jobs.created_at, jobs.updated_at, jobs.completed_at, jobs.id, jobs.workspace_id
`

type ClaimJobParams struct {
	LeasedUntil pgtype.Timestamptz `json:"leased_until"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.LeasedUntil, arg.LeaseOwner, arg.ClaimedAt)
	var i Job
	err := row.Scan(
		&i.LegacyID,
		&i.LegacyWorkspaceID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LeasedUntil,
		&i.LeaseOwner,
		&i.IdempotencyKey,
		&i.LastErrorCode,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ID,
		&i.WorkspaceID,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (
    id, workspace_id, job_type, payload, max_attempts,
    available_at, idempotency_key, trace_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
ON CONFLICT (workspace_id, idempotency_key) DO UPDATE
SET idempotency_key = EXCLUDED.idempotency_key
RETURNING legacy_id, legacy_workspace_id, job_type, payload, status, attempt, max_attempts, available_at, leased_until, lease_owner, idempotency_key, last_error_code, trace_id, created_at, updated_at, completed_at, id, workspace_id
`

type EnqueueJobParams struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	JobType        string             `json:"job_type"`
	Payload        []byte             `json:"payload"`
	MaxAttempts    int32              `json:"max_attempts"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	IdempotencyKey string             `json:"idempotency_key"`
	TraceID        string             `json:"trace_id"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.ID,
		arg.WorkspaceID,
		arg.JobType,
		arg.Payload,
		arg.MaxAttempts,
		arg.AvailableAt,
		arg.IdempotencyKey,
		arg.TraceID,
	)
	var i Job
	err := row.Scan(
		&i.LegacyID,
		&i.LegacyWorkspaceID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LeasedUntil,
		&i.LeaseOwner,
		&i.IdempotencyKey,
		&i.LastErrorCode,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ID,
		&i.WorkspaceID,
	)
	return i, err
}

const extendJobLease = `-- name: ExtendJobLease :execrows
UPDATE jobs
SET leased_until = $1,
    updated_at = $2
WHERE id = $3
  AND status = 'running'
  AND lease_owner = $4
  AND leased_until > $2
`

type ExtendJobLeaseParams struct {
	LeasedUntil pgtype.Timestamptz `json:"leased_until"`
	RenewedAt   pgtype.Timestamptz `json:"renewed_at"`
	ID          pgtype.UUID        `json:"id"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
}

func (q *Queries) ExtendJobLease(ctx context.Context, arg ExtendJobLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendJobLease,
		arg.LeasedUntil,
		arg.RenewedAt,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJobByID = `-- name: GetJobByID :one
SELECT legacy_id, legacy_workspace_id, job_type, payload, status, attempt, max_attempts, available_at, leased_until, lease_owner, idempotency_key, last_error_code, trace_id, created_at, updated_at, completed_at, id, workspace_id FROM jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.LegacyID,
		&i.LegacyWorkspaceID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LeasedUntil,
		&i.LeaseOwner,
		&i.IdempotencyKey,
		&i.LastErrorCode,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ID,
		&i.WorkspaceID,
	)
	return i, err
}

const markJobFailed = `-- name: MarkJobFailed :execrows
UPDATE jobs
SET status = CASE WHEN $1::boolean OR attempt >= max_attempts THEN 'dead_letter' ELSE 'retryable' END,
    available_at = $2,
    leased_until = NULL,
    lease_owner = NULL,
    last_error_code = $3,
    updated_at = $4,
    completed_at = CASE
        WHEN $1::boolean OR attempt >= max_attempts THEN $4::timestamptz
        ELSE NULL::timestamptz
    END
WHERE id = $5
  AND status = 'running'
  AND lease_owner = $6
  AND leased_until > $4
`

type MarkJobFailedParams struct {
	Permanent   bool               `json:"permanent"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	ErrorCode   pgtype.Text        `json:"error_code"`
	FailedAt    pgtype.Timestamptz `json:"failed_at"`
	ID          pgtype.UUID        `json:"id"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markJobFailed,
		arg.Permanent,
		arg.AvailableAt,
		arg.ErrorCode,
		arg.FailedAt,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobSucceeded = `-- name: MarkJobSucceeded :execrows
UPDATE jobs
SET status = 'succeeded',
    leased_until = NULL,
    lease_owner = NULL,
    last_error_code = NULL,
    updated_at = $1,
    completed_at = $1
WHERE id = $2
  AND status = 'running'
  AND lease_owner = $3
  AND leased_until > $1
`

type MarkJobSucceededParams struct {
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          pgtype.UUID        `json:"id"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
}

func (q *Queries) MarkJobSucceeded(ctx context.Context, arg MarkJobSucceededParams) (int64, error) {
	result, err := q.db.Exec(ctx, markJobSucceeded, arg.CompletedAt, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reapExpiredJobs = `-- name: ReapExpiredJobs :many
UPDATE jobs
SET status = CASE WHEN attempt >= max_attempts THEN 'dead_letter' ELSE 'retryable' END,
    available_at = $1,
    leased_until = NULL,
    lease_owner = NULL,
    last_error_code = 'LEASE_EXPIRED',
    updated_at = $1,
    completed_at = CASE WHEN attempt >= max_attempts THEN $1 ELSE NULL END
WHERE status = 'running'
  AND leased_until <= $1
RETURNING legacy_id, legacy_workspace_id, job_type, payload, status, attempt, max_attempts, available_at, leased_until, lease_owner, idempotency_key, last_error_code, trace_id, created_at, updated_at, completed_at, id, workspace_id
`

func (q *Queries) ReapExpiredJobs(ctx context.Context, expiredAt pgtype.Timestamptz) ([]Job, error) {
	rows, err := q.db.Query(ctx, reapExpiredJobs, expiredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.LegacyID,
			&i.LegacyWorkspaceID,
			&i.JobType,
			&i.Payload,
			&i.Status,
			&i.Attempt,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LeasedUntil,
			&i.LeaseOwner,
			&i.IdempotencyKey,
			&i.LastErrorCode,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ID,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
