// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	EventType   string             `json:"event_type"`
	ActorID     pgtype.Text        `json:"actor_id"`
	Payload     []byte             `json:"payload"`
	TraceID     string             `json:"trace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID             string             `json:"id"`
	WorkspaceID    string             `json:"workspace_id"`
	JobType        string             `json:"job_type"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempt        int32              `json:"attempt"`
	MaxAttempts    int32              `json:"max_attempts"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	LeasedUntil    pgtype.Timestamptz `json:"leased_until"`
	LeaseOwner     pgtype.Text        `json:"lease_owner"`
	IdempotencyKey string             `json:"idempotency_key"`
	LastErrorCode  pgtype.Text        `json:"last_error_code"`
	TraceID        string             `json:"trace_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type OutboxEvent struct {
	ID            string             `json:"id"`
	WorkspaceID   string             `json:"workspace_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempt       int32              `json:"attempt"`
	MaxAttempts   int32              `json:"max_attempts"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	LeasedUntil   pgtype.Timestamptz `json:"leased_until"`
	LeaseOwner    pgtype.Text        `json:"lease_owner"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	TraceID       string             `json:"trace_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

type Workspace struct {
	ID          string             `json:"id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
