// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: modelconfig.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearModelSettingDefaults = `-- name: ClearModelSettingDefaults :exec
UPDATE model_settings
SET is_default = false, updated_at = $1
WHERE workspace_id = $2 AND kind = $3
  AND id <> $4
`

type ClearModelSettingDefaultsParams struct {
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Kind        string             `json:"kind"`
	SettingID   pgtype.UUID        `json:"setting_id"`
}

func (q *Queries) ClearModelSettingDefaults(ctx context.Context, arg ClearModelSettingDefaultsParams) error {
	_, err := q.db.Exec(ctx, clearModelSettingDefaults,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.Kind,
		arg.SettingID,
	)
	return err
}

const createModelProvider = `-- name: CreateModelProvider :one

INSERT INTO model_providers (
    id, workspace_id, protocol, display_name, base_url,
    credential_env, credential_revision, enabled, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, workspace_id, protocol, display_name, base_url, credential_env, credential_revision, enabled, created_at, updated_at
`

type CreateModelProviderParams struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Protocol           string             `json:"protocol"`
	DisplayName        string             `json:"display_name"`
	BaseUrl            pgtype.Text        `json:"base_url"`
	CredentialEnv      string             `json:"credential_env"`
	CredentialRevision string             `json:"credential_revision"`
	Enabled            bool               `json:"enabled"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// M2-T009 model configuration queries. Credential material never appears:
// only the env-var NAME and the revision digest are stored or read.
func (q *Queries) CreateModelProvider(ctx context.Context, arg CreateModelProviderParams) (ModelProvider, error) {
	row := q.db.QueryRow(ctx, createModelProvider,
		arg.ID,
		arg.WorkspaceID,
		arg.Protocol,
		arg.DisplayName,
		arg.BaseUrl,
		arg.CredentialEnv,
		arg.CredentialRevision,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ModelProvider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Protocol,
		&i.DisplayName,
		&i.BaseUrl,
		&i.CredentialEnv,
		&i.CredentialRevision,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createModelSetting = `-- name: CreateModelSetting :one
INSERT INTO model_settings (
    id, workspace_id, provider_id, kind, model, enabled, is_default,
    capability, token_limit, embedding_dimension, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, workspace_id, provider_id, kind, model, enabled, is_default, capability, token_limit, embedding_dimension, created_at, updated_at
`

type CreateModelSettingParams struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	ProviderID         pgtype.UUID        `json:"provider_id"`
	Kind               string             `json:"kind"`
	Model              string             `json:"model"`
	Enabled            bool               `json:"enabled"`
	IsDefault          bool               `json:"is_default"`
	Capability         string             `json:"capability"`
	TokenLimit         int32              `json:"token_limit"`
	EmbeddingDimension pgtype.Int4        `json:"embedding_dimension"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateModelSetting(ctx context.Context, arg CreateModelSettingParams) (ModelSetting, error) {
	row := q.db.QueryRow(ctx, createModelSetting,
		arg.ID,
		arg.WorkspaceID,
		arg.ProviderID,
		arg.Kind,
		arg.Model,
		arg.Enabled,
		arg.IsDefault,
		arg.Capability,
		arg.TokenLimit,
		arg.EmbeddingDimension,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ModelSetting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderID,
		&i.Kind,
		&i.Model,
		&i.Enabled,
		&i.IsDefault,
		&i.Capability,
		&i.TokenLimit,
		&i.EmbeddingDimension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultModelSetting = `-- name: GetDefaultModelSetting :one
SELECT setting.id, setting.workspace_id, setting.provider_id, setting.kind, setting.model, setting.enabled, setting.is_default, setting.capability, setting.token_limit, setting.embedding_dimension, setting.created_at, setting.updated_at FROM model_settings AS setting
JOIN model_providers AS provider
  ON provider.workspace_id = setting.workspace_id AND provider.id = setting.provider_id
WHERE setting.workspace_id = $1 AND setting.kind = $2
  AND setting.is_default AND setting.enabled AND provider.enabled
LIMIT 1
`

type GetDefaultModelSettingParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Kind        string      `json:"kind"`
}

func (q *Queries) GetDefaultModelSetting(ctx context.Context, arg GetDefaultModelSettingParams) (ModelSetting, error) {
	row := q.db.QueryRow(ctx, getDefaultModelSetting, arg.WorkspaceID, arg.Kind)
	var i ModelSetting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderID,
		&i.Kind,
		&i.Model,
		&i.Enabled,
		&i.IsDefault,
		&i.Capability,
		&i.TokenLimit,
		&i.EmbeddingDimension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelProvider = `-- name: GetModelProvider :one
SELECT id, workspace_id, protocol, display_name, base_url, credential_env, credential_revision, enabled, created_at, updated_at FROM model_providers
WHERE workspace_id = $1 AND id = $2
`

type GetModelProviderParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ProviderID  pgtype.UUID `json:"provider_id"`
}

func (q *Queries) GetModelProvider(ctx context.Context, arg GetModelProviderParams) (ModelProvider, error) {
	row := q.db.QueryRow(ctx, getModelProvider, arg.WorkspaceID, arg.ProviderID)
	var i ModelProvider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Protocol,
		&i.DisplayName,
		&i.BaseUrl,
		&i.CredentialEnv,
		&i.CredentialRevision,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelSetting = `-- name: GetModelSetting :one
SELECT id, workspace_id, provider_id, kind, model, enabled, is_default, capability, token_limit, embedding_dimension, created_at, updated_at FROM model_settings
WHERE workspace_id = $1 AND id = $2
`

type GetModelSettingParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SettingID   pgtype.UUID `json:"setting_id"`
}

func (q *Queries) GetModelSetting(ctx context.Context, arg GetModelSettingParams) (ModelSetting, error) {
	row := q.db.QueryRow(ctx, getModelSetting, arg.WorkspaceID, arg.SettingID)
	var i ModelSetting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderID,
		&i.Kind,
		&i.Model,
		&i.Enabled,
		&i.IsDefault,
		&i.Capability,
		&i.TokenLimit,
		&i.EmbeddingDimension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceAgentPrincipal = `-- name: GetWorkspaceAgentPrincipal :one
SELECT principal.id, principal.workspace_id, principal.kind, principal.display_name, principal.owner_principal_id, principal.status, principal.created_at FROM principals AS principal
WHERE principal.workspace_id = $1 AND principal.kind = 'agent'
ORDER BY principal.created_at, principal.id
LIMIT 1
`

func (q *Queries) GetWorkspaceAgentPrincipal(ctx context.Context, workspaceID pgtype.UUID) (Principal, error) {
	row := q.db.QueryRow(ctx, getWorkspaceAgentPrincipal, workspaceID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.DisplayName,
		&i.OwnerPrincipalID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listModelProviders = `-- name: ListModelProviders :many
SELECT id, workspace_id, protocol, display_name, base_url, credential_env, credential_revision, enabled, created_at, updated_at FROM model_providers
WHERE workspace_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListModelProviders(ctx context.Context, workspaceID pgtype.UUID) ([]ModelProvider, error) {
	rows, err := q.db.Query(ctx, listModelProviders, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelProvider{}
	for rows.Next() {
		var i ModelProvider
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Protocol,
			&i.DisplayName,
			&i.BaseUrl,
			&i.CredentialEnv,
			&i.CredentialRevision,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelSettings = `-- name: ListModelSettings :many
SELECT id, workspace_id, provider_id, kind, model, enabled, is_default, capability, token_limit, embedding_dimension, created_at, updated_at FROM model_settings
WHERE workspace_id = $1
ORDER BY provider_id, created_at, id
`

func (q *Queries) ListModelSettings(ctx context.Context, workspaceID pgtype.UUID) ([]ModelSetting, error) {
	rows, err := q.db.Query(ctx, listModelSettings, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelSetting{}
	for rows.Next() {
		var i ModelSetting
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProviderID,
			&i.Kind,
			&i.Model,
			&i.Enabled,
			&i.IsDefault,
			&i.Capability,
			&i.TokenLimit,
			&i.EmbeddingDimension,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setModelSettingDefault = `-- name: SetModelSettingDefault :one
UPDATE model_settings
SET is_default = true, updated_at = $1
WHERE workspace_id = $2 AND id = $3
RETURNING id, workspace_id, provider_id, kind, model, enabled, is_default, capability, token_limit, embedding_dimension, created_at, updated_at
`

type SetModelSettingDefaultParams struct {
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	SettingID   pgtype.UUID        `json:"setting_id"`
}

func (q *Queries) SetModelSettingDefault(ctx context.Context, arg SetModelSettingDefaultParams) (ModelSetting, error) {
	row := q.db.QueryRow(ctx, setModelSettingDefault, arg.UpdatedAt, arg.WorkspaceID, arg.SettingID)
	var i ModelSetting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderID,
		&i.Kind,
		&i.Model,
		&i.Enabled,
		&i.IsDefault,
		&i.Capability,
		&i.TokenLimit,
		&i.EmbeddingDimension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModelProvider = `-- name: UpdateModelProvider :one
UPDATE model_providers
SET display_name = $1, base_url = $2,
    credential_env = $3,
    credential_revision = $4,
    enabled = $5, updated_at = $6
WHERE workspace_id = $7 AND id = $8
RETURNING id, workspace_id, protocol, display_name, base_url, credential_env, credential_revision, enabled, created_at, updated_at
`

type UpdateModelProviderParams struct {
	DisplayName        string             `json:"display_name"`
	BaseUrl            pgtype.Text        `json:"base_url"`
	CredentialEnv      string             `json:"credential_env"`
	CredentialRevision string             `json:"credential_revision"`
	Enabled            bool               `json:"enabled"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	ProviderID         pgtype.UUID        `json:"provider_id"`
}

func (q *Queries) UpdateModelProvider(ctx context.Context, arg UpdateModelProviderParams) (ModelProvider, error) {
	row := q.db.QueryRow(ctx, updateModelProvider,
		arg.DisplayName,
		arg.BaseUrl,
		arg.CredentialEnv,
		arg.CredentialRevision,
		arg.Enabled,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ProviderID,
	)
	var i ModelProvider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Protocol,
		&i.DisplayName,
		&i.BaseUrl,
		&i.CredentialEnv,
		&i.CredentialRevision,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModelSetting = `-- name: UpdateModelSetting :one
UPDATE model_settings
SET model = $1, enabled = $2,
    capability = $3, token_limit = $4,
    embedding_dimension = $5, updated_at = $6
WHERE workspace_id = $7 AND id = $8
RETURNING id, workspace_id, provider_id, kind, model, enabled, is_default, capability, token_limit, embedding_dimension, created_at, updated_at
`

type UpdateModelSettingParams struct {
	Model              string             `json:"model"`
	Enabled            bool               `json:"enabled"`
	Capability         string             `json:"capability"`
	TokenLimit         int32              `json:"token_limit"`
	EmbeddingDimension pgtype.Int4        `json:"embedding_dimension"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	SettingID          pgtype.UUID        `json:"setting_id"`
}

func (q *Queries) UpdateModelSetting(ctx context.Context, arg UpdateModelSettingParams) (ModelSetting, error) {
	row := q.db.QueryRow(ctx, updateModelSetting,
		arg.Model,
		arg.Enabled,
		arg.Capability,
		arg.TokenLimit,
		arg.EmbeddingDimension,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.SettingID,
	)
	var i ModelSetting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderID,
		&i.Kind,
		&i.Model,
		&i.Enabled,
		&i.IsDefault,
		&i.Capability,
		&i.TokenLimit,
		&i.EmbeddingDimension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
