// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendRuntimeRunEvent = `-- name: AppendRuntimeRunEvent :exec
WITH locked_run AS (
    SELECT id FROM runtime_runs
    WHERE workspace_id = $2 AND id = $3
    FOR UPDATE
), next_sequence AS (
    SELECT COALESCE(MAX(sequence), 0) + 1 AS value
    FROM runtime_run_events
    WHERE workspace_id = $2 AND runtime_run_id = $3
)
INSERT INTO runtime_run_events (
    id, workspace_id, runtime_run_id, event_key, sequence, event_type, phase,
    progress_current, progress_total, state, error_code, summary, metadata, created_at
)
SELECT $1, $2, $3, $4,
    next_sequence.value, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13
FROM locked_run, next_sequence
ON CONFLICT (workspace_id, runtime_run_id, event_key) DO NOTHING
`

type AppendRuntimeRunEventParams struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	RuntimeRunID    pgtype.UUID        `json:"runtime_run_id"`
	EventKey        string             `json:"event_key"`
	EventType       string             `json:"event_type"`
	Phase           pgtype.Text        `json:"phase"`
	ProgressCurrent pgtype.Int8        `json:"progress_current"`
	ProgressTotal   pgtype.Int8        `json:"progress_total"`
	State           pgtype.Text        `json:"state"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	Summary         pgtype.Text        `json:"summary"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AppendRuntimeRunEvent(ctx context.Context, arg AppendRuntimeRunEventParams) error {
	_, err := q.db.Exec(ctx, appendRuntimeRunEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.RuntimeRunID,
		arg.EventKey,
		arg.EventType,
		arg.Phase,
		arg.ProgressCurrent,
		arg.ProgressTotal,
		arg.State,
		arg.ErrorCode,
		arg.Summary,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const createAuditExport = `-- name: CreateAuditExport :one
INSERT INTO audit_exports (
    id, workspace_id, runtime_run_id, artifact_id, format, filters, row_count,
    content_digest, request_fingerprint, idempotency_key, created_by_principal_id, content, created_at, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14
)
RETURNING id, workspace_id, runtime_run_id, artifact_id, format, filters, row_count, content_digest, request_fingerprint, idempotency_key, created_by_principal_id, content, created_at, expires_at
`

type CreateAuditExportParams struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	RuntimeRunID         pgtype.UUID        `json:"runtime_run_id"`
	ArtifactID           string             `json:"artifact_id"`
	Format               string             `json:"format"`
	Filters              []byte             `json:"filters"`
	RowCount             int32              `json:"row_count"`
	ContentDigest        string             `json:"content_digest"`
	RequestFingerprint   string             `json:"request_fingerprint"`
	IdempotencyKey       string             `json:"idempotency_key"`
	CreatedByPrincipalID pgtype.UUID        `json:"created_by_principal_id"`
	Content              []byte             `json:"content"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuditExport(ctx context.Context, arg CreateAuditExportParams) (AuditExport, error) {
	row := q.db.QueryRow(ctx, createAuditExport,
		arg.ID,
		arg.WorkspaceID,
		arg.RuntimeRunID,
		arg.ArtifactID,
		arg.Format,
		arg.Filters,
		arg.RowCount,
		arg.ContentDigest,
		arg.RequestFingerprint,
		arg.IdempotencyKey,
		arg.CreatedByPrincipalID,
		arg.Content,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i AuditExport
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeRunID,
		&i.ArtifactID,
		&i.Format,
		&i.Filters,
		&i.RowCount,
		&i.ContentDigest,
		&i.RequestFingerprint,
		&i.IdempotencyKey,
		&i.CreatedByPrincipalID,
		&i.Content,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const ensureRuntimeSettings = `-- name: EnsureRuntimeSettings :one
INSERT INTO runtime_settings (workspace_id, created_at, updated_at)
VALUES ($1, $2, $2)
ON CONFLICT (workspace_id) DO UPDATE SET workspace_id = EXCLUDED.workspace_id
RETURNING workspace_id, retry_ceiling, statement_timeout_ms, webhook_timeout_ms, query_row_limit, query_byte_limit, run_metadata_retention_days, version, created_at, updated_at
`

type EnsureRuntimeSettingsParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Now         pgtype.Timestamptz `json:"now"`
}

func (q *Queries) EnsureRuntimeSettings(ctx context.Context, arg EnsureRuntimeSettingsParams) (RuntimeSetting, error) {
	row := q.db.QueryRow(ctx, ensureRuntimeSettings, arg.WorkspaceID, arg.Now)
	var i RuntimeSetting
	err := row.Scan(
		&i.WorkspaceID,
		&i.RetryCeiling,
		&i.StatementTimeoutMs,
		&i.WebhookTimeoutMs,
		&i.QueryRowLimit,
		&i.QueryByteLimit,
		&i.RunMetadataRetentionDays,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuditExportByIdempotency = `-- name: GetAuditExportByIdempotency :one
SELECT id, workspace_id, runtime_run_id, artifact_id, format, filters, row_count, content_digest, request_fingerprint, idempotency_key, created_by_principal_id, content, created_at, expires_at FROM audit_exports
WHERE workspace_id = $1 AND idempotency_key = $2
`

type GetAuditExportByIdempotencyParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetAuditExportByIdempotency(ctx context.Context, arg GetAuditExportByIdempotencyParams) (AuditExport, error) {
	row := q.db.QueryRow(ctx, getAuditExportByIdempotency, arg.WorkspaceID, arg.IdempotencyKey)
	var i AuditExport
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuntimeRunID,
		&i.ArtifactID,
		&i.Format,
		&i.Filters,
		&i.RowCount,
		&i.ContentDigest,
		&i.RequestFingerprint,
		&i.IdempotencyKey,
		&i.CreatedByPrincipalID,
		&i.Content,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAuditExportContent = `-- name: GetAuditExportContent :one
SELECT id, content, content_digest, format, expires_at
FROM audit_exports
WHERE workspace_id = $1 AND id = $2
  AND expires_at > $3
`

type GetAuditExportContentParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	Now         pgtype.Timestamptz `json:"now"`
}

type GetAuditExportContentRow struct {
	ID            pgtype.UUID        `json:"id"`
	Content       []byte             `json:"content"`
	ContentDigest string             `json:"content_digest"`
	Format        string             `json:"format"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetAuditExportContent(ctx context.Context, arg GetAuditExportContentParams) (GetAuditExportContentRow, error) {
	row := q.db.QueryRow(ctx, getAuditExportContent, arg.WorkspaceID, arg.ID, arg.Now)
	var i GetAuditExportContentRow
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.ContentDigest,
		&i.Format,
		&i.ExpiresAt,
	)
	return i, err
}

const getOperationsRuntimeRun = `-- name: GetOperationsRuntimeRun :one
SELECT id, workspace_id, kind, source_type, source_id, source_version_digest, job_id, trace_id, idempotency_key, requested_by_principal_id, state, phase, progress_current, progress_total, attempt, max_attempts, started_at, finished_at, error_code, error_summary, version, created_at, updated_at FROM runtime_runs
WHERE workspace_id = $1 AND id = $2
`

type GetOperationsRuntimeRunParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetOperationsRuntimeRun(ctx context.Context, arg GetOperationsRuntimeRunParams) (RuntimeRun, error) {
	row := q.db.QueryRow(ctx, getOperationsRuntimeRun, arg.WorkspaceID, arg.ID)
	var i RuntimeRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.SourceType,
		&i.SourceID,
		&i.SourceVersionDigest,
		&i.JobID,
		&i.TraceID,
		&i.IdempotencyKey,
		&i.RequestedByPrincipalID,
		&i.State,
		&i.Phase,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.Attempt,
		&i.MaxAttempts,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationsRuntimeRunByJob = `-- name: GetOperationsRuntimeRunByJob :one
SELECT id, workspace_id, kind, source_type, source_id, source_version_digest, job_id, trace_id, idempotency_key, requested_by_principal_id, state, phase, progress_current, progress_total, attempt, max_attempts, started_at, finished_at, error_code, error_summary, version, created_at, updated_at FROM runtime_runs
WHERE workspace_id = $1 AND job_id = $2
FOR UPDATE
`

type GetOperationsRuntimeRunByJobParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	JobID       pgtype.UUID `json:"job_id"`
}

func (q *Queries) GetOperationsRuntimeRunByJob(ctx context.Context, arg GetOperationsRuntimeRunByJobParams) (RuntimeRun, error) {
	row := q.db.QueryRow(ctx, getOperationsRuntimeRunByJob, arg.WorkspaceID, arg.JobID)
	var i RuntimeRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.SourceType,
		&i.SourceID,
		&i.SourceVersionDigest,
		&i.JobID,
		&i.TraceID,
		&i.IdempotencyKey,
		&i.RequestedByPrincipalID,
		&i.State,
		&i.Phase,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.Attempt,
		&i.MaxAttempts,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationsRuntimeRunBySource = `-- name: GetOperationsRuntimeRunBySource :one
SELECT id, workspace_id, kind, source_type, source_id, source_version_digest, job_id, trace_id, idempotency_key, requested_by_principal_id, state, phase, progress_current, progress_total, attempt, max_attempts, started_at, finished_at, error_code, error_summary, version, created_at, updated_at FROM runtime_runs
WHERE workspace_id = $1 AND kind = $2
  AND source_type = $3 AND source_id = $4
FOR UPDATE
`

type GetOperationsRuntimeRunBySourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Kind        string      `json:"kind"`
	SourceType  string      `json:"source_type"`
	SourceID    string      `json:"source_id"`
}

func (q *Queries) GetOperationsRuntimeRunBySource(ctx context.Context, arg GetOperationsRuntimeRunBySourceParams) (RuntimeRun, error) {
	row := q.db.QueryRow(ctx, getOperationsRuntimeRunBySource,
		arg.WorkspaceID,
		arg.Kind,
		arg.SourceType,
		arg.SourceID,
	)
	var i RuntimeRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.SourceType,
		&i.SourceID,
		&i.SourceVersionDigest,
		&i.JobID,
		&i.TraceID,
		&i.IdempotencyKey,
		&i.RequestedByPrincipalID,
		&i.State,
		&i.Phase,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.Attempt,
		&i.MaxAttempts,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOperationsRuntimeRunEvents = `-- name: ListOperationsRuntimeRunEvents :many
SELECT id, workspace_id, runtime_run_id, event_key, sequence, event_type, phase, progress_current, progress_total, state, error_code, summary, metadata, created_at FROM runtime_run_events
WHERE workspace_id = $1 AND runtime_run_id = $2
ORDER BY sequence
LIMIT $3
`

type ListOperationsRuntimeRunEventsParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	RuntimeRunID pgtype.UUID `json:"runtime_run_id"`
	PageLimit    int32       `json:"page_limit"`
}

func (q *Queries) ListOperationsRuntimeRunEvents(ctx context.Context, arg ListOperationsRuntimeRunEventsParams) ([]RuntimeRunEvent, error) {
	rows, err := q.db.Query(ctx, listOperationsRuntimeRunEvents, arg.WorkspaceID, arg.RuntimeRunID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeRunEvent{}
	for rows.Next() {
		var i RuntimeRunEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RuntimeRunID,
			&i.EventKey,
			&i.Sequence,
			&i.EventType,
			&i.Phase,
			&i.ProgressCurrent,
			&i.ProgressTotal,
			&i.State,
			&i.ErrorCode,
			&i.Summary,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationsRuntimeRuns = `-- name: ListOperationsRuntimeRuns :many
SELECT id, workspace_id, kind, source_type, source_id, source_version_digest, job_id, trace_id, idempotency_key, requested_by_principal_id, state, phase, progress_current, progress_total, attempt, max_attempts, started_at, finished_at, error_code, error_summary, version, created_at, updated_at FROM runtime_runs
WHERE workspace_id = $1
  AND (NOT $2::boolean OR kind = $3)
  AND (NOT $4::boolean OR state = $5)
  AND (NOT $6::boolean OR source_type = $7)
  AND (NOT $8::boolean OR source_id = $9)
  AND (NOT $10::boolean OR trace_id = $11)
  AND (
      NOT $12::boolean
      OR updated_at < $13
      OR (updated_at = $13 AND id < $14::uuid)
  )
ORDER BY updated_at DESC, id DESC
LIMIT $15
`

type ListOperationsRuntimeRunsParams struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	HasKind       bool               `json:"has_kind"`
	Kind          string             `json:"kind"`
	HasState      bool               `json:"has_state"`
	State         string             `json:"state"`
	HasSourceType bool               `json:"has_source_type"`
	SourceType    string             `json:"source_type"`
	HasSourceID   bool               `json:"has_source_id"`
	SourceID      string             `json:"source_id"`
	HasTrace      bool               `json:"has_trace"`
	TraceID       pgtype.Text        `json:"trace_id"`
	HasCursor     bool               `json:"has_cursor"`
	CursorTime    pgtype.Timestamptz `json:"cursor_time"`
	CursorID      pgtype.UUID        `json:"cursor_id"`
	PageLimit     int32              `json:"page_limit"`
}

func (q *Queries) ListOperationsRuntimeRuns(ctx context.Context, arg ListOperationsRuntimeRunsParams) ([]RuntimeRun, error) {
	rows, err := q.db.Query(ctx, listOperationsRuntimeRuns,
		arg.WorkspaceID,
		arg.HasKind,
		arg.Kind,
		arg.HasState,
		arg.State,
		arg.HasSourceType,
		arg.SourceType,
		arg.HasSourceID,
		arg.SourceID,
		arg.HasTrace,
		arg.TraceID,
		arg.HasCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeRun{}
	for rows.Next() {
		var i RuntimeRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.SourceType,
			&i.SourceID,
			&i.SourceVersionDigest,
			&i.JobID,
			&i.TraceID,
			&i.IdempotencyKey,
			&i.RequestedByPrincipalID,
			&i.State,
			&i.Phase,
			&i.ProgressCurrent,
			&i.ProgressTotal,
			&i.Attempt,
			&i.MaxAttempts,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorCode,
			&i.ErrorSummary,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuntimeSettings = `-- name: UpdateRuntimeSettings :one
UPDATE runtime_settings
SET retry_ceiling = $1,
    statement_timeout_ms = $2,
    webhook_timeout_ms = $3,
    query_row_limit = $4,
    query_byte_limit = $5,
    run_metadata_retention_days = $6,
    version = version + 1,
    updated_at = $7
WHERE workspace_id = $8 AND version = $9
RETURNING workspace_id, retry_ceiling, statement_timeout_ms, webhook_timeout_ms, query_row_limit, query_byte_limit, run_metadata_retention_days, version, created_at, updated_at
`

type UpdateRuntimeSettingsParams struct {
	RetryCeiling             int32              `json:"retry_ceiling"`
	StatementTimeoutMs       int32              `json:"statement_timeout_ms"`
	WebhookTimeoutMs         int32              `json:"webhook_timeout_ms"`
	QueryRowLimit            int32              `json:"query_row_limit"`
	QueryByteLimit           int64              `json:"query_byte_limit"`
	RunMetadataRetentionDays int32              `json:"run_metadata_retention_days"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID              pgtype.UUID        `json:"workspace_id"`
	ExpectedVersion          int64              `json:"expected_version"`
}

func (q *Queries) UpdateRuntimeSettings(ctx context.Context, arg UpdateRuntimeSettingsParams) (RuntimeSetting, error) {
	row := q.db.QueryRow(ctx, updateRuntimeSettings,
		arg.RetryCeiling,
		arg.StatementTimeoutMs,
		arg.WebhookTimeoutMs,
		arg.QueryRowLimit,
		arg.QueryByteLimit,
		arg.RunMetadataRetentionDays,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ExpectedVersion,
	)
	var i RuntimeSetting
	err := row.Scan(
		&i.WorkspaceID,
		&i.RetryCeiling,
		&i.StatementTimeoutMs,
		&i.WebhookTimeoutMs,
		&i.QueryRowLimit,
		&i.QueryByteLimit,
		&i.RunMetadataRetentionDays,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRuntimeRun = `-- name: UpsertRuntimeRun :one
INSERT INTO runtime_runs (
    id, workspace_id, kind, source_type, source_id, source_version_digest, job_id,
    trace_id, idempotency_key, requested_by_principal_id, state, phase,
    progress_current, progress_total, attempt, max_attempts, started_at, finished_at,
    error_code, error_summary, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21,
    $22, $23
)
ON CONFLICT (workspace_id, kind, source_type, source_id) DO UPDATE
SET source_version_digest = EXCLUDED.source_version_digest,
    job_id = COALESCE(EXCLUDED.job_id, runtime_runs.job_id),
    trace_id = COALESCE(EXCLUDED.trace_id, runtime_runs.trace_id),
    requested_by_principal_id = COALESCE(EXCLUDED.requested_by_principal_id, runtime_runs.requested_by_principal_id),
    state = EXCLUDED.state,
    phase = EXCLUDED.phase,
    progress_current = EXCLUDED.progress_current,
    progress_total = EXCLUDED.progress_total,
    attempt = GREATEST(runtime_runs.attempt, EXCLUDED.attempt),
    max_attempts = GREATEST(runtime_runs.max_attempts, EXCLUDED.max_attempts),
    started_at = COALESCE(runtime_runs.started_at, EXCLUDED.started_at),
    finished_at = EXCLUDED.finished_at,
    error_code = EXCLUDED.error_code,
    error_summary = EXCLUDED.error_summary,
    version = CASE WHEN ROW(
        runtime_runs.source_version_digest, runtime_runs.job_id, runtime_runs.trace_id,
        runtime_runs.requested_by_principal_id, runtime_runs.state, runtime_runs.phase,
        runtime_runs.progress_current, runtime_runs.progress_total, runtime_runs.attempt,
        runtime_runs.max_attempts, runtime_runs.started_at, runtime_runs.finished_at,
        runtime_runs.error_code, runtime_runs.error_summary
    ) IS NOT DISTINCT FROM ROW(
        EXCLUDED.source_version_digest, EXCLUDED.job_id, EXCLUDED.trace_id,
        EXCLUDED.requested_by_principal_id, EXCLUDED.state, EXCLUDED.phase,
        EXCLUDED.progress_current, EXCLUDED.progress_total, EXCLUDED.attempt,
        EXCLUDED.max_attempts, EXCLUDED.started_at, EXCLUDED.finished_at,
        EXCLUDED.error_code, EXCLUDED.error_summary
    ) THEN runtime_runs.version ELSE runtime_runs.version + 1 END,
    updated_at = CASE WHEN ROW(
        runtime_runs.source_version_digest, runtime_runs.job_id, runtime_runs.trace_id,
        runtime_runs.requested_by_principal_id, runtime_runs.state, runtime_runs.phase,
        runtime_runs.progress_current, runtime_runs.progress_total, runtime_runs.attempt,
        runtime_runs.max_attempts, runtime_runs.started_at, runtime_runs.finished_at,
        runtime_runs.error_code, runtime_runs.error_summary
    ) IS NOT DISTINCT FROM ROW(
        EXCLUDED.source_version_digest, EXCLUDED.job_id, EXCLUDED.trace_id,
        EXCLUDED.requested_by_principal_id, EXCLUDED.state, EXCLUDED.phase,
        EXCLUDED.progress_current, EXCLUDED.progress_total, EXCLUDED.attempt,
        EXCLUDED.max_attempts, EXCLUDED.started_at, EXCLUDED.finished_at,
        EXCLUDED.error_code, EXCLUDED.error_summary
    ) THEN runtime_runs.updated_at ELSE EXCLUDED.updated_at END
RETURNING id, workspace_id, kind, source_type, source_id, source_version_digest, job_id, trace_id, idempotency_key, requested_by_principal_id, state, phase, progress_current, progress_total, attempt, max_attempts, started_at, finished_at, error_code, error_summary, version, created_at, updated_at
`

type UpsertRuntimeRunParams struct {
	ID                     pgtype.UUID        `json:"id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	Kind                   string             `json:"kind"`
	SourceType             string             `json:"source_type"`
	SourceID               string             `json:"source_id"`
	SourceVersionDigest    string             `json:"source_version_digest"`
	JobID                  pgtype.UUID        `json:"job_id"`
	TraceID                pgtype.Text        `json:"trace_id"`
	IdempotencyKey         string             `json:"idempotency_key"`
	RequestedByPrincipalID pgtype.UUID        `json:"requested_by_principal_id"`
	State                  string             `json:"state"`
	Phase                  pgtype.Text        `json:"phase"`
	ProgressCurrent        pgtype.Int8        `json:"progress_current"`
	ProgressTotal          pgtype.Int8        `json:"progress_total"`
	Attempt                int32              `json:"attempt"`
	MaxAttempts            int32              `json:"max_attempts"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	FinishedAt             pgtype.Timestamptz `json:"finished_at"`
	ErrorCode              pgtype.Text        `json:"error_code"`
	ErrorSummary           pgtype.Text        `json:"error_summary"`
	Version                int64              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertRuntimeRun(ctx context.Context, arg UpsertRuntimeRunParams) (RuntimeRun, error) {
	row := q.db.QueryRow(ctx, upsertRuntimeRun,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.SourceType,
		arg.SourceID,
		arg.SourceVersionDigest,
		arg.JobID,
		arg.TraceID,
		arg.IdempotencyKey,
		arg.RequestedByPrincipalID,
		arg.State,
		arg.Phase,
		arg.ProgressCurrent,
		arg.ProgressTotal,
		arg.Attempt,
		arg.MaxAttempts,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ErrorCode,
		arg.ErrorSummary,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RuntimeRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.SourceType,
		&i.SourceID,
		&i.SourceVersionDigest,
		&i.JobID,
		&i.TraceID,
		&i.IdempotencyKey,
		&i.RequestedByPrincipalID,
		&i.State,
		&i.Phase,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.Attempt,
		&i.MaxAttempts,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
