// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEvent = `-- name: ClaimOutboxEvent :one
WITH candidate AS (
    SELECT id
    FROM outbox_events
    WHERE status IN ('queued', 'retryable')
      AND available_at <= $3
    ORDER BY available_at, created_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE outbox_events
SET status = 'publishing',
    attempt = attempt + 1,
    leased_until = $1,
    lease_owner = $2,
    last_error_code = NULL,
    updated_at = $3
FROM candidate
WHERE outbox_events.id = candidate.id
RETURNING outbox_events.id, outbox_events.workspace_id, outbox_events.event_type, outbox_events.payload, outbox_events.status, outbox_events.attempt, outbox_events.max_attempts, outbox_events.available_at, outbox_events.leased_until, outbox_events.lease_owner, outbox_events.last_error_code, outbox_events.trace_id, outbox_events.created_at, outbox_events.updated_at, outbox_events.published_at
`

type ClaimOutboxEventParams struct {
	LeasedUntil pgtype.Timestamptz `json:"leased_until"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
}

func (q *Queries) ClaimOutboxEvent(ctx context.Context, arg ClaimOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, claimOutboxEvent, arg.LeasedUntil, arg.LeaseOwner, arg.ClaimedAt)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LeasedUntil,
		&i.LeaseOwner,
		&i.LastErrorCode,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :exec
INSERT INTO outbox_events (
    id, workspace_id, event_type, payload, max_attempts, available_at, trace_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
`

type EnqueueOutboxEventParams struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	MaxAttempts int32              `json:"max_attempts"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	TraceID     string             `json:"trace_id"`
}

func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) error {
	_, err := q.db.Exec(ctx, enqueueOutboxEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.EventType,
		arg.Payload,
		arg.MaxAttempts,
		arg.AvailableAt,
		arg.TraceID,
	)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :execrows
UPDATE outbox_events
SET status = CASE WHEN attempt >= max_attempts THEN 'dead_letter' ELSE 'retryable' END,
    available_at = $1,
    leased_until = NULL,
    lease_owner = NULL,
    last_error_code = $2,
    updated_at = $3
WHERE id = $4
  AND status = 'publishing'
  AND lease_owner = $5
`

type MarkOutboxEventFailedParams struct {
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	ErrorCode   pgtype.Text        `json:"error_code"`
	FailedAt    pgtype.Timestamptz `json:"failed_at"`
	ID          string             `json:"id"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventFailed,
		arg.AvailableAt,
		arg.ErrorCode,
		arg.FailedAt,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :execrows
UPDATE outbox_events
SET status = 'published',
    leased_until = NULL,
    lease_owner = NULL,
    last_error_code = NULL,
    updated_at = $1,
    published_at = $1
WHERE id = $2
  AND status = 'publishing'
  AND lease_owner = $3
`

type MarkOutboxEventPublishedParams struct {
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ID          string             `json:"id"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
}

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, arg MarkOutboxEventPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventPublished, arg.PublishedAt, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reapExpiredOutboxEvents = `-- name: ReapExpiredOutboxEvents :execrows
UPDATE outbox_events
SET status = CASE WHEN attempt >= max_attempts THEN 'dead_letter' ELSE 'retryable' END,
    available_at = $1,
    leased_until = NULL,
    lease_owner = NULL,
    last_error_code = 'LEASE_EXPIRED',
    updated_at = $1
WHERE status = 'publishing'
  AND leased_until <= $1
`

func (q *Queries) ReapExpiredOutboxEvents(ctx context.Context, expiredAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredOutboxEvents, expiredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
