// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOntologyRelation = `-- name: AddOntologyRelation :exec
INSERT INTO ontology_revision_relations (
    workspace_id, ontology_revision_id, semantic_relation_id
) VALUES (
    $1, $2, $3
)
`

type AddOntologyRelationParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	OntologyRevisionID pgtype.UUID `json:"ontology_revision_id"`
	SemanticRelationID pgtype.UUID `json:"semantic_relation_id"`
}

func (q *Queries) AddOntologyRelation(ctx context.Context, arg AddOntologyRelationParams) error {
	_, err := q.db.Exec(ctx, addOntologyRelation, arg.WorkspaceID, arg.OntologyRevisionID, arg.SemanticRelationID)
	return err
}

const createAssetRevision = `-- name: CreateAssetRevision :one
INSERT INTO asset_revisions (
    id, workspace_id, asset_id, sequence, schema_version, content_digest, content, created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, workspace_id, asset_id, sequence, schema_version, content_digest, content, created_by, created_at
`

type CreateAssetRevisionParams struct {
	ID            pgtype.UUID `json:"id"`
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	AssetID       pgtype.UUID `json:"asset_id"`
	Sequence      int64       `json:"sequence"`
	SchemaVersion string      `json:"schema_version"`
	ContentDigest string      `json:"content_digest"`
	Content       []byte      `json:"content"`
	CreatedBy     string      `json:"created_by"`
}

func (q *Queries) CreateAssetRevision(ctx context.Context, arg CreateAssetRevisionParams) (AssetRevision, error) {
	row := q.db.QueryRow(ctx, createAssetRevision,
		arg.ID,
		arg.WorkspaceID,
		arg.AssetID,
		arg.Sequence,
		arg.SchemaVersion,
		arg.ContentDigest,
		arg.Content,
		arg.CreatedBy,
	)
	var i AssetRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AssetID,
		&i.Sequence,
		&i.SchemaVersion,
		&i.ContentDigest,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createEvidenceArtifact = `-- name: CreateEvidenceArtifact :one
WITH inserted AS (
INSERT INTO evidence_artifacts (
    id, workspace_id, evidence_type, source_revision_id, locator, content_digest, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (workspace_id, evidence_type, locator, content_digest) DO NOTHING
RETURNING id, workspace_id, evidence_type, source_revision_id, locator, content_digest, metadata, created_at
)
SELECT id, workspace_id, evidence_type, source_revision_id, locator, content_digest, metadata, created_at FROM inserted
UNION ALL
SELECT id, workspace_id, evidence_type, source_revision_id, locator, content_digest, metadata, created_at FROM evidence_artifacts
WHERE workspace_id = $2
  AND evidence_type = $3
  AND locator = $5
  AND content_digest = $6
LIMIT 1
`

type CreateEvidenceArtifactParams struct {
	ID               pgtype.UUID `json:"id"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	EvidenceType     string      `json:"evidence_type"`
	SourceRevisionID pgtype.UUID `json:"source_revision_id"`
	Locator          string      `json:"locator"`
	ContentDigest    string      `json:"content_digest"`
	Metadata         []byte      `json:"metadata"`
}

type CreateEvidenceArtifactRow struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	EvidenceType     string             `json:"evidence_type"`
	SourceRevisionID pgtype.UUID        `json:"source_revision_id"`
	Locator          string             `json:"locator"`
	ContentDigest    string             `json:"content_digest"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateEvidenceArtifact(ctx context.Context, arg CreateEvidenceArtifactParams) (CreateEvidenceArtifactRow, error) {
	row := q.db.QueryRow(ctx, createEvidenceArtifact,
		arg.ID,
		arg.WorkspaceID,
		arg.EvidenceType,
		arg.SourceRevisionID,
		arg.Locator,
		arg.ContentDigest,
		arg.Metadata,
	)
	var i CreateEvidenceArtifactRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EvidenceType,
		&i.SourceRevisionID,
		&i.Locator,
		&i.ContentDigest,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createOntologyRevision = `-- name: CreateOntologyRevision :one
INSERT INTO ontology_revisions (
    id, workspace_id, sequence, status, content_digest, created_by, published_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, workspace_id, sequence, status, content_digest, created_by, created_at, published_at
`

type CreateOntologyRevisionParams struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	Sequence      int64              `json:"sequence"`
	Status        string             `json:"status"`
	ContentDigest string             `json:"content_digest"`
	CreatedBy     string             `json:"created_by"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateOntologyRevision(ctx context.Context, arg CreateOntologyRevisionParams) (OntologyRevision, error) {
	row := q.db.QueryRow(ctx, createOntologyRevision,
		arg.ID,
		arg.WorkspaceID,
		arg.Sequence,
		arg.Status,
		arg.ContentDigest,
		arg.CreatedBy,
		arg.PublishedAt,
	)
	var i OntologyRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Sequence,
		&i.Status,
		&i.ContentDigest,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const createSemanticAsset = `-- name: CreateSemanticAsset :one
INSERT INTO semantic_assets (
    id, workspace_id, namespace, key, asset_type, lifecycle_state
) VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, workspace_id, namespace, key, asset_type, lifecycle_state, current_revision_id, created_at, updated_at
`

type CreateSemanticAssetParams struct {
	ID             pgtype.UUID `json:"id"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	Namespace      string      `json:"namespace"`
	Key            string      `json:"key"`
	AssetType      string      `json:"asset_type"`
	LifecycleState string      `json:"lifecycle_state"`
}

func (q *Queries) CreateSemanticAsset(ctx context.Context, arg CreateSemanticAssetParams) (SemanticAsset, error) {
	row := q.db.QueryRow(ctx, createSemanticAsset,
		arg.ID,
		arg.WorkspaceID,
		arg.Namespace,
		arg.Key,
		arg.AssetType,
		arg.LifecycleState,
	)
	var i SemanticAsset
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Namespace,
		&i.Key,
		&i.AssetType,
		&i.LifecycleState,
		&i.CurrentRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSemanticRelation = `-- name: CreateSemanticRelation :one
INSERT INTO semantic_relations (
    id, workspace_id, subject_asset_id, predicate, object_asset_id, plane, assertion_state,
    source_revision_id, evidence_artifact_id, inference_rule, created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11
)
RETURNING id, workspace_id, subject_asset_id, predicate, object_asset_id, plane, assertion_state, source_revision_id, evidence_artifact_id, inference_rule, created_by, created_at
`

type CreateSemanticRelationParams struct {
	ID                 pgtype.UUID `json:"id"`
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	SubjectAssetID     pgtype.UUID `json:"subject_asset_id"`
	Predicate          string      `json:"predicate"`
	ObjectAssetID      pgtype.UUID `json:"object_asset_id"`
	Plane              string      `json:"plane"`
	AssertionState     string      `json:"assertion_state"`
	SourceRevisionID   pgtype.UUID `json:"source_revision_id"`
	EvidenceArtifactID pgtype.UUID `json:"evidence_artifact_id"`
	InferenceRule      pgtype.Text `json:"inference_rule"`
	CreatedBy          string      `json:"created_by"`
}

func (q *Queries) CreateSemanticRelation(ctx context.Context, arg CreateSemanticRelationParams) (SemanticRelation, error) {
	row := q.db.QueryRow(ctx, createSemanticRelation,
		arg.ID,
		arg.WorkspaceID,
		arg.SubjectAssetID,
		arg.Predicate,
		arg.ObjectAssetID,
		arg.Plane,
		arg.AssertionState,
		arg.SourceRevisionID,
		arg.EvidenceArtifactID,
		arg.InferenceRule,
		arg.CreatedBy,
	)
	var i SemanticRelation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubjectAssetID,
		&i.Predicate,
		&i.ObjectAssetID,
		&i.Plane,
		&i.AssertionState,
		&i.SourceRevisionID,
		&i.EvidenceArtifactID,
		&i.InferenceRule,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSourceConnection = `-- name: CreateSourceConnection :one
INSERT INTO source_connections (
    id, workspace_id, adapter_kind, name, normalized_locator, credential_ref, status, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, workspace_id, adapter_kind, name, normalized_locator, credential_ref, status, metadata, created_at, updated_at, active_credential_version, artifact_paths, disabled_at, source_kind, active_artifact_set_id, version
`

type CreateSourceConnectionParams struct {
	ID                pgtype.UUID `json:"id"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	AdapterKind       string      `json:"adapter_kind"`
	Name              string      `json:"name"`
	NormalizedLocator string      `json:"normalized_locator"`
	CredentialRef     pgtype.Text `json:"credential_ref"`
	Status            string      `json:"status"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateSourceConnection(ctx context.Context, arg CreateSourceConnectionParams) (SourceConnection, error) {
	row := q.db.QueryRow(ctx, createSourceConnection,
		arg.ID,
		arg.WorkspaceID,
		arg.AdapterKind,
		arg.Name,
		arg.NormalizedLocator,
		arg.CredentialRef,
		arg.Status,
		arg.Metadata,
	)
	var i SourceConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AdapterKind,
		&i.Name,
		&i.NormalizedLocator,
		&i.CredentialRef,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveCredentialVersion,
		&i.ArtifactPaths,
		&i.DisabledAt,
		&i.SourceKind,
		&i.ActiveArtifactSetID,
		&i.Version,
	)
	return i, err
}

const createSourceRevision = `-- name: CreateSourceRevision :one
WITH inserted AS (
INSERT INTO source_revisions (
    id, workspace_id, source_connection_id, external_revision, content_digest,
    adapter_version, observed_at, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
ON CONFLICT (source_connection_id, content_digest) DO NOTHING
RETURNING id, workspace_id, source_connection_id, external_revision, content_digest, adapter_version, observed_at, metadata, created_at
)
SELECT id, workspace_id, source_connection_id, external_revision, content_digest, adapter_version, observed_at, metadata, created_at FROM inserted
UNION ALL
SELECT id, workspace_id, source_connection_id, external_revision, content_digest, adapter_version, observed_at, metadata, created_at FROM source_revisions
WHERE source_connection_id = $3
  AND content_digest = $5
LIMIT 1
`

type CreateSourceRevisionParams struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	SourceConnectionID pgtype.UUID        `json:"source_connection_id"`
	ExternalRevision   pgtype.Text        `json:"external_revision"`
	ContentDigest      string             `json:"content_digest"`
	AdapterVersion     string             `json:"adapter_version"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
	Metadata           []byte             `json:"metadata"`
}

type CreateSourceRevisionRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	SourceConnectionID pgtype.UUID        `json:"source_connection_id"`
	ExternalRevision   pgtype.Text        `json:"external_revision"`
	ContentDigest      string             `json:"content_digest"`
	AdapterVersion     string             `json:"adapter_version"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSourceRevision(ctx context.Context, arg CreateSourceRevisionParams) (CreateSourceRevisionRow, error) {
	row := q.db.QueryRow(ctx, createSourceRevision,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceConnectionID,
		arg.ExternalRevision,
		arg.ContentDigest,
		arg.AdapterVersion,
		arg.ObservedAt,
		arg.Metadata,
	)
	var i CreateSourceRevisionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceConnectionID,
		&i.ExternalRevision,
		&i.ContentDigest,
		&i.AdapterVersion,
		&i.ObservedAt,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getEvidenceArtifactByIdentity = `-- name: GetEvidenceArtifactByIdentity :one
SELECT id, workspace_id, evidence_type, source_revision_id, locator, content_digest, metadata, created_at FROM evidence_artifacts
WHERE workspace_id = $1
  AND evidence_type = $2
  AND locator = $3
  AND content_digest = $4
`

type GetEvidenceArtifactByIdentityParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	EvidenceType  string      `json:"evidence_type"`
	Locator       string      `json:"locator"`
	ContentDigest string      `json:"content_digest"`
}

func (q *Queries) GetEvidenceArtifactByIdentity(ctx context.Context, arg GetEvidenceArtifactByIdentityParams) (EvidenceArtifact, error) {
	row := q.db.QueryRow(ctx, getEvidenceArtifactByIdentity,
		arg.WorkspaceID,
		arg.EvidenceType,
		arg.Locator,
		arg.ContentDigest,
	)
	var i EvidenceArtifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EvidenceType,
		&i.SourceRevisionID,
		&i.Locator,
		&i.ContentDigest,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceRevisionByDigest = `-- name: GetSourceRevisionByDigest :one
SELECT id, workspace_id, source_connection_id, external_revision, content_digest, adapter_version, observed_at, metadata, created_at FROM source_revisions
WHERE workspace_id = $1
  AND source_connection_id = $2
  AND content_digest = $3
`

type GetSourceRevisionByDigestParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	SourceConnectionID pgtype.UUID `json:"source_connection_id"`
	ContentDigest      string      `json:"content_digest"`
}

func (q *Queries) GetSourceRevisionByDigest(ctx context.Context, arg GetSourceRevisionByDigestParams) (SourceRevision, error) {
	row := q.db.QueryRow(ctx, getSourceRevisionByDigest, arg.WorkspaceID, arg.SourceConnectionID, arg.ContentDigest)
	var i SourceRevision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceConnectionID,
		&i.ExternalRevision,
		&i.ContentDigest,
		&i.AdapterVersion,
		&i.ObservedAt,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const publishOntologyRevision = `-- name: PublishOntologyRevision :execrows
UPDATE ontology_revisions
SET status = 'published', published_at = $1
WHERE workspace_id = $2
  AND id = $3
  AND status = 'draft'
`

type PublishOntologyRevisionParams struct {
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	OntologyRevisionID pgtype.UUID        `json:"ontology_revision_id"`
}

func (q *Queries) PublishOntologyRevision(ctx context.Context, arg PublishOntologyRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishOntologyRevision, arg.PublishedAt, arg.WorkspaceID, arg.OntologyRevisionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCurrentAssetRevision = `-- name: SetCurrentAssetRevision :execrows
UPDATE semantic_assets
SET current_revision_id = $1, updated_at = CURRENT_TIMESTAMP
WHERE workspace_id = $2 AND id = $3
`

type SetCurrentAssetRevisionParams struct {
	RevisionID  pgtype.UUID `json:"revision_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AssetID     pgtype.UUID `json:"asset_id"`
}

func (q *Queries) SetCurrentAssetRevision(ctx context.Context, arg SetCurrentAssetRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCurrentAssetRevision, arg.RevisionID, arg.WorkspaceID, arg.AssetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
