// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUsageEvent = `-- name: CreateUsageEvent :execrows
INSERT INTO usage_events (
    id, workspace_id, event_type, idempotency_key, data_version, actor_id,
    asset_id, revision_id, channel, outcome, reason_code, trace_id,
    search_fingerprint, search_language, token_bucket, result_bucket,
    asset_type_filter, lifecycle_filter, occurred_at, received_at, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18,
    $19, $20, $21
)
ON CONFLICT (workspace_id, event_type, idempotency_key) DO NOTHING
`

type CreateUsageEventParams struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	EventType         string             `json:"event_type"`
	IdempotencyKey    string             `json:"idempotency_key"`
	DataVersion       int16              `json:"data_version"`
	ActorID           pgtype.Text        `json:"actor_id"`
	AssetID           pgtype.UUID        `json:"asset_id"`
	RevisionID        pgtype.UUID        `json:"revision_id"`
	Channel           string             `json:"channel"`
	Outcome           string             `json:"outcome"`
	ReasonCode        pgtype.Text        `json:"reason_code"`
	TraceID           string             `json:"trace_id"`
	SearchFingerprint pgtype.Text        `json:"search_fingerprint"`
	SearchLanguage    pgtype.Text        `json:"search_language"`
	TokenBucket       pgtype.Text        `json:"token_bucket"`
	ResultBucket      pgtype.Text        `json:"result_bucket"`
	AssetTypeFilter   pgtype.Text        `json:"asset_type_filter"`
	LifecycleFilter   pgtype.Text        `json:"lifecycle_filter"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createUsageEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.EventType,
		arg.IdempotencyKey,
		arg.DataVersion,
		arg.ActorID,
		arg.AssetID,
		arg.RevisionID,
		arg.Channel,
		arg.Outcome,
		arg.ReasonCode,
		arg.TraceID,
		arg.SearchFingerprint,
		arg.SearchLanguage,
		arg.TokenBucket,
		arg.ResultBucket,
		arg.AssetTypeFilter,
		arg.LifecycleFilter,
		arg.OccurredAt,
		arg.ReceivedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredUsageEvents = `-- name: DeleteExpiredUsageEvents :execrows
WITH expired AS (
    SELECT id
    FROM usage_events
    WHERE usage_events.expires_at <= $1
    ORDER BY usage_events.expires_at, usage_events.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
DELETE FROM usage_events
USING expired
WHERE usage_events.id = expired.id
`

type DeleteExpiredUsageEventsParams struct {
	ExpiredAt   pgtype.Timestamptz `json:"expired_at"`
	DeleteLimit int32              `json:"delete_limit"`
}

func (q *Queries) DeleteExpiredUsageEvents(ctx context.Context, arg DeleteExpiredUsageEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUsageEvents, arg.ExpiredAt, arg.DeleteLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
