// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWebhookDelivery = `-- name: ClaimWebhookDelivery :one
WITH candidate AS (
 SELECT id FROM webhook_deliveries WHERE
 (state='queued' AND next_attempt_at<=$1) OR (state='running' AND leased_until<=$1)
 ORDER BY next_attempt_at,id FOR UPDATE SKIP LOCKED LIMIT 1
)
UPDATE webhook_deliveries d SET state='running',attempt=attempt+1,lease_owner=$2,leased_until=$1::timestamptz+interval '30 seconds',updated_at=$1
FROM candidate WHERE d.id=candidate.id RETURNING d.id, d.workspace_id, d.subscription_id, d.subscription_version, d.signing_version, d.event_id, d.event_type, d.envelope, d.payload_digest, d.state, d.attempt, d.max_attempts, d.http_status, d.error_code, d.next_attempt_at, d.lease_owner, d.leased_until, d.trace_id, d.created_at, d.updated_at, d.runtime_run_id
`

type ClaimWebhookDeliveryParams struct {
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	LeaseOwner pgtype.Text        `json:"lease_owner"`
}

func (q *Queries) ClaimWebhookDelivery(ctx context.Context, arg ClaimWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, claimWebhookDelivery, arg.UpdatedAt, arg.LeaseOwner)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubscriptionID,
		&i.SubscriptionVersion,
		&i.SigningVersion,
		&i.EventID,
		&i.EventType,
		&i.Envelope,
		&i.PayloadDigest,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.HttpStatus,
		&i.ErrorCode,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeasedUntil,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RuntimeRunID,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, workspace_id, subscription_id, subscription_version, signing_version, event_id, event_type, envelope, payload_digest, state, attempt, max_attempts, http_status, error_code, next_attempt_at, lease_owner, leased_until, trace_id, created_at, updated_at, runtime_run_id FROM webhook_deliveries WHERE workspace_id=$1 AND id=$2
`

type GetWebhookDeliveryParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetWebhookDelivery(ctx context.Context, arg GetWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, arg.WorkspaceID, arg.ID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubscriptionID,
		&i.SubscriptionVersion,
		&i.SigningVersion,
		&i.EventID,
		&i.EventType,
		&i.Envelope,
		&i.PayloadDigest,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.HttpStatus,
		&i.ErrorCode,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeasedUntil,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RuntimeRunID,
	)
	return i, err
}

const getWebhookSubscription = `-- name: GetWebhookSubscription :one
SELECT id, workspace_id, name, endpoint, enabled, event_types, version, signing_version, secret_suffix, created_by_principal_id, created_at, updated_at FROM webhook_subscriptions WHERE workspace_id=$1 AND id=$2
`

type GetWebhookSubscriptionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetWebhookSubscription(ctx context.Context, arg GetWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscription, arg.WorkspaceID, arg.ID)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Endpoint,
		&i.Enabled,
		&i.EventTypes,
		&i.Version,
		&i.SigningVersion,
		&i.SecretSuffix,
		&i.CreatedByPrincipalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, workspace_id, subscription_id, subscription_version, signing_version, event_id, event_type, envelope, payload_digest, state, attempt, max_attempts, http_status, error_code, next_attempt_at, lease_owner, leased_until, trace_id, created_at, updated_at, runtime_run_id FROM webhook_deliveries WHERE workspace_id=$1 ORDER BY created_at DESC,id DESC LIMIT 200
`

func (q *Queries) ListWebhookDeliveries(ctx context.Context, workspaceID pgtype.UUID) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubscriptionID,
			&i.SubscriptionVersion,
			&i.SigningVersion,
			&i.EventID,
			&i.EventType,
			&i.Envelope,
			&i.PayloadDigest,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.HttpStatus,
			&i.ErrorCode,
			&i.NextAttemptAt,
			&i.LeaseOwner,
			&i.LeasedUntil,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RuntimeRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptions = `-- name: ListWebhookSubscriptions :many
SELECT id, workspace_id, name, endpoint, enabled, event_types, version, signing_version, secret_suffix, created_by_principal_id, created_at, updated_at FROM webhook_subscriptions WHERE workspace_id=$1 ORDER BY created_at DESC,id DESC LIMIT 200
`

func (q *Queries) ListWebhookSubscriptions(ctx context.Context, workspaceID pgtype.UUID) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptions, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Endpoint,
			&i.Enabled,
			&i.EventTypes,
			&i.Version,
			&i.SigningVersion,
			&i.SecretSuffix,
			&i.CreatedByPrincipalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadWebhookSecret = `-- name: LoadWebhookSecret :one
SELECT envelope FROM webhook_signing_secrets WHERE subscription_id=$1 AND version=$2
`

type LoadWebhookSecretParams struct {
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	Version        int32       `json:"version"`
}

func (q *Queries) LoadWebhookSecret(ctx context.Context, arg LoadWebhookSecretParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadWebhookSecret, arg.SubscriptionID, arg.Version)
	var envelope []byte
	err := row.Scan(&envelope)
	return envelope, err
}

const matchingWebhookSubscriptions = `-- name: MatchingWebhookSubscriptions :many
SELECT id, workspace_id, name, endpoint, enabled, event_types, version, signing_version, secret_suffix, created_by_principal_id, created_at, updated_at FROM webhook_subscriptions WHERE workspace_id=$1 AND enabled AND $2::text=ANY(event_types) ORDER BY id
`

type MatchingWebhookSubscriptionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Column2     string      `json:"column_2"`
}

func (q *Queries) MatchingWebhookSubscriptions(ctx context.Context, arg MatchingWebhookSubscriptionsParams) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, matchingWebhookSubscriptions, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Endpoint,
			&i.Enabled,
			&i.EventTypes,
			&i.Version,
			&i.SigningVersion,
			&i.SecretSuffix,
			&i.CreatedByPrincipalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
