// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, slug, display_name)
VALUES ($1, $2, $3)
RETURNING legacy_id, slug, display_name, created_at, updated_at, id
`

type CreateWorkspaceParams struct {
	ID          pgtype.UUID `json:"id"`
	Slug        string      `json:"slug"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.ID, arg.Slug, arg.DisplayName)
	var i Workspace
	err := row.Scan(
		&i.LegacyID,
		&i.Slug,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
	)
	return i, err
}
