import { test, expect } from "@playwright/test";
import { writeFileSync } from "node:fs";
import { addCompositeTargets, approve, bootstrap, confirmRules, login, openAs, sourceSQL } from "./fixtures";

test("isolated identity and server-owned production workspace", async ({ page, context }) => {
  const failures: string[] = [];
  page.on("response", (response) => { if (response.url().includes("/api/") && response.status() >= 400) failures.push(`${response.status()} ${response.url()}`); });
  expect(bootstrap.mode).toBe("protocol_stub");
  await login(context, "author");
  await page.goto("/assets?section=drafts");
  await expect(page.getByRole("region", { name: "知识确认", exact: true })).toBeVisible();
  const records = await context.request.get(`/api/v1/workspaces/${bootstrap.workspaceId}/production-operations`);
  expect(records.ok()).toBeTruthy();
  const operations = await records.json();
  if (!operations.items.length) await expect(page.getByText("暂无待确认知识")).toBeVisible();
  else await expect(page.getByRole("region", { name: "可恢复的生产记录" })).toBeVisible();
  await page.waitForLoadState("networkidle");
  expect(failures).toEqual([]);
  await page.screenshot({ path: `${process.env.SEMLIA_ACCEPTANCE_ROOT}/empty-${test.info().project.name}.png` });
});

test("source candidate creates a server-owned semantic draft without seeded assets", async ({ page, context }) => {
  await login(context, "author");
  const name = test.info().project.name.replaceAll("-", "_");
  const path = sourceSQL(name);
  await page.goto("/sources");
  await page.getByRole("button", { name: "导入文件", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "导入文件" });
  await dialog.getByLabel("来源名称", { exact: true }).fill(`Acceptance ${name}`);
  await dialog.getByLabel("工件类型").selectOption("sql_bundle");
  await dialog.getByLabel("配置根目录内 SQL 路径").fill(path);
  await dialog.getByRole("button", { name: "校验并保存来源" }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole("button", { name: "关闭持久工件集合", exact: true }).click();
  await page.getByRole("button", { name: `启动发现 Acceptance ${name}`, exact: true }).click();
  await page.getByRole("button", { name: "查看运行", exact: true }).click();
  await page.getByRole("button", { name: new RegExp(`public.${name}_orders`) }).click();
  const production = page.getByRole("region", { name: "知识确认", exact: true });
  await production.getByRole("button", { name: "整理为知识", exact: true }).click();
  await expect(production.getByLabel("业务定义", { exact: true })).toHaveValue("");
  await production.getByLabel("对象名称", { exact: true }).fill(`${name} orders`);
  await production.getByLabel("资产地址", { exact: true }).fill(`acceptance.${name}_orders`);
  await production.getByRole("button", { name: "保存知识草稿" }).click();
  await expect(page).toHaveURL(/production=/);
  await expect(production.getByText("保存知识草稿已由服务器接收。", { exact: true })).toBeVisible();
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await expect(page.getByLabel("资产地址", { exact: true })).toHaveValue(`acceptance.${name}_orders`);
  await page.screenshot({ path: `${process.env.SEMLIA_ACCEPTANCE_ROOT}/draft-${name}.png` });
  await addCompositeTargets(page, name);
  await page.getByRole("button", { name: "保存纠正版本", exact: true }).click();
  await expect(page.getByText("保存纠正版本已由服务器接收。", { exact: true })).toBeVisible();
  let operationId = new URL(page.url()).searchParams.get("production")!;
  let operationPath = `/api/v1/workspaces/${bootstrap.workspaceId}/production-operations/${operationId}`;
  const version2 = await (await context.request.get(operationPath)).json();
  expect(version2.version).toBe(2);
  expect(version2.targets).toHaveLength(10);
  await page.getByLabel("建模要求", { exact: true }).fill("Suggest definitions for the order, customer and revenue-record business objects. Keep business confirmation unresolved.");
  await page.getByRole("button", { name: "生成结构化建议", exact: true }).click();
  await expect(page.getByText("建议已保存", { exact: true })).toBeVisible();
  await expect(page.getByText(/协议替身 · 合成验收响应/)).toBeVisible();
  await page.getByRole("button", { name: "应用到编辑区", exact: true }).click();
  for (const [suffix, definition] of [["orders", "One order per order_id."], ["customers", "One customer per customer_id."], ["revenue", "Sum of paid order amounts, excluding cancelled orders."]]) {
    await page.getByRole("complementary", { name: "生产对象" }).getByRole("button", { name: new RegExp(`^${name} ${suffix}`) }).click();
    await expect(page.getByLabel("业务定义", { exact: true })).toHaveValue(/Protocol stub suggestion/);
    await page.getByLabel("业务定义", { exact: true }).fill(definition);
    await page.getByLabel("适用范围", { exact: true }).fill("Acceptance commerce source; reviewed business scope.");
  }
  await page.getByRole("button", { name: "保存纠正版本", exact: true }).click();
  await expect.poll(async () => (await (await context.request.get(operationPath)).json()).version).toBe(3);
  const corrected = await (await context.request.get(operationPath)).json();
  expect(corrected.generationApplications).toHaveLength(1);
  expect(corrected.targets.filter((target: { declaration: { kind: string } }) => target.declaration.kind === "semantic_asset")).toHaveLength(3);
  await page.screenshot({ path: `${process.env.SEMLIA_ACCEPTANCE_ROOT}/corrected-${name}.png` });
  await page.getByRole("button", { name: "冻结并提交验证", exact: true }).click();
  await expect(page.getByText("验证失败", { exact: true })).toBeVisible();
  await expect(page.getByText("请由有权限的负责人确认业务口径；AI 建议不能代替确认。", { exact: true }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "批准整个集合", exact: true })).toBeDisabled();
  await confirmRules(page, name);
  await page.getByRole("tab", { name: "检查与确认", exact: true }).click();
  await page.getByLabel("审核或重验说明", { exact: true }).fill("Explicit business declarations are complete; revalidate all objects.");
  await page.getByRole("button", { name: "重新验证", exact: true }).click();
  await expect(page.getByText("验证通过", { exact: true })).toBeVisible();
  await approve(page, operationId);
  await openAs(page, "author", operationId);
  await page.getByRole("complementary", { name: "生产对象" }).getByRole("button", { name: new RegExp(`^${name} revenue`) }).click();
  await page.getByLabel("业务定义", { exact: true }).fill("Sum of paid order amounts, excluding cancelled orders and net of refunds.");
  await page.getByRole("tab", { name: "检查与确认", exact: true }).click();
  await expect(page.getByText(/有未保存的纠正/)).toBeVisible();
  await expect(page.getByRole("button", { name: "批准整个集合", exact: true })).toBeDisabled();
  const predecessorId = operationId;
  await page.getByRole("button", { name: "保存纠正版本", exact: true }).click();
  await expect.poll(() => new URL(page.url()).searchParams.get("production")).not.toBe(predecessorId);
  operationId = new URL(page.url()).searchParams.get("production")!;
  operationPath = `/api/v1/workspaces/${bootstrap.workspaceId}/production-operations/${operationId}`;
  const successor = await (await context.request.get(operationPath)).json();
  expect(successor.version).toBe(1);
  expect(successor.activeValidation.status).toBe("not_requested");
  await openAs(page, "publisher", operationId);
  await page.getByRole("tab", { name: "发布记录", exact: true }).click();
  await expect(page.getByRole("button", { name: "发布整个集合", exact: true })).toBeDisabled();
  await openAs(page, "author", operationId);
  await confirmRules(page, name);
  await page.getByRole("button", { name: "冻结并提交验证", exact: true }).click();
  await expect(page.getByText("验证通过", { exact: true })).toBeVisible();
  await page.screenshot({ path: `${process.env.SEMLIA_ACCEPTANCE_ROOT}/validated-${name}.png` });
  await approve(page, operationId);
  await openAs(page, "publisher", operationId);
  await page.getByRole("tab", { name: "发布记录", exact: true }).click();
  await page.getByRole("checkbox", { name: "已核对整个集合及当前验证审核", exact: true }).check();
  await page.getByRole("button", { name: "发布整个集合", exact: true }).click();
  await expect(page.getByText("已同步", { exact: true })).toBeVisible();
  const publishedId = new URL(page.url()).searchParams.get("productionRelease")!;
  expect(publishedId).toBeTruthy();
  const releasePath = `/api/v1/workspaces/${bootstrap.workspaceId}/production-releases/`;
  const published = await (await context.request.get(releasePath + publishedId)).json();
  expect(published.originProposalIds).toHaveLength(10);
  expect(published.beforePins).toHaveLength(10);
  await page.screenshot({ path: `${process.env.SEMLIA_ACCEPTANCE_ROOT}/published-${name}.png` });
  await page.getByLabel("回滚原因", { exact: true }).fill("Acceptance rollback of the complete ten-object set.");
  await page.getByRole("button", { name: "创建回滚版本", exact: true }).click();
  await expect.poll(() => new URL(page.url()).searchParams.get("productionRelease")).not.toBe(publishedId);
  const rollbackId = new URL(page.url()).searchParams.get("productionRelease")!;
  await page.evaluate(() => localStorage.clear()); await page.reload();
  await page.getByRole("tab", { name: "发布记录", exact: true }).click();
  await expect(page.getByText(rollbackId, { exact: true })).toBeVisible();
  await expect(page.getByText("已同步", { exact: true })).toBeVisible();
  await page.getByLabel("回滚原因", { exact: true }).fill("Restore the exact immutable published set by rolling back the rollback.");
  await page.getByRole("button", { name: "创建回滚版本", exact: true }).click();
  await expect.poll(() => new URL(page.url()).searchParams.get("productionRelease")).not.toBe(rollbackId);
  await expect(page.getByText("已同步", { exact: true })).toBeVisible();
  const restoredId = new URL(page.url()).searchParams.get("productionRelease")!;
  const restored = await (await context.request.get(releasePath + restoredId)).json();
  expect(restored.afterManifest).toEqual(published.afterManifest);
  expect(await (await context.request.get(releasePath + publishedId)).json()).toEqual(published);
  await page.screenshot({ path: `${process.env.SEMLIA_ACCEPTANCE_ROOT}/restored-${name}.png` });
  writeFileSync(`${process.env.SEMLIA_ACCEPTANCE_ROOT}/objects-${name}.json`, JSON.stringify({ corrected, successor, published, restored }, null, 2));
  await page.getByRole("button", { name: "知识库", exact: true }).click();
  await page.getByRole("button", { name: "草稿与整理", exact: true }).click();
  await expect(page).toHaveURL(/section=drafts/);
  await page.reload();
  await expect(page.getByRole("region", { name: "可恢复的生产记录" })).toBeVisible();
  await login(context, "author");
  await page.goto("/sources");
  await page.getByRole("button", { name: `查看来源 Acceptance ${name}`, exact: true }).click();
  await page.getByRole("tab", { name: "运行历史", exact: true }).click();
  await page.getByRole("button", { name: /^查看运行 / }).first().click();
  await page.getByRole("button", { name: new RegExp(`public.${name}_customers`) }).click();
  await page.getByRole("button", { name: "整理为知识", exact: true }).click();
  const matchTrigger = page.getByRole("button", { name: "匹配已有资产", exact: true });
  await matchTrigger.focus(); await page.keyboard.press("Enter");
  const matching = page.getByRole("dialog", { name: "匹配已有语义资产", exact: true });
  await expect(matching.getByLabel("搜索匹配资产")).toBeFocused();
  await expect(matching).toHaveCSS("opacity", "1");
  await page.screenshot({ path: `${process.env.SEMLIA_ACCEPTANCE_ROOT}/keyboard-match-${name}.png`, animations: "disabled" });
  await page.keyboard.press("Escape");
  await expect(matchTrigger).toBeFocused();
  await page.keyboard.press("Enter");
  await matching.getByLabel("搜索匹配资产").fill(`acceptance.${name}_customers`);
  await matching.getByRole("button", { name: new RegExp(`acceptance.${name}_customers`) }).click();
  await expect(matching).not.toBeVisible();
  await expect(page.getByLabel("资产地址", { exact: true })).toHaveValue(`acceptance.${name}_customers`);
  await expect(page.getByLabel("资产地址", { exact: true })).toBeDisabled();
  await page.getByLabel("业务定义", { exact: true }).fill("One customer per customer_id, matched from the published catalogue.");
  await page.getByRole("button", { name: "保存知识草稿", exact: true }).click();
  await expect(page.getByText("保存知识草稿已由服务器接收。", { exact: true })).toBeVisible();
  await expect(page).toHaveURL(/production=/);
  const matchedId = new URL(page.url()).searchParams.get("production")!;
  const matchedResponse = await context.request.get(`/api/v1/workspaces/${bootstrap.workspaceId}/production-operations/${matchedId}`);
  expect(matchedResponse.ok()).toBeTruthy();
  const matched = await matchedResponse.json();
  expect(matched.targets).toHaveLength(1);
  expect(matched.targets[0].declaration.intent).toBe("update");
  expect(matched.targets[0].declaration.baseRevisionId).toBeTruthy();
  writeFileSync(`${process.env.SEMLIA_ACCEPTANCE_ROOT}/matched-${name}.json`, JSON.stringify(matched, null, 2));
  await page.emulateMedia({ reducedMotion: "reduce" });
  expect(await page.evaluate(() => matchMedia("(prefers-reduced-motion: reduce)").matches)).toBe(true);
  expect(await page.getByRole("button", { name: "核对服务器状态" }).evaluate((button) => Number.parseFloat(getComputedStyle(button).transitionDuration))).toBeLessThanOrEqual(0.00001);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `${process.env.SEMLIA_ACCEPTANCE_ROOT}/matched-${name}.png` });
  await page.getByRole("button", { name: "返回来源与候选", exact: true }).click();
  await expect(page).toHaveURL(/\/sources$/);
});
