/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether the process is alive */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether required dependencies are ready */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read public build and contract information */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Major version used in public API paths and payloads.
         * @example v1
         */
        ApiVersion: string;
        /**
         * @description Semantic version of the public contract bundle.
         * @example 0.1.0
         */
        SchemaVersion: string;
        /**
         * Format: typeid
         * @description Stable TypeID containing a registered lowercase resource prefix and UUIDv7 value.
         * @example ast_01arz3ndektsv4rrffq69g5fav
         */
        ResourceId: string;
        /**
         * Format: typeid
         * @example wsp_01arz3ndektsv4rrffq69g5fav
         */
        WorkspaceId: string;
        /**
         * Format: typeid
         * @example ast_01arz3ndektsv4rrffq69g5fav
         */
        SemanticAssetId: string;
        /**
         * Format: typeid
         * @example rev_01arz3ndektsv4rrffq69g5fav
         */
        AssetRevisionId: string;
        /**
         * Format: typeid
         * @example rel_01arz3ndektsv4rrffq69g5fav
         */
        SemanticRelationId: string;
        /**
         * Format: typeid
         * @example ont_01arz3ndektsv4rrffq69g5fav
         */
        OntologyRevisionId: string;
        /**
         * Format: typeid
         * @example evd_01arz3ndektsv4rrffq69g5fav
         */
        EvidenceArtifactId: string;
        /**
         * Format: typeid
         * @example run_01arz3ndektsv4rrffq69g5fav
         */
        RunId: string;
        /**
         * @description Workspace-scoped human-readable namespace and stable key.
         * @example commerce.net_revenue
         */
        SemanticAddress: string;
        /** @enum {string} */
        SemanticAssetType: "concept" | "entity" | "semantic_model" | "dimension" | "measure" | "metric" | "segment";
        /** @enum {string} */
        RelationPredicate: "measures" | "describes" | "depends_on" | "derived_from" | "filters_by" | "synonym_of" | "contains" | "broader_than" | "narrower_than" | "equivalent_to" | "disjoint_with";
        /** @enum {string} */
        RelationAssertionState: "asserted" | "inferred" | "candidate" | "deprecated";
        /**
         * Format: date-time
         * @description RFC 3339 timestamp normalized to UTC at public boundaries.
         * @example 2026-08-08T08:00:00Z
         */
        Timestamp: string;
        /**
         * @description Lowercase 16-byte W3C trace identifier.
         * @example 4bf92f3577b34da6a3ce929d0e0e4736
         */
        TraceId: string;
        /** @description Opaque pagination cursor that clients must not interpret. */
        Cursor: string;
        PageInfo: {
            limit: number;
            nextCursor?: components["schemas"]["Cursor"];
        };
        /**
         * @description Stable machine-readable error identifier.
         * @example DEPENDENCY_UNAVAILABLE
         */
        ErrorCode: string;
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            traceId: components["schemas"]["TraceId"];
            details: {
                [key: string]: unknown;
            };
            retryable?: boolean;
        };
        /**
         * @description Namespaced event type using lowercase dot-separated segments.
         * @example system.readiness.changed
         */
        EventType: string;
        EventEnvelope: {
            /** @enum {string} */
            specVersion: "semlia.events/v1";
            id: components["schemas"]["ResourceId"];
            type: components["schemas"]["EventType"];
            /**
             * Format: uri
             * @example urn:semlia:control-plane
             */
            source: string;
            subject?: components["schemas"]["ResourceId"];
            workspaceId?: components["schemas"]["ResourceId"];
            time: components["schemas"]["Timestamp"];
            traceId: components["schemas"]["TraceId"];
            data: {
                [key: string]: unknown;
            };
        };
        HealthResponse: {
            /** @enum {string} */
            status: "live" | "ready";
            traceId: components["schemas"]["TraceId"];
        };
        SystemInfo: {
            /** @enum {string} */
            service: "semlia";
            apiVersion: components["schemas"]["ApiVersion"];
            schemaVersion: components["schemas"]["SchemaVersion"];
            buildVersion: string;
            traceId: components["schemas"]["TraceId"];
        };
    };
    responses: {
        /** @description The request failed. */
        Error: {
            headers: {
                "X-Trace-ID": components["headers"]["TraceId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description A required dependency is unavailable. */
        ServiceUnavailable: {
            headers: {
                "X-Trace-ID": components["headers"]["TraceId"];
                /** @description Suggested retry delay in seconds. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description W3C-compatible trace identifier for support and correlation. */
        TraceId: components["schemas"]["TraceId"];
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    "X-Trace-ID": components["headers"]["TraceId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Required dependencies are ready. */
            200: {
                headers: {
                    "X-Trace-ID": components["headers"]["TraceId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public service information. */
            200: {
                headers: {
                    "X-Trace-ID": components["headers"]["TraceId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
