import { expect, test } from "@playwright/test";
import { resolve } from "node:path";

const accessControlEvidenceDirectory = resolve(process.cwd(), process.env.SEMLIA_BROWSER_EVIDENCE_DIR || "../../docs/evidence/access-control-prototype/T005/screenshots");

test("database-to-answer journey stays inspectable", async ({ page }) => {
  test.slow();
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");

  await expect(page.getByText("原型 · 模拟数据")).toHaveCount(0);
  await expect(page.getByText(/稳定版 ·/)).toHaveCount(0);
  await expect(page.locator(".ask-heading")).toHaveCount(0);
  await expect(page.getByText("可信语义问答", { exact: true })).toHaveCount(0);
  await expect(page.getByText("知识索引就绪", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: /编辑会话标题：新会话/ }).click();
  const titleInput = page.getByRole("textbox", { name: "编辑会话标题" });
  await titleInput.fill("华东收入复盘");
  await titleInput.press("Enter");
  await expect(page.getByRole("button", { name: /编辑会话标题：华东收入复盘/ })).toBeVisible();
  await expect(page.getByRole("button", { name: /华东收入复盘/ }).last()).toBeVisible();
  await expect(page.locator(".context-header")).toHaveCount(0);
  await expect(page.locator(".topbar")).toHaveCSS("height", "52px");
  await expect(page.locator(".answer-route")).toHaveCount(0);
  await expect(page.getByRole("complementary", { name: "回答执行与证据" })).toHaveCount(0);
  await expect(page.getByText("Prototype 预览")).toBeVisible();
  await expect(page.getByText(/不会生成演示答案/)).toBeVisible();
  await expect(page.locator(".workspace-canvas")).toHaveCSS("background-image", "none");
  const composerPosition = await page.locator(".ask-composer").evaluate((element) => {
    const rect = element.getBoundingClientRect();
    return { bottom: window.innerHeight - rect.bottom, position: getComputedStyle(element).position };
  });
  expect(composerPosition.position).toBe("fixed");
  expect(composerPosition.bottom).toBeLessThan(24);
  const clippedAskElements = await page.locator(".ask-layout, .topbar-actions").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedAskElements).toBe(0);

  await expect(page.getByRole("textbox", { name: "向 Semlia 提问" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "发送问题" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "指出问题" })).toHaveCount(0);
  await page.getByRole("button", { name: "知识资产" }).click();
  await page.getByRole("searchbox", { name: "搜索知识目录" }).fill("净收入");
  await page.getByRole("button", { name: "打开语义资产 净收入" }).click();
  await expect(page).toHaveURL(/\/assets\?asset=metric_01J4NETREVENUE8W4Q9D7K2/);
  await page.reload();
  await expect(page.getByRole("heading", { name: "净收入" })).toBeVisible();
  await page.getByRole("tab", { name: "可信度" }).click();
  await expect(page.getByRole("tab", { name: "可信度" })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByText("Cube schema 编译通过")).toBeVisible();
  await expect(page.getByRole("complementary", { name: "治理上下文" }).getByRole("button", { name: /知识块与证据/ })).toHaveCount(0);
  await page.getByRole("tab", { name: "定义" }).click();
  await expect(page.getByRole("heading", { name: "权威语义页" })).toBeVisible();
  await expect(page.getByText("AI 检索词")).toBeVisible();
  await page.getByRole("tab", { name: "本体关系" }).click();
  const ontologyGraph = page.getByRole("img", { name: "净收入 的语义关系图" });
  await expect(ontologyGraph).toBeVisible();
  const ontologyGraphSize = await ontologyGraph.evaluate((element) => { const rect = element.getBoundingClientRect(); return { width: rect.width, height: rect.height }; });
  expect(ontologyGraphSize.width).toBeGreaterThan(560);
  expect(ontologyGraphSize.height).toBeGreaterThan(240);
  await page.getByRole("button", { name: "概念层级" }).click();
  await expect(page.getByRole("img", { name: "净收入 的本体层级图" })).toBeVisible();
  await page.getByRole("button", { name: "依赖与影响" }).click();
  await expect(page.getByRole("img", { name: "净收入 的依赖与影响图" })).toBeVisible();
  await expect(page.getByRole("table", { name: "本体关系类型约束" })).toBeVisible();
  const clippedOntologyElements = await page.locator(".asset-wiki-authority, .asset-ontology-context, .ontology-lineage-map, .asset-relation-list, .asset-ontology-constraints").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedOntologyElements).toBe(0);

  await page.getByRole("button", { name: "工作台" }).click();
  await expect(page.getByRole("heading", { name: "待办" })).toHaveCount(0);
  await expect(page.locator(".lifecycle-rail")).toHaveCount(0);
  await expect(page.locator(".work-summary-band, .work-context-panel")).toHaveCount(0);
  const workbenchContext = page.getByRole("complementary", { name: "治理上下文" });
  const workbenchQueue = page.getByRole("region", { name: "工作台待办队列" });
  await expect(workbenchQueue).toBeVisible();
  await expect(workbenchContext.getByRole("button", { name: /^待办/ })).toHaveCount(0);
  await expect(workbenchContext.locator(".context-workbench-task")).toHaveCount(3);
  await workbenchContext.getByRole("button", { name: "搜索待办" }).click();
  await expect(page.getByRole("searchbox", { name: "搜索待办" })).toBeFocused();
  await expect(workbenchQueue.getByRole("button", { name: /检查客户增长域运行异常/ })).toBeVisible();
  await page.getByRole("combobox", { name: "筛选待办风险" }).selectOption("critical");
  await expect(workbenchQueue.getByRole("button", { name: /旧区域别名无法安全废弃/ })).toBeVisible();
  await expect(workbenchQueue.getByRole("button", { name: /确认客单价退款订单口径/ })).toHaveCount(0);
  await page.getByRole("combobox", { name: "筛选待办风险" }).selectOption("");
  const clippedWorkbenchElements = await page.locator(".workbench-commandbar, .workbench-task-table").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedWorkbenchElements).toBe(0);
  await expect(page.getByRole("complementary", { name: "治理上下文" }).getByRole("button", { name: /动态/ })).toHaveCount(0);
  await workbenchQueue.getByRole("button", { name: /检查客户增长域运行异常/ }).click();
  await expect(page).toHaveURL(/view=overview&attentionItem=ati_01arz3ndektsv4rrffq69g5fax/);
  await page.reload();
  const restoredWorkbenchDetail = page.getByRole("region", { name: "工作台待办详情" });
  await expect(restoredWorkbenchDetail).toContainText("DISCOVERY_FAILED");
  const clippedWorkbenchDetailElements = await page.locator(".workbench-detail-header, .workbench-detail-facts, .workbench-detail-layout").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedWorkbenchDetailElements).toBe(0);
  await page.locator(".topbar").getByRole("button", { name: "返回待办" }).click();

  await page.getByRole("button", { name: "数据接入" }).click();
  await expect(page.getByRole("searchbox", { name: "搜索数据来源" })).toBeVisible();
  await expect(page.getByRole("tab", { name: /数据库连接/ })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("tab", { name: /文件导入/ })).toBeVisible();
  await expect(page.getByText("Cube Commerce")).toHaveCount(0);
  await expect(page.getByText("dbt Analytics")).toHaveCount(0);
  await expect(page.locator(".workspace-breadcrumb")).toHaveText("数据来源");
  await expect(page.locator(".workspace-breadcrumb")).not.toContainText("Semlia");
  await expect(page.locator(".topbar").getByRole("button", { name: "创建提案" })).toHaveCount(0);
  await expect(page.locator(".source-table-row").first()).toBeVisible();
  const sourceContext = page.getByRole("complementary", { name: "治理上下文" });
  await expect(sourceContext.getByRole("button", { name: /权限策略/ })).toHaveCount(0);
  await page.getByRole("tab", { name: /文件导入/ }).click();
  await page.getByRole("button", { name: "导入文件" }).click();
  const fileDialog = page.getByRole("dialog", { name: "导入文件" });
  await fileDialog.getByLabel("选择文件").setInputFiles({ name: "metric_dictionary.md", mimeType: "text/markdown", buffer: Buffer.from("# 净收入\n\n净收入扣除全额退款。") });
  await expect(fileDialog.getByLabel("分块方式")).toHaveValue("按标题层级");
  await expect(fileDialog.getByLabel("保留代码块")).toBeChecked();
  await expect(fileDialog.getByLabel("字段分隔符")).toHaveCount(0);
  await fileDialog.getByRole("button", { name: "检查文件" }).click();
  await expect(fileDialog.getByText("文件检查通过")).toBeVisible();
  await fileDialog.getByRole("button", { name: "导入并开始构建" }).click();
  await expect(page.getByRole("tabpanel", { name: /文件导入/ })).toContainText("metric_dictionary");
  await sourceContext.getByRole("button", { name: /接入自动化/ }).click();
  const buildTaskTable = page.getByRole("region", { name: "接入自动化列表" });
  await expect(buildTaskTable).toBeVisible();
  await expect(buildTaskTable).toContainText("元数据增量");
  await expect(buildTaskTable).not.toContainText("src-ecommerce@9f2e8a");
  await expect(buildTaskTable.getByRole("button", { name: /^(停用|启用) / })).toHaveCount(0);
  await expect(page.locator(".view-sources .page-heading, .build-run-inspector, .build-records-layout")).toHaveCount(0);
  const clippedBuildTaskElements = await page.locator(".build-task-commandbar, .build-task-table").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedBuildTaskElements).toBe(0);
  await page.getByRole("button", { name: "新建构建任务" }).click();
  const buildTaskDialog = page.getByRole("dialog", { name: "新建构建任务" });
  const enabledTaskToggle = buildTaskDialog.getByLabel("启用任务");
  await expect(enabledTaskToggle).toBeChecked();
  expect(await enabledTaskToggle.evaluate((element) => element.closest("header")?.classList.contains("build-task-dialog-header"))).toBe(true);
  await expect(buildTaskDialog.getByText("基本信息", { exact: true })).toHaveCount(0);
  await expect(buildTaskDialog.getByText("输入范围", { exact: true })).toHaveCount(0);
  await expect(buildTaskDialog.getByText("运行策略", { exact: true })).toHaveCount(0);
  await expect(buildTaskDialog.locator(".build-task-section-heading")).toHaveCount(0);
  await expect(buildTaskDialog.getByRole("radio", { name: /元数据增量/ })).toBeChecked();
  const buildModeHelpButton = buildTaskDialog.getByRole("button", { name: "查看元数据增量说明" });
  const buildModeTooltip = buildTaskDialog.getByRole("tooltip");
  await expect(buildModeHelpButton).toBeVisible();
  await expect(buildModeTooltip).toBeHidden();
  await buildModeHelpButton.hover();
  await expect(buildModeTooltip).toBeVisible();
  await expect(buildModeTooltip).toContainText("元数据快照，不是业务数据快照");
  await expect(buildModeTooltip).toContainText("失败运行不会推进 checkpoint");
  await expect(buildTaskDialog.getByRole("combobox", { name: "对象范围" })).toHaveCount(0);
  await expect(buildTaskDialog.getByRole("button", { name: "创建任务" })).toBeDisabled();
  await expect(buildTaskDialog.getByRole("searchbox", { name: "搜索可用数据来源" })).toHaveCount(0);
  const runStrategyTopBeforePicker = await buildTaskDialog.locator(".build-task-section").nth(2).evaluate((element) => element.getBoundingClientRect().top);
  await buildTaskDialog.getByRole("button", { name: /选择数据来源/ }).click();
  const runStrategyTopAfterPicker = await buildTaskDialog.locator(".build-task-section").nth(2).evaluate((element) => element.getBoundingClientRect().top);
  expect(Math.abs(runStrategyTopAfterPicker - runStrategyTopBeforePicker)).toBeLessThan(1);
  await buildTaskDialog.getByRole("searchbox", { name: "搜索可用数据来源" }).fill("PostgreSQL");
  await expect(buildTaskDialog.getByRole("checkbox", { name: "选择数据来源 PostgreSQL Analytics" })).toBeVisible();
  await expect(buildTaskDialog.getByRole("checkbox", { name: "选择数据来源 FY2026 营收目标" })).toHaveCount(0);
  await buildTaskDialog.getByRole("button", { name: "完成选择" }).click();
  await buildTaskDialog.locator(".build-trigger-control").getByText("定时调度", { exact: true }).click();
  await expect(buildTaskDialog.getByLabel("Cron 表达式")).toHaveValue("0 2 * * *");
  await expect(buildTaskDialog.getByLabel("调度时区")).toHaveValue("Asia/Shanghai");
  await expect(buildTaskDialog.locator(".build-schedule-preview, .build-task-toggle")).toHaveCount(0);
  const clippedScheduleElements = await buildTaskDialog.locator(".build-trigger-field, .build-schedule-config").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedScheduleElements).toBe(0);
  const clippedBuildTaskDialogElements = await buildTaskDialog.locator(".build-task-dialog-header, .build-task-section, .build-task-dialog-footer").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedBuildTaskDialogElements).toBe(0);
  await buildTaskDialog.getByRole("button", { name: "关闭构建任务" }).click();
  await buildTaskTable.getByRole("button", { name: "运行 经营数据元数据同步" }).click();
  await expect(buildTaskTable.getByText("已完成")).toBeVisible();
  await expect(sourceContext.getByRole("button", { name: /构建运行/ })).toHaveCount(0);
  await sourceContext.getByRole("button", { name: /接入运行/ }).click();
  const buildRunList = page.getByRole("region", { name: "接入运行" });
  await expect(buildRunList).toBeVisible();
  await expect(buildRunList).not.toContainText("RUN-SESSION");
  await expect(buildRunList).toContainText("2,846 对象 · 12 项变化");
  await expect(buildRunList).toContainText("数据库同步");
  await expect(buildRunList).not.toContainText("候选版本");
  await expect(buildRunList).not.toContainText("知识块");
  const firstBuildRunRow = buildRunList.getByRole("button", { name: /查看运行 RUN-240824-1432/ });
  await expect(firstBuildRunRow.locator(".build-run-list-id")).toHaveText("RUN-240824-1432");
  await expect(firstBuildRunRow.locator(".build-run-list-task")).toHaveText("经营数据元数据同步");
  await expect(firstBuildRunRow.locator(".build-run-list-time")).toHaveText("2026-08-24 14:32:18");
  await expect(firstBuildRunRow.locator(".build-run-list-mode")).toHaveText("数据库同步");
  await expect(firstBuildRunRow.locator(".build-run-list-duration")).toHaveText("2 分 18 秒");
  await expect(buildRunList.locator(".build-run-list-head > span")).toHaveText(["Run ID", "接入任务", "开始时间", "耗时", "类型", "接入结果", "状态", ""]);
  const runTimeFormats = await buildRunList.locator(".build-run-list-time").allTextContents();
  expect(runTimeFormats.every((value) => /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(value))).toBe(true);
  const clippedBuildRunListElements = await page.locator(".build-run-commandbar, .build-run-list-surface").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedBuildRunListElements).toBe(0);
  await expect(page.getByRole("searchbox", { name: "搜索接入运行" })).toHaveAttribute("placeholder", "搜索 Run ID、任务或来源");
  await expect(sourceContext.getByRole("button", { name: /来源版本与变更/ })).toHaveCount(0);
  await page.getByRole("button", { name: /查看运行 RUN-240824-1432/ }).click();
  const buildRunDetail = page.getByRole("region", { name: "接入运行详情" });
  await expect(buildRunDetail.getByLabel("元数据版本差异")).toBeVisible();
  await expect(buildRunDetail.getByLabel("元数据版本差异")).toContainText("3新增8修改1删除");
  await expect(buildRunDetail).toContainText("schema:9f2e8a");
  await expect(buildRunDetail.getByLabel("接入阶段")).toContainText("触发下游");
  await expect(buildRunDetail.getByRole("group", { name: "运行结果关系图" })).toHaveCount(0);
  await buildRunDetail.getByRole("button", { name: "查看执行日志" }).click();
  const runLogDialog = page.getByRole("dialog", { name: "执行日志" });
  await expect(runLogDialog.getByRole("log", { name: "运行执行日志" })).toContainText("连接来源");
  await expect(runLogDialog.getByRole("log", { name: "运行执行日志" })).toContainText("RUN-240901-1208");
  await runLogDialog.getByRole("button", { name: "关闭执行日志" }).click();
  const backToRunList = page.getByRole("button", { name: "返回接入运行" });
  await expect(backToRunList).toBeVisible();
  expect(await backToRunList.evaluate((element) => element.closest(".topbar") !== null)).toBe(true);
  const clippedBuildRunElements = await page.locator(".topbar, .build-run-detail-page").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedBuildRunElements).toBe(0);
  await buildRunDetail.getByRole("button", { name: "打开下游运行" }).click();
  const downstreamDialog = page.getByRole("dialog", { name: "PostgreSQL Analytics" });
  await expect(downstreamDialog.getByRole("region", { name: "运行进度" })).toContainText("68%");
  await expect(downstreamDialog.getByRole("log", { name: "全局运行事件" })).toContainText("服务端已进入候选版本阶段");
  await expect(downstreamDialog).not.toContainText("上游接入 RUN-240824-1432");
  await downstreamDialog.getByRole("button", { name: "关闭", exact: true }).click();

  await page.getByRole("button", { name: "变更与发布", exact: true }).click();
  await page.getByRole("button", { name: "查看候选资产版本 客单价 @9" }).click();
  const releaseContext = page.getByRole("complementary", { name: "治理上下文" });
  await expect(releaseContext.getByRole("button", { name: "搜索资产、变更与功能" })).toHaveCount(0);
  await expect(page.getByRole("tab", { name: /版本差异.*2/ })).toHaveAttribute("aria-selected", "true");
  await page.getByRole("button", { name: "收起发布门禁" }).click();
  await expect(page.getByRole("button", { name: "展开发布门禁" })).toBeVisible();
  await page.getByRole("button", { name: "展开发布门禁" }).click();
  await page.getByRole("tab", { name: /变更来源.*1/ }).click();
  await expect(page.getByRole("heading", { name: "包含的变更事项" })).toBeVisible();
  await expect(page.getByText("PROP-128", { exact: true })).toBeVisible();
  const backToAssetVersions = page.getByRole("button", { name: "返回资产版本列表" });
  await expect(backToAssetVersions).toBeVisible();
  expect(await backToAssetVersions.evaluate((element) => element.closest(".topbar") !== null)).toBe(true);
  await expect(page.locator(".governance-detail-commandbar")).toHaveCount(0);
  await page.getByRole("button", { name: "审核候选版本 客单价 @9" }).click();
  const dialog = page.getByRole("dialog", { name: "审核 客单价 · @9" });
  await expect(dialog.getByRole("button", { name: "批准版本" })).toBeDisabled();
  await dialog.getByRole("textbox", { name: "审核意见" }).fill("退款口径变化已由增长组确认。");
  await dialog.getByRole("button", { name: "批准版本" }).click();
  await expect(page.getByRole("status")).toContainText("评审已记录：批准");

  await expect(page.getByRole("button", { name: "发布 @9" })).toBeVisible();
  const clippedReleaseElements = await page.locator(".candidate-version-detail, .candidate-review-summary, .candidate-review-layout, .candidate-review-card").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedReleaseElements).toBe(0);
  await expect(page.getByRole("button", { name: "变更与发布" })).toHaveAttribute("aria-current", "page");
  await expect(page.getByRole("button", { name: "比较版本" })).toHaveCount(0);
  await page.getByRole("button", { name: "发布 @9" }).click();
  const publishDialog = page.getByRole("dialog", { name: "发布客单价 @9" });
  await expect(publishDialog.getByText("独立发布者由服务端强制")).toBeVisible();
  await publishDialog.getByRole("button", { name: "确认发布并生效" }).click();
  const publishedCandidate = page.getByRole("region", { name: "客单价 @9 候选资产版本详情" });
  await expect(publishedCandidate).toContainText("已发布");
  await expect(publishedCandidate.getByRole("region", { name: "发布记录" })).toContainText("#7");

  await backToAssetVersions.click();
  await page.getByRole("searchbox", { name: "搜索资产版本" }).fill("");
  await expect(page.getByRole("button", { name: "查看发布记录 @9 #7" })).toContainText("当前版本");
  await expect(page.getByRole("button", { name: "查看发布记录 @12 #6" })).toContainText("历史版本");
  await page.getByRole("button", { name: "查看发布记录 @12 #6" }).click();
  await expect(page).toHaveURL(/\/governance\?release=release-2026\.08\.3/);
  await page.reload();
  await expect(page.getByRole("region", { name: "发布 #6 详情" })).toBeVisible();
  await expect(page.getByText("服务端消费影响")).toBeVisible();
  await expect(page.getByText("当前合同提供权威计数，不提供消费者明细。")).toBeVisible();
  await expect(page.getByText("Fluxale Production", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "查看差异基准" }).click();
  const versionCompareDialog = page.getByRole("dialog", { name: "发布差异基准" });
  await expect(versionCompareDialog.getByText("与前一发布固定版本比较")).toBeVisible();
  await expect(versionCompareDialog.getByText("与当前注册表比较")).toBeVisible();
  await expect(versionCompareDialog.getByText("前一发布固定版本").first()).toBeVisible();
  await expect(versionCompareDialog.getByText("当前注册表版本").first()).toBeVisible();
  await expect(versionCompareDialog.getByText("fixture.release_manifest")).toBeVisible();
  await versionCompareDialog.getByRole("button", { name: "完成" }).click();
  await page.getByRole("button", { name: "工作台" }).click();
  const workbenchDetailContext = page.getByRole("complementary", { name: "治理上下文" });
  await workbenchDetailContext.getByRole("button", { name: "打开待办详情 旧区域别名无法安全废弃" }).click();
  const attentionDetail = page.getByRole("region", { name: "工作台待办详情" });
  await expect(attentionDetail).toBeVisible();
  await expect(attentionDetail.getByText("SEMANTIC_QUERY_REFUSED")).toBeVisible();
  await expect(workbenchDetailContext.getByRole("button", { name: "打开待办详情 旧区域别名无法安全废弃" })).toHaveAttribute("aria-current", "page");
  await expect(page.getByRole("button", { name: "工作台" })).toHaveAttribute("aria-current", "page");
  await expect(page.getByRole("button", { name: "变更与发布" })).not.toHaveAttribute("aria-current", "page");
  await expect(page.locator(".topbar").getByRole("button", { name: "返回待办" })).toBeVisible();
  await attentionDetail.getByRole("button", { name: "处理兼容性" }).click();
  await expect(page).toHaveURL(/\/delivery\/compatibility\?consumer=csm_01arz3ndektsv4rrffq69g5fav&binding=cbd_01arz3ndektsv4rrffq69g5fav&query=smq_01arz3ndektsv4rrffq69g5fav/);
  const compatibilityDetail = page.getByRole("region", { name: "兼容性影响详情" });
  await expect(compatibilityDetail).toContainText("Fixture target");
  await expect(compatibilityDetail).toContainText("csm_01arz3ndektsv4rrffq69g5fav");
  await expect(compatibilityDetail).toContainText("cbd_01arz3ndektsv4rrffq69g5fav");
  await expect(compatibilityDetail).toContainText("smq_01arz3ndektsv4rrffq69g5fav");
  await expect(compatibilityDetail).toContainText("不会伪造消费者、绑定或查询结果");
  await page.reload();
  await expect(page.getByRole("region", { name: "兼容性影响详情" })).toBeVisible();

  await page.getByRole("button", { name: "知识资产" }).click();
  await expect(page.getByRole("region", { name: "知识目录" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "知识目录" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "保存视图" })).toHaveCount(0);
  await expect(page.getByRole("region", { name: "语义资产详情" })).toHaveCount(0);
  await expect(sourceContext.getByText("知识目录", { exact: true })).toBeVisible();
  await expect(sourceContext.getByText("最近打开")).toHaveCount(0);
  await expect(sourceContext.getByRole("button", { name: "打开最近资产 净收入" })).toBeVisible();
  await expect(sourceContext.getByRole("button", { name: /关系与映射/ })).toHaveCount(0);
  await expect(sourceContext.getByRole("button", { name: /本体与关系|物理数据图谱/ })).toHaveCount(0);
  await expect(page.getByRole("tab", { name: /清单|语义关系|物理映射/ })).toHaveCount(0);
  await page.getByRole("searchbox", { name: "搜索知识目录" }).fill("净收入");
  await expect(page.getByRole("button", { name: /净收入依赖支付订单数，语义关系/ })).toBeVisible();
  await expect(page.getByRole("button", { name: /analytics.orders 映射至 净收入，物理绑定/ })).toBeVisible();
  await page.getByRole("button", { name: "打开语义资产 净收入" }).click();
  await expect(page.getByRole("heading", { name: "净收入" })).toBeVisible();
  await expect(page.locator(".asset-detail-titlebar")).toHaveCount(0);
  await expect(page.locator(".topbar").getByRole("button", { name: "返回知识目录" })).toBeVisible();
  await expect(page.locator(".asset-detail-commandbar")).toHaveCount(0);
  await expect(page.getByRole("complementary", { name: "生产可用判断" })).toContainText("当前 revision 可用于生产");
  await expect(page.getByRole("complementary", { name: "生产可用判断" })).toContainText("没有阻断门禁");
  await expect(page.locator(".asset-header-state strong")).toHaveText("@12");
  await expect(page.getByRole("button", { name: "修订知识" })).toBeVisible();
  await page.getByRole("button", { name: "修订知识" }).click();
  const revisionPicker = page.getByRole("dialog", { name: "选择知识修订对象" });
  await expect(revisionPicker).toContainText("来源资料与已发布版本保持只读");
  await revisionPicker.getByRole("button", { name: /计算表达式/ }).click();
  const headerRevisionWorkbench = page.getByRole("region", { name: "净收入 知识修订工作台" });
  await expect(headerRevisionWorkbench.getByRole("textbox", { name: "计算表达式候选值" })).toBeVisible();
  await headerRevisionWorkbench.getByRole("button", { name: "取消修订" }).click();
  await page.getByRole("tab", { name: "定义" }).click();
  await expect(page.getByRole("region", { name: "指标内容模板" })).toContainText("业务衡量与比较契约");
  await page.getByRole("tab", { name: "实现" }).click();
  await expect(page.getByRole("heading", { name: "PhysicalBinding" })).toBeVisible();
  await expect(page.getByText("BIND-NET-REV-12").first()).toBeVisible();
  const mappingSections = await page.locator(".asset-mapping-layout > section").evaluateAll((sections) => sections.map((section) => { const rect = section.getBoundingClientRect(); return { top: rect.top, bottom: rect.bottom, left: rect.left, right: rect.right }; }));
  expect(mappingSections[1].top).toBeGreaterThanOrEqual(mappingSections[0].bottom - 1);
  expect(Math.abs(mappingSections[0].left - mappingSections[1].left)).toBeLessThan(1);
  await page.getByRole("tab", { name: "可信度" }).click();
  await expect(page.getByText("Cube schema 编译通过")).toBeVisible();
  await expect(page.getByRole("table", { name: "指标验证规则" })).toContainText("METRIC-001");
  await expect(page.getByRole("table", { name: "字段主张与证据" })).toContainText("spec.expression");
  const assuranceSections = await page.locator(".asset-assurance-layout > section").evaluateAll((sections) => sections.map((section) => { const rect = section.getBoundingClientRect(); return { top: rect.top, bottom: rect.bottom, left: rect.left }; }));
  expect(assuranceSections[1].top).toBeGreaterThanOrEqual(assuranceSections[0].bottom - 1);
  expect(Math.abs(assuranceSections[0].left - assuranceSections[1].left)).toBeLessThan(1);
  await page.getByRole("tab", { name: "交付与影响" }).click();
  await expect(page.getByRole("heading", { name: "当前生产指针" })).toBeVisible();
  const usageSections = await page.locator(".asset-usage-layout > section").evaluateAll((sections) => sections.map((section) => { const rect = section.getBoundingClientRect(); return { top: rect.top, bottom: rect.bottom, left: rect.left }; }));
  expect(usageSections[1].top).toBeGreaterThanOrEqual(usageSections[0].bottom - 1);
  expect(Math.abs(usageSections[0].left - usageSections[1].left)).toBeLessThan(1);
  await page.getByRole("button", { name: "返回知识目录" }).click();
  await expect(page.getByRole("searchbox", { name: "搜索知识目录" })).toHaveValue("净收入");
  const clippedAssetElements = await page.locator(".asset-catalog, .asset-table-head, .asset-row, .asset-tabs, .asset-type-template, .asset-type-rule-table").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedAssetElements).toBe(0);

  const hasDocumentOverflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
  expect(hasDocumentOverflow).toBe(false);
});

test("keyboard navigation reaches the core review flow", async ({ page }) => {
  await page.goto("/");

  await page.getByRole("button", { name: /编辑会话标题：新会话/ }).click();
  const titleInput = page.getByRole("textbox", { name: "编辑会话标题" });
  await titleInput.fill("客单价口径");
  await titleInput.press("Enter");
  await page.keyboard.press("Control+K");
  const conversationSearch = page.getByRole("searchbox", { name: "搜索会话" });
  await expect(conversationSearch).toBeFocused();
  await conversationSearch.fill("客单价");
  const askContext = page.getByRole("complementary", { name: "治理上下文" });
  await expect(askContext.getByRole("button", { name: /客单价口径/ })).toBeVisible();
  await expect(askContext.locator(".context-item")).toHaveCount(1);

  await page.getByRole("button", { name: "系统设置" }).click();
  await page.keyboard.press("Control+K");
  const commandPalette = page.getByRole("dialog", { name: "搜索与命令" });
  await expect(commandPalette).toBeVisible();
  await commandPalette.getByRole("textbox", { name: "搜索资产、变更或功能" }).fill("净收入");
  await page.keyboard.press("Enter");
  await expect(page.getByRole("heading", { name: "净收入" })).toBeVisible();

  const proposalNavigation = page.getByRole("button", { name: "变更与发布" });
  await proposalNavigation.focus();
  await page.keyboard.press("Enter");
  const versionRegistry = page.getByRole("region", { name: "语义资产版本列表" });
  await expect(versionRegistry).toBeVisible();
  await expect(versionRegistry.locator(":scope > *").first()).toHaveClass(/asset-version-toolbar/);
  await expect(versionRegistry.getByRole("heading", { name: "资产版本" })).toHaveCount(0);
  await page.getByRole("button", { name: "查看候选资产版本 客单价 @9" }).click();
  await page.getByRole("button", { name: "审核候选版本 客单价 @9" }).click();

  await expect(page.getByRole("button", { name: "关闭审核" })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog", { name: "审核 客单价 · @9" })).toBeHidden();
});

test("system settings separates LLM inference from Embedding indexing", async ({ page }) => {
  const embeddingWrites: string[] = [];
  page.on("request", request => { if (request.method() === "POST" && request.url().includes("/embedding-index")) embeddingWrites.push(request.url()); });
  await page.setViewportSize({ width: 1024, height: 768 });
  await page.goto("/");
  await page.getByRole("button", { name: "系统设置" }).click();
  const context = page.getByRole("complementary", { name: "治理上下文" });
  await expect(context.getByRole("button", { name: /成员.*24 名成员/ })).toBeVisible();
  await expect(context.getByRole("button", { name: /策略与权限/ })).toHaveCount(0);
  await expect(context.getByRole("button", { name: "搜索资产、变更与功能" })).toHaveCount(0);
  const memberDirectory = page.getByRole("region", { name: "成员目录" });
  await expect(memberDirectory.getByText("EMP-10001")).toBeVisible();
  await expect(memberDirectory.getByText("yue.lin@semlia.example")).toBeHidden();
  await expect(memberDirectory.getByText("Workspace Admin", { exact: true })).toBeVisible();
  await memberDirectory.getByRole("searchbox", { name: "搜索成员" }).fill("许言");
  await expect(memberDirectory.getByText("EMP-10005")).toBeVisible();
  await expect(memberDirectory.getByText("EMP-10001")).toHaveCount(0);
  const clippedMemberElements = await page.locator(".member-directory-toolbar, .member-directory-table, .member-directory-head, .member-directory-row").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedMemberElements).toBe(0);
  await context.getByRole("button", { name: /模型配置/ }).click();

  const configuration = page.getByRole("region", { name: "模型配置" });
  await expect(configuration.getByRole("heading", { name: "模型配置" })).toHaveCount(0);
  await expect(configuration.locator(".model-config-stats")).toHaveCount(0);
  await expect(configuration.getByRole("tab", { name: "LLM 模型" })).toHaveAttribute("aria-selected", "true");
  await expect(configuration.getByRole("combobox", { name: "默认 LLM 模型" })).toHaveValue("mdl_fixture_001");
  await expect(configuration.getByText("gpt-4.1", { exact: true })).toBeVisible();

  await configuration.getByRole("tab", { name: "Embedding 模型" }).click();
  await expect(configuration.getByText("text-embedding-3-large", { exact: true })).toBeVisible();
  await expect(configuration.locator(".embedding-boundary")).toHaveCount(0);
  await expect(configuration.getByRole("button", { name: "重建向量索引" })).toBeVisible();
  await configuration.getByRole("combobox", { name: "默认 Embedding 模型" }).selectOption("mdl_fixture_005");
  await expect(page.getByRole("status")).toContainText("Embedding 默认模型已切换为 bge-m3");
  const persistentIndex = configuration.getByRole("region", { name: "持久向量索引" });
  await expect(persistentIndex.getByRole("alert")).toHaveText("无法读取向量索引状态");
  await expect(persistentIndex.getByRole("button", { name: "重建向量索引" })).toBeDisabled();
  await expect(persistentIndex).not.toContainText("42%");
  await expect(persistentIndex).not.toContainText("RUN-IDX-260901-1132");
  await expect(persistentIndex.getByRole("progressbar")).toHaveCount(0);
  await expect(persistentIndex.getByRole("link", { name: "查看运行" })).toHaveCount(0);

  const internalProvider = configuration.getByRole("region", { name: "内部向量服务 供应商" });
  await internalProvider.getByRole("button", { name: "为 内部向量服务 添加模型" }).click();
  const dialog = page.getByRole("dialog", { name: "添加模型" });
  await dialog.getByLabel("模型 ID").fill("bge-reranker-v2-m3");
  await dialog.getByRole("button", { name: "保存模型" }).click();
  await expect(internalProvider.getByText("bge-reranker-v2-m3")).toBeVisible();

  const clippedModelElements = await page.locator(".model-config-toolbar, .embedding-index-panel, .model-provider-group, .model-provider-row, .model-row").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedModelElements).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)).toBe(false);

  expect(embeddingWrites).toEqual([]);
});

test("interfaces and integrations disclose unavailable fixture operations", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "系统设置" }).click();
  const context = page.getByRole("complementary", { name: "治理上下文" });
  await context.getByRole("button", { name: /接口与集成/ }).click();
  const integrations = page.getByRole("region", { name: "接口与集成" });
  await expect(integrations.getByRole("status")).toHaveText("演示环境未连接集成服务，凭据与投递操作不可用。");
  for (const name of ["创建客户端", "创建机器身份", "登记消费方", "刷新集成设置"]) {
    await expect(integrations.getByRole("button", { name, exact: true })).toBeDisabled();
  }
  const capabilities = integrations.getByRole("region", { name: "接口能力" });
  await expect(capabilities.locator("article")).toHaveCount(4);
  for (const name of ["REST API", "MCP Server", "CLI", "TypeScript SDK"]) {
    await expect(capabilities.getByText(name, { exact: true })).toBeVisible();
    await expect(capabilities.getByRole("button", { name: `复制 ${name} 接入信息`, exact: true })).toBeVisible();
  }
  const restEndpoint = await capabilities.locator("article").filter({ hasText: "REST API" }).locator("code").innerText();
  const mcpEndpoint = await capabilities.locator("article").filter({ hasText: "MCP Server" }).locator("code").innerText();
  expect(new URL(restEndpoint).origin).toBe(new URL(page.url()).origin);
  expect(new URL(restEndpoint).pathname).toMatch(/^\/api\/v1\/workspaces\/[^/]+\/semantic-queries:resolve$/);
  expect(mcpEndpoint).toBe(restEndpoint.replace(/semantic-queries:resolve$/, "mcp"));
  await expect(capabilities.getByText("semlia semantic resolve <query-json>", { exact: true })).toBeVisible();
  await expect(capabilities.getByText("@semlia/sdk-typescript · createSemanticClient", { exact: true })).toBeVisible();
  await expect(integrations.getByText("Fluxale Production", { exact: true })).toHaveCount(0);
  await expect(integrations).not.toContainText("api.semlia.example");
  await expect(integrations.locator(".integration-live-object")).toHaveCount(0);
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await integrations.getByRole("tab", { name: "Webhook 0", exact: true }).click();
  await expect(integrations.getByRole("button", { name: "新增 Webhook", exact: true })).toBeDisabled();
  await expect(integrations.locator(".integration-live-object")).toHaveCount(0);
  const clippedIntegrationElements = await integrations.locator(".integration-commandbar, .integration-channel-grid article, .integration-section-title").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedIntegrationElements).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)).toBe(false);
});

test("audit and runtime unify global execution, traceability and settings", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "系统设置" }).click();
  const context = page.getByRole("complementary", { name: "治理上下文" });
  await context.getByRole("button", { name: /审计与运行/ }).click();

  const fixtureDisclosure = page.getByRole("note", { name: "功能边界" });
  await expect(fixtureDisclosure).toContainText("Prototype 数据环境");
  await expect(fixtureDisclosure).toContainText("不会写入服务端");

  const runtime = page.getByRole("region", { name: "审计与运行" });
  await expect(runtime.getByRole("tab", { name: "运行记录" })).toHaveAttribute("aria-selected", "true");
  const runOverview = runtime.getByRole("region", { name: "运行状态概览" });
  await expect(runOverview).toContainText("当前页服务端记录");
  await expect(runOverview).toContainText("运行中");
  await expect(runOverview).toContainText("排队中");
  await expect(runOverview).not.toContainText("日志投递");
  const runTable = runtime.getByRole("region", { name: "全局运行记录" });
  await expect(runTable.getByText("知识目录向量索引重建", { exact: true })).toBeVisible();
  await runTable.getByRole("button", { name: "查看运行 知识目录向量索引重建" }).click();
  const runDialog = page.getByRole("dialog", { name: "知识目录向量索引重建" });
  await expect(runDialog.getByRole("region", { name: "运行进度" })).toContainText("1,436 / 3,420");
  const runEvents = runDialog.getByRole("log", { name: "全局运行事件" });
  await expect(runEvents).toContainText("服务端记录了批次进度");
  await expect(runEvents).not.toContainText("加载上下文");
  await runDialog.getByRole("button", { name: "关闭", exact: true }).click();

  await runtime.getByRole("tab", { name: "审计日志" }).click();
  const auditFilters = runtime.getByRole("form", { name: "审计事件筛选" });
  await auditFilters.getByRole("textbox", { name: "操作者 ID" }).fill("prn-local-admin");
  await auditFilters.getByRole("button", { name: "应用筛选" }).click();
  const auditTable = runtime.getByRole("region", { name: "审计事件" });
  await expect(auditTable.getByText("runtime.embedding_rebuild.started", { exact: true })).toBeVisible();
  await expect(auditTable.getByText("runtime.discovery.started", { exact: true })).toHaveCount(0);
  await auditTable.getByRole("button", { name: "查看审计事件 runtime.embedding_rebuild.started" }).click();
  const auditDialog = page.getByRole("dialog", { name: "runtime.embedding_rebuild.started" });
  await expect(auditDialog).toContainText("tr_51a90d");
  await expect(auditDialog).toContainText("不可编辑的服务端审计投影");
  await auditDialog.getByRole("button", { name: "关闭", exact: true }).click();
  await auditFilters.getByRole("button", { name: "创建审计导出" }).click();
  const exportStatus = runtime.getByRole("status", { name: "审计导出状态" });
  await expect(exportStatus).toContainText("服务端已创建导出记录");
  await expect(exportStatus).toContainText("不可变导出快照");
  await expect(exportStatus.getByRole("button", { name: "下载 JSON" })).toBeEnabled();

  await runtime.getByRole("tab", { name: "运行设置" }).click();
  await expect(runtime).toContainText("已与服务端版本一致");
  await expect(runtime).toContainText("当前版本 7");
  await runtime.getByRole("spinbutton", { name: "失败重试上限" }).fill("4");
  await runtime.getByRole("button", { name: "保存更改" }).click();
  await expect(runtime).toContainText("当前版本 8");
  await expect(page.getByRole("status")).toContainText("运行设置版本 8 已由服务端确认");
  await expect(runtime.getByRole("region", { name: "部署状态" })).toContainText("部署拥有，只读展示");
  const clippedAuditElements = await page.locator(".audit-runtime-tabs, .audit-runtime-metrics, .operations-filter-panel, .audit-runtime-table, .audit-settings-group, .operations-export-record, .audit-runtime-detail-dialog").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedAuditElements).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)).toBe(false);
});

test("recent asset selection stays spatially stable within a module visit", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "知识资产" }).click();

  const context = page.getByRole("complementary", { name: "治理上下文" });
  const recentNames = () => context.locator(".context-item strong").allTextContents();
  const initialOrder = ["净收入", "订单经营模型", "高价值客户"];

  expect(await recentNames()).toEqual(initialOrder);
  await context.getByRole("button", { name: "打开最近资产 高价值客户" }).click();
  expect(await recentNames()).toEqual(initialOrder);
  await expect(context.getByRole("button", { name: "打开最近资产 高价值客户" })).toHaveAttribute("aria-current", "page");

  await page.getByRole("button", { name: "工作台" }).click();
  await page.getByRole("button", { name: "知识资产" }).click();
  expect(await recentNames()).toEqual(["高价值客户", "净收入", "订单经营模型"]);
});

test("prototype Ask never offers feedback against a fabricated answer", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");

  await expect(page.getByText("Prototype 预览")).toBeVisible();
  await expect(page.getByRole("textbox", { name: "向 Semlia 提问" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "发送问题" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "指出问题" })).toHaveCount(0);
  await expect(page.getByRole("region", { name: "指出回答中的知识问题" })).toHaveCount(0);
});

test("access control remains explainable across supported desktop viewports", async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  await page.getByRole("button", { name: "系统设置" }).click();
  const context = page.getByRole("complementary", { name: "治理上下文" });
  await expect(context.getByRole("button", { name: /访问控制/ })).toBeVisible();
  await context.getByRole("button", { name: /访问控制/ }).click();
  const accessControl = page.getByRole("region", { name: "访问控制" });
  await expect(accessControl.getByRole("button", { name: "查看角色 Workspace Admin" })).toBeVisible();
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-roles.png`), fullPage: true });

  await accessControl.getByRole("button", { name: "查看角色 Reviewer" }).click();
  const roleDialog = page.getByRole("dialog", { name: "Reviewer 角色详情" });
  await expect(roleDialog.getByText("proposal.review", { exact: true })).toBeVisible();
  await expect(roleDialog.getByText("审核语义提案并记录评审结论。", { exact: true })).toBeVisible();
  await expect(roleDialog.getByText("release.publish", { exact: true })).toHaveCount(0);
  await expect(roleDialog.getByRole("button", { name: "编辑角色" })).toHaveCount(0);
  await roleDialog.getByRole("button", { name: "基于此角色创建" }).click();
  const roleEditor = page.getByRole("dialog", { name: "基于 Reviewer 创建角色" });
  await expect(roleEditor.getByRole("checkbox", { name: "配置权限 release.publish" })).toBeVisible();
  await expect(roleEditor.getByText("发布通过治理门禁的候选版本。", { exact: true })).toBeVisible();
  const roleEditorBox = await roleEditor.boundingBox();
  const roleEditorActionBox = await roleEditor.getByRole("button", { name: "预览角色变更" }).boundingBox();
  expect(roleEditorBox).not.toBeNull();
  expect(roleEditorActionBox).not.toBeNull();
  expect((roleEditorBox?.x ?? -1) + (roleEditorBox?.width ?? 0)).toBeLessThanOrEqual(testInfo.project.name === "compact-desktop" ? 1024 : 1440);
  expect((roleEditorActionBox?.y ?? -1) + (roleEditorActionBox?.height ?? 0)).toBeLessThanOrEqual(testInfo.project.name === "compact-desktop" ? 768 : 900);
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-role-editor.png`), fullPage: true });
  await page.keyboard.press("Escape");
  await expect(roleEditor).toBeHidden();

  await accessControl.getByRole("tab", { name: "角色分配" }).click();
  await accessControl.getByRole("button", { name: "分配角色" }).click();
  const assignmentDialog = page.getByRole("dialog", { name: "分配角色" });
  await assignmentDialog.getByRole("button", { name: "预览授权" }).click();
  await expect(assignmentDialog.getByRole("alert")).toContainText("评审者与发布者必须相互独立");
  await expect(assignmentDialog.getByRole("button", { name: "确认分配" })).toBeDisabled();
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-assignment-conflict.png`), fullPage: true });
  await assignmentDialog.getByRole("button", { name: "关闭角色分配" }).click();

  await accessControl.getByRole("tab", { name: "有效权限检查" }).click();
  await accessControl.getByRole("button", { name: "检查有效权限" }).click();
  const decision = accessControl.getByRole("region", { name: "有效权限结果" });
  await expect(decision).toContainText("拒绝");
  await accessControl.getByRole("combobox", { name: "检查主体" }).selectOption("EMP-10001");
  await accessControl.getByRole("button", { name: "检查有效权限" }).click();
  await expect(decision).toContainText("允许");
  await expect(decision).toContainText("Workspace Admin");
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-effective-access.png`), fullPage: true });

  await context.getByRole("button", { name: /成员.*24 名成员/ }).click();
  const members = page.getByRole("region", { name: "成员目录" });
  await expect(members.getByRole("row", { name: /EMP-10001.*语义产品经理.*Workspace Admin/ })).toBeVisible();
  await expect(members.getByText("已停用", { exact: true })).toBeVisible();
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-members.png`), fullPage: true });

  await context.getByRole("button", { name: /接口与集成/ }).click();
  const integrations = page.getByRole("region", { name: "接口与集成" });
  await expect(integrations.getByRole("status")).toHaveText("演示环境未连接集成服务，凭据与投递操作不可用。");
  await expect(integrations.getByRole("button", { name: "创建客户端", exact: true })).toBeDisabled();
  await expect(integrations.getByRole("button", { name: "撤销客户端 Fluxale Production" })).toHaveCount(0);
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-machine-clients.png`), fullPage: true });

  await page.getByRole("button", { name: "变更与发布" }).click();
  await page.getByRole("button", { name: "查看候选资产版本 客单价 @9" }).click();
  await page.getByRole("button", { name: "审核候选版本 客单价 @9" }).click();
  const reviewDialog = page.getByRole("dialog", { name: "审核 客单价 · @9" });
  await expect(reviewDialog.getByText("职责分离由服务端强制")).toBeVisible();
  await expect(reviewDialog.getByRole("button", { name: "批准版本" })).toBeDisabled();
  await reviewDialog.getByRole("textbox", { name: "审核意见" }).fill("口径变化已确认。");
  await reviewDialog.getByRole("button", { name: "批准版本" }).click();
  await expect(page.getByRole("status")).toContainText("评审已记录：批准");
  await page.getByRole("button", { name: "发布 @9" }).click();
  const publishDialog = page.getByRole("dialog", { name: "发布客单价 @9" });
  await expect(publishDialog.getByText("独立发布者由服务端强制")).toBeVisible();
  await expect(publishDialog.getByText("发布者不能是提案作者，也不能是唯一批准评审人（D-006 双人控制）")).toBeVisible();
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-publish-conflict.png`), fullPage: true });

  const clippedElements = await page.locator(".access-control-view, .access-role-table, .assignment-table, .access-inspector-form, .member-directory-table, .integration-client-table, .review-dialog").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedElements).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)).toBe(false);
});

test("governed journey runs author, submit, validation, review, publish and rollback on real flows", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");

  await page.getByRole("button", { name: "知识资产" }).click();
  await page.getByRole("button", { name: "打开语义资产 支付订单数" }).click();
  await page.getByRole("button", { name: "修订知识" }).click();
  await page.getByRole("dialog", { name: "选择知识修订对象" }).getByRole("button", { name: /计算表达式/ }).click();

  const workbench = page.getByRole("region", { name: "支付订单数 知识修订工作台" });
  await expect(workbench.getByText("已发布版本受保护")).toBeVisible();
  const expressionField = workbench.getByRole("textbox", { name: "计算表达式候选值" });
  await expressionField.fill("COUNT_DISTINCT(order_id) FILTER payment_status = 'paid' AND test_order = false");
  await workbench.getByRole("textbox", { name: "知识修订原因" }).fill("把测试订单从支付口径中排除。");
  await workbench.getByRole("button", { name: "运行检查" }).click();
  await expect(workbench.getByText("已就绪")).toBeVisible();
  await workbench.getByRole("button", { name: "提交审核" }).click();

  const candidate = page.getByRole("region", { name: "支付订单数 @6 候选资产版本详情" });
  await expect(candidate).toBeVisible();
  await expect(candidate.getByText("版本范围")).toBeVisible();
  await expect(candidate.getByText("@5 → @6").first()).toBeVisible();
  await expect(candidate.getByText("COUNT_DISTINCT(order_id) FILTER payment_status = 'paid' AND test_order = false")).toBeVisible();
  await expect(candidate.getByText("3/3", { exact: true })).toBeVisible();
  const policyDecision = candidate.getByRole("region", { name: "策略决策" });
  await expect(policyDecision).toBeVisible();
  await expect(policyDecision).toContainText("rule.g1.computation_change");
  await expect(policyDecision).toContainText("专家评审");
  await expect(policyDecision).toContainText("COMPUTATION_CHANGED");

  await page.getByRole("button", { name: "变更与发布", exact: true }).click();
  const candidateRow = page.getByRole("button", { name: "查看候选资产版本 支付订单数 @6" });
  await expect(candidateRow).toContainText("待审核");
  await candidateRow.click();
  await page.getByRole("button", { name: "审核候选版本 支付订单数 @6" }).click();
  const reviewDialog = page.getByRole("dialog", { name: "审核 支付订单数 · @6" });
  await expect(reviewDialog.getByText("structural", { exact: false }).first()).toBeVisible();
  await reviewDialog.getByRole("textbox", { name: "审核意见" }).fill("测试订单排除已与经营组确认。");
  await reviewDialog.getByRole("button", { name: "批准版本" }).click();
  await expect(page.getByRole("status")).toContainText("评审已记录：批准");

  await expect(page.getByRole("button", { name: "发布 @6" })).toBeVisible();
  await page.getByRole("button", { name: "发布 @6" }).click();
  const publishDialog = page.getByRole("dialog", { name: "发布支付订单数 @6" });
  await expect(publishDialog.getByText("独立发布者由服务端强制")).toBeVisible();
  await publishDialog.getByRole("button", { name: "确认发布并生效" }).click();
  const publishedCandidate = page.getByRole("region", { name: "支付订单数 @6 候选资产版本详情" });
  await expect(publishedCandidate).toContainText("已发布");
  await expect(publishedCandidate.getByRole("region", { name: "发布记录" })).toContainText("#7");
  await expect(publishedCandidate.getByRole("region", { name: "发布记录" })).toContainText("rls_fixture_0007");

  await page.getByRole("button", { name: "返回资产版本列表" }).click();
  const releaseRow = page.getByRole("button", { name: "查看发布记录 @6 #7" });
  await expect(releaseRow).toBeVisible();
  await releaseRow.click();
  const releaseDetail = page.getByRole("region", { name: "发布 #7 详情" });
  await expect(releaseDetail).toContainText("当前版本");
  await expect(releaseDetail).toContainText("rls_fixture_0007");
  await expect(releaseDetail.getByRole("button", { name: "回滚此发布" })).toBeEnabled();
  await releaseDetail.getByRole("button", { name: "回滚此发布" }).click();
  await expect(page.locator(".toast")).toContainText("回滚完成：已创建新的不可变发布 #8");

  await page.getByRole("button", { name: "返回资产版本列表" }).click();
  await expect(page.getByRole("button", { name: "查看发布记录 @5 #8" })).toContainText("当前版本");
  await expect(page.getByRole("button", { name: "查看发布记录 @6 #7" })).toContainText("历史版本");
  await page.getByRole("button", { name: "查看发布记录 @6 #7" }).click();
  await expect(page.getByRole("region", { name: "发布 #7 详情" })).toContainText("此发布已被 rls_fixture_0008 回滚");

  await page.getByRole("button", { name: "知识资产" }).click();
  await page.getByRole("button", { name: "打开语义资产 支付订单数" }).click();
  await page.getByRole("tab", { name: "可信度" }).click();
  const governanceEvidence = page.getByRole("region", { name: "提案验证与策略决策" });
  await expect(governanceEvidence).toBeVisible();
  await expect(governanceEvidence).toContainText("structural");
  await expect(governanceEvidence).toContainText("v2026.08.4");
  await expect(governanceEvidence).toContainText("rule.g1.computation_change");
  await expect(governanceEvidence).toContainText("专家评审");
  const clippedGovernanceElements = await page.locator(".release-detail, .candidate-version-detail, .review-batch-surface, .governance-list-surface").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedGovernanceElements).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)).toBe(false);
});
