import type {
  Asset,
  AssetReadinessGate,
  AssetRelation,
  AssetType,
  AssetTypeSpec,
  AssetVersionRelease,
  AuthorizationBinding,
  AuthorizationPrincipal,
  AuthorizationRole,
  CapabilitySession,
  OntologyRelationConstraint,
  PermissionGroup,
  PermissionAction,
  Proposal,
} from "./types";

export const authorizationVersion = "authzv-2026.09.01-001";

export const permissionGroups: PermissionGroup[] = [
  {
    id: "workspace",
    label: "工作区管理",
    description: "成员、角色与授权策略管理",
    actions: ["workspace.read", "workspace.manage", "member.read", "member.manage", "group.manage", "role.read", "role.manage", "role.assign", "authorization.inspect"],
  },
  {
    id: "governance",
    label: "语义治理",
    description: "资产、证据、提案和验证",
    actions: ["asset.read", "asset.propose", "asset.edit", "evidence.read", "proposal.review", "validation.run"],
  },
  {
    id: "release",
    label: "发布管理",
    description: "受保护版本的发布与回滚",
    actions: ["release.publish", "release.rollback"],
  },
  {
    id: "data",
    label: "数据接入",
    description: "来源、摄取和物理绑定",
    actions: ["source.read", "source.manage", "ingestion.run", "binding.read", "binding.manage"],
  },
  {
    id: "runtime",
    label: "消费与运行",
    description: "语义解析、查询、审计和运行时",
    actions: ["semantic.resolve", "semantic.execute", "audit.read", "runtime.read", "runtime.manage"],
  },
];

export const permissionDescriptions: Record<PermissionAction, string> = {
  "workspace.read": "查看工作区基本信息和治理配置摘要。",
  "workspace.manage": "修改工作区级配置和全局治理参数。",
  "member.read": "查看成员、用户组和授权状态。",
  "member.manage": "邀请、停用成员并维护成员资料。",
  "group.manage": "创建用户组并维护组成员关系。",
  "role.read": "查看系统角色、自定义角色和权限定义。",
  "role.manage": "创建、修改或停用自定义角色。",
  "role.assign": "为主体分配或撤销范围化角色。",
  "authorization.inspect": "检查主体对指定资源的最终有效权限。",
  "asset.read": "查看语义资产、定义、关系和版本信息。",
  "asset.propose": "为语义资产创建结构化变更提案。",
  "asset.edit": "编辑语义资产草稿和待发布定义。",
  "evidence.read": "查看资产证据、来源和验证引用。",
  "proposal.review": "审核语义提案并记录评审结论。",
  "validation.run": "运行语义、引用、SQL 和策略验证。",
  "release.publish": "发布通过治理门禁的候选版本。",
  "release.rollback": "将环境恢复到上一稳定发布版本。",
  "source.read": "查看数据来源、连接状态和元数据快照。",
  "source.manage": "创建、修改、轮换或停用数据来源。",
  "ingestion.run": "启动数据接入、扫描和增量同步任务。",
  "binding.read": "查看物理绑定、粒度和 JoinContract。",
  "binding.manage": "创建或修改资产的物理绑定关系。",
  "semantic.resolve": "将业务语义请求解析为已发布资产和计划。",
  "semantic.execute": "执行经过验证且受发布约束的语义计划。",
  "audit.read": "查看不可变审计事件和授权操作记录。",
  "runtime.read": "查看运行记录、阶段、日志和诊断信息。",
  "runtime.manage": "管理运行队列、重试和运行时配置。",
};

export const authorizationPrincipals: AuthorizationPrincipal[] = [
  { id: "EMP-10001", kind: "user", name: "林悦", detail: "平台治理负责人", status: "active" },
  { id: "USR-REVIEWER", kind: "user", name: "陈默", detail: "收入域语义评审", status: "active" },
  { id: "USR-PUBLISHER", kind: "user", name: "周岚", detail: "生产发布负责人", status: "active" },
  { id: "USR-AUDITOR", kind: "user", name: "顾言", detail: "内控审计", status: "active" },
  { id: "GRP-COMMERCE", kind: "group", name: "收入域治理组", detail: "8 名成员", status: "active" },
  { id: "SVC-INGESTION", kind: "service_account", name: "生产摄取服务", detail: "数据接入自动化", status: "active" },
  { id: "CLI-CUBE", kind: "api_client", name: "Cube Production", detail: "语义查询客户端", status: "active" },
  { id: "AGENT-GOVERNANCE", kind: "agent", name: "治理建议 Agent", detail: "只读建议模式", status: "active" },
];

export const authorizationRoles: AuthorizationRole[] = [
  {
    id: "ROLE-WORKSPACE-ADMIN",
    name: "Workspace Admin",
    description: "管理工作区、成员、角色和全部治理配置。",
    category: "system",
    permissions: permissionGroups.flatMap((group) => group.actions),
  },
  {
    id: "ROLE-SECURITY-ADMIN",
    name: "Security Admin",
    description: "管理成员授权并检查有效权限，不参与业务发布。",
    category: "system",
    permissions: ["workspace.read", "member.read", "member.manage", "group.manage", "role.read", "role.manage", "role.assign", "authorization.inspect", "audit.read"],
  },
  {
    id: "ROLE-SEMANTIC-STEWARD",
    name: "Semantic Steward",
    description: "维护语义资产、证据、物理绑定和验证结果。",
    category: "system",
    permissions: ["workspace.read", "asset.read", "asset.propose", "asset.edit", "evidence.read", "validation.run", "binding.read", "binding.manage"],
  },
  {
    id: "ROLE-ASSET-OWNER",
    name: "Asset Owner",
    description: "对指定资产承担业务责任并发起变更。",
    category: "system",
    permissions: ["workspace.read", "asset.read", "asset.propose", "asset.edit", "evidence.read", "validation.run"],
  },
  {
    id: "ROLE-REVIEWER",
    name: "Reviewer",
    description: "独立评审语义变更，不执行同范围生产发布。",
    category: "system",
    permissions: ["workspace.read", "asset.read", "evidence.read", "proposal.review", "validation.run", "audit.read"],
    incompatibleRoleIds: ["ROLE-PUBLISHER"],
  },
  {
    id: "ROLE-PUBLISHER",
    name: "Publisher",
    description: "发布或回滚已通过独立评审的受保护版本。",
    category: "system",
    permissions: ["workspace.read", "asset.read", "evidence.read", "release.publish", "release.rollback", "audit.read"],
    incompatibleRoleIds: ["ROLE-REVIEWER"],
  },
  {
    id: "ROLE-SOURCE-OPERATOR",
    name: "Source Operator",
    description: "管理数据来源、摄取任务和物理绑定。",
    category: "system",
    permissions: ["workspace.read", "source.read", "source.manage", "ingestion.run", "binding.read", "binding.manage", "runtime.read"],
  },
  {
    id: "ROLE-CONSUMER-DEVELOPER",
    name: "Consumer Developer",
    description: "读取已发布语义并执行面向消费端的查询。",
    category: "system",
    permissions: ["workspace.read", "asset.read", "evidence.read", "semantic.resolve", "semantic.execute", "runtime.read"],
  },
  {
    id: "ROLE-AUDITOR",
    name: "Auditor",
    description: "只读检查资产、授权、审计与运行记录。",
    category: "system",
    permissions: ["workspace.read", "member.read", "role.read", "authorization.inspect", "asset.read", "evidence.read", "source.read", "binding.read", "audit.read", "runtime.read"],
  },
];

export const authorizationBindings: AuthorizationBinding[] = [
  {
    id: "BIND-WORKSPACE-ADMIN",
    principalId: "EMP-10001",
    roleId: "ROLE-WORKSPACE-ADMIN",
    scope: { type: "workspace", id: "WS-SEMLIA", label: "Semlia 工作区" },
    assignedBy: "系统初始化",
    assignedAt: "2026-08-18 09:30",
    status: "active",
  },
  {
    id: "BIND-REVIEWER-COMMERCE",
    principalId: "USR-REVIEWER",
    roleId: "ROLE-REVIEWER",
    scope: { type: "domain", id: "commerce", label: "收入域", protected: true },
    assignedBy: "林悦",
    assignedAt: "2026-08-22 14:10",
    status: "active",
  },
  {
    id: "BIND-PUBLISHER-PROD",
    principalId: "USR-PUBLISHER",
    roleId: "ROLE-PUBLISHER",
    scope: { type: "environment", id: "production", label: "生产环境", protected: true },
    assignedBy: "林悦",
    assignedAt: "2026-08-22 14:18",
    status: "active",
  },
  {
    id: "BIND-AUDITOR",
    principalId: "USR-AUDITOR",
    roleId: "ROLE-AUDITOR",
    scope: { type: "workspace", id: "WS-SEMLIA", label: "Semlia 工作区" },
    assignedBy: "林悦",
    assignedAt: "2026-08-25 11:05",
    expiresAt: "2026-12-31",
    status: "active",
  },
  {
    id: "BIND-SOURCE-OPERATOR",
    principalId: "SVC-INGESTION",
    roleId: "ROLE-SOURCE-OPERATOR",
    scope: { type: "source", id: "SRC-PROD-WAREHOUSE", label: "生产数仓" },
    assignedBy: "林悦",
    assignedAt: "2026-08-28 16:40",
    status: "active",
  },
  {
    id: "BIND-CUBE-CONSUMER",
    principalId: "CLI-CUBE",
    roleId: "ROLE-CONSUMER-DEVELOPER",
    scope: { type: "domain", id: "commerce", label: "收入域" },
    assignedBy: "林悦",
    assignedAt: "2026-08-29 10:12",
    expiresAt: "2027-02-28",
    status: "active",
  },
];

export const authorizationSession: CapabilitySession = {
  principalId: "EMP-10001",
  version: authorizationVersion,
  capabilities: authorizationRoles.find((role) => role.id === "ROLE-WORKSPACE-ADMIN")?.permissions ?? [],
};

const readinessLabels: Record<AssetReadinessGate["id"], string> = {
  identity: "稳定身份",
  ownership: "责任归属",
  definition: "语义定义",
  relations: "关系完整",
  mapping: "物理映射",
  evidence: "证据覆盖",
  validation: "验证通过",
  compatibility: "消费兼容",
};

const readinessDetails: Record<AssetReadinessGate["id"], string> = {
  identity: "稳定 ID、key、类型和语义域有效",
  ownership: "业务 owner 与实现维护人已确认",
  definition: "定义、边界和类型专属字段完整",
  relations: "必要依赖和语义关系均已解析",
  mapping: "绑定、粒度与 JoinContract 已验证",
  evidence: "发布字段具备满足策略的权威证据",
  validation: "引用、编译、结果与策略检查通过",
  compatibility: "已识别消费者且没有阻断性影响",
};

function readiness(overrides: Partial<Record<AssetReadinessGate["id"], Pick<AssetReadinessGate, "state" | "detail">>> = {}): AssetReadinessGate[] {
  return (Object.keys(readinessLabels) as AssetReadinessGate["id"][]).map((id) => ({
    id,
    label: readinessLabels[id],
    state: overrides[id]?.state ?? "passed",
    detail: overrides[id]?.detail ?? readinessDetails[id],
  }));
}

type AssetSeed = Omit<Asset, "identity" | "revisionRecord" | "deployment" | "qualitySnapshot" | "claims" | "evidenceArtifacts" | "evidenceLinks" | "validationRuns" | "consumerBindings" | "wikiContext" | "ontologyContext">;

const relationNames: Record<AssetRelation["type"], [string, string]> = {
  measures: ["衡量", "被衡量"],
  describes: ["描述", "被描述"],
  depends_on: ["依赖", "被依赖"],
  derived_from: ["派生自", "派生出"],
  filters_by: ["按其筛选", "筛选"],
  synonym_of: ["同义于", "同义于"],
  contains: ["包含", "属于"],
};

const ontologyRevisions: Record<string, string> = {
  commerce: "7",
  customer: "5",
  shared: "4",
};

function ontologyRelationConstraint(type: AssetRelation["type"], sourceType: AssetType): OntologyRelationConstraint {
  const [label, inverseLabel] = relationNames[type];
  const targetTypes: Record<AssetRelation["type"], AssetType[]> = {
    measures: ["业务实体", "语义模型"],
    describes: ["业务实体", "语义模型", "业务概念"],
    depends_on: ["指标", "度量", "维度", "语义模型"],
    derived_from: ["指标", "度量", "语义模型"],
    filters_by: ["维度", "业务实体"],
    synonym_of: [sourceType],
    contains: ["指标", "度量", "维度", "业务概念"],
  };
  return {
    relationType: type,
    label,
    inverseLabel,
    sourceTypes: [sourceType],
    targetTypes: targetTypes[type],
    cardinality: type === "synonym_of" ? "one_to_one" : type === "contains" ? "one_to_many" : "many_to_many",
    reasoning: type === "synonym_of" ? "symmetric" : "directed",
  };
}

function ontologyParentConcepts(type: AssetType) {
  if (type === "指标") return ["业务衡量", "经营结果"];
  if (type === "度量") return ["可聚合事实"];
  if (type === "维度") return ["业务描述属性"];
  if (type === "业务实体") return ["可识别业务对象"];
  if (type === "语义模型") return ["可查询业务模型"];
  if (type === "分群") return ["业务判定规则"];
  return ["业务概念"];
}

function typeSpec(seed: AssetSeed): AssetTypeSpec {
  const base = {
    expression: seed.formula,
    grain: seed.grain,
    defaultTime: seed.defaultTime,
    unit: seed.unit,
    aggregation: seed.aggregation,
  };

  if (seed.type === "指标") {
    const metricKind = seed.formula.includes("/") ? "ratio" : seed.formula.includes("30") ? "cumulative" : "simple";
    return { ...base, kind: "metric", metricKind, allowedDimensions: seed.grain.split("·").map((item) => item.trim()), comparisonSemantics: "比较必须使用相同时间窗口、日历与维度范围" };
  }
  if (seed.type === "度量") return { ...base, kind: "measure", additivity: seed.aggregation.includes("不可") ? "non_additive" : "additive", nullHandling: "空值不贡献聚合结果" };
  if (seed.type === "维度") return { ...base, kind: "dimension", valueType: seed.unit, nullSemantics: "未知值保留为显式未解析成员", hierarchy: seed.includes };
  if (seed.type === "业务实体") return { ...base, kind: "entity", entityKeys: [seed.formula], identityPolicy: "稳定主身份优先，合并记录保留来源引用", lifecycle: "创建、识别、合并与停用均可追溯" };
  if (seed.type === "语义模型") return { ...base, kind: "model", primaryEntity: seed.grain, publicMembers: seed.includes, joinPathPolicy: "只允许已发布 JoinContract 路径" };
  if (seed.type === "分群") return { ...base, kind: "segment", baseEntity: seed.grain, refreshPolicy: seed.defaultTime, effectiveTime: "按快照时间生效，不回写历史成员资格" };
  return { ...base, kind: "concept", conceptClass: seed.domain, disambiguationRule: "优先使用当前语义域定义，跨域同名时要求澄清" };
}

function claimFieldPath(kind: string) {
  if (kind === "Owner attestation") return "definition.boundary";
  if (kind === "Usage signal") return "usage.compatibility";
  if (kind === "Query regression") return "validation.result_regression";
  if (kind === "Schema check") return "implementation.binding";
  return "spec.expression";
}

function projectAsset(seed: AssetSeed): Asset {
  const sequence = Number(seed.revision.match(/\d+/)?.[0] ?? 0);
  const warningCount = seed.readiness.filter((gate) => gate.state === "warning").length;
  const blockingCount = seed.validations.filter((validation) => validation.state === "failed").length;
  const revisionId = `${seed.id}${seed.revision}`;
  const claims = seed.evidence.map((evidence, index) => ({
    claimId: `CLM-${seed.id.slice(-6)}-${index + 1}`,
    assetRevisionId: revisionId,
    fieldPath: claimFieldPath(evidence.kind),
    label: evidence.supports,
    value: evidence.label,
  }));

  return {
    ...seed,
    identity: {
      workspaceId: "workspace_semlia_analytics",
      assetId: seed.id,
      namespace: seed.namespace,
      key: seed.key,
      type: seed.type,
      domain: seed.domain,
      lifecycleState: "active",
    },
    revisionRecord: {
      revisionId,
      assetId: seed.id,
      sequence,
      schemaVersion: "semlia.semantic-asset/v1alpha1",
      contentHash: `sha256:${`${seed.id}${sequence}`.replace(/[^a-zA-Z0-9]/g, "").toLowerCase().padEnd(64, "0").slice(0, 64)}`,
      recordedAt: seed.updatedAt,
      validFrom: seed.status === "已发布" ? "2026-08-01" : "待发布后确定",
      workflowState: seed.status === "已发布" ? "released" : seed.status === "草稿" ? "draft" : "in_review",
      name: seed.name,
      aliases: seed.aliases,
      definition: seed.definition,
      includes: seed.includes,
      excludes: seed.excludes,
      examples: seed.examples,
      typeSpec: typeSpec(seed),
    },
    deployment: {
      environment: seed.release === "尚未发布" ? "staging" : "production",
      state: seed.release === "尚未发布" ? "unreleased" : "production",
      releaseId: seed.release === "尚未发布" ? undefined : seed.release,
      revisionId: seed.release === "尚未发布" ? undefined : revisionId,
      deployedAt: seed.release === "尚未发布" ? undefined : seed.updatedAt,
    },
    qualitySnapshot: {
      snapshotId: `QSN-${seed.id.slice(-8)}-${sequence}`,
      state: blockingCount > 0 ? "blocked" : warningCount > 0 ? "warning" : "healthy",
      policyVersion: "policy-2026.08.4",
      evaluatedAt: seed.validations[0] ? seed.updatedAt : "尚未评估",
      blockingCount,
      warningCount,
    },
    claims,
    evidenceArtifacts: seed.evidence.map((evidence) => ({
      evidenceId: evidence.id,
      sourceRevision: evidence.source,
      authority: evidence.authority,
      observedAt: evidence.verifiedAt,
      scope: evidence.supports,
      digest: `sha256:${evidence.id.toLowerCase().replace(/[^a-z0-9]/g, "").padEnd(64, "0").slice(0, 64)}`,
    })),
    evidenceLinks: claims.map((claim, index) => ({ claimId: claim.claimId, evidenceId: seed.evidence[index].id, polarity: "supports", strength: seed.evidence[index].authority === "DECLARED" || seed.evidence[index].authority === "CONSTRAINED" ? "primary" : "corroborating" })),
    validationRuns: seed.validations.map((validation, index) => ({
      runId: `VALRUN-${seed.id.slice(-6)}-${index + 1}`,
      validationSpecId: `VALSPEC-${validation.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
      validatorVersion: "2026.08.4",
      assetRevisionId: revisionId,
      executedAt: seed.updatedAt,
      state: validation.state,
      reproducible: true,
    })),
    consumerBindings: seed.consumers.map((consumer, index) => ({
      bindingId: `CB-${seed.id.slice(-6)}-${index + 1}`,
      consumerId: `consumer:${consumer.name.toLowerCase().replace(/\s+/g, "-")}`,
      assetId: seed.id,
      environment: "production",
      versionConstraint: consumer.binding,
      resolvedRevisionId: revisionId,
      compatibility: warningCount > 0 ? "conditional" : seed.status === "已发布" ? "compatible" : "not_evaluated",
    })),
    wikiContext: {
      contextId: `WIKI-${seed.id.slice(-8)}-${sequence}`,
      assetRevisionId: revisionId,
      canonicalSummary: seed.definition,
      retrievalTerms: Array.from(new Set([seed.name, ...seed.aliases, seed.key, seed.domain])),
      disambiguationRules: [
        `${seed.name}默认按${seed.defaultTime || "资产声明的有效时间"}解释。`,
        `跨语义域出现同名含义时，必须先确认${seed.domain}语义域。`,
      ],
      groundedQuestions: seed.examples,
      compiledAt: seed.updatedAt,
    },
    ontologyContext: {
      ontologyId: `ontology:${seed.namespace}`,
      revisionId: `ontology:${seed.namespace}@${ontologyRevisions[seed.namespace] ?? "1"}`,
      domainPath: ["企业语义", "经营分析", seed.domain],
      assetId: seed.id,
      parentConcepts: ontologyParentConcepts(seed.type),
      relatedConcepts: Array.from(new Set(seed.relations.map((relation) => relation.targetName))),
      relationConstraints: Array.from(new Set(seed.relations.map((relation) => relation.type))).map((type) => ontologyRelationConstraint(type, seed.type)),
      consistencyState: seed.readiness.find((gate) => gate.id === "relations")?.state === "warning" ? "warning" : "consistent",
      publishedIn: seed.release === "尚未发布" ? undefined : seed.release,
    },
  };
}

const assetSeeds: AssetSeed[] = [
  {
    id: "metric_01J4NETREVENUE8W4Q9D7K2",
    revision: "@12",
    namespace: "commerce",
    key: "commerce.net_revenue",
    name: "净收入",
    aliases: ["确认收入", "Net Revenue"],
    type: "指标",
    status: "已发布",
    owner: "收入分析组",
    maintainer: "语义平台组",
    domain: "电商经营",
    definition: "支付成功订单扣除退款、折扣与税费后的确认收入，按结算日归属。",
    formula: "SUM(paid_amount - refund_amount - discount_amount - tax_amount)",
    grain: "订单 · 结算日 · 业务区域",
    defaultTime: "结算日 settlement_date",
    unit: "CNY · 货币",
    aggregation: "SUM · 可跨区域与时间加总",
    source: "Cube / commerce.orders",
    updatedAt: "今天 09:42",
    release: "release-2026.08.3",
    tags: ["P0 指标", "财务口径", "生产"],
    includes: ["支付成功且未被撤销的订单", "结算期内确认的退款冲减", "订单级折扣与税费"],
    excludes: ["测试订单", "内部采购订单", "尚未结算的预授权金额"],
    examples: ["华东区 8 月净收入", "本月净收入同比"],
    readiness: readiness(),
    relations: [
      { id: "REL-201", type: "depends_on", targetId: "measure_01J4PAIDORDERS5X8D2N6R", targetName: "支付订单数", direction: "outgoing", evidence: "EVD-2041", release: "release-2026.08.3" },
      { id: "REL-202", type: "describes", targetId: "model_01J4ORDERS7K8M2Q5N9P", targetName: "订单经营模型", direction: "outgoing", evidence: "EVD-2041", release: "release-2026.08.3" },
    ],
    bindings: [
      { id: "BIND-NET-REV-12", sourceRevision: "src-ecommerce@9f2e8a", dataset: "analytics.orders", expression: "paid_amount - refund_amount - discount_amount - tax_amount", grain: "order_id, settlement_date, business_region", defaultTime: "settlement_date", adapter: "cube-commerce", state: "已验证" },
    ],
    joinContracts: [
      { id: "JOIN-ORDERS-REGION-04", target: "共享维度 / 业务区域", keys: "orders.fulfillment_org_id = dim_region.org_id", cardinality: "many_to_one", grainImpact: "保持订单粒度", guardrail: "dim_region.org_id 必须唯一；禁止双向扩散", state: "已发布" },
    ],
    validations: [
      { name: "Schema references", state: "passed", detail: "4 个字段引用均解析到固定来源 revision" },
      { name: "Cube compile", state: "passed", detail: "commerce 模型编译通过 · 4.8s" },
      { name: "Result regression", state: "passed", detail: "近 90 天 48/48 组回归样本通过" },
      { name: "Consumer impact", state: "passed", detail: "2 个消费者兼容当前 release" },
    ],
    evidence: [
      { id: "EVD-2041", kind: "Cube compile", label: "Cube schema 编译通过", source: "models/commerce/orders.yml:48", verifiedAt: "今天 09:41", authority: "DERIVED", supports: "计算表达式、物理绑定", state: "已验证" },
      { id: "EVD-2038", kind: "Owner attestation", label: "收入分析组确认口径", source: "Review RVW-882", verifiedAt: "昨天 17:22", authority: "DECLARED", supports: "业务定义、包含与排除规则", state: "已验证" },
      { id: "EVD-2027", kind: "Usage signal", label: "过去 30 天 1,284 次可信解析", source: "Resolution telemetry", verifiedAt: "今天 08:00", authority: "OBSERVED", supports: "消费稳定性", state: "已验证" },
    ],
    upstream: ["支付订单", "退款金额", "折扣金额", "税费"],
    downstream: ["客单价", "区域收入达成率", "收入预测"],
    consumers: [
      { name: "Fluxale Production", kind: "BI Agent", binding: "release-2026.08.3", lastResolved: "2 分钟前" },
      { name: "经营日报", kind: "Dashboard", binding: "^2026.08", lastResolved: "18 分钟前" },
    ],
  },
  {
    id: "metric_01J4AOV8C6MW3B7K9P2D",
    revision: "@8",
    namespace: "commerce",
    key: "commerce.average_order_value",
    name: "客单价",
    aliases: ["AOV", "平均订单价值"],
    type: "指标",
    status: "需关注",
    owner: "增长分析组",
    maintainer: "语义平台组",
    domain: "电商经营",
    definition: "净收入除以支付成功且未完全退款的订单数。",
    formula: "net_revenue / paid_order_count",
    grain: "结算日 · 业务区域",
    defaultTime: "结算日 settlement_date",
    unit: "CNY / 订单",
    aggregation: "比率 · 禁止直接加总",
    source: "Cube / commerce.orders",
    updatedAt: "昨天 16:08",
    release: "release-2026.08.3",
    tags: ["增长指标", "存在变更事项"],
    includes: ["支付成功且未完全退款订单"],
    excludes: ["全额退款订单", "测试订单"],
    examples: ["各业务区域本月客单价"],
    readiness: readiness({ validation: { state: "warning", detail: "西南区域回归样本变化 +1.8%，等待 owner 判断" }, compatibility: { state: "warning", detail: "Fluxale Production 需要确认口径变化" } }),
    relations: [
      { id: "REL-211", type: "depends_on", targetId: "metric_01J4NETREVENUE8W4Q9D7K2", targetName: "净收入", direction: "outgoing", evidence: "EVD-1981", release: "release-2026.08.3" },
      { id: "REL-212", type: "depends_on", targetId: "measure_01J4PAIDORDERS5X8D2N6R", targetName: "支付订单数", direction: "outgoing", evidence: "EVD-1981", release: "release-2026.08.3" },
    ],
    bindings: [
      { id: "BIND-AOV-08", sourceRevision: "src-ecommerce@9f2e8a", dataset: "analytics.orders", expression: "net_revenue / NULLIF(paid_order_count, 0)", grain: "settlement_date, business_region", defaultTime: "settlement_date", adapter: "cube-commerce", state: "已验证" },
    ],
    joinContracts: [],
    validations: [
      { name: "Schema references", state: "passed", detail: "2 个资产引用均已发布" },
      { name: "Result regression", state: "warning", detail: "近 90 天回归样本通过 47/48" },
      { name: "Consumer impact", state: "warning", detail: "1 个消费者等待确认" },
    ],
    evidence: [
      { id: "EVD-1981", kind: "Query regression", label: "近 90 天回归样本通过 47/48", source: "Validation VAL-610", verifiedAt: "昨天 16:02", authority: "OBSERVED", supports: "结果一致性", state: "需确认" },
    ],
    upstream: ["净收入", "支付订单数"],
    downstream: ["区域经营评分", "渠道质量"],
    consumers: [{ name: "Fluxale Production", kind: "BI Agent", binding: "release-2026.08.3", lastResolved: "7 分钟前" }],
  },
  {
    id: "metric_01J4ACTIVE9Q2K8T5M7C3",
    revision: "@6",
    namespace: "customer",
    key: "customer.active_customers_30d",
    name: "活跃客户",
    aliases: ["30 日活跃客户"],
    type: "指标",
    status: "已发布",
    owner: "客户洞察组",
    maintainer: "客户数据组",
    domain: "客户增长",
    definition: "最近 30 天内至少完成一次有效支付的去重客户数。",
    formula: "COUNT_DISTINCT(customer_id) FILTER paid_at >= now() - 30d",
    grain: "自然日 · 客户区域",
    defaultTime: "自然日 calendar_date",
    unit: "人",
    aggregation: "COUNT DISTINCT · 不可跨窗口直接加总",
    source: "Cube / customer.activity",
    updatedAt: "2 天前",
    release: "release-2026.08.2",
    tags: ["客户指标", "滚动窗口"],
    includes: ["30 天内存在有效支付的客户"],
    excludes: ["内部测试账户", "被合并的重复客户"],
    examples: ["今日 30 日活跃客户数"],
    readiness: readiness(),
    relations: [
      { id: "REL-221", type: "measures", targetId: "entity_01J4CUSTOMER6X2D9K8P4Q", targetName: "客户", direction: "outgoing", evidence: "EVD-1902", release: "release-2026.08.2" },
      { id: "REL-222", type: "depends_on", targetId: "model_01J4ORDERS7K8M2Q5N9P", targetName: "订单经营模型", direction: "outgoing", evidence: "EVD-1902", release: "release-2026.08.2" },
    ],
    bindings: [
      { id: "BIND-ACTIVE-CUSTOMER-06", sourceRevision: "src-customer@71ac03", dataset: "analytics.customer_activity", expression: "COUNT(DISTINCT customer_id) FILTER paid_at >= current_date - 30", grain: "calendar_date, customer_region", defaultTime: "calendar_date", adapter: "warehouse-sql", state: "已验证" },
    ],
    joinContracts: [],
    validations: [{ name: "Schema references", state: "passed", detail: "字段、实体键与时间引用完整" }],
    evidence: [{ id: "EVD-1902", kind: "Schema check", label: "字段与引用完整", source: "Validation VAL-602", verifiedAt: "2 天前", authority: "CONSTRAINED", supports: "实体键、时间字段", state: "已验证" }],
    upstream: ["客户", "支付订单"],
    downstream: ["客户留存率", "客户分层"],
    consumers: [{ name: "客户运营助手", kind: "MCP Agent", binding: "release-2026.08.2", lastResolved: "1 小时前" }],
  },
  {
    id: "measure_01J4PAIDORDERS5X8D2N6R",
    revision: "@5",
    namespace: "commerce",
    key: "commerce.paid_order_count",
    name: "支付订单数",
    aliases: ["Paid Orders"],
    type: "度量",
    status: "已发布",
    owner: "收入分析组",
    maintainer: "数据建模组",
    domain: "电商经营",
    definition: "支付状态成功且未被撤销的去重订单数量。",
    formula: "COUNT_DISTINCT(order_id) FILTER payment_status = 'paid'",
    grain: "订单 · 支付日",
    defaultTime: "支付日 paid_at",
    unit: "单",
    aggregation: "COUNT DISTINCT",
    source: "Cube / commerce.orders",
    updatedAt: "3 天前",
    release: "release-2026.08.1",
    tags: ["基础度量", "高复用"],
    includes: ["支付成功订单"],
    excludes: ["支付撤销订单", "测试订单"],
    examples: ["昨日支付订单数"],
    readiness: readiness(),
    relations: [{ id: "REL-231", type: "measures", targetId: "model_01J4ORDERS7K8M2Q5N9P", targetName: "订单经营模型", direction: "outgoing", evidence: "EVD-1864", release: "release-2026.08.1" }],
    bindings: [{ id: "BIND-PAID-ORDERS-05", sourceRevision: "src-ecommerce@2bc018", dataset: "analytics.orders", expression: "COUNT(DISTINCT order_id) FILTER payment_status = 'paid'", grain: "order_id, paid_at", defaultTime: "paid_at", adapter: "cube-commerce", state: "已验证" }],
    joinContracts: [],
    validations: [{ name: "Cube compile", state: "passed", detail: "基础度量编译与 dry-run 通过" }],
    evidence: [{ id: "EVD-1864", kind: "Cube compile", label: "基础度量编译通过", source: "models/commerce/orders.yml:22", verifiedAt: "3 天前", authority: "DERIVED", supports: "表达式、过滤规则", state: "已验证" }],
    upstream: ["订单", "支付状态"],
    downstream: ["客单价", "支付转化率"],
    consumers: [],
  },
  {
    id: "dimension_01J4REGION3X7Q8K2M5V",
    revision: "@3-draft",
    namespace: "shared",
    key: "shared.business_region",
    name: "业务区域",
    aliases: ["经营区域", "Business Region"],
    type: "维度",
    status: "草稿",
    owner: "待指定",
    maintainer: "数据平台组",
    domain: "共享维度",
    definition: "基于履约组织映射的华东、华北、华南、西南业务区域。",
    formula: "region_mapping.fulfillment_region",
    grain: "履约组织",
    defaultTime: "不适用",
    unit: "枚举",
    aggregation: "不适用",
    source: "Warehouse / dim_region",
    updatedAt: "4 天前",
    release: "尚未发布",
    tags: ["共享维度", "待补 owner"],
    includes: ["华东、华北、华南、西南"],
    excludes: ["海外区域仍保持未解析"],
    examples: ["按业务区域分组净收入"],
    readiness: readiness({ ownership: { state: "warning", detail: "尚未指定业务 owner" }, relations: { state: "warning", detail: "海外区域与组织层级存在 2 项未解析关系" }, evidence: { state: "warning", detail: "只有物理映射证据，缺少业务声明" }, validation: { state: "warning", detail: "唯一性验证等待修复" }, compatibility: { state: "not_applicable", detail: "草稿尚未进入消费兼容检查" } }),
    relations: [{ id: "REL-241", type: "describes", targetId: "entity_fulfillment_org", targetName: "履约组织", direction: "outgoing", evidence: "src-ecommerce@f08ae3", release: "draft" }],
    bindings: [{ id: "BIND-BUSINESS-REGION-03", sourceRevision: "src-ecommerce@f08ae3", dataset: "analytics.dim_region", expression: "fulfillment_region", grain: "fulfillment_org_id", defaultTime: "", adapter: "warehouse-sql", state: "需重验" }],
    joinContracts: [{ id: "JOIN-REGION-ORG-DRAFT", target: "履约组织", keys: "dim_region.org_id = fulfillment_org.id", cardinality: "one_to_one", grainImpact: "预期保持组织粒度", guardrail: "唯一性检查未通过", state: "需关注" }],
    validations: [{ name: "Schema references", state: "passed", detail: "字段引用有效" }, { name: "Result regression", state: "warning", detail: "发现 3 个重复组织映射" }],
    evidence: [{ id: "EVD-1803", kind: "Schema check", label: "字段类型与值域已发现", source: "analytics.dim_region@f08ae3", verifiedAt: "4 天前", authority: "DERIVED", supports: "物理绑定、值域候选", state: "需确认" }],
    upstream: ["履约组织"],
    downstream: ["净收入", "客单价", "活跃客户"],
    consumers: [],
  },
  {
    id: "entity_01J4CUSTOMER6X2D9K8P4Q",
    revision: "@9",
    namespace: "customer",
    key: "customer.customer",
    name: "客户",
    aliases: ["会员", "Customer"],
    type: "业务实体",
    status: "已发布",
    owner: "客户运营部",
    maintainer: "客户数据组",
    domain: "客户增长",
    definition: "与企业发生可识别业务关系、拥有稳定主身份的个人或组织。",
    formula: "entity_key(customer_master_id)",
    grain: "一个主客户身份",
    defaultTime: "首次识别时间 first_seen_at",
    unit: "客户",
    aggregation: "不适用",
    source: "Warehouse / dim_customer",
    updatedAt: "昨天 11:20",
    release: "release-2026.08.3",
    tags: ["核心实体", "主数据"],
    includes: ["完成身份合并的个人客户", "企业账户"],
    excludes: ["匿名浏览会话", "内部测试账户"],
    examples: ["客户 360", "客户生命周期"],
    readiness: readiness(),
    relations: [{ id: "REL-251", type: "contains", targetId: "dimension_customer_region", targetName: "客户区域", direction: "outgoing", evidence: "EVD-2102", release: "release-2026.08.3" }],
    bindings: [{ id: "BIND-CUSTOMER-09", sourceRevision: "src-customer@71ac03", dataset: "analytics.dim_customer", expression: "customer_master_id", grain: "customer_master_id", defaultTime: "first_seen_at", adapter: "warehouse-sql", state: "已验证" }],
    joinContracts: [{ id: "JOIN-CUSTOMER-ORDER-07", target: "订单经营模型", keys: "orders.customer_id = customer.customer_master_id", cardinality: "many_to_one", grainImpact: "订单连接客户后保持订单粒度", guardrail: "客户主键必须唯一", state: "已发布" }],
    validations: [{ name: "Schema references", state: "passed", detail: "主键、生命周期字段和绑定有效" }],
    evidence: [{ id: "EVD-2102", kind: "Schema check", label: "客户主键唯一性通过", source: "Validation VAL-622", verifiedAt: "昨天 11:18", authority: "CONSTRAINED", supports: "实体键、JoinContract", state: "已验证" }],
    upstream: ["客户主档", "账户合并规则"],
    downstream: ["活跃客户", "客户分层", "客户留存率"],
    consumers: [{ name: "客户运营助手", kind: "MCP Agent", binding: "release-2026.08.3", lastResolved: "12 分钟前" }],
  },
  {
    id: "model_01J4ORDERS7K8M2Q5N9P",
    revision: "@14",
    namespace: "commerce",
    key: "commerce.orders_model",
    name: "订单经营模型",
    aliases: ["订单主题", "Orders Model"],
    type: "语义模型",
    status: "已发布",
    owner: "经营分析组",
    maintainer: "数据建模组",
    domain: "电商经营",
    definition: "围绕订单事实组织收入、支付、退款、客户和区域分析的公开语义模型。",
    formula: "model(analytics.orders)",
    grain: "一行一个订单",
    defaultTime: "结算日 settlement_date",
    unit: "不适用",
    aggregation: "成员按各自契约执行",
    source: "Cube / commerce.orders",
    updatedAt: "今天 09:40",
    release: "release-2026.08.3",
    tags: ["公开模型", "订单域"],
    includes: ["净收入", "支付订单数", "客单价", "业务区域"],
    excludes: ["支付风控内部字段", "客户敏感属性"],
    examples: ["经营日报", "收入诊断问答"],
    readiness: readiness(),
    relations: [{ id: "REL-261", type: "contains", targetId: "metric_01J4NETREVENUE8W4Q9D7K2", targetName: "净收入", direction: "outgoing", evidence: "EVD-2041", release: "release-2026.08.3" }],
    bindings: [{ id: "BIND-ORDERS-MODEL-14", sourceRevision: "src-ecommerce@9f2e8a", dataset: "analytics.orders", expression: "public view commerce_orders", grain: "order_id", defaultTime: "settlement_date", adapter: "cube-commerce", state: "已验证" }],
    joinContracts: [{ id: "JOIN-ORDER-CUSTOMER-07", target: "客户", keys: "orders.customer_id = customer.customer_master_id", cardinality: "many_to_one", grainImpact: "保持订单粒度", guardrail: "禁止从客户侧无约束展开订单", state: "已发布" }],
    validations: [{ name: "Cube compile", state: "passed", detail: "模型、公开成员和 Join 路径编译通过" }],
    evidence: [{ id: "EVD-2044", kind: "Cube compile", label: "公开语义模型编译通过", source: "models/commerce/orders.yml", verifiedAt: "今天 09:40", authority: "DERIVED", supports: "公开成员、Join 路径", state: "已验证" }],
    upstream: ["analytics.orders", "dim_customer", "dim_region"],
    downstream: ["净收入", "客单价", "经营日报"],
    consumers: [{ name: "经营日报", kind: "Dashboard", binding: "^2026.08", lastResolved: "18 分钟前" }],
  },
  {
    id: "segment_01J4HIGHVALUE4X7P2K9M6N",
    revision: "@2-draft",
    namespace: "customer",
    key: "customer.high_value_customers",
    name: "高价值客户",
    aliases: ["HVC"],
    type: "分群",
    status: "需关注",
    owner: "客户运营部",
    maintainer: "客户数据组",
    domain: "客户增长",
    definition: "最近 90 天净收入贡献位于客户总体前 10% 且至少完成 3 笔支付订单的客户。",
    formula: "customer_net_revenue_90d >= p90 AND paid_order_count_90d >= 3",
    grain: "客户",
    defaultTime: "每日快照 snapshot_date",
    unit: "布尔分群",
    aggregation: "不适用",
    source: "Semantic / customer.customer",
    updatedAt: "今天 08:30",
    release: "尚未发布",
    tags: ["运营分群", "待审核"],
    includes: ["90 天收入贡献前 10%", "至少 3 笔支付订单"],
    excludes: ["内部账户", "风险冻结账户"],
    examples: ["高价值客户营销触达"],
    readiness: readiness({ evidence: { state: "warning", detail: "阈值策略只有 OBSERVED 证据，等待业务声明" }, validation: { state: "warning", detail: "分群稳定性评测仍在运行" }, compatibility: { state: "not_applicable", detail: "未发布，尚无生产消费者" } }),
    relations: [{ id: "REL-271", type: "filters_by", targetId: "entity_01J4CUSTOMER6X2D9K8P4Q", targetName: "客户", direction: "outgoing", evidence: "EVD-2120", release: "draft" }],
    bindings: [{ id: "BIND-HVC-02", sourceRevision: "src-customer@71ac03", dataset: "analytics.customer_value_90d", expression: "revenue_percentile >= 0.9 AND paid_orders >= 3", grain: "customer_master_id", defaultTime: "snapshot_date", adapter: "warehouse-sql", state: "已验证" }],
    joinContracts: [],
    validations: [{ name: "Result regression", state: "warning", detail: "7 日分群波动率 6.2%，等待阈值评审" }],
    evidence: [{ id: "EVD-2120", kind: "Usage signal", label: "过去 12 周高价值客户贡献占比稳定", source: "Customer value observation", verifiedAt: "今天 08:20", authority: "OBSERVED", supports: "阈值候选", state: "需确认" }],
    upstream: ["客户", "净收入", "支付订单数"],
    downstream: ["客户运营助手", "营销触达"],
    consumers: [],
  },
  {
    id: "concept_01J4VALIDORDER6T2K9M8P3Q",
    revision: "@4",
    namespace: "commerce",
    key: "commerce.valid_paid_order",
    name: "有效支付订单",
    aliases: ["有效订单", "Valid Paid Order"],
    type: "业务概念",
    status: "已发布",
    owner: "收入分析组",
    maintainer: "语义平台组",
    domain: "电商经营",
    definition: "完成支付、未被撤销且不属于内部测试范围，可以进入经营口径计算的订单。",
    formula: "term(valid_paid_order)",
    grain: "订单业务规则",
    defaultTime: "按支付完成时间解释",
    unit: "业务概念",
    aggregation: "不适用",
    source: "Policy / commerce-order-policy",
    updatedAt: "昨天 15:10",
    release: "release-2026.08.3",
    tags: ["核心术语", "订单口径"],
    includes: ["支付成功且未撤销的真实客户订单", "允许部分退款但仍保留有效成交的订单"],
    excludes: ["内部测试订单", "支付撤销订单", "仅完成预授权的订单"],
    examples: ["净收入只统计有效支付订单", "有效订单与已创建订单不是同一概念"],
    readiness: readiness({ mapping: { state: "not_applicable", detail: "纯业务概念不要求物理实现" }, compatibility: { state: "not_applicable", detail: "当前通过 LLM Wiki 和本体关系消费" } }),
    relations: [
      { id: "REL-191", type: "describes", targetId: "model_01J4ORDERS7K8M2Q5N9P", targetName: "订单经营模型", direction: "outgoing", evidence: "EVD-1788", release: "release-2026.08.3" },
      { id: "REL-192", type: "depends_on", targetId: "measure_01J4PAIDORDERS5X8D2N6R", targetName: "支付订单数", direction: "incoming", evidence: "EVD-1788", release: "release-2026.08.3" },
    ],
    bindings: [],
    joinContracts: [],
    validations: [{ name: "Schema references", state: "passed", detail: "术语身份、语义域和本体关系均可解析" }],
    evidence: [{ id: "EVD-1788", kind: "Owner attestation", label: "订单口径委员会确认术语边界", source: "Review RVW-836", verifiedAt: "昨天 15:08", authority: "DECLARED", supports: "规范定义、包含与排除规则", state: "已验证" }],
    upstream: ["支付成功", "订单撤销规则", "测试账户策略"],
    downstream: ["支付订单数", "净收入", "客单价"],
    consumers: [],
  },
];

export const assets: Asset[] = assetSeeds.map(projectAsset);

export const proposals: Proposal[] = [
  {
    id: "PROP-128",
    title: "统一客单价的退款订单处理口径",
    assetName: "客单价",
    assetId: "metric_01J4AOV8C6MW3B7K9P2D",
    author: "Semlia AI",
    createdAt: "12 分钟前",
    risk: "中风险",
    summary: "排除完全退款订单，并将分母绑定到支付订单数的已发布 revision。",
    changes: [
      {
        field: "definition",
        before: "净收入除以支付成功订单数。",
        after: "净收入除以支付成功且未完全退款的订单数。",
      },
      {
        field: "formula",
        before: "net_revenue / orders.count",
        after: "net_revenue / paid_order_count",
      },
    ],
    validations: [
      { name: "Schema references", state: "passed", detail: "2 个引用均解析到已发布资产" },
      { name: "Cube compile", state: "passed", detail: "commerce 模型编译通过 · 4.8s" },
      { name: "Result regression", state: "warning", detail: "西南区域变化 +1.8%，需要负责人确认" },
      { name: "Policy G1", state: "passed", detail: "需要 1 名资产负责人审核" },
    ],
    impact: ["Fluxale Production", "区域经营评分", "渠道质量"],
  },
  {
    id: "PROP-126",
    title: "为净收入补充财务口径证据",
    assetName: "净收入",
    assetId: "metric_01J4NETREVENUE8W4Q9D7K2",
    author: "林悦",
    createdAt: "1 小时前",
    risk: "低风险",
    summary: "附加 FY2026 财务确认规则，不改变计算结果。",
    changes: [
      {
        field: "evidence",
        before: "EVD-2038",
        after: "EVD-2038, EVD-2048",
      },
    ],
    validations: [
      { name: "Schema references", state: "passed", detail: "证据引用有效" },
      { name: "Policy G1", state: "passed", detail: "低风险证据补充" },
    ],
    impact: ["无计算结果变化"],
  },
  {
    id: "PROP-121",
    title: "废弃旧区域编码别名",
    assetName: "业务区域",
    assetId: "dimension_01J4REGION3X7Q8K2M5V",
    author: "Semlia AI",
    createdAt: "昨天 15:30",
    risk: "高风险",
    summary: "删除 region_code_v1 别名，3 个消费者仍在使用。",
    changes: [
      {
        field: "aliases",
        before: "region_code, region_code_v1",
        after: "region_code",
      },
    ],
    validations: [
      { name: "Consumer impact", state: "failed", detail: "3 个消费者尚未迁移" },
      { name: "Policy G1", state: "failed", detail: "破坏性变更不允许直接发布" },
    ],
    impact: ["经营日报", "客户运营助手", "区域预测任务"],
  },
];

export const assetVersionReleases: AssetVersionRelease[] = [
  {
    id: "release-2026.08.3",
    assetId: "metric_01J4NETREVENUE8W4Q9D7K2",
    assetKey: "commerce.net_revenue",
    assetName: "净收入",
    assetType: "指标",
    revision: "@12",
    previousRevision: "@11",
    state: "Stable",
    publishedAt: "今天 10:06",
    publisher: "周屿",
    summary: "收入域证据更新与客户维度兼容性修复。",
    changes: ["2 个资产更新", "1 个证据补充", "0 个破坏性变更", "全部 18 项验证通过"],
    consumers: [
      {
        name: "Fluxale Production",
        kind: "BI Agent",
        binding: "锁定 release-2026.08.3",
        lastResolved: "2 分钟前",
      },
      {
        name: "经营日报",
        kind: "Dashboard",
        binding: "允许 ^2026.08",
        lastResolved: "18 分钟前",
      },
      {
        name: "指标解释 MCP",
        kind: "MCP Server",
        binding: "锁定 release-2026.08.3",
        lastResolved: "34 分钟前",
      },
    ],
  },
  {
    id: "release-2026.08.2",
    assetId: "metric_01J4NETREVENUE8W4Q9D7K2",
    assetKey: "commerce.net_revenue",
    assetName: "净收入",
    assetType: "指标",
    revision: "@11",
    previousRevision: "@10",
    state: "Superseded",
    publishedAt: "昨天 18:20",
    publisher: "林悦",
    summary: "补充退款确认边界与结算日归属说明。",
    changes: ["更新业务口径说明", "补充 1 项负责人证据", "0 个破坏性变更"],
    consumers: [],
  },
  {
    id: "release-2026.08.3",
    assetId: "metric_01J4AOV8C6MW3B7K9P2D",
    assetKey: "commerce.average_order_value",
    assetName: "客单价",
    assetType: "指标",
    revision: "@8",
    previousRevision: "@7",
    state: "Stable",
    publishedAt: "今天 09:58",
    publisher: "周屿",
    summary: "固定净收入与支付订单数的依赖版本。",
    changes: ["更新 2 个依赖修订", "补充回归验证", "1 个消费者兼容"],
    consumers: [{ name: "Fluxale Production", kind: "BI Agent", binding: "锁定 release-2026.08.3", lastResolved: "7 分钟前" }],
  },
  {
    id: "release-2026.08.2",
    assetId: "metric_01J4ACTIVE9Q2K8T5M7C3",
    assetKey: "customer.active_customers_30d",
    assetName: "活跃客户",
    assetType: "指标",
    revision: "@6",
    previousRevision: "@5",
    state: "Stable",
    publishedAt: "昨天 17:42",
    publisher: "林悦",
    summary: "稳定 30 日滚动窗口与去重客户口径。",
    changes: ["固定自然日窗口", "更新客户实体依赖", "全部验证通过"],
    consumers: [{ name: "客户运营助手", kind: "MCP Agent", binding: "锁定 release-2026.08.2", lastResolved: "1 小时前" }],
  },
  {
    id: "release-2026.08.1",
    assetId: "measure_01J4PAIDORDERS5X8D2N6R",
    assetKey: "commerce.paid_order_count",
    assetName: "支付订单数",
    assetType: "度量",
    revision: "@5",
    previousRevision: "@4",
    state: "Stable",
    publishedAt: "8 月 6 日 16:45",
    publisher: "周屿",
    summary: "固定支付成功与撤销订单的统计边界。",
    changes: ["更新支付状态过滤", "绑定订单模型 @13", "0 个未解析引用"],
    consumers: [],
  },
  {
    id: "release-2026.08.3",
    assetId: "model_01J4ORDERS7K8M2Q5N9P",
    assetKey: "commerce.orders_model",
    assetName: "订单经营模型",
    assetType: "语义模型",
    revision: "@14",
    previousRevision: "@13",
    state: "Stable",
    publishedAt: "今天 09:46",
    publisher: "周屿",
    summary: "发布订单域公开成员与受治理 Join 路径。",
    changes: ["新增 1 个 JoinContract", "更新公开成员", "Cube 编译通过"],
    consumers: [{ name: "经营日报", kind: "Dashboard", binding: "允许 ^2026.08", lastResolved: "18 分钟前" }],
  },
];
