import type { Asset, Proposal, Release } from "./types";

export const assets: Asset[] = [
  {
    id: "metric_01J4NETREVENUE8W4Q9D7K2",
    key: "commerce.net_revenue",
    name: "净收入",
    type: "指标",
    status: "已发布",
    trustScore: 96,
    owner: "收入分析组",
    domain: "电商经营",
    definition: "支付成功订单扣除退款、折扣与税费后的确认收入，按结算日归属。",
    formula: "SUM(paid_amount - refund_amount - discount_amount - tax_amount)",
    grain: "订单 · 结算日 · 业务区域",
    source: "Cube / commerce.orders",
    updatedAt: "今天 09:42",
    release: "release-2026.08.3",
    tags: ["P0 指标", "财务口径", "生产"],
    evidence: [
      {
        id: "EVD-2041",
        kind: "Cube compile",
        label: "Cube schema 编译通过",
        source: "models/commerce/orders.yml:48",
        verifiedAt: "今天 09:41",
      },
      {
        id: "EVD-2038",
        kind: "Owner attestation",
        label: "收入分析组确认口径",
        source: "Review RVW-882",
        verifiedAt: "昨天 17:22",
      },
      {
        id: "EVD-2027",
        kind: "Usage signal",
        label: "过去 30 天 1,284 次可信解析",
        source: "Resolution telemetry",
        verifiedAt: "今天 08:00",
      },
    ],
    upstream: ["支付订单", "退款金额", "折扣金额", "税费"],
    downstream: ["客单价", "区域收入达成率", "收入预测"],
    consumers: [
      {
        name: "Fluxale Production",
        kind: "BI Agent",
        binding: "release-2026.08.3",
        lastResolved: "2 分钟前",
      },
      {
        name: "经营日报",
        kind: "Dashboard",
        binding: "^2026.08",
        lastResolved: "18 分钟前",
      },
    ],
  },
  {
    id: "metric_01J4AOV8C6MW3B7K9P2D",
    key: "commerce.average_order_value",
    name: "客单价",
    type: "指标",
    status: "需关注",
    trustScore: 82,
    owner: "增长分析组",
    domain: "电商经营",
    definition: "净收入除以支付成功且未完全退款的订单数。",
    formula: "net_revenue / paid_order_count",
    grain: "结算日 · 业务区域",
    source: "Cube / commerce.orders",
    updatedAt: "昨天 16:08",
    release: "release-2026.08.3",
    tags: ["增长指标", "存在提案"],
    evidence: [
      {
        id: "EVD-1981",
        kind: "Query regression",
        label: "近 90 天回归样本通过 47/48",
        source: "Validation VAL-610",
        verifiedAt: "昨天 16:02",
      },
    ],
    upstream: ["净收入", "支付订单数"],
    downstream: ["区域经营评分", "渠道质量"],
    consumers: [
      {
        name: "Fluxale Production",
        kind: "BI Agent",
        binding: "release-2026.08.3",
        lastResolved: "7 分钟前",
      },
    ],
  },
  {
    id: "metric_01J4ACTIVE9Q2K8T5M7C3",
    key: "customer.active_customers_30d",
    name: "活跃客户",
    type: "指标",
    status: "已发布",
    trustScore: 91,
    owner: "客户洞察组",
    domain: "客户增长",
    definition: "最近 30 天内至少完成一次有效支付的去重客户数。",
    formula: "COUNT_DISTINCT(customer_id) FILTER paid_at >= now() - 30d",
    grain: "自然日 · 客户区域",
    source: "Cube / customer.activity",
    updatedAt: "2 天前",
    release: "release-2026.08.2",
    tags: ["客户指标", "滚动窗口"],
    evidence: [
      {
        id: "EVD-1902",
        kind: "Schema check",
        label: "字段与引用完整",
        source: "Validation VAL-602",
        verifiedAt: "2 天前",
      },
    ],
    upstream: ["客户", "支付订单"],
    downstream: ["客户留存率", "客户分层"],
    consumers: [
      {
        name: "客户运营助手",
        kind: "MCP Agent",
        binding: "release-2026.08.2",
        lastResolved: "1 小时前",
      },
    ],
  },
  {
    id: "metric_01J4PAIDORDERS5X8D2N6R",
    key: "commerce.paid_order_count",
    name: "支付订单数",
    type: "指标",
    status: "已发布",
    trustScore: 98,
    owner: "收入分析组",
    domain: "电商经营",
    definition: "支付状态成功且未被撤销的去重订单数。",
    formula: "COUNT_DISTINCT(order_id) FILTER payment_status = 'paid'",
    grain: "订单 · 支付日",
    source: "Cube / commerce.orders",
    updatedAt: "3 天前",
    release: "release-2026.08.1",
    tags: ["基础指标", "高复用"],
    evidence: [],
    upstream: ["订单", "支付状态"],
    downstream: ["客单价", "支付转化率"],
    consumers: [],
  },
  {
    id: "dimension_01J4REGION3X7Q8K2M5V",
    key: "commerce.business_region",
    name: "业务区域",
    type: "维度",
    status: "草稿",
    trustScore: 64,
    owner: "数据平台组",
    domain: "共享维度",
    definition: "基于履约组织映射的华东、华北、华南、西南四级业务区域。",
    formula: "region_mapping.fulfillment_region",
    grain: "履约组织",
    source: "Warehouse / dim_region",
    updatedAt: "4 天前",
    release: "尚未发布",
    tags: ["共享维度", "待补 owner"],
    evidence: [],
    upstream: ["履约组织"],
    downstream: ["净收入", "客单价", "活跃客户"],
    consumers: [],
  },
];

export const proposals: Proposal[] = [
  {
    id: "PROP-128",
    title: "统一客单价的退款订单处理口径",
    assetName: "客单价",
    assetId: "metric_01J4AOV8C6MW3B7K9P2D",
    author: "Semlia AI",
    createdAt: "12 分钟前",
    risk: "中风险",
    summary: "排除完全退款订单，并将分母绑定到支付订单数的已发布 revision。",
    changes: [
      {
        field: "definition",
        before: "净收入除以支付成功订单数。",
        after: "净收入除以支付成功且未完全退款的订单数。",
      },
      {
        field: "formula",
        before: "net_revenue / orders.count",
        after: "net_revenue / paid_order_count",
      },
    ],
    validations: [
      { name: "Schema references", state: "passed", detail: "2 个引用均解析到已发布资产" },
      { name: "Cube compile", state: "passed", detail: "commerce 模型编译通过 · 4.8s" },
      { name: "Result regression", state: "warning", detail: "西南区域变化 +1.8%，需要 owner 确认" },
      { name: "Policy G1", state: "passed", detail: "需要 1 名资产 owner 审核" },
    ],
    impact: ["Fluxale Production", "区域经营评分", "渠道质量"],
  },
  {
    id: "PROP-126",
    title: "为净收入补充财务口径证据",
    assetName: "净收入",
    assetId: "metric_01J4NETREVENUE8W4Q9D7K2",
    author: "林悦",
    createdAt: "1 小时前",
    risk: "低风险",
    summary: "附加 FY2026 财务确认规则，不改变计算结果。",
    changes: [
      {
        field: "evidence",
        before: "EVD-2038",
        after: "EVD-2038, EVD-2048",
      },
    ],
    validations: [
      { name: "Schema references", state: "passed", detail: "证据引用有效" },
      { name: "Policy G1", state: "passed", detail: "低风险证据补充" },
    ],
    impact: ["无计算结果变化"],
  },
  {
    id: "PROP-121",
    title: "废弃旧区域编码别名",
    assetName: "业务区域",
    assetId: "dimension_01J4REGION3X7Q8K2M5V",
    author: "Semlia AI",
    createdAt: "昨天 15:30",
    risk: "高风险",
    summary: "删除 region_code_v1 别名，3 个消费者仍在使用。",
    changes: [
      {
        field: "aliases",
        before: "region_code, region_code_v1",
        after: "region_code",
      },
    ],
    validations: [
      { name: "Consumer impact", state: "failed", detail: "3 个消费者尚未迁移" },
      { name: "Policy G1", state: "failed", detail: "breaking change 不允许直接发布" },
    ],
    impact: ["经营日报", "客户运营助手", "区域预测任务"],
  },
];

export const releases: Release[] = [
  {
    id: "release-2026.08.3",
    state: "Stable",
    publishedAt: "今天 10:06",
    publisher: "周屿",
    assetCount: 148,
    summary: "收入域证据更新与客户维度兼容性修复。",
    changes: ["2 个资产更新", "1 个证据补充", "0 breaking changes", "全部 18 项验证通过"],
    consumers: [
      {
        name: "Fluxale Production",
        kind: "BI Agent",
        binding: "锁定 release-2026.08.3",
        lastResolved: "2 分钟前",
      },
      {
        name: "经营日报",
        kind: "Dashboard",
        binding: "允许 ^2026.08",
        lastResolved: "18 分钟前",
      },
      {
        name: "指标解释 MCP",
        kind: "MCP Server",
        binding: "锁定 release-2026.08.3",
        lastResolved: "34 分钟前",
      },
    ],
  },
  {
    id: "release-2026.08.2",
    state: "Superseded",
    publishedAt: "昨天 18:20",
    publisher: "林悦",
    assetCount: 147,
    summary: "客户增长域首次稳定发布。",
    changes: ["4 个资产新增", "2 个关系更新", "0 breaking changes"],
    consumers: [],
  },
  {
    id: "release-2026.08.1",
    state: "Superseded",
    publishedAt: "8 月 6 日 16:45",
    publisher: "周屿",
    assetCount: 143,
    summary: "电商经营域基线。",
    changes: ["143 个资产发布", "12 个 owner 确认", "0 unresolved references"],
    consumers: [],
  },
];
