import { expect, test } from "@playwright/test";
import { resolve } from "node:path";

const accessControlEvidenceDirectory = resolve(process.cwd(), "../../docs/evidence/access-control-prototype/T005/screenshots");

test("database-to-answer journey stays inspectable", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");

  await expect(page.getByText("原型 · 模拟数据")).toHaveCount(0);
  await expect(page.getByText(/稳定版 ·/)).toHaveCount(0);
  await expect(page.locator(".ask-heading")).toHaveCount(0);
  await expect(page.getByText("可信语义问答", { exact: true })).toHaveCount(0);
  await expect(page.getByText("知识索引就绪", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: /编辑会话标题：8 月收入诊断/ }).click();
  const titleInput = page.getByRole("textbox", { name: "编辑会话标题" });
  await titleInput.fill("华东收入复盘");
  await titleInput.press("Enter");
  await expect(page.getByRole("button", { name: /编辑会话标题：华东收入复盘/ })).toBeVisible();
  await expect(page.getByRole("button", { name: /华东收入复盘/ }).last()).toBeVisible();
  await expect(page.locator(".context-header")).toHaveCount(0);
  await expect(page.locator(".topbar")).toHaveCSS("height", "52px");
  await expect(page.locator(".answer-route")).toHaveCount(0);
  await expect(page.getByRole("complementary", { name: "回答执行与证据" })).toHaveCount(0);
  await expect(page.getByText("净收入确认口径")).toBeVisible();
  await expect(page.locator(".workspace-canvas")).toHaveCSS("background-image", "none");
  const composerPosition = await page.locator(".ask-composer").evaluate((element) => {
    const rect = element.getBoundingClientRect();
    return { bottom: window.innerHeight - rect.bottom, position: getComputedStyle(element).position };
  });
  expect(composerPosition.position).toBe("fixed");
  expect(composerPosition.bottom).toBeLessThan(24);
  const clippedAskElements = await page.locator(".ask-layout, .topbar-actions").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedAskElements).toBe(0);

  await page.getByRole("button", { name: "新建会话" }).click();
  await page.getByRole("textbox", { name: "向 Semlia 提问" }).fill("客单价当前采用什么退款口径？");
  await page.getByRole("button", { name: "发送问题" }).click();
  await expect(page.getByText("正在形成可信回答")).toBeVisible();
  await expect(page.getByText("当前生效语义版本中的客单价为", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: /净收入确认口径.*KB-2048/ }).click();
  await expect(page.getByRole("heading", { name: "净收入" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "可信度" })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByText("Cube schema 编译通过")).toBeVisible();
  await expect(page.getByRole("complementary", { name: "治理上下文" }).getByRole("button", { name: /知识块与证据/ })).toHaveCount(0);
  await page.getByRole("tab", { name: "定义" }).click();
  await expect(page.getByRole("heading", { name: "权威语义页" })).toBeVisible();
  await expect(page.getByText("AI 检索词")).toBeVisible();
  await page.getByRole("tab", { name: "本体关系" }).click();
  const ontologyGraph = page.getByRole("img", { name: "净收入 的本体关系血缘图" });
  await expect(ontologyGraph).toBeVisible();
  const ontologyGraphSize = await ontologyGraph.evaluate((element) => { const rect = element.getBoundingClientRect(); return { width: rect.width, height: rect.height }; });
  expect(ontologyGraphSize.width).toBeGreaterThan(560);
  expect(ontologyGraphSize.height).toBeGreaterThan(240);
  const clippedOntologyElements = await page.locator(".asset-wiki-authority, .asset-ontology-context, .ontology-lineage-map").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedOntologyElements).toBe(0);

  await page.getByRole("button", { name: "工作台" }).click();
  await expect(page.getByRole("heading", { name: "待办" })).toHaveCount(0);
  await expect(page.locator(".lifecycle-rail")).toHaveCount(0);
  await expect(page.locator(".work-summary-band, .work-context-panel")).toHaveCount(0);
  const workbenchContext = page.getByRole("complementary", { name: "治理上下文" });
  const workbenchQueue = page.getByRole("region", { name: "工作台待办队列" });
  await expect(workbenchQueue).toBeVisible();
  await expect(workbenchContext.getByRole("button", { name: /^待办/ })).toHaveCount(0);
  await expect(workbenchContext.locator(".context-workbench-task")).toHaveCount(3);
  await workbenchContext.getByRole("button", { name: "搜索待办" }).click();
  await expect(page.getByRole("searchbox", { name: "搜索待办" })).toBeFocused();
  await expect(workbenchQueue.getByRole("button", { name: /检查客户增长域运行异常/ })).toBeVisible();
  await page.getByRole("combobox", { name: "筛选待办风险" }).selectOption("高风险");
  await expect(workbenchQueue.getByRole("button", { name: /旧区域别名无法安全废弃/ })).toBeVisible();
  await expect(workbenchQueue.getByRole("button", { name: /确认客单价退款订单口径/ })).toHaveCount(0);
  await page.getByRole("combobox", { name: "筛选待办风险" }).selectOption("全部风险");
  const clippedWorkbenchElements = await page.locator(".workbench-commandbar, .workbench-task-table").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedWorkbenchElements).toBe(0);
  await expect(page.getByRole("complementary", { name: "治理上下文" }).getByRole("button", { name: /动态/ })).toHaveCount(0);

  await page.getByRole("button", { name: "数据接入" }).click();
  await expect(page.getByRole("searchbox", { name: "搜索数据来源" })).toBeVisible();
  await expect(page.getByRole("tab", { name: /数据库连接/ })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("tab", { name: /文件导入/ })).toBeVisible();
  await expect(page.getByText("Cube Commerce")).toHaveCount(0);
  await expect(page.getByText("dbt Analytics")).toHaveCount(0);
  await expect(page.locator(".workspace-breadcrumb")).toHaveText("数据来源");
  await expect(page.locator(".workspace-breadcrumb")).not.toContainText("Semlia");
  await expect(page.locator(".topbar").getByRole("button", { name: "创建提案" })).toHaveCount(0);
  await expect(page.locator(".source-table-row").first()).toBeVisible();
  const sourceContext = page.getByRole("complementary", { name: "治理上下文" });
  await expect(sourceContext.getByRole("button", { name: /权限策略/ })).toHaveCount(0);
  await page.getByRole("tab", { name: /文件导入/ }).click();
  await page.getByRole("button", { name: "导入文件" }).click();
  const fileDialog = page.getByRole("dialog", { name: "导入文件" });
  await fileDialog.getByLabel("选择文件").setInputFiles({ name: "metric_dictionary.md", mimeType: "text/markdown", buffer: Buffer.from("# 净收入\n\n净收入扣除全额退款。") });
  await expect(fileDialog.getByLabel("分块方式")).toHaveValue("按标题层级");
  await expect(fileDialog.getByLabel("保留代码块")).toBeChecked();
  await expect(fileDialog.getByLabel("字段分隔符")).toHaveCount(0);
  await fileDialog.getByRole("button", { name: "检查文件" }).click();
  await expect(fileDialog.getByText("文件检查通过")).toBeVisible();
  await fileDialog.getByRole("button", { name: "导入并开始构建" }).click();
  await expect(page.getByRole("tabpanel", { name: /文件导入/ })).toContainText("metric_dictionary");
  await sourceContext.getByRole("button", { name: /接入自动化/ }).click();
  const buildTaskTable = page.getByRole("region", { name: "接入自动化列表" });
  await expect(buildTaskTable).toBeVisible();
  await expect(buildTaskTable).toContainText("元数据增量");
  await expect(buildTaskTable).not.toContainText("src-ecommerce@9f2e8a");
  await expect(buildTaskTable.getByRole("button", { name: /^(停用|启用) / })).toHaveCount(0);
  await expect(page.locator(".view-sources .page-heading, .build-run-inspector, .build-records-layout")).toHaveCount(0);
  const clippedBuildTaskElements = await page.locator(".build-task-commandbar, .build-task-table").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedBuildTaskElements).toBe(0);
  await page.getByRole("button", { name: "新建构建任务" }).click();
  const buildTaskDialog = page.getByRole("dialog", { name: "新建构建任务" });
  const enabledTaskToggle = buildTaskDialog.getByLabel("启用任务");
  await expect(enabledTaskToggle).toBeChecked();
  expect(await enabledTaskToggle.evaluate((element) => element.closest("header")?.classList.contains("build-task-dialog-header"))).toBe(true);
  await expect(buildTaskDialog.getByText("基本信息", { exact: true })).toHaveCount(0);
  await expect(buildTaskDialog.getByText("输入范围", { exact: true })).toHaveCount(0);
  await expect(buildTaskDialog.getByText("运行策略", { exact: true })).toHaveCount(0);
  await expect(buildTaskDialog.locator(".build-task-section-heading")).toHaveCount(0);
  await expect(buildTaskDialog.getByRole("radio", { name: /元数据增量/ })).toBeChecked();
  const buildModeHelpButton = buildTaskDialog.getByRole("button", { name: "查看元数据增量说明" });
  const buildModeTooltip = buildTaskDialog.getByRole("tooltip");
  await expect(buildModeHelpButton).toBeVisible();
  await expect(buildModeTooltip).toBeHidden();
  await buildModeHelpButton.hover();
  await expect(buildModeTooltip).toBeVisible();
  await expect(buildModeTooltip).toContainText("元数据快照，不是业务数据快照");
  await expect(buildModeTooltip).toContainText("失败运行不会推进 checkpoint");
  await expect(buildTaskDialog.getByRole("combobox", { name: "对象范围" })).toHaveCount(0);
  await expect(buildTaskDialog.getByRole("button", { name: "创建任务" })).toBeDisabled();
  await expect(buildTaskDialog.getByRole("searchbox", { name: "搜索可用数据来源" })).toHaveCount(0);
  const runStrategyTopBeforePicker = await buildTaskDialog.locator(".build-task-section").nth(2).evaluate((element) => element.getBoundingClientRect().top);
  await buildTaskDialog.getByRole("button", { name: /选择数据来源/ }).click();
  const runStrategyTopAfterPicker = await buildTaskDialog.locator(".build-task-section").nth(2).evaluate((element) => element.getBoundingClientRect().top);
  expect(Math.abs(runStrategyTopAfterPicker - runStrategyTopBeforePicker)).toBeLessThan(1);
  await buildTaskDialog.getByRole("searchbox", { name: "搜索可用数据来源" }).fill("PostgreSQL");
  await expect(buildTaskDialog.getByRole("checkbox", { name: "选择数据来源 PostgreSQL Analytics" })).toBeVisible();
  await expect(buildTaskDialog.getByRole("checkbox", { name: "选择数据来源 FY2026 营收目标" })).toHaveCount(0);
  await buildTaskDialog.getByRole("button", { name: "完成选择" }).click();
  await buildTaskDialog.locator(".build-trigger-control").getByText("定时调度", { exact: true }).click();
  await expect(buildTaskDialog.getByLabel("Cron 表达式")).toHaveValue("0 2 * * *");
  await expect(buildTaskDialog.getByLabel("调度时区")).toHaveValue("Asia/Shanghai");
  await expect(buildTaskDialog.locator(".build-schedule-preview, .build-task-toggle")).toHaveCount(0);
  const clippedScheduleElements = await buildTaskDialog.locator(".build-trigger-field, .build-schedule-config").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedScheduleElements).toBe(0);
  const clippedBuildTaskDialogElements = await buildTaskDialog.locator(".build-task-dialog-header, .build-task-section, .build-task-dialog-footer").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedBuildTaskDialogElements).toBe(0);
  await buildTaskDialog.getByRole("button", { name: "关闭构建任务" }).click();
  await buildTaskTable.getByRole("button", { name: "运行 经营数据元数据同步" }).click();
  await expect(buildTaskTable.getByText("已完成")).toBeVisible();
  await expect(sourceContext.getByRole("button", { name: /构建运行/ })).toHaveCount(0);
  await sourceContext.getByRole("button", { name: /接入运行/ }).click();
  const buildRunList = page.getByRole("region", { name: "接入运行" });
  await expect(buildRunList).toBeVisible();
  await expect(buildRunList).not.toContainText("RUN-SESSION");
  await expect(buildRunList).toContainText("2,846 对象 · 12 项变化");
  await expect(buildRunList).toContainText("数据库同步");
  await expect(buildRunList).not.toContainText("候选版本");
  await expect(buildRunList).not.toContainText("知识块");
  const firstBuildRunRow = buildRunList.getByRole("button", { name: /查看运行 RUN-240824-1432/ });
  await expect(firstBuildRunRow.locator(".build-run-list-id")).toHaveText("RUN-240824-1432");
  await expect(firstBuildRunRow.locator(".build-run-list-task")).toHaveText("经营数据元数据同步");
  await expect(firstBuildRunRow.locator(".build-run-list-time")).toHaveText("2026-08-24 14:32:18");
  await expect(firstBuildRunRow.locator(".build-run-list-mode")).toHaveText("数据库同步");
  await expect(firstBuildRunRow.locator(".build-run-list-duration")).toHaveText("2 分 18 秒");
  await expect(buildRunList.locator(".build-run-list-head > span")).toHaveText(["Run ID", "接入任务", "开始时间", "耗时", "类型", "接入结果", "状态", ""]);
  const runTimeFormats = await buildRunList.locator(".build-run-list-time").allTextContents();
  expect(runTimeFormats.every((value) => /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(value))).toBe(true);
  const clippedBuildRunListElements = await page.locator(".build-run-commandbar, .build-run-list-surface").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedBuildRunListElements).toBe(0);
  await expect(page.getByRole("searchbox", { name: "搜索接入运行" })).toHaveAttribute("placeholder", "搜索 Run ID、任务或来源");
  await expect(sourceContext.getByRole("button", { name: /来源版本与变更/ })).toHaveCount(0);
  await page.getByRole("button", { name: /查看运行 RUN-240824-1432/ }).click();
  const buildRunDetail = page.getByRole("region", { name: "接入运行详情" });
  await expect(buildRunDetail.getByLabel("元数据版本差异")).toBeVisible();
  await expect(buildRunDetail.getByLabel("元数据版本差异")).toContainText("3新增8修改1删除");
  await expect(buildRunDetail).toContainText("schema:9f2e8a");
  await expect(buildRunDetail.getByLabel("接入阶段")).toContainText("触发下游");
  await expect(buildRunDetail.getByRole("group", { name: "运行结果关系图" })).toHaveCount(0);
  await buildRunDetail.getByRole("button", { name: "查看执行日志" }).click();
  const runLogDialog = page.getByRole("dialog", { name: "执行日志" });
  await expect(runLogDialog.getByRole("log", { name: "运行执行日志" })).toContainText("连接来源");
  await expect(runLogDialog.getByRole("log", { name: "运行执行日志" })).toContainText("RUN-240901-1208");
  await runLogDialog.getByRole("button", { name: "关闭执行日志" }).click();
  const backToRunList = page.getByRole("button", { name: "返回接入运行" });
  await expect(backToRunList).toBeVisible();
  expect(await backToRunList.evaluate((element) => element.closest(".topbar") !== null)).toBe(true);
  const clippedBuildRunElements = await page.locator(".topbar, .build-run-detail-page").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedBuildRunElements).toBe(0);
  await buildRunDetail.getByRole("button", { name: "打开下游运行" }).click();
  const downstreamDialog = page.getByRole("dialog", { name: "客户增长知识增量构建" });
  await expect(downstreamDialog).toContainText("上游接入 RUN-240824-1432");
  await downstreamDialog.getByRole("button", { name: "关闭", exact: true }).click();

  await page.getByRole("button", { name: "变更与发布", exact: true }).click();
  await page.getByRole("button", { name: "查看候选资产版本 客单价 @9" }).click();
  const releaseContext = page.getByRole("complementary", { name: "治理上下文" });
  await expect(releaseContext.getByRole("button", { name: "搜索资产、变更与功能" })).toHaveCount(0);
  await expect(page.getByRole("tab", { name: /版本差异.*2/ })).toHaveAttribute("aria-selected", "true");
  await page.getByRole("button", { name: "收起发布门禁" }).click();
  await expect(page.getByRole("button", { name: "展开发布门禁" })).toBeVisible();
  await page.getByRole("button", { name: "展开发布门禁" }).click();
  await page.getByRole("tab", { name: /变更来源.*1/ }).click();
  await expect(page.getByRole("heading", { name: "包含的变更事项" })).toBeVisible();
  await expect(page.getByText("PROP-128", { exact: true })).toBeVisible();
  const backToAssetVersions = page.getByRole("button", { name: "返回资产版本列表" });
  await expect(backToAssetVersions).toBeVisible();
  expect(await backToAssetVersions.evaluate((element) => element.closest(".topbar") !== null)).toBe(true);
  await expect(page.locator(".governance-detail-commandbar")).toHaveCount(0);
  await page.getByRole("button", { name: "审核候选版本 客单价 @9" }).click();
  const dialog = page.getByRole("dialog", { name: "审核 客单价 · @9" });
  await expect(dialog.getByText("不会写入或发布真实数据", { exact: false })).toBeVisible();
  await dialog.getByRole("button", { name: "模拟批准版本" }).click();
  await expect(dialog).toBeHidden();

  await expect(page.getByRole("button", { name: "模拟发布 @9" })).toBeVisible();
  const clippedReleaseElements = await page.locator(".candidate-version-detail, .candidate-review-summary, .candidate-review-layout, .candidate-review-card").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedReleaseElements).toBe(0);
  await expect(page.getByRole("button", { name: "变更与发布" })).toHaveAttribute("aria-current", "page");
  await expect(page.getByRole("button", { name: "比较版本" })).toHaveCount(0);
  await page.getByRole("button", { name: "模拟发布 @9" }).click();
  const publishDialog = page.getByRole("dialog", { name: "发布客单价 @9" });
  await expect(publishDialog.getByText("不会真实切换客单价的问答或下游消费绑定", { exact: false })).toBeVisible();
  await publishDialog.getByRole("button", { name: "确认模拟发布并生效" }).click();
  await expect(page.getByText("release-2026.08.4-session")).toBeVisible();

  await backToAssetVersions.click();
  await page.getByRole("searchbox", { name: "搜索资产版本" }).fill("");
  await expect(page.getByRole("button", { name: "查看语义资产版本 净收入 @12" })).toContainText("当前版本");
  await page.getByRole("button", { name: "查看语义资产版本 净收入 @12" }).click();
  await expect(page.getByRole("heading", { name: "使用这个资产版本的应用" })).toBeVisible();
  await expect(page.getByText("Fluxale Production", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "与 @11 比较" }).click();
  const versionCompareDialog = page.getByRole("dialog", { name: "比较净收入版本" });
  await expect(versionCompareDialog.getByText("净收入 · 上一版本")).toBeVisible();
  await expect(versionCompareDialog.getByText("净收入 · 当前选择")).toBeVisible();
  await versionCompareDialog.getByRole("button", { name: "完成" }).click();
  await page.getByRole("button", { name: "工作台" }).click();
  const workbenchDetailContext = page.getByRole("complementary", { name: "治理上下文" });
  await workbenchDetailContext.getByRole("button", { name: "打开待办详情 旧区域别名无法安全废弃" }).click();
  await expect(page.getByRole("region", { name: "业务区域 @4 候选资产版本详情" })).toBeVisible();
  await expect(workbenchDetailContext.getByRole("button", { name: "打开待办详情 旧区域别名无法安全废弃" })).toHaveAttribute("aria-current", "page");
  await expect(page.getByRole("button", { name: "工作台" })).toHaveAttribute("aria-current", "page");
  await expect(page.getByRole("button", { name: "变更与发布" })).not.toHaveAttribute("aria-current", "page");
  await expect(page.locator(".topbar").getByRole("button", { name: "返回待办" })).toBeVisible();
  await page.getByRole("tab", { name: /变更来源.*1/ }).click();
  await expect(page.getByRole("heading", { name: "包含的变更事项" })).toBeVisible();

  await page.getByRole("button", { name: "知识资产" }).click();
  await expect(page.getByRole("region", { name: "知识目录" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "知识目录" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "保存视图" })).toHaveCount(0);
  await expect(page.getByRole("region", { name: "语义资产详情" })).toHaveCount(0);
  await expect(sourceContext.getByText("知识目录", { exact: true })).toBeVisible();
  await expect(sourceContext.getByText("最近打开")).toHaveCount(0);
  await expect(sourceContext.getByRole("button", { name: "打开最近资产 净收入" })).toBeVisible();
  await expect(sourceContext.getByRole("button", { name: /关系与映射/ })).toHaveCount(0);
  await expect(sourceContext.getByRole("button", { name: /本体与关系|物理数据图谱/ })).toHaveCount(0);
  await expect(page.getByRole("tab", { name: /清单|语义关系|物理映射/ })).toHaveCount(0);
  await page.getByRole("searchbox", { name: "搜索知识目录" }).fill("净收入");
  await expect(page.getByRole("button", { name: /净收入依赖支付订单数，语义关系/ })).toBeVisible();
  await expect(page.getByRole("button", { name: /analytics.orders 映射至 净收入，物理绑定/ })).toBeVisible();
  await page.getByRole("button", { name: "打开语义资产 净收入" }).click();
  await expect(page.getByRole("heading", { name: "净收入" })).toBeVisible();
  await expect(page.locator(".asset-detail-titlebar")).toHaveCount(0);
  await expect(page.locator(".topbar").getByRole("button", { name: "返回知识目录" })).toBeVisible();
  await expect(page.locator(".asset-detail-commandbar")).toHaveCount(0);
  await expect(page.getByRole("complementary", { name: "生产可用判断" })).toContainText("当前 revision 可用于生产");
  await expect(page.getByRole("complementary", { name: "生产可用判断" })).toContainText("没有阻断门禁");
  await expect(page.locator(".asset-header-state strong")).toHaveText("@12");
  await expect(page.getByRole("button", { name: "修订知识" })).toBeVisible();
  await page.getByRole("button", { name: "修订知识" }).click();
  const revisionPicker = page.getByRole("dialog", { name: "选择知识修订对象" });
  await expect(revisionPicker).toContainText("来源资料与已发布版本保持只读");
  await revisionPicker.getByRole("button", { name: /计算表达式/ }).click();
  const headerRevisionWorkbench = page.getByRole("region", { name: "净收入 知识修订工作台" });
  await expect(headerRevisionWorkbench.getByRole("textbox", { name: "计算表达式候选值" })).toBeVisible();
  await headerRevisionWorkbench.getByRole("button", { name: "取消修订" }).click();
  await page.getByRole("tab", { name: "定义" }).click();
  await expect(page.getByRole("region", { name: "指标内容模板" })).toContainText("业务衡量与比较契约");
  await page.getByRole("tab", { name: "实现" }).click();
  await expect(page.getByRole("heading", { name: "PhysicalBinding" })).toBeVisible();
  await expect(page.getByText("BIND-NET-REV-12").first()).toBeVisible();
  const mappingSections = await page.locator(".asset-mapping-layout > section").evaluateAll((sections) => sections.map((section) => { const rect = section.getBoundingClientRect(); return { top: rect.top, bottom: rect.bottom, left: rect.left, right: rect.right }; }));
  expect(mappingSections[1].top).toBeGreaterThanOrEqual(mappingSections[0].bottom - 1);
  expect(Math.abs(mappingSections[0].left - mappingSections[1].left)).toBeLessThan(1);
  await page.getByRole("tab", { name: "可信度" }).click();
  await expect(page.getByText("Cube schema 编译通过")).toBeVisible();
  await expect(page.getByRole("table", { name: "指标验证规则" })).toContainText("METRIC-001");
  await expect(page.getByRole("table", { name: "字段主张与证据" })).toContainText("spec.expression");
  const assuranceSections = await page.locator(".asset-assurance-layout > section").evaluateAll((sections) => sections.map((section) => { const rect = section.getBoundingClientRect(); return { top: rect.top, bottom: rect.bottom, left: rect.left }; }));
  expect(assuranceSections[1].top).toBeGreaterThanOrEqual(assuranceSections[0].bottom - 1);
  expect(Math.abs(assuranceSections[0].left - assuranceSections[1].left)).toBeLessThan(1);
  await page.getByRole("tab", { name: "交付与影响" }).click();
  await expect(page.getByRole("heading", { name: "当前生产指针" })).toBeVisible();
  const usageSections = await page.locator(".asset-usage-layout > section").evaluateAll((sections) => sections.map((section) => { const rect = section.getBoundingClientRect(); return { top: rect.top, bottom: rect.bottom, left: rect.left }; }));
  expect(usageSections[1].top).toBeGreaterThanOrEqual(usageSections[0].bottom - 1);
  expect(Math.abs(usageSections[0].left - usageSections[1].left)).toBeLessThan(1);
  await page.getByRole("button", { name: "返回知识目录" }).click();
  await expect(page.getByRole("searchbox", { name: "搜索知识目录" })).toHaveValue("净收入");
  const clippedAssetElements = await page.locator(".asset-catalog, .asset-table-head, .asset-row, .asset-tabs, .asset-type-template, .asset-type-rule-table").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedAssetElements).toBe(0);

  const hasDocumentOverflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
  expect(hasDocumentOverflow).toBe(false);
});

test("keyboard navigation reaches the core review flow", async ({ page }) => {
  await page.goto("/");

  await page.keyboard.press("Control+K");
  const conversationSearch = page.getByRole("searchbox", { name: "搜索会话" });
  await expect(conversationSearch).toBeFocused();
  await conversationSearch.fill("客单价");
  const askContext = page.getByRole("complementary", { name: "治理上下文" });
  await expect(askContext.getByRole("button", { name: /客单价口径/ })).toBeVisible();
  await expect(askContext.getByRole("button", { name: /8 月收入诊断/ })).toHaveCount(0);

  await page.getByRole("button", { name: "系统设置" }).click();
  await page.keyboard.press("Control+K");
  const commandPalette = page.getByRole("dialog", { name: "搜索与命令" });
  await expect(commandPalette).toBeVisible();
  await commandPalette.getByRole("textbox", { name: "搜索资产、变更或功能" }).fill("净收入");
  await page.keyboard.press("Enter");
  await expect(page.getByRole("heading", { name: "净收入" })).toBeVisible();

  const proposalNavigation = page.getByRole("button", { name: "变更与发布" });
  await proposalNavigation.focus();
  await page.keyboard.press("Enter");
  const versionRegistry = page.getByRole("region", { name: "语义资产版本列表" });
  await expect(versionRegistry).toBeVisible();
  await expect(versionRegistry.locator(":scope > *").first()).toHaveClass(/asset-version-toolbar/);
  await expect(versionRegistry.getByRole("heading", { name: "资产版本" })).toHaveCount(0);
  await page.getByRole("button", { name: "查看候选资产版本 客单价 @9" }).click();
  await page.getByRole("button", { name: "审核候选版本 客单价 @9" }).click();

  await expect(page.getByRole("button", { name: "关闭审核" })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog", { name: "审核 客单价 · @9" })).toBeHidden();
});

test("system settings separates LLM inference from Embedding indexing", async ({ page }) => {
  await page.setViewportSize({ width: 1024, height: 768 });
  await page.goto("/");
  await page.getByRole("button", { name: "系统设置" }).click();
  const context = page.getByRole("complementary", { name: "治理上下文" });
  await expect(context.getByRole("button", { name: /成员.*24 名成员/ })).toBeVisible();
  await expect(context.getByRole("button", { name: /策略与权限/ })).toHaveCount(0);
  await expect(context.getByRole("button", { name: "搜索资产、变更与功能" })).toHaveCount(0);
  const memberDirectory = page.getByRole("region", { name: "成员目录" });
  await expect(memberDirectory.getByText("EMP-10001")).toBeVisible();
  await expect(memberDirectory.getByText("yue.lin@semlia.example")).toBeHidden();
  await expect(memberDirectory.getByText("Workspace Admin", { exact: true })).toBeVisible();
  await memberDirectory.getByRole("searchbox", { name: "搜索成员" }).fill("许言");
  await expect(memberDirectory.getByText("EMP-10005")).toBeVisible();
  await expect(memberDirectory.getByText("EMP-10001")).toHaveCount(0);
  const clippedMemberElements = await page.locator(".member-directory-toolbar, .member-directory-table, .member-directory-head, .member-directory-row").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedMemberElements).toBe(0);
  await context.getByRole("button", { name: /模型配置/ }).click();

  const configuration = page.getByRole("region", { name: "模型配置" });
  await expect(configuration.getByRole("heading", { name: "模型配置" })).toHaveCount(0);
  await expect(configuration.locator(".model-config-stats")).toHaveCount(0);
  await expect(configuration.getByRole("tab", { name: "LLM 模型" })).toHaveAttribute("aria-selected", "true");
  await expect(configuration.getByRole("combobox", { name: "默认 LLM 模型" })).toHaveValue("llm-gpt-41");
  await expect(configuration.getByText("gpt-4.1", { exact: true })).toBeVisible();

  await configuration.getByRole("tab", { name: "Embedding 模型" }).click();
  await expect(configuration.getByText("text-embedding-3-large", { exact: true })).toBeVisible();
  await expect(configuration.locator(".embedding-boundary")).toHaveCount(0);
  await expect(configuration.getByRole("button", { name: "重建向量索引" })).toBeVisible();
  await configuration.getByRole("combobox", { name: "默认 Embedding 模型" }).selectOption("embedding-bge-m3");
  await expect(page.getByRole("status")).toContainText("Embedding 默认模型已切换为 bge-m3");
  await configuration.getByRole("button", { name: "重建向量索引" }).click();
  const rebuildDialog = page.getByRole("dialog", { name: "重建向量索引" });
  await expect(rebuildDialog.getByText("全部知识目录")).toBeVisible();
  await expect(rebuildDialog.getByText("bge-m3", { exact: true })).toBeVisible();
  await rebuildDialog.getByRole("button", { name: "开始重建" }).click();
  await expect(page.getByRole("status")).toContainText("向量索引重建任务已创建");
  const rebuildState = configuration.getByRole("region", { name: "最近向量索引重建状态" });
  await expect(rebuildState).toContainText("生成向量 · 42%");

  const internalProvider = configuration.getByRole("region", { name: "内部向量服务 供应商" });
  await internalProvider.getByRole("button", { name: "为 内部向量服务 添加模型" }).click();
  const dialog = page.getByRole("dialog", { name: "添加模型" });
  await dialog.getByLabel("模型 ID").fill("bge-reranker-v2-m3");
  await dialog.getByRole("button", { name: "保存模型" }).click();
  await expect(internalProvider.getByText("bge-reranker-v2-m3")).toBeVisible();

  const clippedModelElements = await page.locator(".model-config-toolbar, .embedding-rebuild-status, .model-provider-group, .model-provider-row, .model-row").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedModelElements).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)).toBe(false);

  await rebuildState.getByRole("button", { name: "查看进度与日志" }).click();
  const rebuildProgressDialog = page.getByRole("dialog", { name: "重建进度与日志" });
  await expect(rebuildProgressDialog.getByRole("region", { name: "向量索引重建进度" })).toContainText("1,436 / 3,420 个知识块");
  await expect(rebuildProgressDialog.getByRole("log", { name: "向量索引重建执行日志" })).toContainText("生成向量");
  await expect(page.getByRole("region", { name: "接入运行详情" })).toHaveCount(0);
  const clippedRebuildDialogElements = await rebuildProgressDialog.locator(".embedding-rebuild-dialog-overview, .embedding-rebuild-dialog-stages, .embedding-rebuild-dialog-facts, .embedding-rebuild-log-entry").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedRebuildDialogElements).toBe(0);
  await rebuildProgressDialog.getByRole("button", { name: "在全局运行记录中打开" }).click();
  const auditRuntime = page.getByRole("region", { name: "审计与运行" });
  await expect(auditRuntime.getByRole("tab", { name: "运行记录" })).toHaveAttribute("aria-selected", "true");
  const rebuildRun = page.getByRole("dialog", { name: "知识目录向量索引重建" });
  await expect(rebuildRun.getByRole("region", { name: "运行进度" })).toContainText("1,436 / 3,420 个知识块");
  await expect(rebuildRun.getByRole("log", { name: "全局运行执行日志" })).toContainText("生成向量");
  const clippedRebuildElements = await page.locator(".audit-runtime-detail-dialog, .audit-run-detail-overview, .audit-run-detail-log").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedRebuildElements).toBe(0);
});

test("interfaces and integrations manage callable clients", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "系统设置" }).click();
  const context = page.getByRole("complementary", { name: "治理上下文" });
  await context.getByRole("button", { name: /接口与集成/ }).click();
  const integrations = page.getByRole("region", { name: "接口与集成" });
  await expect(integrations.getByRole("heading", { name: "接口能力" })).toBeVisible();
  await expect(integrations.getByText("MCP Server", { exact: true })).toBeVisible();
  await expect(integrations.getByText("Fluxale Production", { exact: true })).toBeVisible();
  await expect(integrations.getByText("https://api.semlia.example/v1", { exact: true })).toHaveCount(0);
  await integrations.locator(".integration-channel-grid article").filter({ hasText: "REST API" }).getByRole("button", { name: "使用说明" }).click();
  const guideDialog = page.getByRole("dialog", { name: "REST API 使用说明" });
  await expect(guideDialog.getByText("https://api.semlia.example/v1", { exact: true })).toBeVisible();
  await expect(guideDialog.getByRole("heading", { name: "快速开始" })).toBeVisible();
  await expect(guideDialog).toContainText("knowledge/search");
  await guideDialog.getByRole("button", { name: "完成" }).click();
  await integrations.getByRole("button", { name: "创建客户端" }).click();
  const dialog = page.getByRole("dialog", { name: "创建客户端" });
  await dialog.getByLabel("客户端名称").fill("经营分析 Agent");
  await dialog.getByLabel("调用方式").selectOption("MCP");
  await dialog.getByLabel("环境").selectOption("开发");
  await dialog.getByRole("button", { name: "创建客户端" }).click();
  const secretDialog = page.getByRole("dialog", { name: "保存客户端凭据" });
  await expect(secretDialog).toContainText("只显示一次");
  await secretDialog.getByRole("button", { name: "完成" }).click();
  await expect(integrations.getByText("经营分析 Agent", { exact: true })).toBeVisible();
  const clippedIntegrationElements = await page.locator(".integration-commandbar, .integration-channel-grid article, .integration-client-table, .integration-client-head, .integration-client-row").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedIntegrationElements).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)).toBe(false);
});

test("audit and runtime unify global execution, traceability and settings", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "系统设置" }).click();
  const context = page.getByRole("complementary", { name: "治理上下文" });
  await context.getByRole("button", { name: /审计与运行/ }).click();

  const runtime = page.getByRole("region", { name: "审计与运行" });
  await expect(runtime.getByRole("region", { name: "运行状态概览" })).toContainText("日志投递");
  const runTable = runtime.getByRole("region", { name: "全局运行记录" });
  await expect(runTable.getByText("客户增长知识增量构建", { exact: true })).toBeVisible();
  await runTable.getByRole("button", { name: "查看运行 客户增长知识增量构建" }).click();
  const runDialog = page.getByRole("dialog", { name: "客户增长知识增量构建" });
  await expect(runDialog.getByRole("log", { name: "全局运行执行日志" })).toContainText("加载上下文");
  await runDialog.getByRole("button", { name: "关闭", exact: true }).click();

  await runtime.getByRole("tab", { name: "审计日志" }).click();
  const auditTable = runtime.getByRole("region", { name: "审计事件" });
  await runtime.getByRole("combobox", { name: "筛选调用渠道" }).selectOption("MCP");
  await expect(auditTable.getByText("调用语义检索", { exact: true })).toBeVisible();
  await expect(auditTable.getByText("同步元数据", { exact: true })).toHaveCount(0);
  await auditTable.getByRole("button", { name: "查看审计事件 调用语义检索" }).click();
  const auditDialog = page.getByRole("dialog", { name: "调用语义检索" });
  await expect(auditDialog).toContainText("tr_d219a4");
  await auditDialog.getByRole("button", { name: "关闭", exact: true }).click();

  await runtime.getByRole("tab", { name: "运行设置" }).click();
  await runtime.getByRole("spinbutton", { name: "最大并发任务" }).fill("6");
  await runtime.getByRole("button", { name: "保存更改" }).click();
  await expect(page.getByRole("status")).toContainText("审计与运行设置已保存");
  const clippedAuditElements = await page.locator(".audit-runtime-tabs, .audit-runtime-metrics, .audit-runtime-commandbar, .audit-runtime-table, .audit-settings-group").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedAuditElements).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)).toBe(false);
});

test("recent asset selection stays spatially stable within a module visit", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "知识资产" }).click();

  const context = page.getByRole("complementary", { name: "治理上下文" });
  const recentNames = () => context.locator(".context-item strong").allTextContents();
  const initialOrder = ["净收入", "订单经营模型", "高价值客户"];

  expect(await recentNames()).toEqual(initialOrder);
  await context.getByRole("button", { name: "打开最近资产 高价值客户" }).click();
  expect(await recentNames()).toEqual(initialOrder);
  await expect(context.getByRole("button", { name: "打开最近资产 高价值客户" })).toHaveAttribute("aria-current", "page");

  await page.getByRole("button", { name: "工作台" }).click();
  await page.getByRole("button", { name: "知识资产" }).click();
  expect(await recentNames()).toEqual(["高价值客户", "净收入", "订单经营模型"]);
});

test("answer feedback becomes a governed knowledge revision", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");

  await page.getByRole("button", { name: "指出问题" }).click();
  const issuePanel = page.getByRole("region", { name: "指出回答中的知识问题" });
  await issuePanel.getByRole("radio", { name: /计算规则或实现不准确/ }).check();
  await issuePanel.getByRole("button", { name: "修订相关知识" }).click();

  const workbench = page.getByRole("region", { name: "净收入 知识修订工作台" });
  await expect(workbench).toBeVisible();
  await expect(workbench.getByText("已发布版本受保护")).toBeVisible();
  await expect(workbench.getByRole("complementary", { name: "证据与检查" })).toContainText("修订只改变候选知识");
  await workbench.getByRole("textbox", { name: "计算表达式候选值" }).fill("SUM(paid_amount - confirmed_refund_amount - discount_amount - tax_amount)");
  await workbench.getByRole("button", { name: "运行检查" }).click();
  await expect(workbench.getByText("3/3 完成")).toBeVisible();

  const clippedWorkbenchElements = await page.locator(".knowledge-revision-workbench, .knowledge-revision-layout, .knowledge-field-editor, .knowledge-revision-inspector, .knowledge-revision-actions").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedWorkbenchElements).toBe(0);

  await workbench.getByRole("button", { name: "提交审核" }).click();
  await expect(page.getByRole("region", { name: "净收入 @13 候选资产版本详情" })).toBeVisible();
  await expect(page.getByText("spec.expression")).toBeVisible();
  await expect(page.getByText(/confirmed_refund_amount/)).toBeVisible();
  await page.getByRole("tab", { name: /变更来源.*1/ }).click();
  await expect(page.getByText("人工知识修订")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)).toBe(false);
});

test("access control remains explainable across supported desktop viewports", async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  await page.getByRole("button", { name: "系统设置" }).click();
  const context = page.getByRole("complementary", { name: "治理上下文" });
  await expect(context.getByRole("button", { name: /访问控制/ })).toBeVisible();
  await context.getByRole("button", { name: /访问控制/ }).click();
  const accessControl = page.getByRole("region", { name: "访问控制" });
  await expect(accessControl.getByRole("button", { name: "查看角色 Workspace Admin" })).toBeVisible();
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-roles.png`), fullPage: true });

  await accessControl.getByRole("button", { name: "查看角色 Reviewer" }).click();
  const roleDialog = page.getByRole("dialog", { name: "Reviewer 角色详情" });
  await expect(roleDialog.getByText("proposal.review", { exact: true })).toBeVisible();
  await expect(roleDialog.getByText("审核语义提案并记录评审结论。", { exact: true })).toBeVisible();
  await expect(roleDialog.getByText("release.publish", { exact: true })).toHaveCount(0);
  await expect(roleDialog.getByRole("button", { name: "编辑角色" })).toHaveCount(0);
  await roleDialog.getByRole("button", { name: "基于此角色创建" }).click();
  const roleEditor = page.getByRole("dialog", { name: "基于 Reviewer 创建角色" });
  await expect(roleEditor.getByRole("checkbox", { name: "配置权限 release.publish" })).toBeVisible();
  await expect(roleEditor.getByText("发布通过治理门禁的候选版本。", { exact: true })).toBeVisible();
  const roleEditorBox = await roleEditor.boundingBox();
  const roleEditorActionBox = await roleEditor.getByRole("button", { name: "预览角色变更" }).boundingBox();
  expect(roleEditorBox).not.toBeNull();
  expect(roleEditorActionBox).not.toBeNull();
  expect((roleEditorBox?.x ?? -1) + (roleEditorBox?.width ?? 0)).toBeLessThanOrEqual(testInfo.project.name === "compact-desktop" ? 1024 : 1440);
  expect((roleEditorActionBox?.y ?? -1) + (roleEditorActionBox?.height ?? 0)).toBeLessThanOrEqual(testInfo.project.name === "compact-desktop" ? 768 : 900);
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-role-editor.png`), fullPage: true });
  await page.keyboard.press("Escape");
  await expect(roleEditor).toBeHidden();

  await accessControl.getByRole("tab", { name: "角色分配" }).click();
  await accessControl.getByRole("button", { name: "分配角色" }).click();
  const assignmentDialog = page.getByRole("dialog", { name: "分配角色" });
  await assignmentDialog.getByRole("button", { name: "预览授权" }).click();
  await expect(assignmentDialog.getByRole("alert")).toContainText("评审者与发布者必须相互独立");
  await expect(assignmentDialog.getByRole("button", { name: "确认分配" })).toBeDisabled();
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-assignment-conflict.png`), fullPage: true });
  await assignmentDialog.getByRole("button", { name: "关闭角色分配" }).click();

  await accessControl.getByRole("tab", { name: "有效权限检查" }).click();
  await accessControl.getByRole("button", { name: "检查有效权限" }).click();
  const decision = accessControl.getByRole("region", { name: "有效权限结果" });
  await expect(decision).toContainText("拒绝");
  await accessControl.getByRole("combobox", { name: "检查主体" }).selectOption("EMP-10001");
  await accessControl.getByRole("button", { name: "检查有效权限" }).click();
  await expect(decision).toContainText("允许");
  await expect(decision).toContainText("Workspace Admin");
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-effective-access.png`), fullPage: true });

  await context.getByRole("button", { name: /成员.*24 名成员/ }).click();
  const members = page.getByRole("region", { name: "成员目录" });
  await expect(members.getByRole("row", { name: /EMP-10001.*语义产品经理.*Workspace Admin/ })).toBeVisible();
  await expect(members.getByText("已停用", { exact: true })).toBeVisible();
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-members.png`), fullPage: true });

  await context.getByRole("button", { name: /接口与集成/ }).click();
  const integrations = page.getByRole("region", { name: "接口与集成" });
  await expect(integrations.getByText("已过期", { exact: true })).toBeVisible();
  await expect(integrations.getByRole("button", { name: "撤销客户端 Fluxale Production" })).toBeVisible();
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-machine-clients.png`), fullPage: true });

  await page.getByRole("button", { name: "变更与发布" }).click();
  await page.getByRole("button", { name: "查看候选资产版本 客单价 @9" }).click();
  await page.getByRole("button", { name: "审核候选版本 客单价 @9" }).click();
  await page.getByRole("dialog", { name: "审核 客单价 · @9" }).getByRole("button", { name: "模拟批准版本" }).click();
  await page.getByRole("button", { name: "模拟发布 @9" }).click();
  const publishDialog = page.getByRole("dialog", { name: "发布客单价 @9" });
  await publishDialog.getByRole("combobox", { name: "发布身份" }).selectOption("USR-REVIEWER");
  await expect(publishDialog.getByRole("alert")).toContainText("评审者与发布者必须相互独立");
  await expect(publishDialog.getByRole("button", { name: "确认模拟发布并生效" })).toBeDisabled();
  await page.screenshot({ path: resolve(accessControlEvidenceDirectory, `${testInfo.project.name}-publish-conflict.png`), fullPage: true });

  const clippedElements = await page.locator(".access-control-view, .access-role-table, .assignment-table, .access-inspector-form, .member-directory-table, .integration-client-table, .review-dialog").evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).length);
  expect(clippedElements).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)).toBe(false);
});
