import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { IntegrationSettingsView } from "./IntegrationSettingsView";
import { IntegrationPartialSuccess, type ClientCredential, type IntegrationApi, type IntegrationData, type IssuedCredential, type Webhook } from "./integrations";
import { AUTHORIZATION_STALE_EVENT } from "./apiClient";

const empty: IntegrationData = { credentials: [], consumers: [], bindings: [], webhooks: [], deliveries: [] };
const credential: ClientCredential = { id: "ccd_test", workspaceId: "wsp_test", principalId: "prn_test", consumerId: "csm_test", bindingId: "cbd_test", name: "Persisted client", tokenPrefix: "ccd_test.abcd", allowedActions: ["asset.read", "semantic.resolve"], scopeType: "workspace", scopeId: "wsp_test", issuedBy: "prn_admin", issuedAt: "2026-01-01T00:00:00Z", expiresAt: "2030-01-01T00:00:00Z" };
const webhook: Webhook = { id: "whs_test", workspaceId: "wsp_test", name: "Persisted hook", endpoint: "https://receiver.example/a", enabled: true, eventTypes: ["release.published"], version: 3, signingVersion: 2, secretSuffix: "abcd", createdBy: "prn_admin", createdAt: "2026-01-01T00:00:00Z", updatedAt: "2026-01-01T00:00:00Z" };
function api(): IntegrationApi { return { load: vi.fn().mockResolvedValue(empty), issue: vi.fn(), rotate: vi.fn(), revoke: vi.fn(), createPrincipal: vi.fn(), grant: vi.fn(), createConsumer: vi.fn(), createBinding: vi.fn(), saveWebhook: vi.fn(), rotateWebhook: vi.fn(), replayDelivery: vi.fn() }; }
describe("persisted integration settings", () => {
  it("loads server state without fixture clients and respects permissions", async () => {
    const backend = api();
    render(<IntegrationSettingsView workspaceId="wsp_test" canRead canManage={false} api={backend} onNotify={vi.fn()} />);
    await waitFor(() => expect(backend.load).toHaveBeenCalled());
    expect(screen.getByText("尚无客户端凭据")).toBeInTheDocument();
    expect(screen.queryByText("Fluxale Production")).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: "创建客户端" })).toBeDisabled();
  });
  it("keeps persisted credentials visible but disables mutations after refresh fails", async () => {
    const backend = api();
    vi.mocked(backend.load).mockRejectedValue(new Error("offline"));
    render(<IntegrationSettingsView workspaceId="wsp_test" canRead canManage api={backend} onNotify={vi.fn()} />);
    await screen.findByRole("alert");
    expect(screen.getByRole("button", { name: "创建客户端" })).toBeDisabled();
    vi.mocked(backend.load).mockResolvedValue(empty);
    fireEvent.click(screen.getByRole("button", { name: "刷新集成设置" }));
    await screen.findByText("尚无客户端凭据");
    expect(screen.getByRole("button", { name: "创建客户端" })).toBeEnabled();
  });
  it("shows only the returned secret, reports clipboard failure, and clears on Escape with focus restoration", async () => {
    const user = userEvent.setup(); const backend = api(), notify = vi.fn();
    vi.mocked(backend.load).mockResolvedValue({ ...empty, credentials: [credential] });
    vi.mocked(backend.rotate).mockResolvedValue({ credential, token: "returned-once-secret" });
    Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: vi.fn().mockRejectedValue(new Error("denied")) } });
    render(<IntegrationSettingsView workspaceId="wsp_test" canRead canManage api={backend} onNotify={notify} />);
    const trigger = await screen.findByRole("button", { name: "轮换 Persisted client 的凭据" });
    await user.click(trigger);
    const dialog = await screen.findByRole("dialog", { name: "保存一次性凭据" });
    expect(dialog).toHaveTextContent("returned-once-secret");
    await user.click(within(dialog).getByRole("button", { name: "复制凭据" }));
    expect(await within(dialog).findByRole("alert")).toHaveTextContent("复制失败");
    expect(notify).not.toHaveBeenCalledWith("已复制。");
    await user.keyboard("{Escape}");
    expect(screen.queryByText("returned-once-secret")).not.toBeInTheDocument();
    expect(trigger).toHaveFocus();
    expect(localStorage.getItem("returned-once-secret")).toBeNull();
  });
  it("restores focus once after a secret closes during its deferred refresh", async () => {
    const user = userEvent.setup(); const backend = api();
    let finishRefresh!: (value: IntegrationData) => void;
    vi.mocked(backend.load).mockResolvedValueOnce({ ...empty, credentials: [credential] }).mockImplementationOnce(() => new Promise(resolve => { finishRefresh = resolve; })).mockResolvedValue({ ...empty, credentials: [credential] });
    vi.mocked(backend.rotate).mockResolvedValue({ credential, token: "deferred-refresh-secret" });
    render(<IntegrationSettingsView workspaceId="wsp_test" canRead canManage api={backend} onNotify={vi.fn()} />);
    const trigger = await screen.findByRole("button", { name: "轮换 Persisted client 的凭据" });
    await user.click(trigger);
    await screen.findByRole("dialog", { name: "保存一次性凭据" });
    expect(trigger).toBeDisabled();
    await user.keyboard("{Escape}");
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
    expect(screen.queryByText("deferred-refresh-secret")).not.toBeInTheDocument();
    await act(async () => finishRefresh({ ...empty, credentials: [credential] }));
    await waitFor(() => expect(trigger).toHaveFocus());
    const refresh = screen.getByRole("button", { name: "刷新集成设置" });
    await user.click(refresh);
    await waitFor(() => expect(backend.load).toHaveBeenCalledTimes(3));
    expect(refresh).toHaveFocus();
  });
  it("does not take focus back if the user moved while refresh was pending", async () => {
    const user = userEvent.setup(); const backend = api();
    let finishRefresh!: (value: IntegrationData) => void;
    vi.mocked(backend.load).mockResolvedValueOnce({ ...empty, credentials: [credential] }).mockImplementationOnce(() => new Promise(resolve => { finishRefresh = resolve; }));
    vi.mocked(backend.rotate).mockResolvedValue({ credential, token: "focus-preservation-secret" });
    render(<IntegrationSettingsView workspaceId="wsp_test" canRead canManage api={backend} onNotify={vi.fn()} />);
    await user.click(await screen.findByRole("button", { name: "轮换 Persisted client 的凭据" }));
    await screen.findByRole("dialog", { name: "保存一次性凭据" });
    await user.keyboard("{Escape}");
    const search = screen.getByRole("searchbox", { name: "搜索集成客户端" });
    await user.click(search);
    await act(async () => finishRefresh({ ...empty, credentials: [credential] }));
    expect(search).toHaveFocus();
  });
  it("prevents duplicate pending mutations and does not reopen a dismissed secret", async () => {
    const user = userEvent.setup(); const backend = api();
    vi.mocked(backend.load).mockResolvedValue({ ...empty, credentials: [credential] });
    let finish!: (value: IssuedCredential) => void;
    vi.mocked(backend.rotate).mockImplementation(() => new Promise(resolve => { finish = resolve; }));
    render(<IntegrationSettingsView workspaceId="wsp_test" canRead canManage api={backend} onNotify={vi.fn()} />);
    const trigger = await screen.findByRole("button", { name: "轮换 Persisted client 的凭据" });
    await user.dblClick(trigger);
    expect(backend.rotate).toHaveBeenCalledTimes(1);
    expect(trigger).toBeDisabled();
    act(() => window.dispatchEvent(new Event(AUTHORIZATION_STALE_EVENT)));
    await act(async () => finish({ credential, token: "late-secret-must-not-appear" }));
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
    expect(screen.queryByText("late-secret-must-not-appear")).not.toBeInTheDocument();
  });
  it("distinguishes persisted mutation from failed follow-up refresh", async () => {
    const user = userEvent.setup(); const backend = api();
    vi.mocked(backend.load).mockResolvedValueOnce({ ...empty, credentials: [credential] }).mockRejectedValue(new Error("offline"));
    vi.mocked(backend.revoke).mockResolvedValue();
    render(<IntegrationSettingsView workspaceId="wsp_test" canRead canManage api={backend} onNotify={vi.fn()} />);
    await user.click(await screen.findByRole("button", { name: "撤销客户端 Persisted client" }));
    expect(await screen.findByRole("alert")).toHaveTextContent("变更已保存，但刷新失败");
    expect(screen.getByRole("button", { name: "撤销客户端 Persisted client" })).toBeDisabled();
    expect(screen.getByText("Persisted client", { exact: true })).toBeVisible();
  });
  it("edits persisted endpoint and event filters using its expected version", async () => {
    const user = userEvent.setup(); const backend = api();
    vi.mocked(backend.load).mockResolvedValue({ ...empty, webhooks: [webhook] });
    vi.mocked(backend.saveWebhook).mockResolvedValue({ subscription: { ...webhook, version: 4 }, signingSecret: "" });
    render(<IntegrationSettingsView workspaceId="wsp_test" canRead canManage api={backend} onNotify={vi.fn()} />);
    await user.click(await screen.findByRole("tab", { name: /Webhook/ }));
    await user.click(await screen.findByRole("button", { name: "编辑 Persisted hook 的订阅" }));
    const dialog = screen.getByRole("dialog", { name: "编辑 Webhook" });
    await user.clear(within(dialog).getByLabelText("HTTPS 接收地址"));
    await user.type(within(dialog).getByLabelText("HTTPS 接收地址"), "https://receiver.example/b");
    await user.click(within(dialog).getByRole("checkbox", { name: "catalog.asset.changed" }));
    await user.click(within(dialog).getByRole("checkbox", { name: "release.published" }));
    await user.click(within(dialog).getByRole("button", { name: "保存" }));
    expect(backend.saveWebhook).toHaveBeenCalledWith("wsp_test", { name: webhook.name, endpoint: "https://receiver.example/b", eventTypes: ["catalog.asset.changed"], expectedVersion: 3, enabled: true }, webhook.id);
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
  });
  it("reloads partial consumer success and recovers with binding creation only", async () => {
    const user = userEvent.setup(); const backend = api();
    const consumer = { id: "csm_partial", workspaceId: "wsp_test", name: "Partial consumer", stableKey: "partial", kind: "agent" as const, status: "active" as const, ownerPrincipalRef: "prn_admin", metadata: {}, createdAt: "2026-01-01T00:00:00Z", updatedAt: "2026-01-01T00:00:00Z" };
    vi.mocked(backend.load).mockResolvedValueOnce(empty).mockResolvedValue({ ...empty, consumers: [consumer] });
    vi.mocked(backend.createConsumer).mockRejectedValue(new IntegrationPartialSuccess("消费方已创建，但绑定创建失败。"));
    vi.mocked(backend.createBinding).mockResolvedValue();
    render(<IntegrationSettingsView workspaceId="wsp_test" canRead canManage api={backend} onNotify={vi.fn()} />);
    await screen.findByText("尚无客户端凭据");
    await user.click(screen.getByRole("button", { name: "登记消费方" }));
    let dialog = screen.getByRole("dialog");
    await user.type(within(dialog).getByLabelText("名称"), "Partial consumer");
    await user.type(within(dialog).getByLabelText("稳定键"), "partial");
    await user.click(within(dialog).getByRole("button", { name: "创建" }));
    expect(await screen.findByRole("alert")).toHaveTextContent("消费方已创建");
    await user.click(await screen.findByRole("button", { name: "补建绑定" }));
    dialog = screen.getByRole("dialog", { name: "补建消费绑定" });
    await user.click(within(dialog).getByRole("button", { name: "创建" }));
    expect(backend.createConsumer).toHaveBeenCalledTimes(1);
    expect(backend.createBinding).toHaveBeenCalledWith("wsp_test", "csm_partial", "prod");
  });
});
