import { Plus, X } from "lucide-react";
import { useContext, useState } from "react";
import type { KnowledgeExpression, KnowledgeReference, KnowledgeSpec, KnowledgeType } from "./knowledge";
import { knowledgeFieldLabels } from "./knowledge";
import { physicalReference, type PhysicalReference, type SnapshotMember } from "./semanticProduction";
import { KnowledgeReferenceEditor, KnowledgeWorkspaceContext } from "./KnowledgeReferencePicker";

type Member = SnapshotMember & { snapshotId: string };
const emptyRef = (): KnowledgeReference => ({ assetId: "", revisionId: "", releaseId: "" });

function ExpressionEditor({ label, value, onChange, metric, depth = 0 }: { label: string; value?: KnowledgeExpression; onChange: (value: KnowledgeExpression) => void; metric: boolean; depth?: number }) {
  const ops: Array<[KnowledgeExpression["op"], string]> = metric ? [["ref", "指标引用"], ["add", "加"], ["subtract", "减"], ["multiply", "乘"], ["divide", "除"]] : [["ref", "属性引用"], ["parameter", "查询参数"], ["literal", "固定值"], ["eq", "等于"], ["neq", "不等于"], ["lt", "小于"], ["lte", "小于等于"], ["gt", "大于"], ["gte", "大于等于"], ["and", "且"], ["or", "或"]];
  const leaf = !value || ["ref", "parameter", "literal"].includes(value.op);
  return <div className="knowledge-expression"><label className="production-field"><span>{label}</span><select aria-label={`${label}算子`} value={value?.op ?? ""} onChange={(event) => onChange({ op: event.target.value as KnowledgeExpression["op"] })}><option value="">选择运算</option>{ops.filter(([op]) => depth < 6 || ["ref", "parameter", "literal"].includes(op)).map(([op, name]) => <option key={op} value={op}>{name}</option>)}</select></label>
    {value?.op === "ref" && <KnowledgeReferenceEditor label={`${label}引用`} type={metric ? "metric" : "business_object"} member={!metric} value={value.ref} onChange={(ref) => onChange({ op: "ref", ref })} />}
    {value?.op === "parameter" && <label className="production-field"><span>参数名</span><input aria-label={`${label}参数名`} value={value.parameter ?? ""} onChange={(event) => onChange({ op: "parameter", parameter: event.target.value })} /></label>}
    {value?.op === "literal" && <LiteralEditor label={label} value={value.value} onChange={(literal) => onChange({ op: "literal", value: literal })} />}
    {!leaf && depth < 7 && <div className="knowledge-expression-inputs"><ExpressionEditor label={`${label}左项`} value={value.left} onChange={(left) => onChange({ ...value, left })} metric={metric} depth={depth + 1} /><ExpressionEditor label={`${label}右项`} value={value.right} onChange={(right) => onChange({ ...value, right })} metric={metric} depth={depth + 1} /></div>}
  </div>;
}

function LiteralEditor({ label, value, onChange }: { label: string; value: unknown; onChange: (value: KnowledgeExpression["value"]) => void }) {
  const typeOf = (item: unknown) => typeof item === "number" ? "number" : typeof item === "boolean" ? "boolean" : "string";
  const [draft, setDraft] = useState(() => ({ value, text: String(value ?? ""), type: typeOf(value) }));
  if (value !== draft.value) setDraft({ value, text: String(value ?? ""), type: typeOf(value) });
  const update = (next: KnowledgeExpression["value"], text: string, type = draft.type) => { setDraft({ value: next, text, type }); onChange(next); };
  return <div className="knowledge-literal">
    <label className="production-field"><span>固定值类型</span><select aria-label={`${label}固定值类型`} value={draft.type} onChange={(event) => { const type = event.target.value; const next = type === "number" ? 0 : type === "boolean" ? false : ""; update(next, String(next), type); }}><option value="string">文本</option><option value="number">数值</option><option value="boolean">布尔值</option></select></label>
    <label className="production-field"><span>固定值</span>{draft.type === "boolean" ? <select aria-label={`${label}固定值`} value={String(value)} onChange={(event) => update(event.target.value === "true", event.target.value)}><option value="false">否</option><option value="true">是</option></select> : <input aria-label={`${label}固定值`} type={draft.type === "number" ? "number" : "text"} step={draft.type === "number" ? "any" : undefined} value={draft.text} onChange={(event) => update(draft.type === "string" ? event.target.value : Number.isFinite(event.target.valueAsNumber) ? event.target.valueAsNumber : undefined, event.target.value)} />}</label>
  </div>;
}

export function KnowledgeSpecEditor({ type, value, onChange, members = [], workspaceId }: { type: KnowledgeType; value?: KnowledgeSpec | null; onChange: (value: KnowledgeSpec) => void; members?: Member[]; workspaceId?: string }) {
  const inheritedWorkspaceId = useContext(KnowledgeWorkspaceContext);
  const spec = value ?? {};
  const patch = (values: Partial<KnowledgeSpec>) => onChange({ ...spec, ...values });
  const text = (field: keyof KnowledgeSpec, label = knowledgeFieldLabels[field]) => <label className="production-field" key={field}><span>{label}</span><input aria-label={label} value={typeof spec[field] === "string" ? spec[field] as string : ""} onChange={(event) => patch({ [field]: event.target.value || undefined })} /></label>;
  const select = (field: keyof KnowledgeSpec, options: Array<[string, string]>, change?: (value: string) => void) => <label className="production-field"><span>{knowledgeFieldLabels[field]}</span><select aria-label={knowledgeFieldLabels[field]} value={typeof spec[field] === "string" ? spec[field] as string : ""} onChange={(event) => change ? change(event.target.value) : patch({ [field]: event.target.value || undefined })}><option value="">待确认</option>{options.map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select></label>;
  const reference = (field: "subjectRef" | "inputRef" | "timeAttributeRef" | "baseObjectRef" | "defaultTimeAttributeRef", member = false) => <KnowledgeReferenceEditor key={field} label={knowledgeFieldLabels[field]} value={spec[field]} member={member} onChange={(ref) => patch({ [field]: ref })} />;
  const references = (field: "filterRefs" | "publicAttributeRefs" | "metricRefs" | "compatibleTermRefs" | "dataAssetRefs", member = false) => <section className="knowledge-reference-list"><h4>{knowledgeFieldLabels[field]}</h4>{(spec[field] ?? []).map((ref, index) => <KnowledgeReferenceEditor key={index} label={`${knowledgeFieldLabels[field]} ${index + 1}`} type={field === "metricRefs" ? "metric" : field === "dataAssetRefs" ? "data_asset" : field === "publicAttributeRefs" ? "business_object" : "business_term"} value={ref} member={member} onChange={(next) => patch({ [field]: next ? spec[field]!.map((item, i) => i === index ? next : item) : spec[field]!.filter((_, i) => i !== index) })} />)}<button className="secondary-button" type="button" onClick={() => patch({ [field]: [...(spec[field] ?? []), emptyRef()] })}><Plus size={14} />添加{knowledgeFieldLabels[field]}</button></section>;
  const source = (label: string, ref: PhysicalReference | undefined, kind: "dataset" | "field", change: (ref: PhysicalReference | undefined) => void) => {
    const key = (item: { snapshotId: string; objectId: string; revisionId: string }) => `${item.snapshotId}:${item.objectId}:${item.revisionId}`;
    const options = members.filter((item) => item.kind === kind && (kind === "dataset" || item.parentObjectId === spec.datasetRef?.objectId && item.snapshotId === spec.datasetRef?.snapshotId));
    return <label className="production-field"><span>{label}</span><select aria-label={label} value={ref ? key(ref) : ""} onChange={(event) => { const found = options.find((item) => key(item) === event.target.value); change(found ? physicalReference(found.snapshotId, found) : undefined); }}><option value="">待选择</option>{ref && !options.some((item) => key(item) === key(ref)) && <option value={key(ref)}>固定来源 · {ref.objectId} @ {ref.snapshotId}</option>}{options.map((item) => <option key={key(item)} value={key(item)}>{item.name}</option>)}</select></label>;
  };
  return <KnowledgeWorkspaceContext.Provider value={workspaceId ?? inheritedWorkspaceId}><section className="knowledge-spec-editor" aria-label="类型专属知识结构">
    {(type === "business_object" || type === "data_asset") && <>
      {text("grain")}
      {type === "business_object" ? <>{text("identityPolicy")}{text("lifecycle")}</> : <>{source("来源数据集版本", spec.datasetRef, "dataset", (ref) => patch({ datasetRef: ref, members: [], keys: [] }))}{text("coverage")}{text("refreshFrequency")}{text("sensitivity")}</>}
      <section className="knowledge-members"><h4>{type === "business_object" ? "业务属性" : "字段成员"}</h4>{(spec.members ?? []).map((member, index) => {
        const update = (values: Partial<typeof member>) => patch({ members: spec.members!.map((item, i) => i === index ? { ...item, ...values } : item) });
        return <div className="knowledge-member-row" key={index}>
          <label><span>成员 ID</span><input aria-label={`成员 ${index + 1} ID`} value={member.id} onChange={(event) => { const id = event.target.value; patch({ members: spec.members!.map((item, i) => i === index ? { ...item, id } : item), keys: (spec.keys ?? []).map((key) => key === member.id ? id : key) }); }} /></label>
          <label><span>业务含义</span><input aria-label={`成员 ${index + 1} 含义`} value={member.name ?? ""} onChange={(event) => update({ name: event.target.value })} /></label>
          {type === "business_object" ? <><label><span>值类型</span><select aria-label={`成员 ${index + 1} 类型`} value={member.valueType ?? ""} onChange={(event) => update({ valueType: event.target.value as typeof member.valueType })}><option value="">待确认</option>{["string", "number", "integer", "boolean", "date", "timestamp"].map((item) => <option key={item}>{item}</option>)}</select></label><label><span>历史语义</span><select aria-label={`成员 ${index + 1} 历史语义`} value={member.historyPolicy ?? ""} onChange={(event) => update({ historyPolicy: event.target.value as typeof member.historyPolicy })}><option value="">待确认</option><option value="stable">稳定身份</option><option value="current_value">当前值</option><option value="event_time">事件时值</option></select></label></> : source(`成员 ${index + 1} 来源字段`, member.sourceFieldRef, "field", (ref) => update({ sourceFieldRef: ref }))}
          <label><span>空值处理</span><select aria-label={`成员 ${index + 1} 空值处理`} value={member.nullPolicy ?? ""} onChange={(event) => update({ nullPolicy: event.target.value as typeof member.nullPolicy })}><option value="">待确认</option><option value="required">不允许为空</option><option value="unknown">未知</option><option value="excluded">排除</option></select></label>
          <label className="production-check"><input type="checkbox" aria-label={`成员 ${index + 1} 唯一键`} checked={spec.keys?.includes(member.id) ?? false} onChange={(event) => patch({ keys: event.target.checked ? [...(spec.keys ?? []), member.id] : spec.keys?.filter((key) => key !== member.id) })} /><span>唯一键</span></label>
          <button type="button" className="icon-button" aria-label={`移除成员 ${index + 1}`} title="移除成员" onClick={() => patch({ members: spec.members!.filter((_, i) => i !== index), keys: spec.keys?.filter((key) => key !== member.id) })}><X size={14} /></button>
        </div>;
      })}<button type="button" className="secondary-button" onClick={() => { let index = 1; while (spec.members?.some((member) => member.id === `member_${index}`)) index++; patch({ members: [...(spec.members ?? []), { id: `member_${index}` }] }); }}><Plus size={14} />添加成员</button></section>
    </>}
    {type === "business_term" && <>
      {select("capability", [["definition", "仅解释定义"], ["predicate", "定义与可执行判定"]], (capability) => onChange(capability === "definition" ? { capability: "definition" } : { capability: "predicate", stage: "object", nullPolicy: "unknown_does_not_match" }))}
      {spec.capability === "predicate" && <>{reference("subjectRef")}<ExpressionEditor label="判定条件" value={spec.predicate} onChange={(predicate) => patch({ predicate })} metric={false} />{select("stage", [["object", "对象行级判定"]])}{select("nullPolicy", [["unknown_does_not_match", "未知值不匹配"]])}
        <h4>查询参数</h4>{(spec.parameters ?? []).map((parameter, index) => <div className="knowledge-member-row" key={index}><label><span>参数名</span><input aria-label={`参数 ${index + 1} 名称`} value={parameter.name} onChange={(event) => patch({ parameters: spec.parameters!.map((item, i) => i === index ? { ...item, name: event.target.value } : item) })} /></label><label><span>类型</span><select aria-label={`参数 ${index + 1} 类型`} value={parameter.type} onChange={(event) => patch({ parameters: spec.parameters!.map((item, i) => i === index ? { ...item, type: event.target.value as typeof parameter.type } : item) })}>{["date", "timestamp", "string", "number", "integer", "boolean"].map((type) => <option key={type}>{type}</option>)}</select></label><label className="production-check"><input type="checkbox" aria-label={`参数 ${index + 1} 必填`} checked={parameter.required} onChange={(event) => patch({ parameters: spec.parameters!.map((item, i) => i === index ? { ...item, required: event.target.checked } : item) })} />必填</label><button type="button" className="icon-button" aria-label={`移除参数 ${index + 1}`} title="移除参数" onClick={() => patch({ parameters: spec.parameters!.filter((_, i) => i !== index) })}><X size={14} /></button></div>)}<button type="button" className="secondary-button" onClick={() => patch({ parameters: [...(spec.parameters ?? []), { name: "period_start", type: "date", required: true }] })}><Plus size={14} />添加参数</button>
      </>}
    </>}
    {type === "metric" && <>
      {select("kind", [["aggregate", "基础聚合"], ["derived", "派生计算"]], (kind) => { const common = { ...spec }; delete common.expression; delete common.inputRef; delete common.aggregation; delete common.zeroDenominator; delete common.rollup; onChange({ ...common, kind: kind as "aggregate" | "derived", ...(kind === "derived" ? { zeroDenominator: "null", rollup: "recompute_from_inputs" } : {}) }); })}
      {spec.kind === "derived" ? <><ExpressionEditor label="派生计算" value={spec.expression} onChange={(expression) => patch({ expression })} metric />{select("zeroDenominator", [["null", "返回空值"]])}{select("rollup", [["recompute_from_inputs", "从基础指标重新计算"]])}</> : <>{reference("inputRef", true)}{select("aggregation", [["sum", "求和"], ["avg", "平均"], ["count", "计数"], ["count_distinct", "去重计数"], ["min", "最小值"], ["max", "最大值"]])}</>}
      {text("unit")}{select("nullPolicy", [["exclude", "排除空值"], ["required", "执行前检查非空"]])}{reference("timeAttributeRef", true)}{references("filterRefs")}
    </>}
    {type === "analysis_model" && <>{reference("baseObjectRef")}{text("grain")}{reference("defaultTimeAttributeRef", true)}{references("publicAttributeRefs", true)}{references("metricRefs")}{references("compatibleTermRefs")}{references("dataAssetRefs")}
      <h4>成员映射</h4>{(spec.memberBindings ?? []).map((binding, index) => <div className="knowledge-binding" key={index}><KnowledgeReferenceEditor label={`映射 ${index + 1} 业务属性`} member value={binding.semanticRef} onChange={(ref) => patch({ memberBindings: ref ? spec.memberBindings!.map((item, i) => i === index ? { ...item, semanticRef: ref } : item) : spec.memberBindings!.filter((_, i) => i !== index) })} /><KnowledgeReferenceEditor label={`映射 ${index + 1} 数据成员`} type="data_asset" member value={binding.dataRef} onChange={(ref) => patch({ memberBindings: ref ? spec.memberBindings!.map((item, i) => i === index ? { ...item, dataRef: ref } : item) : spec.memberBindings!.filter((_, i) => i !== index) })} /></div>)}<button type="button" className="secondary-button" onClick={() => patch({ memberBindings: [...(spec.memberBindings ?? []), { semanticRef: emptyRef(), dataRef: emptyRef() }] })}><Plus size={14} />添加成员映射</button>
      <label className="production-field"><span>已发布连接契约</span><textarea aria-label="已发布连接契约" value={(spec.joinContractIds ?? []).join("\n")} onChange={(event) => patch({ joinContractIds: event.target.value.split(/\s+/).filter(Boolean) })} /></label>
    </>}
  </section></KnowledgeWorkspaceContext.Provider>;
}
