import { expect, test } from "@playwright/test";

test("shared ingestion tables expose details without losing list context", async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  // Only read responses are replaced; this test never creates or runs a plan.
  await page.route("**/sources/*/schedules*", async (route) => {
    const sourceId = new URL(route.request().url()).pathname.split("/").at(-2);
    await route.fulfill({ json: { items: [{ id: "sch_01arz3ndektsv4rrffq69g5fav", sourceId, expression: "0 2 * * *", timezone: "Asia/Shanghai", misfirePolicy: "skip", enabled: true, version: 2, nextRunAt: "2026-09-09T02:00:00+08:00", createdAt: "2026-09-08T02:00:00+08:00", updatedAt: "2026-09-08T02:00:00+08:00" }], total: 1, limit: 50 } });
  });
  await page.route("**/schedules/*/occurrences*", (route) => route.fulfill({ json: { items: [], total: 0, limit: 50 } }));
  await page.goto("/");
  await page.getByRole("button", { name: "数据接入", exact: true }).click();
  const sourceTable = page.getByRole("table", { name: "数据来源", exact: true });
  const sourceOpen = sourceTable.getByRole("button", { name: /查看来源/ }).first();
  await expect(sourceOpen).toBeVisible();
  const sourcePanelBox = await page.getByRole("tabpanel", { name: "数据来源列表" }).boundingBox();
  const sourceHeadBox = await sourceTable.locator("thead").boundingBox();
  await page.screenshot({ path: testInfo.outputPath("sources.png") });
  await sourceOpen.focus();
  await page.keyboard.press("Enter");
  const detail = page.getByRole("dialog", { name: "数据来源详情" });
  await expect(detail).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("source-detail.png") });
  await page.keyboard.press("Escape");
  await expect(sourceOpen).toBeFocused();
  const navigation = page.getByRole("complementary", { name: "治理上下文" });
  await navigation.getByRole("button", { name: /接入自动化/ }).click();
  const planTable = page.getByRole("table", { name: "接入计划", exact: true });
  await expect(planTable.getByRole("button", { name: /查看计划 sch/ })).toBeVisible();
  const planPanelBox = await page.getByRole("region", { name: "接入计划列表" }).boundingBox();
  const planHeadBox = await planTable.locator("thead").boundingBox();
  for (const key of ["x", "y", "width", "height"] as const) expect(Math.abs(planPanelBox![key] - sourcePanelBox![key])).toBeLessThanOrEqual(1);
  expect(planHeadBox!.height).toBe(sourceHeadBox!.height);
  const more = planTable.getByRole("button", { name: /更多操作计划/ });
  await expect(planTable.getByRole("button", { name: /立即运行计划/ })).toBeVisible();
  await more.click();
  await expect(page.getByRole("menuitem", { name: "暂停计划" })).toBeEnabled();
  await page.screenshot({ path: testInfo.outputPath("schedule-actions.png") });
  await page.getByRole("menuitem", { name: "编辑计划" }).click();
  await expect(page.getByRole("dialog", { name: "编辑接入计划" })).toBeVisible();
  const editPlan = page.getByRole("dialog", { name: "编辑接入计划" });
  const enabled = editPlan.getByRole("checkbox", { name: "启用计划" });
  await expect(enabled).toBeChecked();
  const checkboxBox = await enabled.boundingBox();
  expect(checkboxBox!.width).toBe(18);
  expect(checkboxBox!.height).toBe(18);
  await page.screenshot({ path: testInfo.outputPath("schedule-edit.png") });
  await enabled.focus();
  await page.keyboard.press("Space");
  await expect(enabled).not.toBeChecked();
  await editPlan.getByRole("button", { name: "取消", exact: true }).click();
  await expect(editPlan).toHaveCount(0);
  await more.click();
  await page.getByRole("menuitem", { name: "删除计划" }).click();
  await expect(page.getByRole("dialog", { name: "删除接入计划" })).toBeVisible();
  await page.keyboard.press("Escape");
  await page.screenshot({ path: testInfo.outputPath("schedules.png") });
  await planTable.getByText("Asia/Shanghai").click();
  await expect(page.getByRole("dialog", { name: "接入计划详情" })).toBeVisible();
  await expect(page.getByText("暂无执行记录")).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("schedule-detail.png") });
  await page.keyboard.press("Escape");
  await expect(planTable.getByRole("button", { name: /查看计划 sch/ })).toBeFocused();
  await navigation.getByRole("button", { name: /接入运行/ }).click();
  const runTable = page.getByRole("table", { name: "接入运行", exact: true });
  const runOpen = runTable.getByRole("button", { name: /查看运行/ }).first();
  await expect(runOpen).toBeVisible();
  const runPanelBox = await page.getByRole("region", { name: "接入结果列表" }).boundingBox();
  for (const key of ["x", "y", "width", "height"] as const) expect(Math.abs(runPanelBox![key] - sourcePanelBox![key])).toBeLessThanOrEqual(1);
  await page.screenshot({ path: testInfo.outputPath("runs.png") });
  await runOpen.click();
  await expect(page.getByRole("region", { name: "接入运行详情" })).toBeVisible();
  await page.getByRole("button", { name: "返回接入运行", exact: true }).click();
  await expect(runTable).toBeVisible();
  await expect(runOpen).toBeFocused();
  await page.getByRole("tab", { name: /语义候选/ }).click();
  await expect(page.getByRole("table", { name: "语义候选", exact: true })).toBeVisible();
  const candidatePanelBox = await page.getByRole("region", { name: "接入结果列表" }).boundingBox();
  expect(candidatePanelBox).toEqual(runPanelBox);
  await page.screenshot({ path: testInfo.outputPath("candidates.png") });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
